CUBRID/cubrid

src/cm_common/cm_dep_tasks.c
- fixed, _op_get_db_user_id function doesn't work and it also causes
core dump like following when debug mode:
```
$ cub_manager: ../../src/compat/db_macro.c:2604: db_get_int: Assertion
`value->domain.general_info.type == DB_TYPE_INTEGER' failed.
#0 0x00000038c8e328a5 in raise () from /lib64/libc.so.6
#1 0x00000038c8e34085 in abort () from /lib64/libc.so.6
#2 0x00000038c8e2ba1e in __assert_fail_base () from /lib64/libc.so.6
#3 0x00000038c8e2bae0 in __assert_fail () from /lib64/libc.so.6
#4 0x00007f27abf567f6 in db_get_int (value=0x7f27977e9830) at
../../src/compat/db_macro.c:2604
#5 0x00007f27ad900737 in _op_get_db_user_id (res=0x7f277c00caa0,
user=0x99bae0) at ../../src/cm_common/cm_dep_tasks.c:2830
#6 0x00007f27ad8fd4c5 in cm_ts_userinfo (in=0x7f277c01dcb0,
out=0x7f277c00caa0, …
```
=> [TOOLS-4265] _op_get_db_user_id() in cm_common causes core dump

src/communication/network_interface_sr.c, src/communication/network_sr.c, src/connection/connection_defs.h, src/connection/connection_sr.c, src/connection/server_support.c, src/query/query_executor.c, src/thread/critical_section.c, src/thread/critical_section.h, src/transaction/boot_sr.c, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_tran_table.c
- introduce RWLOCK and its monitoring stub
- rename CSS_CRITICAL_SECTION as CRITICAL_SECTION
=> [CBRD-20156] introduce light weight rwlock

src/connection/connection_defs.h, src/query/query_executor.c, src/thread/critical_section.c, src/thread/critical_section.h, src/transaction/log_impl.h
rename CRITICAL_SECTION as SYNC_CRITICAL_SECTION
rename RWLOCK as SYNC_RWLOCK
=> [CBRD-20156] rename CRITICAL_SECTION as SYNC_CRITICAL_SECTION, RWLOCK as SYNC_RWLOCK for Windows build

src/base/perf_monitor.h, src/communication/network_interface_sr.c, src/communication/network_sr.c, src/connection/connection_sr.c, src/connection/server_support.c, src/query/query_executor.c, src/thread/critical_section.c, src/thread/critical_section.h, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-20165
We have 3 kinds of synchronization primitives:
* critical section: FCFS, reentrancy, read/write mode, promotion/demotion
* rwlock: no FCFS, no reentrancy, read/write mote
* simple mutex: no FCFS, no reentrancy, only write mode
I'd like to introduce a new synchronization primitive, reentrant mutex which does not use condition variable. 
* reentrant mutex: no FCFS, reentrancy, only write mode
Pseudo codes are
```C
lock (rmutex)
{
if (rmutex->owner == me)
{
assert (rmutex->nenters > 0);
}
else
{
mutex_lock (rmutex->mutex);
assert (rmutex->nenters == 0);
rmutex->owner = me;
}
rmutex->nenters++;
}
unlock (rmutex)
{
assert (rmutex->nenters > 0);
assert (rmutex->owner == me);
rmutex->nenters--;
if (rmutex->nenters == 0)
{
rmutex->owner = 0;
mutex_unlock …
```
=> [CBRD-20165] introduce light weight reentrant mutex

src/communication/network_sr.c, src/thread/critical_section.c, src/thread/critical_section.h, src/transaction/boot_sr.c, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_page_buffer.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-20166
- replace CSECT_LOG_PB with LOGPB_RMUTEX_LOG_PB
- macros: START_EXCLUSIVE_ACCESS_LOG_PB, END_EXCLUSIVE_ACCESS_LOG_PB
- also fixes a bug of RMUTEX implementation: duplicated sync_stats entry
- includes some miscellaneous changes
=> [CBRD-20166] replace CSECT_LOG_PB with a SYNC_RMUTEX

src/query/query_executor.c, src/query/query_executor.h, src/query/scan_manager.c, src/storage/heap_file.c, src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20174
This field of MVCC_REEV_DATA was used incorrectly used after CBRD-20167 patch.
Also, in locator_delete_force_internal() the reevaluation data will be ignored when the object is already locked.
=> [CBRD-20174] Removed primary_key from MVCC_REEV_DATA

src/query/query_executor.c
The issue was caused by a memory overrun of uninitialized variable.
=> [CBRD-20177] Fixed uninitialized recdes in qexec_execute_obj_fetch()

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20187
When adjusting header for update/insert, the insert id will to be set for all mvcc classes, unless stand alone mode is active.
=> [CBRD-20187] Consider mvcc class when setting insert id in heap_insert_adjust_recdes_header()

src/connection/connection_sr.c, src/connection/connection_sr.h, src/connection/server_support.c, src/thread/critical_section.c, src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-20189
The name of critical section for a temporary connection should be empty.
Introduce two debugging support functions, `css_is_valid_conn_csect` and `css_is_temporary_conn_csect`.
=> [CBRD-20189] fixed a bad assertion for temporary connection

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20196
Deleted records may be still visible after locking. This case will be considered a serializable conflict.
=> [CBRD-20196] Raise serializable conflict for deleted visible records

src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20190
In the testing scenario, we had two index keys with 100k objects each. These two keys covered almost all instance of the class. During `locator_check_btree_entries`, the objects are fetched from heap and then looked up in index. Fetching objects used heap_next and kept the page latched until all its objects were verified. The page has 480 objects and each must be looked up in about 150 overflow OID's pages. This could take a long time, even longer than 5 minutes, which caused the latch timeout on heap page for a vacuum worker.
=> [CBRD-20190] Fix long heap page latch times during locator_check_btree_entries

src/storage/catalog_class.c
http://jira.cubrid.org/browse/CBRD-20200
The issue is caused by not setting the link to log record with previous version when doing update-in-place.
The first alter does an MVCC update on db_class entry which also sets the LSA to previous version in heap record. The second alter does an update-in-place operation on same db_class entry (same-transaction update optimization) which does not set the LSA link to log record.
The MVCC versioning design in banana milestone had a huge problem modifying schemas in certain cases. For instance, creating a class with 1000 partitions would add each partition separately and flush/update the catalog class entries every time. As a consequence, the instances in catalog classes were updated 1k times and for each instance we created 1k versions.
To fix the …
=> [CBRD-20200] Disable "in-place" update on catalog entries.

src/query/vacuum.c
At the end of vacuum job we call pgbuf_unfix_all. It makes sure no pages are still latched (and hits an assert if any pages are fixed). In stand-alone, while running vacuum jobs we also keep vacuum data pages latched. Therefore, we cannot call pgbuf_unfix_all.
=> [CBRD-20219] Do not unfix all pages at the end of a vacuum job in stand-alone mode

src/executables/compactdb.c, src/query/serial.c, src/storage/catalog_class.c, src/storage/heap_file.c, src/storage/heap_file.h, src/transaction/boot_sr.c, src/transaction/locator_sr.c, src/transaction/log_applier.c, src/transaction/log_manager.c, src/transaction/replication.c, src/transaction/replication.h
http://jira.cubrid.org/browse/CBRD-20175
Removed some unused or obsolete arguments and variables.
=> [CBRD-20175] Fix replication log : always perform index update before heap update.

src/object/trigger_manager.c, src/query/execute_statement.c, src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-20210
We used to have SCH_M_LOCK in banana, because trigger OID changed when altered. Therefore, db_class entry of table also had to be updated (where trigger OID's were kept).
We no longer change trigger OID and we do not require to update db_class entry. We still use S_LOCK to prevent conflicts with concurrent DML statements.
=> [CBRD-20210] S_LOCK on referenced table when altering a trigger.

src/storage/heap_file.c, src/transaction/locator_sr.c
We have two-fixes-in-one here:
1. Fix notify vacuum when updating REC_ASSIGN_ADDRESS.
After changing the MVCC versioning, the update logic was "simplified" to is_mvcc_op when we keep link to old version and !is_mvcc_op when we don't keep the link (and we always have update-in-place). The problem is that vacuum notification is also linked to "is_mvcc_op". When we update a REC_ASSIGN_ADDRESS (as we do with catalog entries), we do not keep link to old version but we need to notify vacuum.
I added a quick fix for the case. Mr. Andrei should make a more graceful code when he fixes logging issues.
2. Fix checkdb issue.
I fixed it here, because the second issue reproduced once first was fixed. This is same as CBRD-20234 issue.
The problem was one change we made earlier to …
=> [CBRD-20225] Fix notify vacuum when updating REC_ASSIGN_ADDRESS; Fix checkdb issue.

src/thread/thread.c
If the shutdown request occurred in the middle of a vacuum master iteration, vacuum_finalize call may have been missed.
Moved vacuum_finalize after the "while (!tsd_ptr->shutdown)" loop.
=> [CBRD-20227] Always call vacuum_finalize in thread_vacuum_master_thread

src/query/vacuum.c
Removed code that incremented the number of assigned vacuum workers a second time.
@eseokoh : This is not the original issue of CBRD-20229. This is the issue I reproduced by running the same scenario. The original issue did not reproduce and I could not investigate the core files on the issue because the machine IP was missing.
I can create a new issue for this problem and add the fix with the new issue number.
=> [CBRD-20229] Fix assign vacuum worker

src/query/vacuum.c
In debug mode, the vacuum master thread is busy performing various checks (vacuum_verify_vacuum_data_page_fix_count), by default finished job queue is small (90).
=> [CBRD-20237] Increase vacuum finished job queue capcacity to 2048

src/storage/btree.c, src/transaction/log_manager.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-20240
Only release builds suffer from this defect. Since `rv_redo_data_ptr` was not set, redo data length would be negative and this leads to memory overrun. 
It also includes assertions and refactoring of logging functions.
=> [CBRD-20240] fix redo logging of btree_key_remove_object_and_keep_visible_first for release builds.

win/cubridcs/cubridcs.def, win/cubridsa/cubridsa.def
`db_get_session_mode` function was removed during refactoring, however, def files still include it. This causes unresolved external symbol error.
=> [CBRD-20161] Fix Windows build - remove db_get_session_mode from def files

src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-20238
=> [CBRD-20238] Update assert check in log_append_dboutside_redo: vacuum master can call function because it allocates pages for vacuum data.

src/query/list_file.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20256
The worker was interrupted but it didn't set an error. Query Executor expects an error was set.
=> [CBRD-20256] fixes qfile_allocate_new_page to set ER_INTERRUPTED error.

src/storage/heap_file.c, src/transaction/log_applier.c, src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-20263
An update log was changed as UNDOREDO record of either RVHF_UPDATE_NOTIFY_VACUUM or RVHF_UPDATE. 
Remove unused heap_log_update_undo and heap_log_update_redo function.
=> [CBRD-20263] fix replication log record

msg/de_DE.utf8/utils.msg, msg/en_US.utf8/utils.msg, msg/en_US/utils.msg, msg/es_ES.utf8/utils.msg, msg/fr_FR.utf8/utils.msg, msg/it_IT.utf8/utils.msg, msg/ja_JP.utf8/utils.msg, msg/km_KH.utf8/utils.msg, msg/ko_KR.euckr/utils.msg, msg/ko_KR.utf8/utils.msg, msg/ro_RO.utf8/utils.msg, msg/tr_TR.utf8/utils.msg, msg/vi_VN.utf8/utils.msg, msg/zh_CN.utf8/utils.msg
http://jira.cubrid.org/browse/CBRD-20265
This is a slip of http://jira.cubrid.org/browse/CBRD-20037 which supports `extend` option of `gen_tz`. It allows to omit database name and it means to retrieve the database list file and updates all the databases listed.
=> [CBRD-20265] fix unupdated usages of gen_tz utility. database name would be omitted.

contrib/gdb_debugging_scripts/vacuum.gdb, src/query/vacuum.c, src/query/vacuum.h, src/transaction/boot_sr.c
The next block of code in vacuum_load_data_from_disk has two purposes: to find interrupted jobs and mark them accordingly and to find last vacuum data page:
```c
while (!VPID_ISNULL (&data_page->next_page))
{
VPID_COPY (&next_vpid, &data_page->next_page);
vacuum_unfix_data_page (thread_p, data_page);
data_page = vacuum_fix_data_page (thread_p, &next_vpid);
if (data_page == NULL)
{
ASSERT_ERROR_AND_SET (error_code);
goto error;
}
if (data_page->index_unvacuumed >= 0)
{
assert (data_page->index_unvacuumed < vacuum_Data.page_data_max_count);
assert (data_page->index_unvacuumed <= data_page->index_free);
for (i = data_page->index_unvacuumed; i < data_page->index_free; i++)
{
entry = &data_page->data[i];
if (VACUUM_BLOCK_STATUS_IS_IN_PROGRESS (entry->blockid))
{
/* Reset in progress flag, mark …
```
=> [CBRD-20239] Fix checking interrupted jobs when loading vacuum data. Notify vacuum of shutdown request before ending threads.

src/base/lock_free.c
http://jira.cubrid.org/browse/CBRD-20252
With help of a reproduction of 10.1.0.0020, we have understood that a race condition on `vacuum_Finished_job_queue` which is a latch-free circular queue caused the trouble. 
All Vacuum workers were infinitely iterating the loop of `lf_circular_queue_produce` to produce a job, however, Vacuum master will not work because it has to think the queue is empty. Queue pointers, `consume_cursor` and `produce_cursor` were broken due to race condition.
That's why server just consumed CPUs and throughputs dropped.
10.0 may suffer from the same issue.
=> [CBRD-20252] fix race condition on lf_circular_queue.

src/executables/util_sa.c
This is a quick fix to show usages of gen_tz with unimplemented update option.
=> [CBRD-20277] to show usages of gen_tz with unimplemented update option.

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-20278
`vacuum_Data.shutdown_requested` was not reset when SA_MODE shutdowns followed by restart. This prevents vacuum from finalizing its data. 
`createdb` with `--csql-initialization-file` option creates a new database, shutdowns it. Then it calls `csql` function to execute the given input file. `csql` subsequently calls `boot_restart_client` and `boot_restart_server`. `commit` from `boot_restart_client` complains it owns fixed buffer pages. 
The fix is to surely make `vacuum_Data.shutdown_requested` `false` during initializing vacuum.
=> [CBRD-20278] fix a crash of SA_MODE shutdown followed by restart

src/query/vacuum.c, src/storage/heap_file.c, src/transaction/log_tran_table.c
I don't have a reproduction case. I guess it is very hard to find a reproduction.
https://github.com/CUBRID/cubrid/pull/73 for [CBRD-20252](http://jira.cubrid.org/browse/CBRD-20252) shown a race condition of CAS operation with a global variable and a local variable of its copy. 
It should be safer to fix potential vulnerabilities.
=> [CBRD-20280] fix potential race condition of CAS operation.

src/storage/btree.c
The bug was quite easy to reproduce. My comment in btree_insert_mvcc_delid_into_page explains it:
```c
/* We need to check if insert MVCCID is the same as delete MVCCID for recovery purposes. Take next scenario:
*
* context:
* auto-commit off
* table t (a int), index on t(a)
* table t has row with a value 1.
*
* scenario:
* 1.   update t set a = 2 where a = 1;
* 2.   update t set a = 1 where a = 2;
* 3=1. update t set a = 2 where a = 1;
* 4.   rollback;
*
* Let's follow what happens in key 1:
* Before scenario: OID1-MVCCID1-MVCCID_NULL
* After update#1:  OID1-MVCCID1-MVCCID2
* After update#2:  OID1-MVCCID1-MVCCID2, OID1-MVCCID2-MVCCID_NULL.
* After update#3:  OID1-MVCCID1-MVCCID2, OID1-MVCCID2-MVCCID2.
*
* At rollback, we should execute undo MVCC delete key1,OID1,delid=MVCCID2, undo …
```
=> [CBRD-20262] Fix ambiguous case of undo b-tree mvcc delete

CMakeLists.txt, broker/CMakeLists.txt, cas/CMakeLists.txt, cci/CMakeLists.txt, cm_common/CMakeLists.txt, conf/CMakeLists.txt, config.h.cmake, contrib/CMakeLists.txt, cs/CMakeLists.txt, cubrid/CMakeLists.txt, demo/CMakeLists.txt, java/CMakeLists.txt, jdbc/CMakeLists.txt, locales/CMakeLists.txt, msg/CMakeLists.txt, sa/CMakeLists.txt, src/base/release_string.c, src/base/release_string.h, timezones/CMakeLists.txt, tools/CMakeLists.txt, util/CMakeLists.txt, version.h.cmake, version.rc.cmake, win/CMakeLists.txt
This is a 2nd step for introducing CMake.
Add 3 files for CMake's version info management 
- VERSION file:
- 2 dots format version string- major. minor.patch (eg: 10.1.0)
- (extra version string will be appened to version string. commit-count and hash-tag info from Git)
- (eg: 10.1.0.6826-35077f4) ("_modified" can be appended if you build with locally modified sources) 
- version.h.cmake template
- cmake will replace version.h.cmake into version.h at configure.
- generated version.h will be used for all Linux and Windows build
- version.rc.cmake template
- cmake will replace version.rc.cmake into version.rc
- generated version.rc will be used for Windows exe binary.
So, below files can be removed at next 3rd step:
- BUILD_NUMBER - used for Linux build. it contains 3 dots syntax version …
=> [CBRD-20155] introduce a new version info management way for CMake

src/query/vacuum.c, src/query/vacuum.h, src/transaction/recovery.c
The initial implementation assumed that since jobs are generated in order, the vacuum data pages will become empty also in order. Therefore, if a page is empty, it must be the first page.
The assumption was wrong. In some special circumstances, jobs from vacuum data pages that are not first can be finished first. For instance, if we have a lot of log data without any MVCC operation log records, the vacuum data pages will only have few actualy jobs to generate.
Normally, there is a fair amount of time between two successive job generations. It is very likely that jobs will also be finished in the same order. However, after restart or in stressful scenarios, vacuum master can generate multiple jobs in the same iteration. The chance that jobs are not finished in order become higher. …
=> [CBRD-20255] Handle vacuum data page deallocation when empty page is not first vacuum data page.

src/base/lock_free.c, src/base/lock_free.h, src/base/porting.h, src/query/vacuum.c
Lock-free circular queue changes:
The main issue behind these changes occurs in the next scenario:
thrd1: load queue->produce_cursor = PC1 and get preempted.
thrd2: successfully produce at PC1. queue->produce_cursor becomes bigger than PC1.
thrd3: successfully consume at PC1. queue->consume_cursor becomes bigger than PC1.
thrd1: try produce at PC1. since the entry state is alread READY_FOR_PRODUCE, the thread successfully produces here, behind current consume cursor. the entry state becomes READY_FOR_CONSUME.
all producers: when produce cursor becomes PC1 + queue->capacity, the discovered entry state is READY_FOR_CONSUME instead of READY_FOR_PRODUCE. All producers loop infinitely.
So, we have to prevent thrd3 from producing behind consume cursor. To do so, we need to include expected …
=> [CBRD-20252] Change lock-free circular queue states.

src/query/vacuum.c, src/transaction/locator_sr.c, src/transaction/log_manager.c, src/transaction/log_page_buffer.c
The code that initialized vacuum_Global_oldest_active_mvccid in recovery of vacuum data is legacy code. When vacuum data is loaded, the server is already started. Setting global oldest to log_Gl.hdr.mvcc_next_id is incorrect (hence the issue).
=> [CBRD-20290] Remove setting vacuum_Global_oldest_active_mvccid in vacuum_load_data_from_disk.

src/query/vacuum.c
This is a slip of [CBRD-20255](http://jira.cubrid.org/browse/CBRD-20255) as https://github.com/CUBRID/cubrid/pull/78.
`(*data_page)` was deallocated. It should be `prev_data_page` to follow the page chain.
=> [CBRD-20291] fix vacuum to correctly follow the page chain when deallocates a non-first vacuum data page.

src/query/vacuum.c
This is a slip of https://github.com/CUBRID/cubrid/pull/87.
=> [CBRD-20295] fixed to unfix vacuum data page when master stops generating a new job

src/base/lock_free.c, src/base/lock_free.h, src/query/vacuum.c
The vacuum_Block_data_buffer circular queue is left in an inconsistent state after it is hackishly used for recovery vacuum data blocks.
Fix by resetting to the queue to original state.
=> [CBRD-20299] Reset vacuum_Block_data_buffer circular queue after using it for recovery.

src/parser/name_resolution.c, src/transaction/locator_sr.c
Fixed by checking object existance when trying to bind to an object type name parameter.
xlocator_does_exist was also updated for the NULL class OID case.
=> [CBRD-20302] Fix fetching the OID of old named parameter which now points to a deallocated file.

src/query/vacuum.c
The issue hit an assert that expected vacuum data entries to be marked in progress, while they are still available.
The entries status has been changed to in progress. However, the page was not set dirty. While executing stand-alone vacuum, the pages were victimized. Since they were not marked dirty, they were not flushed to disk and status change was lost.
When finished job queue was filled, these pages were fixed from disk again and all their entries were available again.
Fixed by setting pages dirty when status is changed.
Also fixed the buffer size used in vacuum_data_mark_finished in order to consume the entire finished job queue.
=> [CBRD-20300] Set page dirty when changing job status; Set finished_blocks capacity  in vacuum_data_mark_finished to VACUUM_FINISHED_JOB_QUEUE_CAPACITY

src/query/vacuum.c, src/query/vacuum.h, src/storage/page_buffer.c
Issue explained:
1. Vacuum master deallocates a page VPID1 once it was filled with vacuumed blocks.
2. Checkpoint starts and notifies master to flush vacuum data. Master flushes all existing pages.
3. Vacuum master reallocated page VPID1 and appends it to vacuum data pages. The oldest_unflushed_lsa and dirty flags are not modified. Note that oldest_unflushed_lsa is older than checkpoint LSA.
4. Checkpoint checks page VPID1 and since oldest_unflushed_lsa preceeds checkpoint LSA, it wants to flush it to disk. However, the page is help by vacuum master.
5. 5 minutes passes the checkpoint thread times out on page latch.
The case was missed when vacuum data flush was implemented. Current implementation was a temporary one and it was meant to be changed.
Therefore, it was changed to new …
=> [CBRD-20309] Redesign vacuum data flush.

CMakeLists.txt, build.sh
fix to do not append 'modified' string on version string.
=> [CBRD-20155] remove modified postfix of hash tag in version string

src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-20315
server leaks `BTREE_ISCAN_OID_LIST.oidp` when it has plenty of oid buffers. 
10.0 also has the defect.
=> [CBRD-20315] fix memory leak of BTREE_ISCAN_OID_LIST.oidp, where server has plenty of oid buffers

src/transaction/log_recovery.c, src/transaction/log_tran_table.c
initialized global lowest_active_mvccid with next MVCCID
=> [CBRD-20317] fixed global lowest_active_mvccid initialization

src/parser/xasl_generation.c, src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-20303
Only the simple insert was handled using the XASL cache hit/miss, while the other special inserts, like REPLACE and ODKU, were handled client-side with generation and caching of XASL, but no usage of that cache. Everytime a new XASL was generated instead of getting it from the cache. Now we changed that and it will first try to get the XASL from the cache before generating it.
=> [CBRD-20303] Do prepare insert with XASL fixed for special inserts

src/object/trigger_manager.c, src/object/trigger_manager.h, src/transaction/locator_cl.c
http://jira.cubrid.org/browse/CBRD-20318
Even though we only have a reproduction of x86 Windows, this is a legacy and potential memory corruption issue of all versions/platforms. 
Commit and deferred trigger were not well tracked and they overran tr_Stack. This might ruin other areas and caused unexpected behavior. 
The patch also includes refactoring of trigger manager.
=> [CBRD-20318] fix issue firing a {commit,deferred} trigger overruns tr_Stack.

src/base/lock_free.c, src/query/xasl_cache.c
This fixes http://jira.cubrid.org/browse/CBRD-20352 and http://jira.cubrid.org/browse/CBRD-20353
=> [CBRD-20352] allow the smaller number of xcache entries

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20359
The format has indeed change with XASL cache redesign. I have added some of the missing information to XASL cache dump.
=> [CBRD-20359] Add entry clone count, sql hash text and sql plan text to xcache_dump

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20359
To show SQL_ID may help DBAs to troubleshoot.
=> [CBRD-20359] add SQL_ID to xcache_dump

src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-20338
Since before the `prepare insert` issue, only the simple inserts were allowed to reuse the XASL cache, if there were any simple inserts that result in an error, the error message display would be:
`In line 1, column 1,
ERROR: error message. `
Now I have removed this error type display for the inserts that are allowed to reuse the XASL cache, and now errors of this kind will be displayed as : 
` In the command from line 5,
ERROR: error message.`
For example, the `sql1.sql` from the JIRA issue reflected the errors quite good.
Previous behavior : 
```
csql -u dba basic -S -i sql1.sql
Execute OK. (0.043683 sec) Committed.
Execute OK. (0.038904 sec) Committed.
Execute OK. (0.124656 sec) Committed.
In the command from line 5,
ERROR: SQL statement …
```
=> [CBRD-20338] Wrong error display

src/query/vacuum.c, src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20389
A checkpoint flushed the page which was the first Vacuum data page and the page had not had a change, then the page was about to be deallocated. To write RVVAC_DATA_MODIFY_FIRST_PAGE log set oldest_unflush_lsa of the page and deallocated the page. The page remains as non-dirty. Then, the page is re-allocated as a Vacuum data page and the assertion hit. Its oldest_unflush_lsa is set, while its dirty flag is not.
It also includes an assertion of `pgbuf_unfix` for easier detection of such inconsistencies.
=> [CBRD-20389] fix an inconsistent vacuum data page state where its oldest_unflush_lsa_is set but dirty flag

src/query/vacuum.c
This fixes another potential leak of `dirty` flag of vacuum data page. 
When a non-first vacuum data page is deallocated, make it sure the page is marked as dirty.
=> [CBRD-20389] fix a potential leak of dirty flag of vacuum data page

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-20387
* Fixed recovering log_Gl.hdr.vacuum_data_first_vpid changes. We used to log the change in previous first page which gets deallocated. On recovery, if the page is deallocated, redo changes logged in page are skipped. Fixed by logging the VPID change in new first page.
* Fixed logging into vacuum data pages without setting them dirty.
This includes the fix from https://github.com/CUBRID/cubrid/pull/149.
=> [CBRD-20387] Fix recovery of vacuum first page change; Fix cases when pages are logged but are not set dirty

src/base/lock_free.c, src/base/lock_free.h, src/query/filter_pred_cache.c, src/query/filter_pred_cache.h, src/query/query_manager.c, src/query/xasl_cache.c, src/query/xasl_cache.h, src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-20357
* xcache_drop_all
* Iterate through all entries and mark for delete. The implementation is similar to existing implementation of xcache_remove_by_oid.
* fpcache_drop_all
* Use lf_hash_clear function (swap hash table with back buffer).
* lf_hash_clear
* Fixed some potential bugs.
* Modified return type to void (NO_ERROR was always returned).
=> [CBRD-20357] XASL/filter predicate cache drop all

src/storage/heap_file.c, src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20392
Heap page was logged with RVHF_MVCC_DELETE_NO_MODIFY_HOME but remained as non-dirty. Page might be modified due to change on vacuum status of header. 
This is detected by assertion introduced as #148.
=> [CBRD-20392] fix a heap page is logged with RVHF_MVCC_DELETE_NO_MODIFY_HOME but remains as non-dirty

src/query/xasl_cache.c
This is a regression of #151 and `cleanup_count` is badly calculated.
=> [CBRD-20357] fixes cleanup_count of xcache_cleanup

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20388
=> [CBRD-20388] Put correct page rank on watcher when group id is not initiallly provided by calling code.

contrib/gdb_debugging_scripts/lock_free.gdb, src/base/error_manager.h, src/base/lock_free.c, src/base/lock_free.h, src/executables/unittests_lf.c, src/session/session.c, src/storage/slotted_page.c, src/transaction/lock_manager.c, util/CMakeLists.txt
I fixed several issues and I added some sanity checks in lock-free hash table & unit test.
The fix is not yet complete. There is an entry leak left. So far I discovered there is an inconsistency between the number of successful inserts and deletes and the final hash-table entry count. I can imagine only two possible scenarios:
1. Insert does not link the new entry in the hash table (even though it thinks it is successful).
2. Delete removes more than one entry in one action.
=> [CBRD-20401] Fix lock-free hash table & lock-free unit test

src/base/lock_free.c, src/executables/unittests_cqueue.c, util/CMakeLists.txt
http://jira.cubrid.org/browse/CBRD-20405
lock_free.c
* Fix assert expecting that consume/produce cursor is incremented. There is one case when the cursor might not increment if the entry was not yet ready for produce/consume in the beginning. Reserving the entry fails, but by the time the assert is reached, the status was changed to ready for produce/consume. The assert was updated to check if the status was not ready when cursors is not incremented. The purpose of the assert was to make sure we don't spin over and over in the same context. If the status of entry has changed from not ready to ready to produce/consume by the time assert check is verified, we know that the context has changed for the next loop.
* Asserts abort execution in release mode also when UNITTEST_CQ is defined. …
=> [CBRD-20405] Fix bad assert in lock-free circular queue produce/consume; Improve lock-free circular queue unit test

broker/CMakeLists.txt, util/CMakeLists.txt, win/CMakeLists.txt
fix to popup admin's cmd window after UAC window when 'cubrid server/broker start' or 'broker_changer' command is executed on normal user's terminal.
(You need start 'cmd' as an Administrator mode to see a usage or output anyway)
Changes:
- set UACExecutionLevel to requireAdministrator for cubrid, cubrid_broker and broker_changer.
=> [CBRD-20350] fix to elevate UACExecutionLevel for some cubrid utilities es on Windows build

util/CMakeLists.txt
This fixes a slip of https://github.com/CUBRID/cubrid/pull/164.
=> [CBRD-20350] fix Windows build issue of UACExecutionLevel change

src/connection/connection_sr.c, src/connection/connection_sr.h, src/connection/server_support.c, src/query/execute_schema.c, src/session/session.c, src/storage/system_catalog.c, src/thread/critical_section.c, src/thread/critical_section.h
http://jira.cubrid.org/browse/CBRD-20407
replaces CSECT_CONN_ACTIVE and CSECT_CONN_FREE with CSS_RWLOCK_ACTIVE_CONN_ANCHOR and CSS_RWLOCK_FREE_CONN_ANCHOR for each.
=> [CBRD-20407] replaces CSECT_CONN_ACTIVE and CSECT_CONN_FREE with CSS_RWLOCK_ACTIVE_CONN_ANCHOR and CSS_RWLOCK_FREE_ANCHOR for each

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-20409
=> [CBRD-20409] btree_key_remove_object_and_keep_visible_first: use a copy of second_object_info.mvcc_info to match MVCC info while searching for object

src/base/perf_monitor.c, src/object/object_domain.c, src/storage/btree.c, src/storage/page_buffer.c, src/storage/slotted_page.c
http://jira.cubrid.org/browse/CBRD-20415
This includes fixes:
* replace `thread_num_worker_threads`/`thread_first_vacuum_worker_thread_index` calls from `perf_get_module_type with locals`
* force inlining `tp_domain_get_list`/`tp_domain_get_list_ptr`. misc change of `tp_domain_get_list`
* optimize `btree_generate_prefix_domain` function
* remove `MUTEX_LOCK_VIA_BUSY_WAIT`. `mutex_busy_waiting_cnt` is now obsoleted.
* introduce `SPAGE_DB_PAGESIZE` to replace `DB_PAGESIZE` calls.
=> [CBRD-20415] misc fixes for performance

src/storage/slotted_page.c, src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-20417
It is a regression of #174.
Non default sized database will not be restarted from backup, because `spage_User_page_size` is bad. To start spage and heap file manager is delayed until restoring backup.
=> [CBRD-20417] fixed to restore a non default sized database from its backup.

src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-20419
Missed out that the `or_put_varchar_internal` function set the `compressed_length` to `0`, instead of `-1`. Decided to keep the assert just to check if there are any other cases that I might have missed out.
=> [CBRD-20419] Fixing crashes cause by assert

src/object/object_primitive.c, src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-20421
In case of a failed compression due to `compressed_length >= original_size - 8`, `compressed_length` was set to `-1`. But `compressed_length` is an unsigned value so in this case everything would go wrong. Changed the `compressed_length` to be set to `0`, in case of such event.
It should also fix the memory leak issue since I think that would come from the assert that caught the error. Also I have switched the asserts to catch those that might be set bad.
=> [CBRD-20421] Fixed bad set for compressed_length

src/base/memory_alloc.c, src/object/object_primitive.c, src/object/object_primitive.h, src/object/object_representation.c
The patch fixes warnings of string compression and also beautify code layout.
=> [CBRD-20146] fix warnings of string compression and also beautify code layout

src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-20422
In or_put_varchar_internal we have set `compressed_length` to `0` when `compressed_length >= charlen - 8`. But in `mr_get_compression_length` it was set to return when `charlen >= compressed_length + 8` and it should be `charlen > compressed_length + 8`, or `compressed_length < charlen - 8`.
=> [CBRD-20422] Fixed bad set to compression_length in mr_get_compression_length

src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20431
This is a slip of #105. It badly called `locator_get_lock_mode_from_op_type`. It should be `locator_decide_operation_type`.
=> [CBRD-20431] fixed bad function call from xlocator_does_exist

src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20435
It is also a slip of #105.
When a client does not know class_oid, it just to pass `NULL` to let server to figure it out. 
Only debugging builds did.
=> [CBRD-20435] fixed xlocator_fetch for release build to figure out class_oid when a client does not know

src/base/object_representation_sr.c, src/executables/compactdb.c, src/storage/btree.c, src/storage/heap_file.c, src/storage/heap_file.h
http://jira.cubrid.org/browse/CBRD-20432
This is a slip of #105.
`scancache` was not given to `heap_get_visible_version`.
=> [CBRD-20432] fixed crash due to missing scancache from heap_get_alloc

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20421
Due to bad error handling of `_setjmp`, in `or_put_varchar_internal`, if an error like `ER_TF_BUFFER_OVERFLOW` was encountered, it would jump out of the function and let `string` and `wrkmem` leaked. We have removed the `_setjmp` in this scenario and handle the errors that might appear.
We might also want to remove any `_setjmp` usage other than this, to have better error handling in these situations.
=> [CBRD-20421]Removed _setjump in heap_attrinfo_transform_to_disk_internal

src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-20434
It fixes latch leak of `catalog_get_dir_oid_from_cache`. 
This is a legacy issue and #105 reveals the defect.
=> [CBRD-20434] fixed latch leak of catalog_get_dir_oid_from_cache

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20437
It just fixes the first issue of CBRD-20437. 
`class_oid_local` was not initialized.
=> [CBRD-20437] fixes UMR of class_oid_local from heap_get_visible_version_internal

src/storage/heap_file.c, src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20439
Scan cache is required for locator_get_object ().
=> [CBRD-20439] Use scan_cache when calling locator_get_object

src/object/object_representation.c, src/storage/heap_file.c
We just set `buf->error_abort` to `0`, and if there are any `ER_TF_BUFFER_OVERFLOW` errors that might have returned from `or_put_*` functions, we clean `wrkmem` and `compressed_string`, then set back the `buf->error_abort` and do a `or_overflow(buf)`.
=> [CBRD-20437] Reverted _setjmp removal and add a workaround for possible leaks

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20440
Fixed a memory leak regarding a `dbvalue` that was not freed.
=> [CBRD-20440] Fixed memory leak that causes dump in server

src/base/object_representation_sr.c, src/object/object_primitive.c, src/object/object_primitive.h, src/object/object_representation.c, src/object/virtual_object.c, src/query/query_executor.c, src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-20430
Since `pr_data_writeval_disk_size` would simulate a compression for `STRING` and `VARNCHAR` types, I have added another function to avoid it.
=> [CBRD-20430] Optimizing compressions

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20452
`DB_VALUE` was not cleared.
=> [CBRD-20452] fix lea memory leak of HQ

src/base/lock_free.c
http://jira.cubrid.org/browse/CBRD-20451
Lock-free freelist claim: start a lock-free transaction (if it was not started yet) without incrementing transaction ID.
The scenario that otherwise creates problems:
1. t1: claim from freelist. no transaction is started. top of freelist available stack is read, next of top is read. thread is preempted before calling CAS on top with next.
2. t2: claim top from freelist available stack.
3. other transactions claim other entries from stack.
4. t2: retire claimed entry back to freelist. Decide to also transport the element. Since t1 has no transaction, the entry can be transported and added back to top of available stack. However, this time next has a different value.
5. t1: swap top with old next value. Since the old top has been recycled, the …
=> [CBRD-20451] lf_freelist_claim: start lock-free transaction.

cmake/CPackWixPatch.cmake.in
Fix to remove the 'REPAIR' option in Windows ARP (Add/Remove Program)
=> [CBRD-20462] remove REPAIR option for Windows ARP

contrib/gdb_debugging_scripts/log_records.gdb, src/base/error_code.h, src/base/perf_monitor.c, src/base/perf_monitor.h, src/cm_common/cm_mem_cpu_stat.c, src/cm_common/cm_stat.h, src/communication/network.c, src/query/vacuum.c, src/query/vacuum.h, src/thread/thread.h, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_page_buffer.c, src/transaction/log_recovery.c, src/transaction/log_tran_table.c, src/transaction/log_writer.c
http://jira.cubrid.org/browse/CBRD-20340
Changes:
* Replaced hash with an array to store log pages in memory.
* Removed synchronization on reading log pages from buffer.
* Changed some return types.
=> [CBRD-20340] Redesign the log page buffer.

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-20471
When the function logpb_flush_all_append_pages is called, the page buffer is replaced with an end of log record and is read wrong by other threads, so the operation should be made on a copy, not directly on the buffer.
=> [CBRD-20471] fix overwriting log_page_buffer record with end of log record during flush

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20469
=> [CBRD-20469] do not use COPY in case of overflow record if recdes->data=scan_cache->area

contrib/gdb_debugging_scripts/log_records.gdb, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-20479
There might be no page flushed, since we now want to avoid flushing page including EOL until the end of flush. 
```C
assert (last_idxflush != -1);
```
is no longer true.
=> [CBRD-20479] remove invalid assertion of logpb_flush_all_append_pages

src/base/lock_free.c, src/base/lock_free.h, src/compat/db_admin.c, src/compat/db_info.c, src/object/authenticate.c, src/object/object_accessor.c, src/object/object_primitive.c, src/object/object_template.c, src/object/set_object.c, src/object/transform_cl.c, src/object/work_space.c, src/object/work_space.h, src/query/execute_statement.c, src/transaction/locator_cl.c
http://jira.cubrid.org/browse/CBRD-20274
The mvcc_link was relevant only for partititions update when objects may change their `OID `and class `OID`. 
The mechanism to handle these cases was restored as it was before mvcc.
=> [CBRD-20274] Removing mvcc_link

src/transaction/log_page_buffer.c
The old condition for setting the dirty flag in logpb_end_append, that the log_Gl.append.prev_lsa.pageid and log_Gl.hdr.append_lsa.pageid must be equal was wrong. The condition should be that the append.prev_lsa and hdr.append_lsa must be different to set the dirty flag.
=> [CBRD-20472] Fix wrong condition for dirty flag in logpb_end_append

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-20483
This is a slip of logpb_flush_all_append_pages refactoring. Sorry for the error :).
However, log entries are really useful!
=> [CBRD-20483] logpb_flush_all_append_pages: check physical pageids to be successive before collecting buffer for flush

src/transaction/log_page_buffer.c
The logic flushed at most 2 consecutive pages.
=> [CBRD-20483] logpb_flush_all_append_pages: to fully collect successive pages to flush them at once

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-20483
The best description can be found in this comment:
```c
/* how this works:
* ok, so we might have to flush several pages here. if there is only one page, the implementation is straight
* forward, just flush the page.
*
* however, if there are two or more pages, we really need to make sure that the first page, where previous end of log
* record resides (where nxio_lsa points), is flushed last! we cannot validate the new end of log record until we are
* sure all log pages have been flushed!
* so, we'll do a two-step flushing: in the first step we skip nxio_lsa page and flush all other pages. in the second
* step we flush the nxio_lsa page.
*
* the story becomes a lot more complicated when a log entry is only partially appended before flush is called. …
```
=> [CBRD-20483] Fix flushing log

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-20494
The bug is possible only in stand-alone mode.
The problem is that stand-alone mode for vacuum forces a restart when finished blocks queue becomes full. Then completed blocks are removed. In some cases, the cursor can become invalid.
1. If right after current cursor we already have vacuumed blocks (e.g. blocks with no MVCC ops which are considered vacuumed from the start), they may be skipped or even removed. We need to make sure that the cursor is not left behind index_unvacuumed in cursor page.
2. When page is removed. The process can stop exactly on last vacuum data page entry. That page may be reset (if it is last) or may be removed completely (and deallocated). We need to make sure the cursor does not point to deallocated page and is moved next …
=> [CBRD-20494] Advance vacuum job cursor when it points to page being deallocated

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-20499
Archive logs needed for vacuum might be purged during restart recovery. 
It should be postponed until vacuum is available.
=> [CBRD-20499] not to remove archive logs during restart recovery.

src/connection/connection_sr.c, src/connection/server_support.c, src/thread/critical_section.c, src/thread/critical_section.h, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-20502
This is a preliminary to enhance monitoring of readers to `SYNC_CRITICAL_SECTION`.
=> [CBRD-20502] change tdes->cs_topop implementation as SYNC_RMUTEX

src/query/vacuum.c, src/storage/page_buffer.c, src/storage/page_buffer.h
http://jira.cubrid.org/browse/CBRD-20504
The fix count check was outdated. A while ago we changed access on vacuum data pages and how they get flushed on checkpoint. In the crash, checkpoint thread also fixed page during fix count check. Fix count was 2 instead of 1.
The purpose of the check was not to leak any pages. Since this is vacuum data thread, the check now has two components:
1 verify first and last vacuum data pages are only fixed once.
2 get number of page holds. it should be one if last page and first page are the same, or two otherwise.
=> [CBRD-20504] Update fix count check

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20510
fix xasl cache entry count when user uses recompile hint but entry does not exist
=> [CBRD-20510] fix xasl cache entry count

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-20507
The bug was discovered at recovery while redoing a LOG_COMPENSATE.
The LOG_COMPENSATE was an undo that was executed before crash but its page wasn't flushed. At recovery redo `vacuum_Global_oldest_active_mvccid` is 0 and because of that it was considered not vacuumable.
=> [CBRD-20507] Change vacuum_rv_check_at_undo to clean flags at recovery also

src/object/object_representation.c, src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20162
or_mvcc_get_chn was called after insid and delid, which caused some errors.
This is a slip for CBRD-20162.
=> [CBRD-20162] Fix or_mvcc_get_chn and or_mvcc_get_insid order (slip from #235)

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-20518
=> [CBRD-20518] vacuum_recover_lost_block_data: fix reading from log record header when log page is changed

src/executables/load_object.c, src/object/transform_cl.c, src/storage/catalog_class.c
In transform_cl.c, in function tf_mem_to_disk, chn was set after insert id, but the order was changed, so it must be set before.
=> [CBRD-20524] In transform_cl.c chn was set after insert id

src/storage/heap_file.c, src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20529
lockdb hit assertion, because it forces no wait (this means latching will be done as conditionally) and latching a page (to show mvcc info) may fail.
This is a quick hit.
=> [CBRD-20529] lockdb forces no blocking and latching a page may fail

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20510
=> [CBRD-20510] xcache_insert: fix cache entry count when new entry is not inserted and is not recompiled

src/base/perf_monitor.c, src/base/perf_monitor.h, src/transaction/boot_sr.c, src/transaction/mvcc.c
Affected issues:
http://jira.cubrid.org/browse/CBRD-20533
http://jira.cubrid.org/browse/CBRD-20535
http://jira.cubrid.org/browse/CBRD-20536
Maybe also:
http://jira.cubrid.org/browse/CBRD-20538
- performance statistics: skip collecting stats if perfmon is not initialized
- STATIC_INLINE internal perfmon functions
- check perfmon is tracking before calling perfmon_mvcc_snapshot
- initialize perfmon on server after css_init_conn_list
=> [CBRD-20533] Fix performance monitor redesign issues

src/compat/dbi_compat.h, src/compat/dbtype.h
http://jira.cubrid.org/browse/CBRD-20542
This adds the `is_max_string` flag in the `sm`, `medium` and `large` structures from the `db_char` union. Also, it has been redefined to `unsigned char`.
=> [CBRD-20542] Added the flag in the other structures

src/base/perf_monitor.c, src/transaction/boot_cl.c, src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-20543
This is a slip of #259.
Before #259, pstat_Global was initialized twice: one for SA_MODE and the other for SERVER_MODE. 
To avoid multiple initialization, it gave 0, no. of trans for SA_MODE and MAX_TRANS for SERVER_MODE. 
As #259, it is initialized once for SA_MODE with 0 transaction. This causes the crash. 
One another change is to allocate one more transaction slot for easier indexing with tran_index. Please notice that tran_index starts with 1 and 0 is reserved for system transaction.
=> [CBRD-20543] fixes initialization of pstat_Global for SA_MODE.

src/base/perf_monitor.c
http://jira.cubrid.org/browse/CBRD-20544
`perfmon_set_start` can be reached without initialization as `restoredb` for the case.
=> [CBRD-20544] remove a bad assertion of perfmon_set_stat. It may be reached without initialization.

src/base/perf_monitor.c
http://jira.cubrid.org/browse/CBRD-20545
watcher disappeared during collection. It is known race condition.
=> [CBRD-20545] fixes assertion and check for perfmon_add_stat_at_offset

src/object/object_primitive.c, src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-20448
After the commit #246  there was introduced another case of compression and the parameter enable_string_compression is not checked. (It could be a slip).
=> [CBRD-20448] Added a new case for enable_string_compression

src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-20565
After the patch with the compression enhance, `lengthval` and `writeval` functions will require a clear of the possible compressed string that might be stored in the local `DB_VALUE` inside the enumeration function.
=> [CBRD-20565] Leak issues

src/object/object_domain.c, src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-20572
Since `VARCHAR` and `VARNCHAR` `DB_VALUE` types will now hold a possible `compressed_string`, when coercion is done, in some cases it would just change the type of the original `DB_VALUE`, therefore it might have become a `CHAR` or `NCHAR` type, types that could not have a `compressed_string` field in it. So now we just have to copy in the destination instead of just switching the types.
=> [CBRD-20572] Fixed leak of bad value coercion

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20571
This is a slip of #289.
Since `last_cleaned_time` was not set at startup, the very first query execution of server tried to clear xasl cache. The patch sets it as the current time at server startup. 
A message of plandump, `Full cache cleanups:` is also changed as `Cache cleanups:`.
=> [CBRD-20571] set xcache_Global.last_cleaned_time as current time of startup

src/base/memory_alloc.c
=> [CBRD-20570] fix typo on db_private_realloc_external

src/executables/util_sa.c, src/object/set_object.c, win/cubridcs/cubridcs.def, win/cubridsa/cubridsa.def
After the #291 there were introduced new functions, db_private_realloc_debug and db_private_realloc_release, and was defined a macro db_private_realloc. The compilation failed because it expected to find the function db_private_realloc, not just a macro, so I removed the old macro and added db_private_realloc_debug and db_private_realloc_release.
=> [CBRD-20570]  Added definitions for db_private_realloc_debug and db_private_realloc_release

src/parser/type_checking.c
A wrong attribute was set for disk_size function, which doesn't need collation. This is a slip of #270. I also added the disk_size function on the is_able_to_determine_return_type .
=> [CBRD-20576] disk_size required arguments with compatible collations

src/query/query_executor.c
#297 includes "dbval.h" into query_executor.c and `db_make_xxx` calls are expanded by its corresponding macros.
Since the macros refers to the argument multiple times, `out_values[idx_val++]` is incorrect and compiler complains it.
=> [CBRD-20583] fixes warnings related to db_make_xxx macro expansion

src/base/perf_monitor.c, src/base/perf_monitor.h, src/base/tz_compile.c
http://jira.cubrid.org/browse/CBRD-20580
Print all the timer info for timer type statistic. Fix pointer update bug for dump in buffer functions
in perf_monitor.c .
=> [CBRD-20580] Print all the timer info for timer type statistic

src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-20594
The crash is caused by memory leak. The leak occurs when executes a join and the inner is scanned using index coverage. The index is scanned twice.
Currently, index coverage uses the same db_value to write in partial result (`iscan_id->indx_cov.list_id`) and in final result (`xasl->list_id`). Thus, the value is used to dump in index coverage list file first, through `iscan_id->indx_cov.output_val_list` regu variable (`btree_dump_curr_key` function).
After index scanning, the values is used to write in xasl list file through `xasl->outptr_list` (`qexec_end_one_iteration` function).
The value must be cleared if we scan the same tree twice. Otherwise, the db_value written with `xasl->outptr_list` will not be clearead and will be filled with the next …
=> [CBRD-20594] Clear val list regu variable before btree search in case of index covering

src/query/fetch.c
This fixes:
http://jira.cubrid.org/browse/CBRD-20599
http://jira.cubrid.org/browse/CBRD-20600
http://jira.cubrid.org/browse/CBRD-20601
http://jira.cubrid.org/browse/CBRD-20603
http://jira.cubrid.org/browse/CBRD-20604
I know the patch may cause potential memory leak but I've not found a counter case. 
I'd like to propose to revert the change to fix the regression cases and consider a fix for potential leaks with a repro case.
=> [CBRD-20599] revert potential leak fix on fetch_copy_dbval

src/base/perf_monitor.c
http://jira.cubrid.org/browse/CBRD-20615
I added searching also for computed statistics. In the current implementation those statistics will not appear in the statdump if the searched string isn't found in the statistic name. Basically the other statistics will not be listed as it was in the previous performance monitor implementation.
=> [CBRD-20615] Search also in computed statistics names

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-20620
`CSECT_DISK_CHECK` leaked.
=> [CBRD-20620] fixes CSECT_DISK_CHECK leaks

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20621
latch was leaked in file_dump.
=> [CBRD-20621] fixes latch leak of file_dump

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-20627
Fixed the free sector count of temporary purpose volume after resetting.
=> [CBRD-20627] disk_volume_boot: fix number of free pages for temporary purpose volumes

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20651
It fixes UMR of `stop` in `file_tracker_map`.
=> [CBRD-20651] fixes UMR of stop in file_tracker_map

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20654
It should unfix `page_ftab` not `page_fhead`.
=> [CBRD-20654] fixes bad unfix of file_temp_reset_user_pages

src/storage/file_manager.c, src/storage/file_manager.h
http://jira.cubrid.org/browse/CBRD-20647
`initial_size` may suffer from overflow when `npages` is big.
=> [CBRD-20647] fixes overflow of initial_size of FILE_TABLESPACE

src/query/query_manager.c, src/query/query_manager.h, src/session/session.c, src/storage/file_manager.c, src/storage/file_manager.h
http://jira.cubrid.org/browse/CBRD-20629
temporary file cache retirement had a bug. it tried to find the entry of preserved file in transaction list (even though it was removed when the file was preserved).
call file_temp_retire_preserved to notify temporary file cache that the file is no longer in transaction list.
=> [CBRD-20629] file temporary cache: fix retiring preserved files

src/query/vacuum.c, src/storage/btree.c, src/storage/disk_manager.c, src/storage/overflow_file.c
fixes incorrect usage of pgbuf_set_page_ptype and also beautify codes.
=> [CBRD-20146] use pgbuf_check_page_ptype instead of pgbuf_set_page_ptype in overflow_insert

src/transaction/log_manager.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-20639
RVBT_LOG_GLOBAL_UNIQUE_STATS_COMMIT recovery index is special because it affects only in memory data structure. Global stats are only flushed on checkpoint. Therefore, their recovery should be applied every time and undoing stats should be never compensated.
=> [CBRD-20639] undo: fix undoing RVBT_LOG_GLOBAL_UNIQUE_STATS_COMMIT

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-20185
* volumes are booted before recovery. the temporary purpose volumes are reset and their pages are set dirty, however, right before recovery, the page buffer is invalidated without flushing any bcb. the changes are then lost. fix by flushing pages immediately if LOG_ISRESTARTED is false.
* correct nsects_sys changes and logging.
=> [CBRD-20185] disk_stab_init: fix flushing pages; fix nsects_sys

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20664
qexec_destroy_upddel_ehash_files: don't allow interruptions while destroying ehashes
=> [CBRD-20664] qexec_destroy_upddel_ehash_files: don't allow interruptions

src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-20671
Warnings remain in memory. file_create has a debug check at the end that no errors are set if it is executed successfully. Replace warning with a notification to avoid leaking the error.
=> [CBRD-20671] do_alter_index_rebuild: notification instead of warning

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20669
> assert (pgbuf_has_any_waiters (crt_watcher.pgptr) == false);
I think the check does not belong here. @razvanradulescu please confirm.
=> [CBRD-20669] heap_remove_page_on_vacuum: move no waiter check

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20661
fix checking that partial table is file header is not fully used
=> [CBRD-20661] file_create: fix bad check

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-20674
Volume is invalid, but it should not crash.
=> [CBRD-20674] disk_is_page_sector_reserved_with_debug_crash: assert (!debug_crash)

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20634
error is leaked and file_create crashes
=> [CBRD-20634] heap_object_upgrade_domain: clear error when it is ignored

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20655
heap_hfid_cache_get did not always ended lock-free transaction (e.g. when error occurs while reading hfid and file type).
this may cause lock-free inconsistencies.
another shell case that may fail for the same reason:
> cubrid-testcases-private-ex/shell/_06_issues/_12_2h/bug_bts_8198/cases/bug_bts_8198.sh
=> [CBRD-20655] heap_hfid_cache_get: always call lf_tran_end_with_mb

src/storage/slotted_page.c
http://jira.cubrid.org/browse/CBRD-20678
This fixes a slip of https://github.com/CUBRID/cubrid/pull/352.
=> [CBRD-20678] fixes page latch leak of spage_slots_start_scan

src/storage/slotted_page.c
http://jira.cubrid.org/browse/CBRD-20686
ER_DIAG_PAGE_NOT_FOUND message expects pageid as the first argument and volid as the second.
=> [CBRD-20686] fixes arguments of ER_DIAG_PAGE_NOT_FOUND messages

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-20690
Removed the assert that checked bug info flag is not set. Logging new key insert, when the key is overflowing, is now done under a system operation and is logged with RVBT_RECORD_MODIFY_UNDOREDO. The debug info is not really saved to undo data (there is no undo data), but is saved in redo data, so the flag is set in rcv.offset).
Therefore, the assert is no longer valid.
=> [CBRD-20690] btree_rv_record_modify_internal: remove outdated assert

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-20687
Creating temporary volumes also log undo of RVDK_FORMAT. If the log is rollbacked, it is not yet added to cache. If it is undone during recovery, no temporary volumes are loaded to cache. It is enough to update volid check to:
> assert (disk_Cache->nvols_perm <= volid);
=> [CBRD-20687] disk_rv_undo_format: expect temporary volumes

src/transaction/log_page_buffer.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-20695
* logpb_checkpoint
- use act_tdes not tdes
- check act_tdes->rcv.sysop_start_postpone_lsa instead of act_tdes->state
* log_rv_analysis_sysop_end
- accept that tdes->state can also be TRAN_UNACTIVE_UNILATERALLY_ABORTED and correct the transaction state
note: I wrongfully assumed we can surely have state either TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE or TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE. the fact that transactions are logged during end checkpoint tricked me into believing this. However, the analysis starts with start checkpoint LSA and end checkpoint can come much later. If a transaction's first found log record is end system op of run logical postpone, its state is TRAN_UNACTIVE_UNILATERALLY_ABORTED and not one of the expected states.
I …
=> [CBRD-20695] Fix recovery of system operations postpones

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20703
This patch purpose is to optimize index loading. Specifically it tries to optimize file_numerable_find_nth function which takes a lot of loading index time because it goes through many of user page table pages every time is called.
Since the pattern of file_numerable_find_nth is to find nth, then nth+1, then nth+2 and so on, we can cache the location in user page table for last search. Next search is likely find the page it's looking for in the same user page table page or in next, significantly reducing the number of fixed/unfixed pages.
Note that deallocating a page will reset the cached search location (external sort never calls it anyway, so it is just a safeguard).
=> [CBRD-20703] file numerable find nth: cache last search location

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20713
When an invalid error is discovered during file_track_map call, disk_map_clone is freed and set to NULL. Then disk_map_clone is accessed, thus the segmentation fault.
I don't know what the invalid error was, but I hope debug mode can discover it. Fixed the NULL access.
=> [CBRD-20713] file_tracker_check: fix access on NULL disk_map_clone

src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-20711
log_read_sysop_start_postpone: fix reading LOG_REC_SYSOP_START_POSTPONE when it doesn't fit
=> [CBRD-20711] log_read_sysop_start_postpone: fix reading LOG_REC_SYSOP_START_POSTPONE

src/base/xserver_interface.h, src/communication/network_interface_cl.c, src/communication/network_interface_cl.h, src/communication/network_interface_sr.c, src/storage/catalog_class.c, src/storage/file_manager.c, src/storage/heap_file.c, src/transaction/locator_sr.c, src/transaction/lock_manager.c, src/transaction/lock_manager.h, src/transaction/log_manager.c, src/transaction/log_tran_table.c, src/transaction/transaction_cl.c
http://jira.cubrid.org/browse/CBRD-20691
Lock Manager changes:
* Do not unlock the current locks when reset isolation to `TRAN_READ_COMMITTED`
* Removing `lock_unlock_object (..., X_LOCK, false);` because it does nothing.
* Removing `lock_unlock_scan (...);` No effect.
* Removing `LK_ACQUISITION_HISTORY`. This consumed huge amount of main memory.
* To release instance locks to escalate to class lock for entire isolation levels. It did only for `TRAN_READ_COMMITTED`.
* Removing `lock_demote_shared_class_lock`
* Changing `lock_remove_all_inst_locks`: `TRAN_READ_COMMITTED` releases only shared locks of non-MVCC tables. 
* Changing `lock_unlock_objects_lock_set`: same as above
* Changing `lock_unlock_classes_lock_hint`: same as above
* Introduces `lock_unlock_object_by_isolation`
* Introduces …
=> [CBRD-20691] Revise Lock Manager for MVCC

src/object/authenticate.c, src/object/authenticate.h, src/object/quick_fit.c
http://jira.cubrid.org/browse/CBRD-20659
* change default password encryption method as SHA2
* The legacy passwords are also supported. DBAs should reset legacy passwords to encrypt them by SHA2.
=> [CBRD-20659] change default password encryption algorithm as SHA2

src/transaction/log_manager.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-20725
* fix updating tdes.posp_nxlsa when postpone of logical run postpone is recovered.
* do not set log_record->run_postpone.is_sysop_postpone when log_sysop_end_recovery_postpone is called.
* fix log_rv_analysis_sysop_start_postpone  when state is not the expected one.
* fix checking for system op postpone inside system op postpone
=> [CBRD-20725] fix postpone recovery

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20734
Thread was interrupted while creating a new file but error was not propagated.
=> [CBRD-20734] fixes file_create to properly return error code

src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-20735
`btree_load_new_page` returned NO_ERROR for error cases.
=> [CBRD-20735] fixes btree_load_new_page to propagate error

src/query/query_executor.c, src/query/scan_manager.c, src/query/scan_manager.h
rename `stats` of `SCAN_ID` as `scan_stats` for readability and easier browsing.
=> [CBRD-20146] rename stats of SCAN_ID as scan_stats

src/base/system_parameter.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20731
Set decache flag to XASL members of the clone. This is needed to avoid memory leak when clears the clone.
=> [CBRD-20731] fixed memory leak issue

src/object/trigger_manager.c, src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20743
In this scenario, the error was reached because of the mechanism from **tr_drop_trigger_internal**(). It is supposed to always recheck the existence of the trigger after it is dropped.
=> [CBRD-20743] xlocator_fetch: set warning instead of error for non-existent objects

src/storage/heap_file.c
Some functions may set errors before calling `heap_get_class_name_alloc_if_dif ()`.
=> [CBRD-20747] Do not expect no error is set when reaching heap get class name

src/storage/extendible_hash.c
http://jira.cubrid.org/browse/CBRD-20751
Redo log for creating temporary ehash was written.
=> [CBRD-20751] redo log for creating temp ehash was written

src/base/system_parameter.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20719
Set partition pruning as false when clear access spec type. This is needed to perform partition pruning, next time when reuse the clone.
=> [CBRD-20719] fixed incr on partition

src/executables/util_sa.c, src/storage/disk_manager.c, src/storage/disk_manager.h, src/storage/storage_common.h, src/transaction/boot_sr.c, src/transaction/boot_sr.h
The database volume size from createdb mesage was set to its real value, according to the minimum number of sectors and the number of  pages  per sector.
=> [CBRD-20696] Correct disk space from createdb message

src/query/query_manager.c, src/query/query_manager.h, src/session/session.c, src/storage/file_manager.c, src/storage/file_manager.h
http://jira.cubrid.org/browse/CBRD-20748
Remove file_temp_save_tran_file, it was incorrectly used.
When calling qmgr_free_query_temp_file_helper, we should consider that holdable queries were preserved.
=> [CBRD-20748] fix freeing query temporary files considering holdable/preserved

src/transaction/log_applier_sql_log.c
http://jira.cubrid.org/browse/CBRD-20756
sql log was badly written with `current_value` of the serial. 
Since incrementing the serial is not applied at the moment of logging, logging with `current_value` is incorrect. 
It is one of tasks of legacy patches.
=> [CBRD-20756] applylogdb badly did sql logging of incrementing a serial object

src/executables/util_service.c
http://jira.cubrid.org/browse/CBRD-20761
Now only hides arguments of an exec from command line.
=> [CBRD-20761] fixes crash to hide comamnd args of internally forked execs

src/query/cursor.c, src/query/list_file.c, src/query/query_executor.c, src/query/query_list.h, src/query/query_opfunc.c, src/query/query_opfunc.h
http://jira.cubrid.org/browse/CBRD-20766
The compressed string is not cleared if the regu variable must be cleared at clone decache.
The issue occurs because the compressed string is cleared when generates the tuple descriptor. However, I'm not sure that we need to call pr_clear_compressed_string in qdata_generate_tuple_desc_for_valptr_list. 
I expect that compressed string to be cleared, together with uncompressed string, later.
Maybe we need to analyze more whether we need to clear compressed string in qdata_generate_tuple_desc_for_valptr_list.
=> [CBRD-20766] fixed crash caused by clear compressed string

src/query/query_executor.c, src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-20722
The list_id should not be set to null, since is reused. I suppose that this is the source of the issue, but I don't have a simple scenario.
=> [CBRD-20722] Fixed crash caused by null list_id when executes analytic

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20740
The issue:
- a new page was requested when adding a full sector as the extdata was full. 
- while allocating this page, another sector becomes full and `file_table_add_full_sector` is called again. Since the newly allocated page was not added to the extdata yet, another page needs to be allocated. 
These steps are repeated until the newly allocated page doesn't fill a partial sector.
Not only that this generated more pages than necessary, but also the vpid_next links from extdata were overwritten in `file_table_add_full_sector` which caused the crash.
FILE_ALLOC_TABLE_PAGE_FULL_SECTOR was added to specify in file_perm_alloc if the page was requested when adding a full sector. In this way the allocated page is added to full sectors extdata directly …
=> [CBRD-20740] file_perm_alloc: handle the case when the page was requested from file_table_add_full_sector

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20806
extdata_new_ftab corresponds to page_ftab.
=> [CBRD-20806] correct file_log_extdata_set_next arguments

src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-20825
In fact, it is not a CTE but a type resolution issue. 
These functions:
```c
case PT_YEARF:
case PT_DAYF:
case PT_MONTHF:
case PT_DAYOFMONTH:
case PT_DAYOFWEEK: 
case PT_DAYOFYEAR:
case PT_QUARTERF:
case PT_TODAYS:
case PT_WEEKDAY:
```
accepted two types of argument: `string` and `date` type.
`Timestamp` and `Datetime` types were accepted as `string`.
=> [CBRD-20825] fixed type resolution of DAYOFYEAR (and other functions)

src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20819
A group by column from the CTE was found in the CTE spec attributes. Since the CTE spec was one level higher than the query from within, it was considered a correlated query which was crashing at execution.
With the fix, group by columns will be identified only in the curent scope attributes, while executing pt_bind_names.
=> [CBRD-20819] Avoid name binding lookup of group by column outside current scope, level 0

src/parser/name_resolution.c, src/parser/parse_tree.h
http://jira.cubrid.org/browse/CBRD-20835
CTE spec attributes were resolved as for an entity spec. Extending condition should handle CTE specs correctly.
=> [CBRD-20835] Extend condition to differentiate entity specs from derived table/cte

src/parser/xasl_generation.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20828
The recursive and non-recursive parts remained linking to the same list_id, because of the execution error. 
XASL clones kept the list_id in both parts which caused the crash at the second run.
=> [CBRD-20828] CTE - fix recursive list id leak

src/query/query_dump.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20857
Query trace for CTE were missed as well as XASL dump.
You can see a sample query trace result of both json and text format from [here](http://jira.cubrid.org/browse/CBRD-20857?focusedCommentId=4740718&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4740718). 
I just leave dumping details of XASL for CTE as a TODO task.
=> [CBRD-20857] to support query trace for CTE

src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-20843
Correlation level is needed for CTEs to avoid adding it multiple times to the aptr list. The correlation level of a CTE will be kept in its non-recursive part query.
=> [CBRD-20843] Consider correlation level of CTEs when generating XASL aptr list

src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20860
Non recursive part pointer remained outdated, which caused the crash.
=> [CBRD-20860] Fix outdated pointer of cte non recursive part

src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20820
Removed `PT_STOP_WALK `from `pt_resolve_cte_specs`. 
Also resolved leaks of `node->etc` from `pt_resolve_spec_to_cte `by adding `pt_count_ctes_post` to tree walk.
=> [CBRD-20820] pt_resolve_cte_specs: do not stop parse tree walk

src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20830
Continue resolving CTE specs in tree after one was found. PT_LIST_WALK was used as an optimization, but it is not correct.
=> [CBRD-20830] Removed PT_LIST_WALK from pt_resolve_spec_to_cte

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20870
Parts of error log formats were regarded as arguments because of extra commas.
=> [CBRD-20870] fixes bad debugging logs of xasl cache

src/parser/parse_tree.c, src/parser/parse_tree.h, src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-20857
This is a quick fix for `pt_short_print`. 
`pt_short_print` printed the entire text of PT_NODE and truncated it as 60. It may use huge amount of string buffer.
=> [CBRD-20857] introduce max_print_len of parser for pt_short_print

src/storage/btree_load.c, src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20765
- allow rebuild foreign key using 'alter table .. add constraint...' on the table which is not empty
- allow one or more NULL values for foreign key like [CBRD-20523]
- found used function is defined: (locator_check_primary_key_upddel(...))
in the file src/transaction/locator_sr.c:4020 linw, 
a function 'static int locator_check_primary_key_upddel()'  was defined 
but nobody references that function. (marked '#if 0  #endif' compiler directive)
=> [CBRD-20765] Allow Re-creation of foreign key having one or more NULL values for foreign keys

src/base/release_string.c, src/query/vacuum.c, src/storage/file_manager.c, src/storage/file_manager.h, src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20842
Vacuum heap pages requires two pieces of information: hfid and file type. These are regularly obtain from heap cache (where key is class OID), even if class is dropped (removing the info from cache is postponed until all vacuum workers are notified of this change).
However, if class is dropped immediately after server restart, the information is not in cache. It cannot be obtained from class record either (since it is deleted by the time vacuum gets here). One place that can be accessed is file header. File type was  already there, but I had to also add HFID in the heap descriptor.
Also call cleanup dropped files when oldest MVCCID not vacuumed advances.
=> [CBRD-20842] Fix vacuum crash on dropped file after restart

src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-20846
The CTE pointers have to be handled separately in parse tree copy, otherwise they will remain pointing to the CTEs from the old tree.
PT_TREE_COPY_INFO was created to keep a list of cloned CTE nodes in new/old pairs. This list will be used for each CTE pointer to identify the updated CTE node address.
=> [CBRD-20846] Handling of CTE pointers in parse tree copy 

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20901
pgbuf_fix: register fixed to meter before checking if page is deallocated (and unfixed)
=> [CBRD-20901] pgbuf_fix: register to track meter before unfix

src/parser/semantic_check.c, src/parser/semantic_check.h, src/parser/type_checking.c, src/parser/view_transform.c
http://jira.cubrid.org/browse/CBRD-20850
The order_by clause should be also removed when the query is marked with `PT_DISTINCT`. 
Without CTE, the order_by was removed mq_make_derived_spec and the semantic was checked afterwards.
I am not sure if `pt_try_remove_order_by `function belongs to **semantic_check.c** Let me know if you have suggestions.
=> [CBRD-20850] Remove order by from range expression argument

src/query/query_executor.c, src/query/query_manager.c, src/query/query_opfunc.c, src/query/scan_manager.c, src/query/show_scan.c, src/query/string_opfunc.c, src/storage/btree.c, src/storage/catalog_class.c, src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-20909
6d8aa6a fixes memory leak. 
It also changes avoid compat APIs from server.
=> [CBRD-20909] fixes memory leak of select_btree_node_info scan

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-20911
Fix by logging RVPGBUF_NEW_PAGE using undoredo instead of redo. A newly allocated page should be deallocated on rollback (type set to NULL).
=> [CBRD-20911] log RVPGBUF_NEW_PAGE undoredo

src/storage/extendible_hash.c
http://jira.cubrid.org/browse/CBRD-20911
note: this bug crashes sql regressions.
=> [CBRD-20911] ehash_create_helper: fix initializing temporary page

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20697
This issue is that vacuum deallocated pages unfixed by ordered fix. Active worker wants to advance during heap scan from a page to next page. Next page has higher priority, so current page must be unfixed. A vacuum worker fixes page and deallocates it before active worker fixes it again.
=> [CBRD-20697] Ordered fix: prevent unfixed page from being deallocated

src/query/vacuum.c, src/query/vacuum.h, src/transaction/log_page_buffer.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-20906
The bug is generated by a mistake in vacuum_recover_lost_block_data code. When we need to recovery vacuum data (that is not logged), we may have two cases:
1. mvcc_op_log_lsa is not in vacuum data blocks. we go backward and process mvcc log records until we rebuild lost blocks (and update cached data in log global header).
2. mvcc_op_log_lsa is in vacuum data blocks, which means it was already added and we do not need to process it. It is reset, but the mistake was that last_block_oldest_mvccid and last_block_newest_mvccid fields were left untouched.
On the next mvcc op the code:
```c
/* Check if the block of log data is changed */
if (!LSA_ISNULL (&log_Gl.hdr.mvcc_op_log_lsa)
&& (vacuum_get_log_blockid (log_Gl.hdr.mvcc_op_log_lsa.pageid) != …
```
=> [CBRD-20906] fix vacuum recovery of log_Gl.hdr

src/query/vacuum.c, src/thread/thread.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-20839
Bug is caused by server shutdown and incorrect interrupt handling. When shutdown is executed, all transactions (including system transaction) are notified to interrupt their current tasks. System transaction is also shared by vacuum workers and one of them may check the interrupt flag, clear it and set interrupted error. The server then crashes because errors are not accepted during vacuum execution.
Actually, vacuum workers (and master) and never meant to be interrupted during a server run. They can be interrupted by shutdown. Checking for interrupted flag is redundant considering thread entry shut_down flag is also checked.
For stand-alone mode (CSQL and utilities), vacuum is executed serially and we no longer have daemon threads (that are not …
=> [CBRD-20839] handle vacuum interruption

src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-20932
Loosen-up safe-guard. During recovery, we can allow interrupts even if thread is vacuum worker.
Note that the thread is not actually a vacuum worker. It is hacked into thinking it is a vacuum worker while recovering the work of the vacuum worker. This is beyond the scope of initial safe-guard, which only tries to ensure a good control on errors during vacuum job execution.
=> [CBRD-20932] logtb_is_interrupted_tdes: allow vacuum interrupt during recovery

src/storage/heap_file.c, src/storage/page_buffer.c, src/storage/page_buffer.h, src/thread/thread.c, src/thread/thread.h
http://jira.cubrid.org/browse/CBRD-20669
The crashed safe-guard is there for a clear purpose: we tried to make sure no worker will try to access a heap page deallocated by vacuum. While this is true for all active and vacuum workers, the checkpoint thread cannot be prevented from try to latch page (and we don't to).
Change safe-guard check from is any waiter on page to is any non-checkpoint waiter on page.
=> [CBRD-20669] heap_remove_page_on_vacuum: allow checkpoint thread waiter

src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20935
Multiple UNIONs in the CTE remain accepted, but the recursive part can be only a PT_SELECT.
=> [CBRD-20935] Allow only PT_SELECT nodes as the recursive query of CTEs

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-20934
The type_enum remained set to the default PT_TYPE_NONE.
=> [CBRD-20934] Fix type_enum when folding UNION to NULL

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20941
The rownum can not be computed correctly with the optimization, when the same list_id is used for both reading and writing.
=> [CBRD-20941] Avoid recursive CTE optimization for rownum

src/parser/parser_support.c
http://jira.cubrid.org/browse/CBRD-20953
* Fix bug for 'show create view' when the value of sys. param 'plus_as_concat=no'
* This modification is quite simple, query for show create view contains '+' symbol
since 10.x. Hence, when the CUBRID param for 'plus_as_concat' is set to 'no'
Query processor may try arithmetic plus operation instead of 'concatenate',
which is intended.
* Change query for 'show create view' from PT_PLUS to PT_CONCAT
* QA passed for SQL/Medium
* I'm not sure for TC modification for this case, please advise.
=> [CBRD-20953] Fix show create view when the value of param plus_as_concat = no

src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-20701
log_rv_analysis_sysop_end: make sure stack is not null when setting last to 0
=> [CBRD-20701] log_rv_analysis_sysop_end: allocate topops stack

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20937
The optimization with using the same list_id for both reading and writing results for recursive query can work only if the CTE is the first in FROM specs. After every advance of the CTE scan, all the other scans involved in the recursive query must be restarted. This is the only mechanism that accepts writing in the same list_id. Otherwise there will be more separate scans on the CTE and the number of resulted tuples will be different since it is continously added new tuples.
This will affect a lot the performance of recursive CTEs, but the results will be correct.
The best solution would be to reorder the FROM specs in such a way that the self reference of the CTE would be the first node. This approach require more investigation.
=> [CBRD-20937] Recursive CTE optimization restriction

src/parser/parse_tree.h, src/parser/semantic_check.c, src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-20960
If the CTE has false_where, the recursive_part can be removed without affecting the results.
=> [CBRD-20960] Remove recursive part of CTEs with false where

src/parser/xasl_generation.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20959
The CTEs should be executed only once. They should be independent of the context (they may depend on other CTEs but remain independent overall).
=> [CBRD-20959] Set correlation level zero for CTEs

src/base/system_parameter.c, src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20871
1. xcache_compare_key: check skip recompiled in a loop.
2. fix delete from cache. each thread will mark the entry it wants to delete differently.
The PR also includes unrelated fix in system parameter (min/max).
=> [CBRD-20871] Fix XASL cache handling concurrent recompiles

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-20957
Analytic functions must be applied on each recursive level of the CTE individually.
=> [CBRD-20957] Avoid recursive CTE optimization for analytics

src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-20969
`NO_ERROR` was given to er_set.
=> [CBRD-20969] missing error code to er_set from number_to_char

src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-20971
It was removed when #518 did `xcache_fix`.
=> [CBRD-20971] xcache fix count was not incremented

src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-20865
Iterating over the attributes is not needed since the print function is handling lists also.
=> [CBRD-20865] Fix CTE attributes printing

src/object/schema_manager.c
* Fix truncate tables whose table name is a reserved word of the CUBRID, such as 'create', 'convert'
* Test Case for this PR can be found in [CBRD-20975]
=> [CBRD-20975] truncate problem,  whose table name is a reserved word of the CUBRID

src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20978
According to the comment "the exposed name of a derived table may not be used alone" queries like SELECT count(cte.*) FROM cte should also throw error. 
In this way there will be the same behaviour with CTEs as it is with derived tables.
The only incosistency will appear when the derived table is considered a dummy select and it is folded. Dummy CTEs can not be folded and will return error.
```sql
select count(x.*) from (select * from t1) x;
``` 
-> 
```sql
select count(x.*) from t1 x; --success
```
```sql
with tmp as (select * from t1)select count(tmp.*) from tmp;
```
->
```
ERROR: Class instance reference tmp.* to a derived table name is not allowed.
```
=> [CBRD-20978] Return error for cte.* usage in count function

src/broker/broker_log_util.c, src/cm_common/cm_utils.c
http://jira.cubrid.org/browse/CBRD-20986
memcpy function is non-deterministic when using the same memory in src and dst arguments, making the program unreliable.
=> [CBRD-20986] fix ut_trim (memmove)

src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-20983
=> [CBRD-20983] do not deallocate compressed string when generate tuple descriptor

src/storage/extendible_hash.c
http://jira.cubrid.org/browse/CBRD-20808
we need to destroy temporary extensible hashes, or they'd get leaked. so don't mind interruptions.
=> [CBRD-20808] Do not interrupt temp ehash destroy

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21021
file_temp_alloc: fix file_Tempcache->spacedb_temp stats when new file table page is allocated
=> [CBRD-21021] file_temp_alloc: fix file_Tempcache->spacedb_temp

src/query/vacuum.c, src/query/vacuum.h, src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-21037
Call load & recovery in main thread after recovery to avoid active workers starting during its execution.
=> [CBRD-21037] Recover vacuum data before starting workers

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21064
This is a regression of CBRD-21037. vacuum_Global_oldest_active_mvccid used to be read in vacuum_process_vacuum_data, before vacuum data was loaded. Since vacuum_data_load_and_recover is now called before master is woke, the vacuum_Global_oldest_active_mvccid remained 0.
Fixed by reading vacuum_Global_oldest_active_mvccid.
=> [CBRD-21064] vacuum_data_load_and_recover: read vacuum_Global_oldest_active_mvccid

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21074
This is a legacy issue. 
`cmpval` function does not treat NULL. `btree_compare_individual_key_value` compares two individual key values with `total_order`.
=> [CBRD-21074] fixed MRO to consider NULL from a key value

src/base/perf_monitor.c, src/base/perf_monitor.h, src/cm_common/cm_mem_cpu_stat.c, src/cm_common/cm_stat.h
http://jira.cubrid.org/browse/CBRD-20074
quick fix cm server compatibility issue in daily build. should be reverted when the daily build is fixed to fetch develop head revision instead of master.
=> [CBRD-20074] add stats back temporarily

src/storage/file_manager.c, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_manager.h, src/transaction/log_page_buffer.c, src/transaction/log_recovery.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-21003
The issue is caused by finishing postpone of file dealloc meddling with another file alloc or dealloc operation interrupted by crash. The correct order is to first abort interrupted system operations and then finishing postpones.
But of course, this is easier said than done. Because we have to abort only interrupted system operations and not entire transactions. But we have no way of determining where a system operation has started during recovery. This is the first problem.
The second problem is caused by nested system operations. We can have one atomic system operation that has another nested system operation using postpones and that can be running postpone during crash. In this case, we first have to finish postpone of nested system operation …
=> [CBRD-21003] Recovery: abort sysops before finishing postpone

contrib/gdb_debugging_scripts/page_buffer.gdb, src/storage/page_buffer.c, src/thread/thread.c, src/thread/thread.h
http://jira.cubrid.org/browse/CBRD-21080
Four cases when safe-guard is hit:
- two of them are acceptable scenarios. I updated the safe-guard so it would not be hit in these cases. The waiters have no candidates and under-quota private lists, while other lists have enough victim candidates.
- one scenario when thread does not find a victim in his private lists although there are more than 4k victim candidates. I suspect the victim hint was bad and I tried to quick fix it by changing the hint to bottom when bottom is not dirty.
- one scenario when flush thread should have found victim candidates in list, but it didn't. I still don't understand why and how it happened. However, I changed the looping pgbuf_get_victim_candidates_from_lru in order to make sure all lists are processed exactly …
=> [CBRD-21080] pgbuf_flush_victim_candidates: fix hitting safe-guard

src/query/vacuum.c, src/storage/slotted_page.c, src/storage/slotted_page.h
http://jira.cubrid.org/browse/CBRD-20699
The issue was caused by accessing an unfixed page (home page was unfixed while trying to fix forward page which failed).
Abort vacuum when the case happens. Other minor changes in vacuum_heap_page.
=> [CBRD-20699] vacuum_heap_page: error handling for release mode

src/storage/btree.c, src/storage/btree.h, src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-21087
assert (thread_p != NULL) was hit in pgbuf_block_bcb. The thread entry was not propagated by btree_leaf_change_first_object. I fixed the case and another few in b-tree files.
=> [CBRD-21087] add thread_p argument to b-tree functions

src/base/release_string.c, src/storage/btree.c, src/storage/extendible_hash.c, src/storage/file_manager.c, src/storage/file_manager.h, src/storage/heap_file.c, src/storage/system_catalog.c, src/transaction/boot_sr.c, src/transaction/recovery.c, src/transaction/recovery.h
http://jira.cubrid.org/browse/CBRD-21039
1. Fix protecting heap and b-tree key overflow files while iterating.
2. Unregister from tracker first while destoying file.
3. Fix rollbacking unregister from tracker.
4. Use SCH_S_LOCK protection while checking catalog entries for a class.
=> [CBRD-21039] Fix tracking processing & unregister

src/communication/network_interface_cl.c
http://jira.cubrid.org/browse/CBRD-21094
Forget client error to enter server.
=> [CBRD-21094] SA_MODE clears client error when enter into server

src/storage/file_manager.c, src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-20740
file_perm_dealloc: handle the strange case of page being merged in full table belonging to the same sector being moved to partial table
=> [CBRD-20740] file_perm_dealloc: fix merging & moving to partial table

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21100
This is not an actual fix, but just more safe-guards to hopefully catch the issue earlier (or at least rule out some cases).
=> [CBRD-21100] Safe-guards for bcb.count_fix_and_avoid_dealloc

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21101
```c
if (is_old (bcb, lru))
pgbuf_lru_boost_bcb ()
pgbuf_lru_boost_bcb
assert (is_old (bcb, lru));
lock (lru);
```
The safe-guard is not reliable. The initial condition can match just on the edge. Since lru list is not locked, it can change (e.g. zone 1 can be adjusted), increasing the size of zone 2. That affect the is_old condition and from true it can become false.
Fix by removing the unreliable safe-guard.
=> [CBRD-21101] pgbuf_lru_boost_bcb: remove unreliable safe-guard

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21106
file_extdata_apply_funcs: copy vpid_next before unfixing page_extdata
Should also fix [CBRD-21107](http://jira.cubrid.org/browse/CBRD-21107).
=> [CBRD-21106] file_extdata_apply_funcs: fix advance to next

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21081
In the scenario provided, it happened to rename a table, having an auto-increment key, to a new name, then back to its original name. In this case, one key would be marked for insert, while the other would be marked for insert and delete, so therefore the MVCC info would not match, eventually failing an assert. We remove the assert since it was incorrect.
=> [CBRD-21081] Removed assert regarding the match of MVCC info

src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21105
cannot abort up to tail_topresult_lsa; some end sysops may be nested and need to be processed (logical undo) or skipped (commits).
=> [CBRD-21105] Fix undoing unfinished sysops during execute postpone

src/storage/page_buffer.c, src/storage/page_buffer.h, src/thread/thread.c, src/thread/thread.h
http://jira.cubrid.org/browse/CBRD-21115
The issue is again a preempted direct victim waiter that puts itself into waiting list after flush thread flushes enough candidates. Moreover, it puts itself in the waiting list between searching for victims and safe-guard. Should be fixed with next changes:
1. stop looping if pgbuf_get_victim_candidates_from_lru failed to produce anything.
2. update safe-guard:
- replace pgbuf_is_any_thread_waiting_for_direct_victim () with direct_victim_waiters which is obtained before searching victims.
- safe-guard is passed if assigned_directly is true.
=> [CBRD-21115] pgbuf_flush_victim_candidates: update looping & safe-guard

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21115
fix previous revision compile error.
=> [CBRD-21115] pgbuf_flush_victim_candidates: fix compile error

src/transaction/log_page_buffer.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21116
We had two issues:
1. log_sysop_start changes vacuum worker state to VACUUM_WORKER_STATE_TOPOP. the state is changed  back to VACUUM_WORKER_STATE_RECOVERY only when last system op is ended. Finish postpone has an early out to skip vacuum transactions when state is not VACUUM_WORKER_STATE_RECOVERY.
2. tdes->rcv.sysop_start_postpone_lsa was reset by any system op end. However, we can have nested system ops inside run postpone phase.
Fixed both issues.
=> [CBRD-21116] fix abort atomic sysop inside sysop run postpone

src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21133
Fix resetting rcv.sysop_start_postpone_lsa when system op end is analyzed and lastparent_lsa precedes tdes.rcv.sysop_start_postpone_lsa.
=> [CBRD-21133] log_rv_analysis_sysop_end: reset rcv.sysop_start_postpone_lsa

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21122
In is_merged_page_from_sector case, we only removed page from sector in file table. I missed updating the number of pages in file header.
Fixed by updating header.
=> [CBRD-21122] file_perm_dealloc: fix fhead for is_merged_page_from_sector case

src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21139
Search for previous run postpone and set it as last parent LSA before rollbacking interrupted system op.
=> [CBRD-21139] recovery: fix rollbacking logical run postpones

src/storage/disk_manager.c, src/storage/extendible_hash.c, src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21020
On interruption, if thread managed to allocate sector bits from disk, it used to "free" them from cache twice. Once while clearing bit from disk and once in disk_cache_free_reserved.
Fixed by removing from context given as argument to disk_cache_free_reserved the sectors freed by disk_unreserve_ordered_sectors_without_csect.
=> [CBRD-21020] disk_reserve_sectors: fix double sector free from cache

src/jsp/jsp_sr.c
http://jira.cubrid.org/browse/CBRD-21142
On Windows, starting with VS2015 rev 3, __pfnDliNotifyHook2 and __pfnDliFailureHook2 external pointers, defined in Delayimp.h are const and, thus cannot be modified. This leads to a compilation error because jsp_sr.c needs to modify those pointers.
In order to make the above pointers writable, one needs to
#define DELAYIMP_INSECURE_WRITABLE_HOOKS
before
#include <Delayimp.h>
=> [CBRD-21142] Fix build on windows VS2015 and newer

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21144
I don't really know why does valgrind complains of the UMR. The code is:
```c
/* is list empty? */
if (lru_list->bottom == NULL)
{
...
bcb->tick_lru3 = lru_list->tick_lru3 - 1;
}
else
{
...
bcb->tick_lru3 = lru_list->bottom->tick_lru3 - 1;
...
}
/* make sure tick_lru3 is not negative */
if (bcb->tick_lru3 < 0)   /* <---- UMR */
{
bcb->tick_lru3 += DB_INT32_MAX;
}
```
Unless compiler does a freak optimization and reverses the operations order (which I doubt), the tick should be initialized.
In any case, I also initialize both ticks in pgbuf_initialize_bcb_table .
=> [CBRD-21144] initialize bcb ticks

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21100
page unfixed by pgbuf_ordered_fix can be victimized; update code to register/unregister avoid deallocation to accept this truth
check avoid deallocation counter before decrementing it (avoid negative values)
=> [CBRD-21100] Do not deregister "avoid deallocation" on victimized bcb

src/query/vacuum.c, src/query/vacuum.h, src/storage/btree.c, src/storage/disk_manager.c, src/storage/file_manager.c, src/storage/heap_file.c, src/storage/slotted_page.c, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_page_buffer.c, src/transaction/log_recovery.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-20692
The patch does not really have anything to do with the issue, other than that some of the extended logging will be used for its investigation.
1. Log transaction ID insteand of transaction index. Much easier to identify the culprit of a change and match it with logdump transactions.
2. Vacuum processing log block logs the LSA's of vacuum tasks. Also log thread/trid to identify the worker.
3. Refactoring of vacuum_er_log to make it easier to be used in the future.
=> [CBRD-20692] extend logging

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21159
LOG_CS was missing.
=> [CBRD-21159] hold LOG_CS for logpb_flush_pages_direct

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21157
=> [CBRD-21157] Fix to retry victimization in single threaded mode after victim flush was run.

src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-21171
Some shutdown jobs also need help of system threads.
=> [CBRD-21171] delay shutdown daemon threads

src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-21176
server hung due to mutex leak
=> [CBRD-21176] fixes catalog_Max_space_lock leak

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21177
`pgbuf_invalidate_all` considers case that BCB is being flushed as `pgbuf_invalidate`.
=> [CBRD-21177] pgbuf_invalidate_all considers BCB is being flushed

src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-20692
=> [CBRD-20692] fixed global mvccc op log lsa when redo sysop end

src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-21089
TBH, I don't figure out how it happened. To mount temp volumes is useless and risky for unlucky cases. A corrupted temp volumes might be inaccessible and even more important thing is they will be removed soon.
=> [CBRD-21089] fixes not to mount temp volumes during bootstrapping

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21121
It was not deallocated and remained as it was. Then, the page was allocated later and its allocator fixed the page as NEW_PAGE. This hit assertion.
=> [CBRD-21121] deallocate the merge page from sector

src/storage/heap_file.c, src/storage/heap_file.h, src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-21190
bug is caused by write latch over a read latched page.
when class_oid is unknown locator_lock_and_get_object_with_evaluation fixes pages using read latch to get class oid. it then is write-latched.
use write latch from the start, since the purpose of the function is to get object to update or delete it.
=> [CBRD-21190] locator_lock_and_get_object_with_evaluation: use latch write

src/transaction/lock_manager.c
http://jira.cubrid.org/browse/CBRD-21191
The thread was interrupted while fetching class oid of the requested oid of lockset.
Since lockset->quit_on_errors is 0, it continued to fetch remaining requested objects.
It tried to unlock the locked objects and hit the assertion of not null class oid.
=> [CBRD-21191] fixes to unlock lockset; class oid might be null oid

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-21189
heap_check_all_pages was disabled during file manager redesign. it should have been enabled back.
also crash during debug if file_numpages != npages.
the patch does not fix CBRD-21189.
=> [CBRD-21189] activate heap_check_all_pages

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21199
During server run, vacuum thread vacuumed objects, deallocated its page and continued. In the meantime, someone else reused page as file table. Server crashed and restarted for checkdb.
During restart, vacuum tries to clean same object again and finds a file table page (unexpectedly). Fixed by changing expectations and allowing file table pages when job is interrupted.
=> [CBRD-21199] vacuum_heap_page: interrupted vacuum job can find file table page

src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-20146
=> [CBRD-20146] printing parse tree omitted limit clause for update/delete

src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-21201
Transaction that deletes temporary volumes during restart is "leaked". Fix by committing it.
Also remove obsolete code (boot_Db_parm.query_vfid can be removed completely when we upgrade disk version).
=> [CBRD-21201] boot_restart_server: commit deleting temporary volumes

src/query/vacuum.c, src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-21203
Safe-guard hit in the issue checks that vacuum data blocks have increasing oldest MVCCID's (a requirement for optimized estimation of vacuum data global oldest MVCCID).
On live server run, each block sets its `oldest_mvccid` to `vacuum_Global_oldest_active_mvccid` when it is first logged. Subsequent blocks can only have equal or bigger oldest_mvccid's because `vacuum_Global_oldest_active_mvccid` can never decrease.
`vacuum_data_load_and_recover` misses this restriction and computes `oldest_mvccid` solely based on MVCCID's found in each block. However, a small MVCCID in a later block may have been active (but suspended) in previous blocks. So it ends up with decreasing oldest_mvccid's. In the issue, there were two blocks recovered, last having …
=> [CBRD-21203] fix vacuum data recovery

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-21126
Fix the recovery of disk cache when sector table pages (but not volume header) are flushed to disk before server crash. This used to generate some inconsistencies from format/extend (which wrongfully assumed all added sectors are free).
Also added more disk logging and a plan B for disk_reserve_sectors release version (assuming it fails due to incorrect cache).
=> [CBRD-21126] fix disk cache recovery

src/storage/disk_manager.c, src/storage/page_buffer.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21204
`copydb` uses a special volid as `LOG_DBCOPY_VOLID`.
It caused ABR and corruption of log header. This lead to a corruption and a crash for some cases.
=> [CBRD-21204] fixes ABR of copydb

src/transaction/log_manager.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21206
Transaction state was changed before log record for system op start postpone. End checkpoint log record saved it, thus causing the inconsistency during recovery.
Fix by changing state under the protection of prior LSA mutex.
=> [CBRD-21206] fix tdes state inconsistency during checkpoint

contrib/gdb_debugging_scripts/page_buffer.gdb, src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21207
page flush is innocent but the assertion was bad. probably typo :)
The fix also changes `pgbuf_show_lru_dirties` debugging script and introduces `pgbuf_show_all_lru_dirties`.
=> [CBRD-21207] fixed bad assertion for no page flush cases

src/query/vacuum.c, src/query/vacuum.h, src/transaction/log_impl.h, src/transaction/log_page_buffer.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21204
There was another defect along with #667. It reset source's log header not dest's.
Since I have not had my own reproduction, I don't know this is the last defect of copydb. I hope this resolves the case.
=> [CBRD-21204] resets log header of copied db; it did source's not dest's

timezones/make_tz.sh
It fixes nothing but removes deleted options of `make_tz.sh` as #673.
=> [CBRD-21212] remove deleted options of make_tz.sh

src/storage/file_manager.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21223
Typo in log_recovery_abort_atomic_sysop function has unwanted effect. Instead of early out because there is no log record after atomic start, transaction is completely rollbacked. Which messes up the file header since another transaction was in the middle of file operation.
=> [CBRD-21223] log_recovery_abort_atomic_sysop: fix atomic_sysop_start_lsa last record

src/transaction/boot_sr.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21212
Fix two issues:
1. Call vacuum_data_load_and_recover after restore.
vacuum_data_load_and_recover addes new log records. And we thought initially that restore can be called iteratively (-l0, then -l1, then -l2). Restore does not expect pages with LSA's higher than their end_redo_lsa (which happened in this case). However, that proved wrong, and restore should be called with -l2 directly.
2. Do not reset vacuum_Data.recovery_lsa when finding RVVAC_COMPLETE on redo.
Resetting vacuum's recovery_lsa was a minor optimization for recovery (to skip trying to recover vacuum data). But it only considered recovery case and not restore. For recovery, to find RVVAC_COMPLETE after checkpoint, means no other MVCC operations are possible afterwards (since last run …
=> [CBRD-21212] Fix vacuum recovery on restore

src/storage/file_manager.c, src/storage/file_manager.h, src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-21275
The class_oid in file descriptor is incorrect or outdated for short window during heap create and heap reuse. That's because adding or reusing in file tracker was done in a different step than updating the file descriptor.
Heap file create issue is fixed by setting class OID in descriptor from the start.
Heap file reuse updates descriptor while keeping latch on file tracker.
=> [CBRD-21275] fix heap-file descriptor missmatch during reuse/create

contrib/gdb_debugging_scripts/page_buffer.gdb, src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21280
Some private lists were assigned a target for flush although they had no possible candidates. Each list had only on bcb in zone 1 and quota 0, which means they are considered over-quota. Flush thread sets a flush target bigger than 0 for these lists although there is no victimizable bcb.
The hit assert checks there are more victims than target when flush finds nothing, which was not true for these lists.
Fix by setting the flush target on private lists to MIN (over_quota_bcb's, zone_3_bcb_count).
=> [CBRD-21280] don't try to flush from empty zone 3

timezones/make_tz_Win32.bat, timezones/make_tz_x64.bat
http://jira.cubrid.org/browse/CBRD-21285
Because some global variables are not properly reinitialized when a database restart is performed
crashes can occur. In order to fix this a gen_tz process is run for each database at a time.
=> [CBRD-21285] make_tz is failed on windows when try to make_tz for the second time

src/broker/cas_execute.c, src/query/query_executor.c, src/storage/catalog_class.c
http://jira.cubrid.org/browse/CBRD-21328
space for quotes were missed.
It also fixes http://jira.cubrid.org/browse/CBRD-21327
=> [CBRD-21328] fixed memory overrun of printing default expression

src/storage/disk_manager.c, src/transaction/boot_sr.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21325
The volume info file is not synchronized after crash during disk_add_volume. Find volumes during restart bug also kept things that way. During unlikely case described [here](http://jira.cubrid.org/browse/CBRD-21325?focusedCommentId=4743682&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4743682), the issue ends up with a crash in debug mode.
Fix by making sure that volume info file is correct if:
* disk_add_volume is aborted.
* volume found in volume info file could not be mounted.
=> [CBRD-21325] correct volume info file if disk_add_volume crashes

src/executables/util_sa.c, src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-21352
The issue is caused by shutdown/restart server in the same execution instance. Global variables are not always properly reset.
This case was caused by log_GL.rcv_phase. We supress **pgbuf_is_temporary_volume** check when server is not yet restarted. This may be called before disk cache is loaded, which is problematic and a safe-guard is hit.
In our case, restoreslave first calls **boot_restart_from_backup**, shuts it down and then **db_restart** to apply HA logs. Since log_GL.rcv_phase was not properly reset during shutdown, when volumes are booted, it crashes calling pgbuf_is_temporary_volume (debug mode).
This fixes log_GL.rcv_phase, which proved to be enough for the case described in issue. However, I doubt this is the only issue we face because …
=> [CBRD-21352] log_final: reset log_GL.rcv_phase

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21353
The page b-tree scan was interrupted at has become empty in the meantime. Vacuum cleaned its last entry. In btree_range_scan_resume, btree_leaf_is_key_between_min_max returns BTREE_KEY_NOTFOUND, btree_search_leaf_page call is suppressed, and then crash happens. I added BTREE_KEY_NOTFOUND to accepted cases that need to restart search from the top.
Why is page empty and not merged with next page? I can only guess that the next page was full (or we have a bug, I don't know). The page was pretty empty (its last record being only 24-byte long).
I also added an extra condition in btree_merge_node_and_advance to force loading right child node from disk when advance to child node has only one record. (in case the only existing record, that is going to be …
=> [CBRD-21353] btree_range_scan_resume: expect not found from empty pages

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-21356
=> [CBRD-21356] clear db_value content if is allocated during qexec_end_one_iteration when build indexes

src/base/object_representation_sr.c, src/query/partition.c, src/query/query_executor.c, src/query/xasl_cache.c, src/storage/btree.c, src/storage/btree_load.c, src/storage/catalog_class.c, src/storage/heap_file.c, src/storage/heap_file.h, src/storage/statistics_sr.c, src/storage/system_catalog.c, src/storage/system_catalog.h, src/transaction/locator_sr.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-21362
Replace `heap_classrepr_free` with `heap_classrepr_free_and_init` macro to avoid double free.
Error handler of `qexec_execute_build_indexes` and `qexec_execute_build_columns` had a chance to free class representation twice. 
`qexec_execute_build_indexes` also had a potential to double free of disk representation.
=> [CBRD-21362] fixes double free of heap_classrepr_free

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21366
Fix the safe-guard by considering floating numbers are not always accurate.
=> [CBRD-21366] pgbuf_initialize: fix lru ratios safe-guard

src/storage/file_io.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21367
the bug here is that logpb_backup_for_volume tries to backup a volume in progress of being added.
to discover all volumes, logpb_backup_for_volume calls fileio_find_next_perm_volume, which gets it from fileio_Vol_info_header, with no synchronization whatsoever. another thread is formatting a new volume, which is added to fileio_Vol_info_header, but is not yet initialized. backup is accessing volume first page and discovers it is deallocated, hitting safe-guard.
to fix the issue, I forced fileio_find_next_perm_volume get block on disk extensions. I thought of blocking fileio_traverse_permanent_volume, but it is dangerous, since it may be called while mutex is already blocked.
[EDIT] I have moved disk_lock_extend/disk_unlock_extend even upper. It …
=> [CBRD-21367] fileio_find_next_perm_volume: lock disk extensions

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21371
clear error if index name could not be obtained.
=> [CBRD-21371] btree_set_error: clear error if index name could not be obtained

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21378
vacuum will not always find the lob's to delete. but we don't need to leak errors when it doesn't.
=> [CBRD-21378] vacuum_process_log_block: clear lob not found error

src/communication/network_cl.c, src/communication/network_interface_sr.c, src/connection/connection_support.c, src/connection/server_support.c, src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-21375
We had a race condition among client, worker thread and connection handler when client disconnects the connection. 
Detailed scenarios are [here](http://jira.cubrid.org/browse/CBRD-21375?focusedCommentId=4743927&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4743927).
Fix is to synchronize disconnecting worker thread and connection handler.
I think "kill statement" and "killtran utility" have the same potentials. I don't think we have to fix these case (at least for this milestone).
=> [CBRD-21375] client may suffer from closed socket while closing connection

src/object/authenticate.c, src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-21369
In fact, the reported case reproduces only for non auto commit mode. But the more serious issues are hidden.
I wanted to completely revise authorization module as well as do_statement level, however I had to change my mind. To rewrite authorization module requires time, lots of testing and might be risky at the moment. So, this is the minimal fix to avoid potential inconsistencies of **DDLs** such as *'create user'*, *'alter user'*, *'drop user'*, *'grant user'* and *'revoke user'*. Since it missed savepoint and to abort upto savepoint for an error, objects might be ruined and there might be some recovery issues. 
Some routines tried to manually recover failues, for instance, `do_create_user` tries to drop the created user object when an error …
=> [CBRD-21369] {create,alter,drop,grant,revoke} user missed savepoint

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-21401
heap_classrepr_get: fix deadlock between cache entry mutex and heap page latch
=> [CBRD-21401] heap_classrepr_get: fix deadlock

src/query/xasl_cache.c, src/query/xasl_cache.h
http://jira.cubrid.org/browse/CBRD-21402
Use atomic operation on INT64 field instead of the varying in size timeval.tv_sec.
=> [CBRD-21402] xcache_check_recompilation_threshold: fix race

src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-21406
It was interrupted while updating the class.
`heap_mark_class_as_modified` might return `ER_FAILED`.
=> [CBRD-21406] deletes a bad assertion: locator_update_force

src/session/session.c
http://jira.cubrid.org/browse/CBRD-21405
destroy, check, create session state: be more careful handling limit cases
=> [CBRD-21405] fix session state handling

src/query/vacuum.c, src/storage/btree_load.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-21412
xbtree_load_index: fix deleting globals stats for null btid
the patch includes minor fix in vacuum module.
=> [CBRD-21412] xbtree_load_index: fix for null btid

src/transaction/log_manager.c, src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-21415
This is a complicated case.
1. file_destroy (during postpone)
2. file_tracker_unregister (file_dealloc).
3. sysop with logical undo starts postpone
4. crash!
We have a sysop postpone phase inside a logical undo, inside a logical run during transaction postpone phase. The recovery code was not adept to handle the case, so it had a safe-guard to ban the case.
This is a hack/quick fix that should work in this case. We allow a sysop start postpone in this context and try to correct the transaction state changes. However, it may not work in other complicated cases (if they exist or if they will be added). A correct way to manage nested system operations is log more information (e.g. previous transaction state).
=> [CBRD-21415] fix recovery for file_tracker_unregister crash

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21426
do not leak errors from file_header_sanity_check.
=> [CBRD-21426] clear errors during file_header_sanity_check

src/compat/db_macro.c, src/query/scan_manager.c, src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21431
Once a `MAX_STRING` type of `DB_VALUE` would be required to be inserted in a `MIDXKEY`, since the MAX_STRING info is held into the `is_max_string` field, it would not be added into the `MIDXKEY`. Therefore, the `MIDXKEY` would reside no information that it should hold a `MAX_STRING` type of value. We decided to try a workaround by correctly setting the `MAX_COLUMN` value into the `min_max_val` field of the `MIDXKEY`.
=> [CBRD-21431] Fix prepared statements on multi-column indexes with like clause

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-21442
#760 sliped SA_MODE.
=> [CBRD-21442] no need to check dropped file to reuse heap for SA_MODE

COPYING, README
https://github.com/CUBRID/cubrid-manager-server/pull/15 removed web manager.
Patch removes mentions about web manager.
=> [CBRD-20146] remove web manager

src/connection/tcp.c
http://jira.cubrid.org/browse/CBRD-20146
error from `accept` was not handled.
I don't think the bug was realized.
=> [CBRD-20146] error to connect master was not handled

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-21451
Allocation might be ended with multiple extendible volumes.
One possible peephole of `disk_reserve_sectors` is
* wants to extend many sectors
* starts a system operation
* extends upto the max of the last volume (at the moment)
* also adds a new volume (because the extension of the last volume is not big enough to satisfy the demand)
* starts a system operation  
* adds a new volume 
* system operation to add a volume commits
* an error happens while reserving sectors (might be an interrupt??)
* aborts system operation
It this case, extension of the existing volume aborts but adding a new volume commits. 
The proposed fix is to commit system op of extending the existing volume.
=> [CBRD-21451] fixes to commit sysop of extending existing volume

src/storage/btree.c, src/storage/btree_load.c, src/storage/catalog_class.c, src/storage/external_sort.c, src/storage/heap_file.c, src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-21454
The reproduction shows error from `catcls_update_subset` was not propagated to caller.
There were same slips that did not properly return error.
=> [CBRD-21454] error was not propagated

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-21467
It was interrupted while deleting overflow record.
=> [CBRD-21467] removed incorrect assertion: heap_update_bigone

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-21477
bug in disk format online rollback. although the volume count says volume is in cache, actually nothing else is added to cache. "removing" from cache was wrongfully forced, and cache was corrupted.
fix by correctly handling disk_rv_undo_format. there are three cases:
1. rollback, not recovery. volume is not in cache.
2. recovery, volume is not in cache (volume count is less or equal to volid)
3. recovery, volume is in cache (volume count is volid + 1).
First two cases will not touch cache (the volume count in first case is decremented by disk_add_volume).
Third case has to completely remove volume data from cache.
Other changes:
* debug disk check after volume extensions.
* do not interrupt disk_add_volume.
=> [CBRD-21477] Fix disk format rollback (not recovery)

src/storage/disk_manager.c
http://jira.cubrid.org/browse/CBRD-21483
it's an outdated safe-guard. before adding volume, because page buffer must know which volumes are permanent and which are temporary, the number of permanent volumes is incremented and volume purpose is set.
previous disk_rv_undo_format fix now redirected case handling and hit the assert that checked purpose is unknown.
fix by removing safe guard and resetting purpose.
=> [CBRD-21483] disk_rv_undo_format reset volume purpose

src/storage/heap_file.c
#789 missed to free `last_repr`.
=> [CBRD-21489] fixed potential memory leak when classrepr cache is full

src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-21492
this is a hack to avoid combining regular and ordered fix, but keep the optimization of latching page and not repeating search in case of REC_HOME.
=> [CBRD-21492] heap_classrepr_get: don't combine regular and ordered fix

src/query/vacuum.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21503
In SA_MODE, vacuum_Data.keep_from_log_pageid is never updated and it prevents log archive purger from removing log archives. But after xvacuum, it is safe to remove any archives, since new MVCC ops are not logged and vacuum is not required.
=> [CBRD-21503] allow archive purging in SA_MODE

src/storage/storage_common.h
[CBRD-21512](http://jira.cubrid.org/browse/CBRD-21512)
Fix values for lock_no, lock_yes and lock_unknown to match previous values.
TODO: use LOCK_COMPATIBILITY everywhere lock compatibility is checked.
Also fixes [CBRD-21510](http://jira.cubrid.org/browse/CBRD-21510) and [CBRD-21511](http://jira.cubrid.org/browse/CBRD-21511).
=> [CBRD-21512] quick fix LOCK_COMPATIBILITY issue

src/base/object_representation.h, src/jsp/jsp_cl.c
[CBRD-21513](http://jira.cubrid.org/browse/CBRD-21513)
fixed using UINT64 argument for OR_GET_DOUBLE/OR_PUT_DOUBLE. GET/PUT monetary was broken.
TODO: the macros are not safe. we should replace with inlined functions that can check type correctness.
=> [CBRD-21513] fix OR_GET_MONETARY/OR_PUT_MONETARY

src/base/porting.h
I considered to replace `indent` with `astyle`, but I'm unhappy with its output of C code.
The only option is to use two formatters: `indent` for C files and `astyle` for C++ ones.
Since `indent` does not understand C++, I did manual formatting and disable indent for C++ block.
=> [CBRD-21524] indent off C++ code block from porting.h

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-21517
This is a legacy bug of grouping by index scan.
string compression of 10.1 hides the bug.
=> [CBRD-21517] fixes potential FMR overflow columns for grouping by iscan

src/query/list_file.c
[CBRD-21509](http://jira.cubrid.org/browse/CBRD-21509)
Refactor the code in list_file.c
The issue was that in qfile_add_overflow_tuple_to_list, qfile_add_tuple_to_list_id was called with tuple_length as offset parameter, this list_id_p->last_offset got a very large value.
In the code before switching to C++, list_id_p->last_offset was reset to 32 in qfile_allocate_new_page_if_need->qfile_allocate_new_page.
In the code refactored for C++, qfile_is_last_page_full returned false because of some integer overflow (which in normal condition should not happen) so qfile_allocate_new_page did not got called (to reset the last_offset) when error reproduced.
Refactored code so that qfile_add_tuple_to_list_id is called with proper offset and added more asserts.
=> [CBRD-21509]: Core dumped in qfile_add_overflow_tuple_to_list at src/query/list_file.c:1968

src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-21528
Fixed server doesn't load client-only sysprms and client doesn't do server-only ones.
=> [CBRD-21536] server doesn't load client-only sysprms

src/transaction/log_applier.c, src/transaction/log_applier.h
http://jira.cubrid.org/browse/CBRD-21551
Enable back la_print_log_header and la_print_log_arv_header. They were disabled to avoid exposing log_impl.h to client, but it has been exposed anyway.
log_repl_data_dump depends on printing DB_VALUE and must be solved with CBRD-21538.
=> [CBRD-21551] (re)enable log applier log print

src/storage/btree_load.c
Quick fix for a small slip of the last push. It fixes the failed regressions on partitions.
=> [CBRD-21433] Fix a small slip

src/storage/heap_file.c
http://www.jira.cubrid.org/browse/CBRD-21558
=> [CBRD-21558] Set HFID in heap_get_context when it is already available in the scan cache

src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-21579
Fixed by @rimio 
Remove eval created on non-leaf level and order children by level.
To be tested thoroughly with 4 or more analytic expressions.
=> [CBRD-21579] Fix analytics optimization with >= 4 expressions

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21583
This seems to be just a safe-guard issue. We usually mark in vacuum data when jobs are started and when they are finished, so we can adjust safe-guards after restart (expecting already vacuumed heap pages).
However, stand-alone mode vacuuming partial blocks can be interrupted and will not be flagged in any way. Therefore, it is better to consider that job was interrupted when sa_mode_partial_block is true.
I've set the milestone to 10.1 Patch 1, but since it is just a bad safeguard in an exceptional case, we can change it to cherry.
=> [CBRD-21583] sa_mode_partial_block may be interrupted

src/query/vacuum.c, src/query/vacuum.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21584
I think this was a regression of CBRD-21503 (commit 8192537c).
Since that patch, NULL_PAGEID was reinterpreted as safe to remove archives (to allow archives be purged after stand-alone vacuum). However, NULL_PAGEID is also returned when vacuum_Data.keep_from_log_pageid is not initialized - which is initialized on vacuum_data_load_and_recover, after recovery.
However, log records may be generated during recovery and although very unlikely, a new archive may be created and as a side effect archives will be purged too.
The fix prevents archives from being purged until vacuum_Data.keep_from_log_pageid is initialized.
I think this would also fix CBRD-21155.
=> [CBRD-21584] prevent archive purging until safe for vacuum

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21595
vacuum_update_oldest_unvacuumed_mvccid: empty vacuum data case in SA_MODE means everything up to log_Gl.hdr.mvcc_next_id has been vacuumed.
=> [CBRD-21595] fix updating oldest unvacuumed mvccid in SA_MODE

src/parser/xasl_generation.c, src/query/stream_to_xasl.c
http://jira.cubrid.org/browse/CBRD-21579
This is an alternative quick fix for the cases.
When an invalid evaluation structure is generated, we regard optimization is failed and generate trivial list.
I believe this fixes all the regression of b72ce30. However we should tackle issues of `pt_optimize_analytic_list`.
=> [CBRD-21579] alternative fix: generate one eval structure for an analytic function when optimization fails

src/base/object_representation.h, src/compat/db_macro.c, src/compat/dbtype.h, src/object/object_primitive.c, src/object/object_primitive.h, src/object/object_representation.c, src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-21558
Profile shows overhead of retrieving strings.
Patch inlines or_get_varchar_compression_lengths, db_set_compressed_string and db_get_compressed_size functions.
=> [CBRD-21558] inline functions for string compression

.gitignore, src/base/base_flag.hpp, src/base/contiguous_memory_buffer.hpp, src/base/db_private_allocator.hpp, src/base/extensible_array.hpp, src/base/lockfree_circular_queue.hpp, src/cci/cci_log.cpp, src/cci/cci_map.cpp, src/heaplayers/customheaps.cpp, src/heaplayers/stats.cpp, src/heaplayers/wrapper.cpp
introduce [astyle](http://astyle.sourceforge.net/) to format .cpp and .hpp files. Since astyle does not beautifully format .c and .h files, we will use `indent` and `astyle`.
This means we use `indent` for .c and .h and `astyle` for .cpp and .hpp.
The options for `astyle` I use is 
```sh
~/bin/astyle --style=gnu --mode=c --indent-namespaces --indent=spaces=2 -xT8 -xt4 --add-brackets --max-code-length=120 --align-pointer=name --indent-classes --pad-header --pad-first-paren-out "$1"
```
I will also update commit hook of http://jira.cubrid.org/browse/CBRD-20385.
=> [CBRD-21524] introduce astyle to format .cpp and .hpp files

cs/CMakeLists.txt, cubrid/CMakeLists.txt, include/system.h, sa/CMakeLists.txt, src/base/cubrid_getopt.h, src/base/cubrid_getopt_long.c, src/broker/broker_admin_pub.c, src/broker/broker_log_converter.c, src/broker/broker_log_replay.c, src/broker/broker_log_top.c, src/broker/broker_monitor.c, src/broker/broker_tester.c, src/broker/cas_runner.c, src/executables/commdb.c, src/executables/csql.h, src/executables/csql_launcher.c, src/executables/esql_grammar.y, src/executables/gencat.c, src/executables/loadjava.c, src/executables/util_admin.c, src/executables/util_support.c, src/executables/utility.h, src/tools/cci_applier.c, tools/CMakeLists.txt, util/CMakeLists.txt
http://jira.cubrid.org/browse/CBRD-21600
getopt compilation error on GCC 7.2.0:
```
Building CXX object util/CMakeFiles/csql.dir/__/src/executables/csql_launcher.c.o
In file included from /usr/include/bits/getopt_posix.h:27:0,
from /usr/include/unistd.h:872,
from /home/valeri/cubrid/include/system.h:64,
from /home/valeri/cubrid/build_x86_64_debug/config.h:94,
from /home/valeri/cubrid/src/executables/csql.h:30,
from /home/valeri/cubrid/src/executables/csql_launcher.c:34:
/usr/include/bits/getopt_core.h:91:12: error: declaration of ‘int getopt(int, char const, const char*) throw ()’ has a different exception specifier
extern int getopt (int ___argc, char const ___argv, const char *__shortopts)
^~~~~~
In file included from /home/valeri/cubrid/src/executables/csql_launcher.c:31:0: …
```
=> [CBRD-21600] fix getopt compilation error on GCC 7.2.0

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21617
Fixed code that tries to handle interrupted vacuum jobs and deallocated heap pages. One of the cases it used to consider a heap page was deallocated is when the number of slots is less that what it expected.
However, that is not always true. Another possible case is undoing a series of inserts. The number of slots are incremented while inserting (and vacuum is logged for each insert), but on rollback the number of slots are decremented (this doesn't always happen, only when the deleted slot happens to be last).
The crash was caused by a safe-guard that was supposed to be true in case page was really deleted. Since the page was not deleted, the safe-guard failed.
Heap pages are no longer assumed deleted and usual checks are executed on each record.
=> [CBRD-21617] vacuum_heap_page: fix interrupted case

cubrid/CMakeLists.txt
Add dependency between cubrid-win-lib and external targets in cubrid/CMakeLists.txt to fix build failure regression
=> [CBRD-21522] Fix Json Regression

src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-21636
copydb resets append_lsa as (0,0) and eof_lsa as (-1, -1).
When deletedb tries to mount a database that was not shutdown (e.g, a crash), it reset append_lsa as null_lsa.
Fix never allows to reset it as null_lsa.
It is a legacy issue with small probability of reproduction.
=> [CBRD-21636] deletedb which follows a crash of copydb crashes

src/compat/dbi_compat.h
I re-added #define bool char in dbi_compat.h only for C compiler
=> [CBRD-21629] Fix ctltool broken compilation

src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-21628
data volume size is normally rounded up to IO_PAGESIZE, but that may be false in case of crash and recovery.
=> [CBRD-21628] fix fileio_expand_to safe-guard

src/storage/file_io.c, src/storage/file_io.h
http://jira.cubrid.org/browse/CBRD-21630
Fix compile by wrapping entire fileio_expand_to in #if defined (SERVER_MODE)/#endif
=> [CBRD-21630] Fix compile from previous patch

src/base/perf_monitor.c, src/connection/server_support.c, src/query/filter_pred_cache.c, src/query/vacuum.c, src/query/vacuum.h, src/storage/disk_manager.c, src/storage/file_io.c, src/storage/file_manager.c, src/transaction/log_comm.c, src/transaction/log_impl.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21634
Fix setting log_Gl.hdr.vacuum_last_blockid to last completely logged block.
=> [CBRD-21634] Fix log_Gl.hdr.vacuum_last_blockid

src/query/vacuum.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21630
http://jira.cubrid.org/browse/CBRD-21632
Removed an early out that bounded `vacuum_Data.blockid_job_cursor` to `vacuum_Data.last_blockid`. This is no longer correct. Also fixed `logpb_last_complete_blockid` when `prev_lsa` is `NULL`.
This will also fix CBRD-21632. We decided on updating the `last_blockid` from `vacuum_Data` when both the `vacuum_Data.recovery_lsa` and `log_Gl.hdr.mvcc_op_log_lsa` are `NULL`.
=> [CBRD-21630] Removed early out

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21645
Bad `keep_from_log_pageid` allows archive removal although it was required for vacuum. At the time of the crash it has value -1, although there are many blocks in vacuum.
The problem was that `keep_from_log_pageid` was updated only in two places:
1. `vacuum_data_load_and_recover`.
2. `vacuum_data_mark_finished`, but only if blocks are removed from vacuum data.
After `vacuum_data_mark_finished`, if vacuum data becomes empty, `keep_from_log_pageid` is set to NULL_PAGEID, allowing archive removals. Which is what happens in our case too.
However, it is followed by a very long run that creates many new blocks but doesn't execute jobs (I guess a very long transaction prevents vacuum from executing). `vacuum_data_mark_finished` always earlies out and …
=> [CBRD-21645] updates keep_from_log_pageid when blocks are consumed and vacuum data was empty

src/base/perf_monitor.c, src/connection/server_support.c, src/query/vacuum.c, src/query/vacuum.h, src/storage/file_manager.c, src/storage/storage_common.h, src/transaction/log_comm.c, src/transaction/log_impl.h, src/transaction/log_page_buffer.c
Merge the recent fixes of log archive and vacuum to 10.1 patch 1.
* [CBRD-21583](http://jira.cubrid.org/browse/CBRD-21583): https://github.com/CUBRID/cubrid/pull/834
* [CBRD-21584](http://jira.cubrid.org/browse/CBRD-21584): https://github.com/CUBRID/cubrid/pull/833
* [CBRD-21595](http://jira.cubrid.org/browse/CBRD-21595): https://github.com/CUBRID/cubrid/pull/836
* [CBRD-21617](http://jira.cubrid.org/browse/CBRD-21617): https://github.com/CUBRID/cubrid/pull/847
* [CBRD-21593](http://jira.cubrid.org/browse/CBRD-21593): https://github.com/CUBRID/cubrid/pull/837
* [CBRD-21634](http://jira.cubrid.org/browse/CBRD-21634): https://github.com/CUBRID/cubrid/pull/860
* [CBRD-21630](http://jira.cubrid.org/browse/CBRD-21630): https://github.com/CUBRID/cubrid/pull/863
* …
=> [CBRD-21658] Merge log archive and vacuum fixes to 10.1 patch1

src/base/system_parameter.c, src/base/system_parameter.h, src/compat/db_json.cpp, src/object/object_domain.c
DB_MAKE_CHAR was overriding my need_clear flag to false and the memory wasn't deallocated, thus resulting in a mem leak. I suggest adding a "need_clear" parameter to DB_MAKE_CHAR.
I have also added the json_show_callstack hidden system parameter to aid in resolving future memory leak problems.
=> [CBRD-21650] Fix json mem leak

src/executables/csql.c
http://jira.cubrid.org/browse/CBRD-21657
After update of libedit from version 20120601-3.0 to version 20170329-3.1, csql history does not work anymore. This patch fixes csql history using new version of libedit.
=> [CBRD-21657] fix ;historylist after editline update

src/compat/db_json.cpp, src/compat/db_macro.c, src/compat/dbtype.h, src/executables/loader.c, src/object/object_domain.c, src/object/object_primitive.c, src/object/object_representation.c, src/parser/xasl_generation.c, src/query/execute_statement.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21679
During restoredb it is not safe to update log_Gl.hdr.vacuum_last_blockid based on append_lsa, because vacuum was not executed.
The used a hack, comparing log_Gl.hdr.mvcc_op_log_lsa to NULL_LSA, to detect the case.
=> [CBRD-21679] fix vacuum last_blockid after restoredb

src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-21676
Never ever again call functions in arguments of macros.
=> [CBRD-21676] Fix Json String Mem Leak

src/compat/db_json.hpp
http://jira.cubrid.org/browse/CBRD-21680
Release memory from `db_json_convert_string_and_call`
=> [CBRD-21680]  Crash for json query with the complex expression

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21679
During restoredb it is not safe to update log_Gl.hdr.vacuum_last_blockid based on append_lsa, because vacuum was not executed.
The used a hack, comparing log_Gl.hdr.mvcc_op_log_lsa to NULL_LSA, to detect the case.
=> [CBRD-21679] 10.1p1: fix vacuum last_blockid after restoredb (#879)

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21645
vacuum_update_keep_from_log_pageid - if vacuum data is empty we considered safe to remove archives. we were almost right, except that we did not consider partially logged block still in log_Gl.hdr;
One design flaw that causes us trouble is the condition to produce a log block - first mvcc operation in a different block. This sometimes leaves us with a very old block cached in header for a long time; one such case is very long undo recovery (that appends non-mvcc log records). I think the condition may be changed to first _any_ log record in a different block.
=> [CBRD-21645] keep archive when empty data and mvcc_op_log_lsa not null

src/query/vacuum.c, src/transaction/log_impl.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21704
memcopy vacuum_last_blockid to avoid alignment issues.
this is a hack for 10.1 p1 only.
=> [CBRD-21704] Fix log_Gl.hdr.vacuum_last_blockid

src/compat/db_class.c, src/compat/db_temp.c, src/object/class_object.c, src/object/schema_template.c, src/object/schema_template.h, src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-21567 "The comment does not be copied when creating table using "create table ... like" statement."
Both table and columns comments were ignored during CREATE TABLE Like ...
=> [CBRD-21567] Copy class and columns comments for CREATE TABLE LIKE

src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-21711
Fix fileio_expand_to adding one extra-page.
Should be applied to 10.1p1 too.
=> [CBRD-21711] Fix IO expand extra page

src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-21711
Fix fileio_expand_to adding one extra-page.
=> [CBRD-21711] 10.1p1: Fix IO expand extra page (#897)

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21703
This is a quick fix to avoid potential regressions.
=> [CBRD-21703] avoid vacuums purging log archives

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21703
This is a quick fix to avoid potential regressions.
=> [CBRD-21703] 10.1p1: avoid vacuums purging log archives (#902)

src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-21700 "[JSON] alter json column as json not null will be fail"
adding the default value "null" for json data type solved the problem
=> [CBRD-21700] Default value for json type

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21253
This issue was a very particular case hard to reproduce. Sometimes flush is forced while a log record is partially appended, and the case is handled like this:
1. Replace log record header with end of log record.
2. Flush all pages & synchronize active log file.
3. Finish appending log record.
4. Flush all pages & synchronize active log file.
5. Restore log record header and flush page again.
You may notice that after restoring log header, active log file was not synchronized. This patch fixes it.
Our suspicion in this JIRA issue is that the interrupted log record is undo of RVDK_FORMAT. Log is flushed & synchronized without RVDK_FORMAT log header, and then flushed with RVDK_FORMAT but without synchronizing.
Then new volume is created (which is …
=> [CBRD-21253] Sync after flushing log

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21253
This issue was a very particular case hard to reproduce. Sometimes flush is forced while a log record is partially appended, and the case is handled like this:
1. Replace log record header with end of log record.
2. Flush all pages & synchronize active log file.
3. Finish appending log record.
4. Flush all pages & synchronize active log file.
5. Restore log record header and flush page again.
You may notice that after restoring log header, active log file was not synchronized. This patch fixes it.
Since this case is complicated and has an additional expensive sync call, I try to avoid it by forcing log flush one page early at the start of a new log record rather than risking flushing partial log record.
=> [CBRD-21253] Sync after flushing log (#911)

cm_common/CMakeLists.txt
http://www.jira.cubrid.org/browse/CBRD-21727
* Changed cm_common/CMakeLists.txt to use 32bit time_t in Win32 Build
* We did QA inside our organization for CMS behavior & passed (Win32 build only)
=> [CBRD-21727] Use of 32bit time_t for Win32 build (_USE_32BIT_TIME_T)

src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-21732
There are some early outs that prevent the deletion of memory, so I simply don't perform the copy, but rather use the already allocated pointer which gets dealt with later. Not sure why I performed the copy in the first place.
There is one test, json_set_variables.sql, that will fail, but it will be resolved after merging https://github.com/CUBRID/cubrid/pull/919
=> [CBRD-21732] Solve memory leak from early out

src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-21734
Because of the way mr_writeval_string treats errors, I was left with memory leaks. I simply treat the error in the same function to avoid memory leaks.
=> [CBRD-21734] or_overflow jump causes memory leaks

src/compat/db_json.cpp, src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-21739
The case where a null JSON is read (size = 0 from the offset table) was not treated, this generating a buffer underflow.
=> [CBRD-21739] Treat null case from readmem json

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-21741
m_schema_raw is created using strdup, so free() has to be used
=> [CBRD-21741] Mismatched free/delete

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-21740
fixes a legacy issue to hit an assertion
=> [CBRD-21740] functions are not allowed in a predicate index

src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-21738
It isn't expected that the value from stx_build_val_list->stx_restore_db_value will be deleted, so cloning it results in a mem leak. We now simply make the pointer of the schema_raw null because it is not used when only creating a temporary container for the next dbvalue.
=> [CBRD-21738] Fix memory leak in XASL node

src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-21743
This is a slip of checking the visibility of keys in their respective btree. Before, it would check if the first record had any visible keys. It is now chaged, by checking if the record has any visible key regarding to the respective `slot_id`.
=> [CBRD-21743] [Regression] fail to alter table add FOREIGN KEY constraint

src/storage/file_io.c, src/storage/file_io.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21645
Restore uses the current log files (active/archive logs and log info) if exists. Otherwise, does them from backup volume.
The current files are more recent ones than those from backup volume.
=> [CBRD-21645] restore uses the current log files if exists

src/compat/db_json.cpp, src/compat/db_json.hpp, src/compat/db_macro.c
http://jira.cubrid.org/browse/CBRD-21731
Added DB_JSON_BOOL type because we need it for the comparison in 'order by' statement.
The bool type will be converted to string scalar for further comparison. Also, because of the copy parameter when getting the string from value we need to be careful in order to avoid a memory leak. So, I used two functions to get a const char* or char* (with copy).
=> [CBRD-21731] added DB_JSON_BOOL type

src/storage/file_io.c, src/storage/file_io.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21645
Restore uses the current log files (active/archive logs and log info) if exists. Otherwise, does them from backup volume.
The current files are more recent ones than those from backup volume.
=> [CBRD-21645] restore uses the current log files if exists (#929)

src/compat/db_macro.c
http://jira.cubrid.org/browse/CBRD-21758
The function **db_json_bool_to_string** allocates memory when converting a bool to string.
Right now **db_make_string** expects a const char* and the need_clear flag is **false**, but in the future it will require a char*. After making the DB_VALUE from string we need to set need_clear flag to **true** in order to avoid memory leak.
=> [CBRD-21758] JSON - cub_server crashed in thread_rc_track_meter_check

src/parser/type_checking.c, src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-21776
multiplication overflow is detected as follows:
```
x = a * b
x / b != a
```
devtoolset-6 optimizer does not actually do division operation and overflow is not detected.
=> [CBRD-21776] devtoolset-6: multiplication overflow is not detected

src/parser/parse_dbi.c
http://jira.cubrid.org/browse/CBRD-21760
pt_type_enum_to_db_domain(DB_TYPE_JSON): return a new object instance
instead address of a global variable (because it will be integrated in dynamic lists later)
=> [CBRD-21760] [JSON] csql crashed when execute arithmetic operations with JSON collection types

src/base/lockfree_circular_queue.hpp, src/thread/thread_task.hpp, src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-21805
when worker pool is stopped, it also deletes tasks in task queue.
=> [CBRD-21805] delete unexecuted tasks in worker pool

src/base/porting.h, src/thread/thread.c
http://jira.cubrid.org/browse/CBRD-21811
The internal mutex used for initialization of other mutexes was already initialized at the time of this call.
=> [CBRD-21811] Quick fix for bad reinit of mutex

src/parser/parse_tree.c, src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-21782
`parser_free_node()`:
- clear db_value for node type PT_INSERT_VALUE 
Already fixed in previous PRs:
- mem::default_realloc()
- db_json_contains_dbval()
I could reproduce only one memory leak related to `db_json_allocate_doc()` with
`sql/_31_cherry/issue_21522_json/cases/json_remove_and_dml.sql`
Waiting instructions how to reproduce memory leaks other than the above one
=> [CBRD-21782] memory leak of JSON

src/base/system_parameter.c, src/base/system_parameter.h, src/connection/connection_sr.c, src/connection/connection_sr.h, src/thread/thread.c
http://jira.cubrid.org/browse/CBRD-21809
Fix thread_has_threads regressions:
1. Fix thread_belongs_to to avoid matching thread entries with both tran_index and conn_entry NULL.
2. Fix thread_has_threads to search only workers, not all threads.
Any one of two changes was enough, however I think the logic is more clear now.
I also added some connection logging while trying to investigate the connection issue.
As consequence of thread_has_threads bug, net_server_conn_down looped infinitely and connections were never closed and connection entry pool was completely depleted. Paired with bad handling of new clients, it leaves admin connection with no conn_entry, hence the issue.
@paulgheorghecristian @razvanradulescu 
While working on HA connection, please consider changing …
=> [CBRD-21809] Fix thread_has_threads false match

src/connection/connection_cl.c
http://jira.cubrid.org/browse/CBRD-21814
This is a quick fix to the issue.
To disconnect the temporary connection for the cases right after sending error to client prevents the client from properly receiving the entire error area. Client may access bad memory and crashes. 
It is a legacy issue and we need a complete fix.
=> [CBRD-21814] Receiving error from server may not be completed

cubrid/CMakeLists.txt, sa/CMakeLists.txt, src/base/lockfree_circular_queue.hpp, src/query/vacuum.c, src/thread/thread_daemon.cpp, src/thread/thread_daemon.hpp, src/thread/thread_entry_task.cpp, src/thread/thread_entry_task.hpp, src/thread/thread_manager.cpp, src/thread/thread_manager.hpp, src/thread/thread_task.hpp, src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-21815
The bug surfaced by memory leak fix in thread_worker_pool::run was corrupted pointer used after circular_queue->consume failed.
circular_queue->consume does not guarantee argument element is not changed when consume fails. It is an intended optimization of the underlying implementation and caller should consider it.
This bug was also a flaw of initial thread manager design. Creating/retiring context was part of thread task implementation. I fixed by separating context manager into a different class context_manager.
Daemons/worker pools will also receive the context manager as argument during construction.
Several thread files and vacuum had to be changed because of design change.
=> [CBRD-21815] Separate thread context of thread task

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21818
This requires attention. Since it seems to be legacy code, it needs an update to cover all the possible cases. For now, we have removed an assert.
=> [CBRD-21818] Removed an assert

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-21818
This requires attention. Since it seems to be legacy code, it needs an update to cover all the possible cases. For now, we have removed an assert.
=> [CBRD-21818] Removed an assert (#959)

src/base/object_representation.h, src/compat/db_macro.c, src/compat/dbtype.h, src/object/object_primitive.c, src/object/object_primitive.h, src/object/object_representation.c, src/query/query_executor.c
* inline or_get_varchar_compression_lengths, db_set_compressed_string and db_get_compressed_size
* change OR_GET_STRING_SIZE_BYTE as or_get_string_size_byte
=> [CBRD-21558] 10.1p1: inline functions for string compression (#839)

src/query/query_manager.c, src/session/session.c, src/session/session.h
http://jira.cubrid.org/browse/CBRD-21497
Recycling query id may allocates a query id which is for a holdable cursor. It causes unexpected close of the existing holdable cursor.
=> [CBRD-21497] assigns an idle query id

src/compat/db_admin.c
http://jira.cubrid.org/browse/CBRD-21831
createdb also needs session state. It is a regression of #968 .
=> [CBRD-21831] initializes session state for createdb

src/base/error_manager.h, src/base/resource_shared_pool.hpp, src/base/system_parameter.c, src/base/system_parameter.h, src/query/vacuum.c, src/thread/thread_compat.hpp, src/thread/thread_daemon.cpp, src/thread/thread_daemon.hpp, src/thread/thread_entry.cpp, src/thread/thread_entry.hpp, src/thread/thread_looper.cpp, src/thread/thread_looper.hpp, src/thread/thread_manager.cpp, src/thread/thread_manager.hpp, src/thread/thread_task.hpp, src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-21827
Make worker pool execution stop robust in regard with concurrent task execution.
The bug context - vacuum stop and three thread involved: master thread (calls vacuum_stop), vacuum master thread (is executing vacuum_process_vacuum_data) and vacuum worker. The order of calls:
1. Vacuum master thread starts pushing task, but is preempted somewhere inside worker_pool->execute
2. Master thread notifies vacuum to shutdown and stops worker pool.
3. Vacuum master regains focus, registers thread (or has already registered one) and starts new execution.
4. Worker pool is destroyed, threads are deleted, but one thread is joinable (crash).
The fix requires worker pool to register all threads in order to stop execution. This prevents any further thread …
=> [CBRD-21827] Fix worker pool stop & concurrent tasks

src/parser/type_checking.c, src/query/list_file.c
http://jira.cubrid.org/browse/CBRD-21674
We need a schema in order to validate a json when inserting a new value in table. In order to do that we have the **JSON_VALIDATOR** object. 
We will store in cache a **tp_domain** pointer which will be used further for the retrieval of the domain. 
When trying to unify two types ("**/src/query/list_file.c**", method: **qfile_unify_types**) we will check if the **domain pointers are the same**, but when we are dealing with json types, if the schemas are not the same, **those pointer will be different** so we need an additional check to pass that condition and to successfully make the union.
=> [CBRD-21674] - Added support for json union

src/base/tz_support.c
http://jira.cubrid.org/browse/CBRD-21839
It is a legacy bound read bug to parse a timezone offset which does not have a second.
=> [CBRD-21839] fixes bound read of parsing timezone offset

src/base/tz_support.c
http://jira.cubrid.org/browse/CBRD-21839
It is a legacy bound read bug to parse a timezone offset which does not have a second.
=> [CBRD-21839] fixes bound read of parsing timezone offset (#974)

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-21540
This is a regression of 10.1.
orderby list is already expanded and semantic checking should consider the expanded list.
=> [CBRD-21540] order by list might be already expanded

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-21540
This is a regression of 10.1.
orderby list is already expanded and semantic checking should consider the expanded list.
=> [CBRD-21540] order by list might be already expanded (#976)

src/thread/thread_manager.cpp
http://jira.cubrid.org/browse/CBRD-21857
construct/destruct default entry manager (cubthread::manager.m_entry_manager).
=> [CBRD-21857] construct/destruct default entry manager

src/base/porting.c
http://jira.cubrid.org/browse/CBRD-21819
Critical sections were useless due to the same thread id used by several threads.
=> [CBRD-21819] Quick fix for thread id

src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-21861
fixes UMR to cast zero length string to number.
=> [CBRD-21861] UMR of tp_atof with zero length string

src/base/memory_hash.c
http://jira.cubrid.org/browse/CBRD-21862
This is also a legacy bug.
It might badly access zero length string to generate hash key.
=> [CBRD-21862] IVR of mht_get_hash_number with zero length string

src/object/object_template.c, src/object/object_template.h, src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-21871
It is a regression of #984 
Before #984, it accessed freed object template. It worked as a hack.
To access inserted object template, client insert routines request to template manager to keep it by resetting `discard_on_finish`. Since the flag was not used, fix changes its behavior. Caller who wants to keep the template after flush should explicitly free it.
=> [CBRD-21871] to keep inserted object template for getGeneratedKeys

src/cci/cas_cci.c
http://jira.cubrid.org/browse/CBRD-21895
It is a legacy bug which can be reproduced when connection to cas is disconnected and cci retries.
The return of `qe_set_cas_change_mode` is confusing. Fix separates input cas mode from return code.
=> [CBRD-21895] cci_set_cas_change_mode: fixes bad retry

src/query/vacuum.c, src/thread/thread.c, src/thread/thread.h, src/thread/thread_entry_task.cpp, src/thread/thread_entry_task.hpp, src/thread/thread_looper.hpp, src/thread/thread_manager.cpp, src/thread/thread_manager.hpp, src/transaction/boot_sr.c, src/transaction/lock_manager.c
http://jira.cubrid.org/browse/CBRD-21841
Refactor deadlock detect daemon thread using new thread API, also a daemon_entry_manager class was added which will serve as daemon manager for creating and retiring a daemon thread entry, later this new class will be used for other daemon threads migration
=> [CBRD-21841] migrate deadlock detect daemon thread to new API

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-21875
Expected json path will be parsed correctly
When parsing the sql path, if we have an array index like ```$.[123]``` we need to move the index of the iteration **i** to the index of the last ending bracket. This way the index will be auto incremented in the for loop.
This PR should fix the parsing of numeric index in sql path.
=> [CBRD-21875] Expected json path will be parsed correctly

src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-21873
Wrong parameter in json_arary_append
When calling db_json_array_append_func, the 3rd parameter (raw_path) was passed using a wrong index.
=> [CBRD-21873] Wrong parameter in json_arary_append

src/transaction/lock_manager.c
http://jira.cubrid.org/browse/CBRD-21901
Fix for a regression bug that was introduced after migration of deadlock detection thread to new thread API.
=> [CBRD-21901] fix deadlock detection

src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-21884
If the **value** that we want to append is null then the result should be null.
=> [CBRD-21884] Crash for json_array_append in view

src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21902
Stop checkpoint daemon before log finalize enters in critical section.
A quick fix for a bug that was introduced by refactoring checkpoint ([CBRD-21843](http://jira.cubrid.org/browse/CBRD-21843), #997) daemon.
=> [CBRD-21902] stop checkpoint daemon before log finalize enters in critical section

src/query/query_executor.c, src/storage/statistics_sr.c, src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-21897
This is a legacy issue.
Dead-lock/latch between `qexec_execute_build_indexes` and `xstats_get_statistics_from_server`.
The latter acquires lock and then fixes a page latch to access class representation, while the former did into reverse. This caused deadlock chances.
Fix is to make `show indexes` to follow the same order of query execution.
=> [CBRD-21897] fix to avoid deadlock of "show indexes"

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-21916
fixes a slip of #1000.
=> [CBRD-21916] db_json_get_json_from_str returns null for an invalid json

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-21883
I left cristi's logic unchanged and I added the case when the string is surrounded by double quotes. If I find a double quote, I look immediately for the closing one, ignoring all other tokens.
=> [CBRD-21883] Tokenize an SQL path string that's surrounded by double quotes

contrib/gdb_debugging_scripts/thread_tran.gdb, src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-21914
In case when worker pool is stopped and a task was pushed for execution, worker needs to be unregistered so it can be stopped as well.
Plus a fix for gdb thread scripts for finding thread by index,transaction index and thread id
=> [CBRD-21914] deregister worker in case of an early out from execute

src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-21933
Fixes XASL_ID leak which is a regression of #969.
=> [CBRD-21933] fixes a memory leak of query recompilation

src/query/vacuum.c, src/query/vacuum.h, src/storage/es.c, src/storage/es.h, src/transaction/log_global.c, src/transaction/log_impl.h, src/transaction/log_manager.c, src/transaction/recovery.c
http://jira.cubrid.org/browse/CBRD-21847
We are suffering linking errors building libcubrid on Windows 10, Visual Studio 2017. This is a regression of CBRD-21847, but we cannot explain it.
All we know is that we get a series of linker errors like this:
>   es.obj : error LNK2005: "void __cdecl std::_Store_relaxed_1(unsigned char volatile *,unsigned char)" (?_Store_relaxed_1@std@@YAXPECEE@Z) already defined in vacuum.obj [C:\Work\Cubrid\Github\upstream\build\cubrid\cubrid.vcxproj]
es.obj : error LNK2005: "void __cdecl std::_Store_release_1(unsigned char volatile *,unsigned char)" (?_Store_release_1@std@@YAXPECEE@Z) already defined in vacuum.obj [C:\Work\Cubrid\Github\upstream\build\cubrid\cubrid.vcxproj]
es.obj : error LNK2005: "void __cdecl std::_Store_seq_cst_1(unsigned char volatile …
=> [CBRD-21847] fix windows linker error for es.obj

src/base/error_context.cpp, src/base/error_context.hpp, src/base/error_manager.c
http://jira.cubrid.org/browse/CBRD-21937
The hang is caused by double error log file mutex: one in er_final and once in nested logging for error context.
The logging of error context is only for debug and should be disabled anyway. However, if we ever want to reactivate it, the mutex issue must be tackled too.
=> [CBRD-21937] disable error context/message logging

src/base/error_manager.c, src/communication/network_sr.c, src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-21940
Quick fix reloading error manager in boot_restart_client for broker/cas case.
Make "sticky" error manager initialization. If a specific file is given (name string is not NULL), the error manager initialization is considered sticky. A new er_init call is skipped.
This way, csql and utilities will keep their initial file as error log file, while broker/cas will be set in boot_restart_client.
=> [CBRD-21940] Fix reloading error manager for broker/cas

msg/de_DE.utf8/cubrid.msg, msg/en_US.utf8/cubrid.msg, msg/en_US/cubrid.msg, msg/es_ES.utf8/cubrid.msg, msg/fr_FR.utf8/cubrid.msg, msg/it_IT.utf8/cubrid.msg, msg/ja_JP.utf8/cubrid.msg, msg/km_KH.utf8/cubrid.msg, msg/ko_KR.euckr/cubrid.msg, msg/ko_KR.utf8/cubrid.msg, msg/ro_RO.utf8/cubrid.msg, msg/tr_TR.utf8/cubrid.msg, msg/vi_VN.utf8/cubrid.msg, msg/zh_CN.utf8/cubrid.msg, src/base/error_code.h, src/compat/db_json.cpp, src/compat/db_json.hpp, src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-21889
Handle duplicate keys in json_keys
When creating the result json array that will contain all the keys for a specific path, we need to add **only unique values**, so we need to keep track of already inserted keys. For that we can use an unordered_set for O(1) find operation.
Suppose the following example:
```
select json_keys('{"a":{"c":1, "d":2},"a":3, "c":2}');
+------------------------------------------------+
| json_keys('{"a":{"c":1, "d":2},"a":3, "c":2}') |
+------------------------------------------------+
| ["a", "c"]                                     |
+------------------------------------------------+
```
We have 2 keys with name "a" but only one in the result.
=> [CBRD-21889] Handle duplicate keys in json_keys

src/storage/page_buffer.c, src/storage/page_buffer.h, src/thread/thread.c, src/thread/thread.h, src/thread/thread_daemon.cpp, src/thread/thread_daemon.hpp, src/thread/thread_looper.cpp, src/thread/thread_looper.hpp, src/thread/thread_waiter.hpp, src/transaction/boot_sr.c, src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-21848
http://jira.cubrid.org/browse/CBRD-21849
http://jira.cubrid.org/browse/CBRD-21850
http://jira.cubrid.org/browse/CBRD-21851
This patch includes migration of:
- [CBRD-21848](http://jira.cubrid.org/browse/CBRD-21848) page buffer maintenance daemon
- [CBRD-21849](http://jira.cubrid.org/browse/CBRD-21849) page flush daemon
- [CBRD-21850](http://jira.cubrid.org/browse/CBRD-21850) page post flush daemon
- [CBRD-21851](http://jira.cubrid.org/browse/CBRD-21851) flush control daemon
=> [CBRD-21848] [CBRD-21849] [CBRD-21850] [CBRD-21851] page flush daemons migration

src/broker/cas.c
http://jira.cubrid.org/browse/CBRD-21944
Reload error manager instead of just calling er_final. This was legacy code that relied on automatic initialization to be called whenever required.
=> [CBRD-21944] cas_main reload error manager

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-21948
Server start hanged during recovery because it tried to notify vacuum workers of dropped file when no workers was running.
Fixed by skipping notification during recovery.
=> [CBRD-21948] skip dropped file notification during recovery

src/base/perf_monitor.c, src/base/perf_monitor.h, src/communication/network_interface_sr.c, src/communication/network_sr.c, src/query/query_executor.c, src/query/vacuum.c, src/session/session.c, src/storage/page_buffer.c, src/thread/thread.c, src/thread/thread.h, src/thread/thread_looper.cpp, src/thread/thread_looper.hpp, src/thread/thread_manager.cpp, src/thread/thread_waiter.cpp, src/thread/thread_waiter.hpp, src/thread/thread_worker_pool.hpp, src/transaction/boot_sr.c, src/transaction/lock_manager.c, src/transaction/log_manager.c, src/transaction/log_manager.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21852
This patch includes:
- option to provide a period function to the thread looper that will be used to refresh sleep interval on every task execution
- change of the daemon sleep strategy
from: **execute task then sleep for fixed period**
to: **execute task then sleep for `fixed period - execution time`**
- migration of log flush daemon
=> [CBRD-21852] migrate log flush daemon thread to new API

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-21952
When server is down and log flush daemon is not yet stopped, a worker thread needs to flush pages directly not through daemon.
=> [CBRD-21952] flush pages directly on server stop

src/parser/parse_tree_cl.c, src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-21953
It is an issue of legacy client-side update. Two different update queries badly share an XASL for select.
The system generated select was "SELECT ..., rhs1, rhs2, ... FROM table ...".
When two different updates set different sets of attrs, generated select was lead to one XASL entry.
This causes unexpected issues of reusing an XASL entry, e.g, mismatched types.
Uses lhs of an assignment as its column alias:
For example, "UPDATE t SET x = ?, y = ?;" will generate "SELECT ..., ? AS x, ? AS y FROM t;".
=> [CBRD-21953] system generated select for client-side update has column names as well as its value

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-21960
There was memory leak of `default (TO_CHAR(...) )` expression.
=> [CBRD-21960] fixed memory leak of "show columns"

src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-21941
Now that we logic for controlling looper period using a function of a form:
`std::function<void (bool & is_timed_wait, delta_time & period)>`
I applied old sleeping strategy from [src/thread/thread.c](https://github.com/CUBRID/cubrid/blob/4b1610de177307725ef61281c779b2104e8e141c/src/thread/thread.c#L2183) to the new remove log archive daemon.
=> [CBRD-21941] apply old sleeping strategy for remove log archive daemon

locales/make_locale_x64.bat
http://jira.cubrid.org/browse/CBRD-21966
In the case of VS2017 v150, the tools needed for make_locale.bat cannot be located using VS140COMNTOOLS but I found another variable pointing exactly to the necessary path: VS150COMCOMNTOOLS
=> [CBRD-21966] Make locale based on %VS150COMCOMNTOOLS% for VS2017 v150

src/base/lockfree_circular_queue.hpp, src/query/vacuum.c, unit_tests/lockfree/test_cqueue_functional.cpp
http://jira.cubrid.org/browse/CBRD-21970
Fix producing/consuming block data buffers. Current version that produces and consumes pointers to data is broken.
Side effect of fix is that lock-free circular queue data type is no longer limited to atomic types. I don't think the restrictions was so useful anyway. Simple copy instructions should be enough, with the note that more complex structure may suffer performance penalties.
Should also fix [CBRD-21971](http://jira.cubrid.org/browse/CBRD-21971), [CBRD-21972](http://jira.cubrid.org/browse/CBRD-21972) and [CBRD-21973](http://jira.cubrid.org/browse/CBRD-21973)
=> [CBRD-21970] fix lfcq & vacuum

src/compat/db_macro.c, src/compat/dbtype.h, src/parser/parse_dbi.c, src/parser/parser.h, src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-21974
This is momentarily a test PR. I'd like to see regression results and then discuss the fix.
@cristighr1995 found an issue while investigating crash on #1039.
Scenario can easily reproduce:
```sql
create table t (i int, [json] json );
update t set [json]='111' where [json]='"a"' order by [json];
```
The problem was ultimately generated by unsafe ```pt_init_precision_and_scale```. It wants to set precision and scale in value according to node data type, but does no check if data types match. Therefore, it may modify wrong fields in wrong type of domain/data.
With JSON, since its schema is stored in ```value.data```, it overwrites the ```value.data.ch.medium``` when value is char type. Before Cristi's changes, the overwrite was harmless because it …
=> [CBRD-21974] fix pt_make_val_list type missmatch

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-21975
Fix passing consumed pointer in pgbuf_get_thread_waiting_for_direct_victim.
=> [CBRD-21975] Fix pgbuf_get_thread_waiting_for_direct_victim argument

locales/make_locale_x64.bat
http://jira.cubrid.org/browse/CBRD-21976
- search for Visual Studio installations in reverse order of the versions (from newest to oldest) and fall back to an older version if one doesn't exists or it is invalid
- display more messages for trace and better information about Visual Studio version & tools, compiler & linker
NOTE: just for testing it is not necessary to re-generate the whole project, it is enough to use the last build and replace the content of
`<cubrid_install_path>/bin/make_locale.bat`
with the content of the file from this PR
`make_locale_x64.bat`
and call it for at least one locale, e.g.:
`make_locale.bat ro_RO`
TODO: test with VS2017 v150 Professional & Enterprise
=> [CBRD-21976][Regression] make locale failed on Windows

src/query/vacuum.c, src/query/vacuum.h
http://jira.cubrid.org/browse/CBRD-21982
When vacuum worker contexts are created, they are also assigned a private LRU list. When a thread entry is claimed for vacuum job, it inherits the private list.
This is a regression of thread manager refactoring.
=> [CBRD-21982] assign private LRU list to vacuum workers

src/base/perf_monitor.c
http://jira.cubrid.org/browse/CBRD-21984
Changes are:
- Daemon stats are qualified with its name.
- Thread and daemon stats were activated by default.
=> [CBRD-21984] make daemon stats grep-friendly

src/transaction/lock_manager.c
…NTERVAL
http://jira.cubrid.org/browse/CBRD-21986
It is a bad legacy bug and was not so serious since there was forced sleep of 100ms.
=> [CBRD-21986] fixes deadlock detector to keep PRM_ID_LK_RUN_DEADLOCK_INTERVAL

src/storage/page_buffer.c, src/thread/thread_daemon.cpp, src/thread/thread_daemon.hpp
http://jira.cubrid.org/browse/CBRD-21987
Two changes were required to stop checkpoint thread on shutdown:
1. a way to tell thread context when daemon is stopped. In order to avoid storing the context in daemon (and would have forced us to make daemon template based on Context), I bind the stop function at runtime (calling context.interrupt_execution). As a result, thread_p.shutdown is set to true.
2. pgbuf_flush_chkpt_seq_list check thread_p->shutdown regularly.
=> [CBRD-21987] stop checkpoint on shutdown

src/session/session.c, src/storage/btree.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-21994
The issue is caused by system transaction being interrupted and reflect unique statistics handling the case in a wrong manner.
This patch addresses second issue by:
1. if reflecting statistics of one entry fails, unlock entry before aborting.
2. do not interrupt reflect unique statistics
Should be enough to fix the issue, I will tackle first issue in a separate patch.
=> [CBRD-21994] do not interrupt reflect unique statistics

src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-21996
The logic of stopping log writer stop should be to first abort request handler and then its connection. This order changed as regression of migration request handlers to new thread manager.
Stop log writer request handler before its connection.
=> [CBRD-21996] stop logwr request handler before connection

src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-21995
Map css_stop_log_writer on all thread entries when css_stop_all_workers is called with THREAD_STOP_LOGWR.
=> [CBRD-21995] fix calling stop log writer

src/thread/thread_manager.cpp
http://jira.cubrid.org/browse/CBRD-22011
Reduce number of total threads (connection entries are counted twice although they are not migrated yet).
=> [CBRD-22011] do not count connection threads twice

src/thread/thread_entry_task.cpp
http://jira.cubrid.org/browse/CBRD-21980
The resume_status member variable of a thread context wasn't reset when recycling or retiring a context,
so the if (thread_p->resume_status == THREAD_RESUME_DUE_TO_INTERRUPT) at log_writer.c:xlogwr_get_log_pages would execute and would make the entry's eof_lsa not null. The whole logic in xlogwr_get_log_pages relies on the fact that entry's eof_lsa is null, so this was generating
a replication bug.
=> [CBRD-21980] [Regression] [HA] tables can't be replicated to slave node

src/connection/server_support.c, src/query/show_scan.c, src/thread/thread.c, src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-21998
System transaction is only for internal usage. We cannot allow it to be interrupted.
There are two ways it can be interrupted:
1. By client request. In this case an error is returned.
2. Automatically by internal code. This case should crash on debug. On release it will ignore the request.
@eseokoh 
The patch may cause regressions. I think it is better to run some manual tests first.
=> [CBRD-21998] do not kill system transaction

unit_tests/thread/test_worker_pool.cpp
http://jira.cubrid.org/browse/CBRD-22034
Enable test_worker_pool code now that compatibility with gcc 4.4.7 is no longer required (atomic header was not supported).
Updated code to latest worker pool changes.
=> [CBRD-22034] remove gcc 4.4.7 compatibility - test_worker_pool

src/communication/stream_transfer_receiver.cpp, src/communication/stream_transfer_sender.cpp, src/query/vacuum.c, src/session/session.c, src/storage/page_buffer.c, src/thread/thread_daemon.cpp, src/thread/thread_daemon.hpp, src/thread/thread_manager.cpp, src/thread/thread_manager.hpp, src/thread/thread_task.hpp, src/transaction/lock_manager.c, src/transaction/log_manager.c, unit_tests/communication_channel/test_main.cpp, unit_tests/transfer_channel/test_main.cpp
http://jira.cubrid.org/browse/CBRD-22008
1. extend tasks and daemons to be used without a context.
2. thread manager tracks entry-less daemons.
3. remove entry/dummy thread contexts from stream transfer and unit test daemons.
4. add daemons names that show up on thread stack.
5. minor fixes in unit tests - add missing signal.h header and remove unnecessary lock-free transactions code.
=> [CBRD-22008] no context task/daemons

src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-22047
Skip doing sanity checks of file header/table if there are waiters on file header and file logging is disabled.
=> [CBRD-22047] fix slow file header sanity checks stacking

src/connection/connection_sr.c, src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-22082
The issue is unchecked connection state and error code. Packet header is not read and then connection transaction ID is set to 0 (system transaction).
Added checks to correctly handle the case.
Note: this patch does not include safe code handling connection entry transaction ID. I may add it or open a different PR.
=> [CBRD-22082] check stop_talk and errors on read & queue

src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-22081
Removed safe-guard. The case is possible even if it is not during recovery. Sometimes file gets extended, but volume header changes are rollbacked. There is no easy way to ensure exact synchronization.
Is is best to just accept file bigger than expected while expanding. If file is big enough, early out.
=> [CBRD-22081] remove incorrect file_expand_to safe-guard

src/query/crypt_opfunc.c
http://jira.cubrid.org/browse/CBRD-22084
http://jira.cubrid.org/browse/CBRD-22086
This is legacy issue triggered by gcrypt library update. Checking that library was loaded should consider that gcry_control return (1 + source flag) for true and 0 for false. Quoting from manual:
_/* Tell Libgcrypt that initialization has completed. */
`gcry_control (GCRYCTL_INITIALIZATION_FINISHED, 0);`
It is important that these initialization steps are not done by a library but by the actual
application. A library using Libgcrypt might want to check for finished initialization using:
`if (!gcry_control (GCRYCTL_INITIALIZATION_FINISHED_P))`
`{`
`fputs ("libgcrypt has not been initialized\n", stderr);`
`abort ();`
`}`_
The code tried to predict exactly the returned code in case of success by expecting …
=> [CBRD-22084] fix checking gcrypt was successfully loaded

src/communication/network_sr.c, src/connection/client_support.c, src/connection/connection_cl.c, src/connection/connection_defs.h, src/connection/connection_list_cl.c, src/connection/connection_sr.c, src/connection/connection_support.c, src/connection/server_support.c, src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-22083
Safe-guard setting/getting transaction index from connection entry. We cannot set system transaction as transaction index.
@eseokoh, if you think it is necessary, please trigger a manual test.
=> [CBRD-22083] safe-guard connection entry's transaction index

src/communication/network_cl.c, src/communication/network_interface_sr.c, src/connection/connection_cl.c
http://jira.cubrid.org/browse/CBRD-22091
#1092 revealed this old legacy bug.
There was a protocol mismatch between client and server.
Not all list files have a page. One for insert may be empty. Server sends nil buffer as size 0 for the case. 
Client tried to receive data from server only when its non-zero sized receiving buffer is given. Size 0 remains in the packet and the next packet read accidentally read it. The badly read packet is thrashed and client continues to read. This is the way the old legacies worked.
The major changes are
* `css_receive_data` of connection_cl.c // to properly read size 0 buffer
* `net_client_request_with_callback` // to fix potential leak
* `sqmgr_execute_query` // to consider an empty list file page
The other changes are to remove ugly nested blocks for …
=> [CBRD-22091] protocol mismatches when zero size buffer is delivered

src/communication/network_cl.c
http://jira.cubrid.org/browse/CBRD-22093
fixes a bad assertion of #1094.
an empty list_id might be returned.
=> [CBRD-22093] fixes query execution also expects nil list_id

src/transaction/lock_manager.c
http://jira.cubrid.org/browse/CBRD-22095
click counter ignores deadlock error, continues to execute then suspends a lock.
The safe guard expects a deadlock victim will not be a lock suspender.
To ignore the deadlock victim error should also reset `tran_abort_reason`. 
it is an old legacy issue.
=> [CBRD-22095] clearing deadlock victim also resets tran_abort_reason

src/thread/thread_entry.cpp
http://jira.cubrid.org/browse/CBRD-22064
During shutdown, interrupt_execution is called on all thread entries of all running threads (daemon, active workers, vacuum workers). However, it used to only set shutdown flag. If thread is waiting on a latch, it would remain waiting.
Fix by forcing wakeup when thread is waiting.
=> [CBRD-22064] force thread entry wakeup on shutdown

src/thread/thread_entry.cpp
http://jira.cubrid.org/browse/CBRD-22104
Set interrupt as resume status instead of shutdown.
=> [CBRD-22104] use interrupt reason on shutdown threads

src/query/vacuum.c, src/thread/thread_daemon.hpp, src/thread/thread_entry.cpp, src/thread/thread_entry.hpp, src/thread/thread_entry_task.cpp, src/thread/thread_entry_task.hpp, src/thread/thread_task.hpp, src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-22121
JIRA issue is due to dropped files page being fix being interrupted on shutdown. It was not expected and fatal error is set.
Fixed by accepting and propagating the error until vacuum worker is stopped.
Another potential undiscovered issue is interrupting the vacuum master. Its current behavior relies on no interruptions. As a consequence I've made a change on how threads are stopped, by moving stop/interrupt functionality from context (entry) to context manager. From thread design point of view is even better, since this is an outside interaction with context too (like create, retire, recycle context). It allows better tuning on how to stop your workers/daemons.
=> [CBRD-22121] fix stopping execution on shutdown

src/object/work_space.c
http://jira.cubrid.org/browse/CBRD-22127
This must be a legacy issue.
To decache a class mop whose class name is missing caused crash.
=> [CBRD-22127] safer decaching class mop from workspace

src/storage/btree.c
a class lock is required to consistent read.
=> [CBRD-22130] "show index" statements needs a table lock

src/parser/parse_tree.h
http://jira.cubrid.org/browse/CBRD-22132
add variadic macros for messages in a catalog:
```
pt_cat_error(parser, node, setNo, msgNo, ...)
pt_cat_warning(parser, node, setNo, msgNo, ...)
```
to be used with errors & warnings instead
```
PT_ERRORmf(), PT_ERRORmf2(), PT_ERRORmf3(), PT_ERRORmf4(), PT_ERRORmf5()
PT_WARNINGmf(), PT_WARNINGmf2(), PT_WARNINGmf3()
```
For normal formatted messages (without catalog) use directly pt_frob_error(), pt_frob_warning() instead:
```
PT_ERRORf(), PT_ERRORf2(), PT_ERRORf3(), PT_ERRORf4(), PT_ERRORf5()
PT_WARNINGf(), PT_WARNINGf2(), PT_WARNINGf3()
```
The numbered macros should be removed later on
What "frob" means in pt_frob_error???
=> [CBRD-22132] Variadic instead numbered macros for cataloged formatted messages: PT_ERRORmf?, PT_WARNINGmfx?

src/parser/parse_tree_cl.c, src/parser/parser_support.c, src/parser/show_meta.c, src/parser/show_meta.h, src/query/execute_statement.c, src/query/show_scan.c
http://jira.cubrid.org/browse/CBRD-22118
* show columns|index requires select authorization of the table
* some show statements update statistics [all | catalog] are allowed for dba groups
* update statistics of table requires alter authorization of the table
The complete list of the changes are:
http://jira.cubrid.org/browse/CBRD-22118?focusedCommentId=4750765&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4750765
=> [CBRD-22118] authorizations for some show and update statistics statements

src/connection/tcp.c, src/connection/wintcp.c
http://jira.cubrid.org/browse/CBRD-22123
This bug appears because cub_master gets blocked when delegating the connection to cub_server because the socket send is blocking and cub_server spawns receiving threads instead of pooling them, which has overhead. Because cub_master has a backlog of only 50, clients quickly saturate this value and they get rejected.
We decided, for the time being, to simply increase the cub_master backlog to 1K in order to fix the regression. We conveyed that pooling threads on the cub_server side it's not worth it and we may, in the future, separate connections to threads on cub_master's side.
=> [CBRD-22123] Broker failed to connect to database server when insert data with multi-threads

src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-22145
The issue is caused by a miss-match between the actual number of maximum connections and the number expected by server request worker pool.
The worker pool used to allocate `css_get_max_conn ()` workers, which is the maximum number of connections that can push task at any time. However, there is also the master connection which, even though it cannot push a tasks on worker pool, interferes with the algorithm of dispatching workers on cores.
In our case, master connection has index 0, which would be normally assigned to core 0. However, the connection with index equal to `css_get_max_conn ()` was not considered. Since master connection can be re-established and a new connection may be assigned to it, with a different index, we cannot be sure which …
=> [CBRD-22145] fix number of server request workers

src/base/object_representation_sr.c, src/base/object_representation_sr.h, src/executables/unload_schema.c, src/object/class_object.c, src/object/class_object.h, src/object/object_printer.cpp, src/object/schema_manager.c, src/object/schema_manager.h, src/object/schema_template.c, src/object/schema_template.h, src/object/transform_cl.c, src/parser/csql_grammar.y, src/parser/parse_tree.h, src/parser/parse_tree_cl.c, src/parser/parser.h, src/parser/parser_support.c, src/parser/semantic_check.c, src/query/execute_schema.c, src/query/query_executor.c, src/storage/catalog_class.c
http://jira.cubrid.org/browse/CBRD-22108
Update grammar to allow on update current times values in table definition statements. These values need to be saved in the table's schema, to be then retrieved when making update queries in http://jira.cubrid.org/browse/CBRD-22109.
=> [CBRD-22108] Grammar for update default

src/connection/server_support.c, src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22146
This is a regression of a recent change. Vacuum workers are forced to wake up if they are waiting on a page latch. The case we tried to solve was a long queue of workers all trying to deallocate pages from overflow file.
However, there is no way we can discriminate between these cases and uninterruptible operations (like page manipulation during system operation postpone phase).
This patch removes force wakeup. As a consequence, shutdown may again take a long time.
=> [CBRD-22146]  do not force interrupt vacuum on shutdown

src/compat/db_json.cpp, src/object/object_primitive.c, src/parser/parse_dbi.c, src/parser/view_transform.c
http://jira.cubrid.org/browse/CBRD-21832
The function which caused the memory leak is `mq_invert_subqueries` because the parser_node was overwritten with the value returned by `mq_invert_assign`.
The fix was to free the current node before being overwritten. Instead of creating a new empty node which will be freed when the program stops the execution, I think it is better to delete the node from the select list (`select_statements->info.query.q.select.list`) instead of replacing it with an empty node.
=> [CBRD-21832] DL in db_json_allocate_doc

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22137
Fix recovery of vacuum data after freshly initialized last page:
1. Include last page allocation, initialization **and appending data blocks** in a system operation.
2. Check vacuum data last page free index is valid after recovery.
3. Make vacuum data last_blockid private and do sanity checks when setting new value.
4. Add more logging on vacuum data recovery.
=> [CBRD-22137] fix recovery of vacuum data page

src/connection/server_support.c
I removed the code that initialized the new replication code with some mocked instances and did not deactivate all new replication code (it being reliant on that initialization). I will reactivate it later, after having a common branch with Razvan. Many regressions should disappear.
=> [CBRD-22165] [HA] Core dumped in cubreplication::master_senders_manager::get_stream

src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-22166
Condition for finding threads to not stop in css_find_not_stopped was wrong, it was true and did the early out when it wasn't supposed to (for connection workers). This patch fixes the condition, now connection workers should also be stopped.
=> [CBRD-22166] [Regression] Core dumped in map_running_contexts

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22164
Safe-guard failed after copydb because `logpb_last_complete_blockid ()` returns `VACUUM_NULL_LOG_BLOCKID`. Fix the case by skipping `vacuum_Data.set_last_blockid ()` in this case.
=> [CBRD-22164] fix vacuum_data_load_and_recover after copydb

src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-22178
While investigating connection issues, I noticed many connections waiting on worker queue; some of the owners were allocating memory to add new workers to queue.
I am trying a different approach that will hopefully work faster:
1. use a single preallocated stack for all available workers, active or inactive.
2. added a new field to worker `m_has_thread` to tell if thread is started. The field is set to true on `init_run` and set to false if `get_new_task` times out without task. `m_has_thread` must be protected by `m_task_mutex`.
3. decision to notify running thread or spawn can only be done after getting `m_task_mutex` and checking `m_has_thread` (`push_task_on_running_thread` and `start_new_thread` were merged into `assign_task`).
@eseokoh 
Would …
=> [CBRD-22178] optimize available worker queues

src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-22178
Retire context while holding mutex to prevent another thread from overwriting it.
=> [CBRD-22178] protect retire context

src/base/mem_block.hpp, src/base/string_buffer.hpp, src/object/object_primitive.c, src/object/object_print.c, src/parser/parse_tree_cl.c, src/parser/parser_support.c
http://jira.cubrid.org/browse/CBRD-22035
New compiler version allows now the use of lambdas => string_buffer instances  can use context specific allocator/deallocator instead global/generic ones:
- parser allocator 
- private allocator
=> [CBRD-22035] Remove GCC 4.4.7 compatibility code - string buffer

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22174
This is a hack to reset last_blockid of vacuum data on the first start of copied database (last_blockid is inherited from original database). It is not a proper fix and we should probably find a better one :).
The way now copydb works makes it hard to find non-hackish fix for the issue.
=> [CBRD-22174] reset last blockid for copied database

src/connection/connection_support.c, src/connection/connection_support.h, unit_tests/replication_channels/CMakeLists.txt, unit_tests/replication_channels/cub_master_mock.cpp, unit_tests/replication_channels/master_replication_channel_mock.cpp, unit_tests/replication_channels/test_main.cpp
http://jira.cubrid.org/browse/CBRD-22179
Made changes for Windows side in order to prevent replication unit test from crashing. The libraries have different behaviors for Linux and Windows, so I made the unit test conscious of the differences.
=> [CBRD-22179] Fix replication unit test for Windows

src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-22193
Worker pool cannot rely on worker queue anymore to make sure all are stopped.
Legacy design permitted consuming from "inactive" list and count stopped workers. Being in inactive list guaranteed the worker thread has stopped (or was stopping but not using worker resources anymore).
Updated worker stop notification to output if thread is stopped. m_has_thread field should guarantee that thread is not running or at least that it will no longer use worker resources.
=> [CBRD-22193] fix waiting workers to stop

src/parser/view_transform.c
http://jira.cubrid.org/browse/CBRD-22169
The new functionality of `mq_invert_subqueries` is when we can not invert the current node from list (calling `pt_invert (parser, *column, attr)`) we better delete the node and free it. 
Because free is called recursively on all of its next links, we need to assign `NULL` to the next pointer in order to free just the current node.
Maybe this will resolve also this issue: http://jira.cubrid.org/browse/CBRD-22170
=> [CBRD-22169] Core dumped in free_node_in_tree_pre

src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-22171
In the beginning of the function `pt_fold_const_expr` we set `expr->next = NULL` which in case of error will produce a memory leak if the next pointer is not null. 
The quick fix for this issue is to reestablish the link to `expr_next` when we return the `expr` node. I saw that in majority cases when we encounter an error we return the node unmodified, but because the next is set to null we will lose this link.
I think a better fix will be to refactor this method because is confusing the return part: we either `return` in all cases or use the `goto end` label.  Also I think that when the `result` node is `NULL` we will also have a memory leak which will be triggered by other cases.
=> [CBRD-22171] DL in db_json_allocate_doc

src/query/vacuum.c, src/query/vacuum.h, src/transaction/boot_sr.c, src/transaction/log_impl.h, src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-22174
Add a routine to handle first boot after copydb. Log header is extended for this purpose, but it should be backward compatible.
Properly handle the case when log_blockid is `NULL`. It may happen on both branches of condition:
`if (LSA_ISNULL (&vacuum_Data.recovery_lsa) && LSA_ISNULL (&log_Gl.hdr.mvcc_op_log_lsa))`
=> [CBRD-22174]  first boot after copydb

src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22215
On xasl generation of the On duplicate key update the appending of the on update defaults was left out.
=> [CBRD-22215] ON UPDATE does not apply to ODKU 

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22220
To reuse XASL clone, clear trace stats.
=> [CBRD-22220] clears trace stats to reuse xasl clone

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22220
To reuse XASL clone, clear trace stats.
=> [CBRD-22220] clears trace stats to reuse xasl clone (#1160) 

src/compat/db_json.cpp, src/compat/db_json.hpp, src/executables/loader.c, src/object/object_domain.c, src/parser/parse_dbi.c, src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-22232
The implementation of `db_json_get_json_from_str` does `doc.Parse(str)`. Because the string is not null terminated, it will go until reaches `'\0'` so this is why we will have a parse error. 
Modified the header of `db_get_json_from_str` to send a string with a specific length.
=> [CBRD-22232] [JSON]Cannot coerce value of domain "national character" to domain "json"

src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-22226
The `json->document` pointer was `NULL`, but dereferencing a nullptr causes undefined behavior. 
So, in order to avoid these cases, we should add a safety check before entering the function.
=> [CBRD-22226] [shell] Core dumped in db_json_serialize at src/compat/db_json.cpp:2945

src/base/error_context.cpp
http://jira.cubrid.org/browse/CBRD-22257
keep error stack safe-guard for server mode only
=> [CBRD-22257] keep error stack safe-guard for server mode only

src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-22266
Deallocate is undone and a compensate record is appended to overwrite usual fetch mode - we need to force page fix even if it is deallocated.
However, it does not mean fixed page is always deallocated. Compensation may have been flushed to disk.
=> [CBRD-22266] expect allocated page for OLD_PAGE_DEALLOCATED

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22268
b-tree page initialization is logged with undoredo. on undo, page type is set to deallocated/unknown. xbtree_add_index initialized root page twice; which lead to inconsistent state during rollback.
remove duplicate b-tree root page initialization.
=> [CBRD-22268] remove duplicate b-tree root page initialization

src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-22277
worker is marked as having thread too late (only after thread was spawned).
vacuum worker pool is stopped. all workers are notified to stop. one worker was just assigned a task, but has not started yet, and its m_has_thread flag is false. pool wrongfully assumes everyone is stopped and gets destroyed.
worker finally wakes up to init_run and finds destroyed core parent, causing the crash.
To have a safe stop, we need to set m_has_thread before actually starting the thread.
=> [CBRD-22277] fix worker pool stopping

src/broker/cas_execute.c
http://jira.cubrid.org/browse/CBRD-22283
Revert 0f894069227b3b009ae685adf26d0d9c1f5a3f79, since the current code closes the cursor
To auto-commit scrollable cursors, we should have to hold the cursors.
We may improve it later.
=> [CBRD-22283] not to auto-commit and close a scrollable cursor.

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-22287
Slip of  #1149. Check for attempt to update an attribute of a CTE and raise an error during semantic check.
=> [CBRD-22287] fix crash updating CTE attribute

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22290
remove safe-guard. sometimes errors are set and not removed.
=> [CBRD-22290] remove no error safe-guard from btree_merge_node_and_advance

src/parser/parse_tree_cl.c, src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22288
OID list of the update's XASL parent was built using the references of the BUILDLIST PROC (it's aptr) which is underneath it. To enable CTEs for Update, CTE procs were placed as aptrs before the last BUILDLIST proc. The fix was to copy the oid list from the last aptr.
=> [CBRD-22288] fix update xasl's referenced oid list

src/jdbc/cubrid/jdbc/driver/CUBRIDStatement.java
http://jira.cubrid.org/browse/CBRD-22325
Statement.setFetchSize(0) should work. but it throws illegalArgumentException.
=> [CBRD-22325] setFetchSize throws an exception when zero size is given

src/optimizer/query_graph.c, src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-22326
It is an inherited vulnerability might crash.
I've pushed another patch to raise an error when using index clause refers to an invisible index.
I believe this will also fix the other client crashes.
=> [CBRD-22326]  raise an error when using index clause refers to an invisible index

src/storage/catalog_class.c
http://jira.cubrid.org/browse/CBRD-22315
In case default_expr is not a default expression it is left out of default_value in db_attribute. Fix is to convert the value to string and later append the on update default part to it (same way as when there is no on update expression either).
=> [CBRD-22315] unexpected default_value in db_attribute

src/thread/thread_entry_task.cpp
http://jira.cubrid.org/browse/CBRD-22336
In case when a thread worker pool is stopped from execution a thread entry that was marked with `shutdown = true` could be reused afterwards. Since shutdown flag is not cleared it might cause problems when reusing the thread entry
=> [CBRD-22336] clear shutdown flag from thread entry when reusing it

src/parser/csql_grammar.y
http://jira.cubrid.org/browse/CBRD-22344
Fixed by placing the JSON_TABLE token on the same level as other sibling's tokens. The issue was that during state transitions the parser was trying to find from remaining buffer _测试表__P__P0_ a token matching the regex: **([a-zA-Z_#]|([\xc0-\xfe]))([a-zA-Z_#0-9]|([\x80-\xfe]))***. It tried then with GLR parsing to traverse down _original_table_spec -> json_table_rule_, and saved the expected token as _"JSON_TABLE"_.
=> [CBRD-22344] Json_Table error message correction

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22345
Update safe-guard to accept that multiple pages can be allocated in a consume iteration.
Details on JIRA issue.
=> [CBRD-22345] vacuum consume iteration may allocate multiple data pages

src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-22343
log_rv_analysis_sysop_end: reset `tdes->rcv.atomic_sysop_start_lsa` and `tdes->rcv.sysop_start_postpone_lsa` if they are equal to sysop_end->lastparent_lsa.
Fix is explained in JIRA issue.
=> [CBRD-22343] reset sysop LSA's

src/parser/xasl_generation.c, src/query/execute_statement.c, src/query/query_executor.c, src/query/xasl.h
http://jira.cubrid.org/browse/CBRD-22181
Changed to pass the with clause of the update/delete down to the generated server-run select query. CTE proc is being generated for the select query, making cte list file results available when executing the client-side queries.
=> [CBRD-22181] Enable CTEs for client-side queries

src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22378
fixes another regression of #1215 
out_list had a loop because `regu_constant_list` were added twice.
=> [CBRD-22378] To generate XASL of percentil functions loops infinitely

src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-22375
Vector's db_vals are not cleared before its destruction
=> [CBRD-22375] Core dumped in cubbase::restrack_assert

src/object/schema_manager.c
http://jira.cubrid.org/browse/CBRD-22397
The normal behavior for shared constraints, specifically for indexes, is that they copy the `BTID` of the original constraint and they do not start another load process for the new index. Online indexes now follow the same behavior.
The issue resided in the fact that the new index will start another load process that will use the first index's `BTID`. Therefore, it will begin inserting objects into the `BTREE`, which was already loaded, and will fail asserts for already inserted objects.
=> [CBRD-22397] Skip online index loading for shared constraints

src/compat/db_json.cpp, src/compat/db_json.hpp, src/compat/db_macro.c, src/object/object_domain.c, src/query/arithmetic.c, src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-21869
This patch adds support for BIGINT type to JSON functionality and also partially implements requirements from [CBRD-21771](http://jira.cubrid.org/browse/CBRD-21771)
=> [CBRD-21869] add support for BIGINT type in JSON

src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22394
Registered uncleared db_vals of char type to be cleared as parser orphans.
=> [CBRD-22394] pt_to_aggregate_node memory leak

src/parser/xasl_generation.c
Create as subquery creates underneath an insert subquery. Since there is a false where in the non_recursive part of the cte, the non_recursive part is transformed to a false_subquery. This transforms the non_recursive part into a PT_VALUE, making the assert test fail.
It is however alright to just change the assertion since the non_recursive_part will not get its xasl built. Execution does recognize non_recursive_part null as being a false where.
=> [CBRD-22403] Core dumped in pt_uncorr_post

src/parser/name_resolution.c, src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-22413
Fix consists of multiple changes in how json table column names are handled.
1. We have to include json table name in "apply" of walker (fix copy tree and free one of the copies).
2. Use different nodes in spec's as_attr_list (again, duplicate pointers may lead to complications).
3. Fix resolving json table column info's name (pt_bind_name_to_spec workaround).
=> [CBRD-22413] use different name nodes for spec.as_attr_list and json table columns

src/object/schema_manager.c, src/storage/btree.c, src/storage/btree.h, src/storage/btree_load.c, src/transaction/locator_sr.c
It fixes **unique** as well as **not_null** flag of index being built.
http://jira.cubrid.org/browse/CBRD-22424 requires to ship **not null** flag to server.
=> [CBRD-22418] correct {unique | not_null} btree index type

src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-21486
Even though error occurs, fileio_expand_to returns NO_ERROR.
file_create has a safe-guard. If everything worked correctly, it should find no error set. Safe-guard was triggered due to fileio_expand_to bug.
Fixed by returning error code.
=> [CBRD-21486] fileio_expand_to return error code

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22429
Statistics were badly computed after a deletion of an object, not before. Also, some missing btree logging has been added.
=> [CBRD-22429] Fix bad statistics of Online Index

src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-22437
It is a not json_table issue but legacy.
=> [CBRD-22437] fix crash to print a bad group_concat expr

src/object/class_object.c
http://jira.cubrid.org/browse/CBRD-22421
Set the correct `index_status` when the online index finishes loading.
=> [CBRD-22421] Set correct index status of online index

src/compat/db_json.cpp, src/object/object_domain.c, src/query/scan_json_table.cpp, src/query/scan_json_table.hpp, src/xasl/access_json_table.cpp
http://jira.cubrid.org/browse/CBRD-22432
Fix memory leaks in json table (below are listed top elements of the call stack from jira issue):
=> [CBRD-22432] fix memory leaks in json table

src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-22434
Fix cast from empty `DB_TYPE_JSON` to `DB_TYPE_DATETIME`.
When cast from empty `DB_TYPE_JSON` to `DB_TYPE_DATETIME` is not possible `db_value src_replacement` variable needs to be cleared otherwise there is a memory leak
=> [CBRD-22434] fix cast from empty DB_TYPE_JSON to DB_TYPE_DATETIME

src/query/scan_json_table.cpp, src/xasl/access_json_table.cpp, src/xasl/access_json_table.hpp
http://jira.cubrid.org/browse/CBRD-22444
Because json iterators from cubxasl::json_table::node could be reused then delete them only when xasl is destroyed
=> [CBRD-22444] json table: delete json iterators only when xasl is destroyed

src/storage/disk_manager.c, src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-22441
This issue was a regression of propagating interrupt error from fileio_initialize_pages, because it lead to inconsistencies between volume header and disk cache.
After we "commit" the changes in volume header, we cannot permit any interruptions. Fix by verifying logtb_get_check_interrupt in fileio_initialize_pages.
=> [CBRD-22441] do not interrupt fileio_expand_to

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22447
For the case of insert with `DELETE_FLAG` in place, we need to check if we have enough space in the leaf page to insert the new object/key. However, this was badly implemented, as the insert_helper did not hold the information of the key's length, and therefore it would always try to insert the key even if there was not enough space. This should fix it.
=> [CBRD-22447] Fix key_len_in_page set for insert_helper

src/object/schema_manager.c
http://jira.cubrid.org/browse/CBRD-22443
This fixes the second issue.
I was thinking to solve it as lock manager and change my mind to have a simpler fix. (We may have to manage full lock acquisition history. I don't really like it.)
If the transaction holds a lock greater than `IX`, it may break transaction consistencies to demote the lock. Online index creation is only allowed where transaction holds weaker locks, typically, it should be `SCH_S`.
=> [CBRD-22443] online index creation is only allowed for safe cases

src/object/class_object.c, src/storage/btree.c, src/storage/btree_load.c, src/storage/btree_load.h, src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-22422
The issue is caused by b-tree scan current key being reset to nil without clearing when index loose scan is used.
It didn't reproduce with offline index because it didn't generate fence keys and it used to "peak" key value. With online index, fence keys are added and b-tree scan key is reconstructed using fences. As a consequence it has to allocate the midxkey buffer.
Fix by correctly clearing the scan key.
=> [CBRD-22422] fix leak when key value is reset to null

src/communication/network_interface_cl.c, src/communication/network_interface_sr.c
http://jira.cubrid.org/browse/CBRD-22443
It is just a safe guard that helps things don't go worse. I hope we will remove it in someday. 
When server fails to promote the demoted lock, client synchronizes its lock cache with server's.
=> [CBRD-22443] client resynchronizes cached lock if server fails to restore the demoted lock

src/compat/db_json.cpp, src/compat/db_json.hpp, src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-22454
* casting `DB_JSON_BOOL` to one of the following cases: `DB_TYPE_CHAR, DB_TYPE_VARCHAR, DB_TYPE_NCHAR or DB_TYPE_VARNCHAR` will generate the string true or false depending on the json value.
For example statements mentioned below will produce string `'true'` as output:
* `select cast(cast('true' as json) as string);`
* `select cast(cast('true' as json) as varchar);`
* `select cast(cast('true' as json) as char(4));`
* casting `DB_JSON_BOOL` to any other type will generate int with value 1 or 0 depending on the json value. Then int value will be cast to desired type.
For example statements mentioned below will produce string `1` as output:
* `select cast(cast('true' as json) as smallint);`
* `select cast(cast('true' as json) as bigint);`
=> [CBRD-22454] add option to cast from DB_JSON_BOOL to any other type

src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22338
Safe-guard said that if vacuum is not empty, it expects there is at least one entry in last page. However, it is invalidated by a corner case involving very long transaction and a very long period of time with no MVCC operations.
According to log dump, this is what happens:
1. Multiple vacuum data blocks cannot be vacuumed because of very long transactions.
2. Transactions are aborted. A very long rollback phase occurs, which is logged using compensate log records and generates no MVCC ops.
3. Active transactions restart and new MVCC operations are logged. A new vacuum data block is consumed, adding many dummy vacuumed blocks and a block to be vacuumed. A new page is created for new block.
4. In the meantime, jobs that vacuum old blocks start.
5. …
=> [CBRD-22338] vacuum_data_load_and_recover: remove wrong safe-guard

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-22453
When invalid json path is provided for json_array_insert function, instead of using assertion just set an error and return. Statement `select json_array_insert('true', '$', '1');` now returns `ERROR: Invalid JSON path`
=> [CBRD-22453] fix json_array_insert when invalid json path is provided

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22450
For online indexes that are currently loading, skip REPLACE and ODKU routines.
=> [CBRD-22450] Disable Replace and ODKU for online indexes

src/thread/thread_entry.hpp
http://jira.cubrid.org/browse/CBRD-22124
Make thread entry's shutdown flag atomic for safety reasons.
=> [CBRD-22124] make cubthread::entry::shutdown atomic

src/compat/db_json.cpp, src/compat/db_json.hpp, src/parser/type_checking.c, src/query/arithmetic.c, src/query/arithmetic.h, src/query/query_opfunc.c, src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-22451
In case of `JSON_ARRAYAGG` and `JSON_OBJECTAGG` functions, input values must be treated as `JSON_VALUE` and not `JSON_DOC`. Therefore for remove cast to json from type checking, and let server decide how to handle input values
Also this patch includes a side fix for a crash (see backtrace below). Fix was to check for a valid collation_id in qdata_aggregate_value_to_accumulator function only when needed
```
#0  qdata_aggregate_value_to_accumulator (thread_p=0x7ffff6659c18, acc=0x555556739868, domain=0x7fff0400a828, func_type=PT_JSON_ARRAYAGG, func_domain=0x7ffff7f1fa40 <tp_Json_domain>, value=0x7fff040090a0) at ./src/query/query_opfunc.c:6632
#1  0x00007ffff792ad57 in qdata_aggregate_multiple_values_to_accumulator (thread_p=0x7ffff6659c18, …
```
=> [CBRD-22451] Handle type checking for JSON_(OBJECT|ARRAY)AGG functions on server side

src/storage/btree.c, src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-22476
Overflow record was passed instead of leaf record argument to `btree_key_remove_object`.
=> [CBRD-22476] fix btree_key_remove_object leaf record argument

src/object/schema_manager.c, src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-22427
This tries to fix the issue with the partition case for Online Index where the index was not loading for partitions, but only for the top class.
The flow looks like this:
`Create empty indices for the top class and all its subclasses.`
`Demote the lock on the top class and all its subclasses to IX_LOCK.`
`Each index begins loading and checks for unique constraint violation.`
`Promote all locks back to SCH_M_LOCK.`
`Commit changes if everything is in order.`
=> [CBRD-22427] Fix partition issues for Unique Online Index

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22494
Fix `JSON_ARRAYAGG` function when aggregating only NULL values
```sql
drop table if exists t1;
create table t1 (id int , col varchar(10));
insert into t1 values (2, NULL), (2, NULL);
select id, JSON_ARRAYAGG(col) from t1 group by id;
```
Expected result of the select statement is:
```sql
id  json_arrayagg(col)
===================================
2  [null, null]
```
=> [CBRD-22494] fix JSON_ARRAYAGG function when aggregating only NULL values

src/xasl/xasl_stream.hpp
http://jira.cubrid.org/browse/CBRD-22461
The issue is caused by bug in stx_restore. Pointer was marked as visited before allocating, while its value was NULL.
New function is mostly used for json table structures, which are usually right-most scans in query execution. Which hid the bug, because pointers were usually correctly marked as visited by other structures.
For the count query in the issue, column output value pointer is first to pack/unpack. Since it was not properly marked as visited, another pointer was generated for inner heap scan. When inner heap scan predicate was checked, the value read from json table scan was missing.
Fixed stx_restore operation order.
=> [CBRD-22461] stx_restore: alloc struct, then mark as visited

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22492
`prev_page` would be leaked, this should fix it.
=> [CBRD-22492] Fix leak of prev_page

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22502
In the case of deleting an object which was not yet inserted into the index, we would try to insert it in place if we have enough space available. However, the case of overflow keys was not handled, such as it would try to insert a new key but the `btid` could not handle it. This should fix it.
=> [CBRD-22502] Fix overflow keys for a delete which turns into an insert

src/communication/network_interface_cl.c
http://jira.cubrid.org/browse/CBRD-22509
btree_load_index returns NO_ERROR when net_client_request call fails. Fix by propagating network error.
=> [CBRD-22509] propagate network error on btree_load_index

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-22485
Fix slip of not checking db_string_like returned error_code
=> [CBRD-22485] incorrect escape characters passed validation

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-22528
Coercion error is not checked and json_table's expr is removed.
=> [CBRD-22528] json_table leaked error not checked

src/query/scan_json_table.cpp
http://jira.cubrid.org/browse/CBRD-22510
Reset json_table cursor's m_need_advance_row and m_row_was_expanded members to defaults during final clear.
=> [CBRD-22510] JSON_TABLE fix final clear

src/query/scan_json_table.cpp
http://jira.cubrid.org/browse/CBRD-22511
Remove assert in case json_table scan's input is empty to enable using an empty table's column as json expression argument.
=> [CBRD-22511] JSON_TABLE crashes if expression is empty

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22542
During rollbacks of transactions in online index, keys that were large enough to be compressed would get eventually leaked.
This should fix it.
=> [CBRD-22542] Fixed leak of key with compressed string set

src/parser/name_resolution.c, src/parser/parse_tree.h, src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-22513
Default() function called on json_table's columns that should return NULL.
Fix pt_node names of colums that reference json_table to have a null db_value as default_value
=> [CBRD-22513] JSON_TABLE core dump in pt_semantic_check_local

src/parser/csql_grammar.y, src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-22525
1. Reset column index count in grammar after building a json table.
- Initializing before does not help (the order of code execution is before_1, before_2, json_table_2, after_2, json_table_1, after_1)
2. Building json table attribute list should not walk expression.
=> [CBRD-22525] fix nested json tables

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22530
The issue was that when executing select update the lookup for class oid/hfid was done only at `xasl->spec_list` level and `xasl->scan_ptr` was excluded.
instead of:
```cpp
for (specp = xasl->spec_list; specp; specp = specp->next)
{
// search for class oid/hfid
}
```
should be:
```cpp
for (scan_ptr = xasl; scan_ptr; scan_ptr = scan_ptr->scan_ptr)
{
for (specp = scan_ptr->spec_list; specp; specp = specp->next)
{
// search for class oid/hfid
}
}
```
=> [CBRD-22530] fix click counter functions over partitions

src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-22484
It is a legacy issue. 
To exit redundant backup request cleared some globals and the existing backup might be dead ended.
The fix is to early out the extra backup request without initializing backup session (globals).
=> [CBRD-22484] backup failed with any other backup

src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-22561
Use recursive merge preserve for matching object keys.
Changed how values are copied and appended to object/arrays to use local allocators.
=> [CBRD-22561] fix recursive merge preserve

src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-22590
heap_get_visible_version was interrupted, but error was not handled by scan_next_index_lookup_heap
=> [CBRD-22590] scan_next_index_lookup_heap: handle S_ERROR

src/object/schema_manager.c
http://jira.cubrid.org/browse/CBRD-22585
http://jira.cubrid.org/browse/CBRD-22587
http://jira.cubrid.org/browse/CBRD-22588
This is quick fix. 
It does not really make sense for SA_MODE to build online index.
=> [CBRD-22585] SA_MODE does not allow online index

src/thread/critical_section.c
http://jira.cubrid.org/browse/CBRD-22591
Tracker was triggered on entering CSECT function (enter as writer, enter as reader, exit, promote/demote). However, sometimes operation may return with timeout.
Fix by triggering tracker when operation returns with no error.
=> [CBRD-22591] fix tracking csect

src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-22578
It is a legacy issue.
Only ridiculous NAME nodes were suppressed. The fix also removes EXPR nodes.
```sql
select  max(col1 + col2) 
from 
(select i as col1 from t), 
(select i as col2 from t) 
order by col1+col2 
limit 10;
```
=> [CBRD-22578] removes useless ordering clause for single tuple agg query

src/executables/unload_schema.c
http://jira.cubrid.org/browse/CBRD-22477
This PR covers the unique indexes definitions during online index loading. For unique indexes, if there are in the process of being loaded with an online operation, for the unload we cannot tell whether the index is correct or not, as it may not finish. Therefore, we move the definitions to the `indexes` file resulted from the unload operation, so that DBAs can decide how to load them afterwards.
=> [CBRD-22477] - Add code to handle unique indexes for unloaddb

msg/de_DE.utf8/cubrid.msg, msg/en_US.utf8/cubrid.msg, msg/en_US/cubrid.msg, msg/es_ES.utf8/cubrid.msg, msg/fr_FR.utf8/cubrid.msg, msg/it_IT.utf8/cubrid.msg, msg/ja_JP.utf8/cubrid.msg, msg/km_KH.utf8/cubrid.msg, msg/ko_KR.euckr/cubrid.msg, msg/ko_KR.utf8/cubrid.msg, msg/ro_RO.utf8/cubrid.msg, msg/tr_TR.utf8/cubrid.msg, msg/vi_VN.utf8/cubrid.msg, msg/zh_CN.utf8/cubrid.msg, src/compat/db_json.cpp, src/compat/db_macro.c, src/parser/func_type.cpp, src/parser/func_type.hpp, src/parser/parse_type.cpp, src/parser/parse_type.hpp, src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-22553
cmp_type_equivalent/cmp_type_castable are not always synchronized with pt_get_equivalent_type. Sometimes equivalent/castable checks may pass and pt_get_equivalent_type then returns PT_TYPE_NONE.
Changed type checking to consider pt_get_equivalent_type in the first step.
Also changed error messages to make more clear (need to update all languages).
=> [CBRD-22553] Accept enum for JSON value

src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22594
In case of an error, the `OID` would have been kept as locked after propagating the error. However the assert fails so, in case of an error, we now also unlock the object.
=> [CBRD-22594] Fix case of error during unique search

src/compat/db_json.cpp, src/query/arithmetic.c
http://jira.cubrid.org/browse/CBRD-22569
Instead of appending a null value, an inexistent path is just ignored.
=> [CBRD-22569] json_extract: ignore inexistent paths

src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22584
Scanning multiple partitions will leave the XASL current spec have the btid set to where the last scan ended. Therefore, if the XASL would not have been cleaned, it would be in an incorrect state. This should fix it.
=> [CBRD-22584] Fix btid restore for XASL nodes that were reused with partition cases

msg/de_DE.utf8/cubrid.msg, msg/en_US.utf8/cubrid.msg, msg/en_US/cubrid.msg, msg/es_ES.utf8/cubrid.msg, msg/fr_FR.utf8/cubrid.msg, msg/it_IT.utf8/cubrid.msg, msg/ja_JP.utf8/cubrid.msg, msg/km_KH.utf8/cubrid.msg, msg/ko_KR.euckr/cubrid.msg, msg/ko_KR.utf8/cubrid.msg, msg/ro_RO.utf8/cubrid.msg, msg/tr_TR.utf8/cubrid.msg, msg/vi_VN.utf8/cubrid.msg, msg/zh_CN.utf8/cubrid.msg, src/base/error_code.h, src/compat/db_json.cpp, src/parser/func_type.cpp
http://jira.cubrid.org/browse/CBRD-22611
Change behavior to reject numeric types conversion to json document.
NOTE: json value arguments can still accept numeric types.
=> [CBRD-22611] do not accept numerics for json document arguments

src/object/class_object.c, src/object/class_object.h, src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-22617
On client-side we do not get statistics on online and invisible indexes. However, these statistics are needed for the reorganize of partitions to get information regarding the key_type of current indexes. This should fix it.
=> [CBRD-22618] Fix invisible index during reorganize of partitions

src/object/schema_manager.c, src/object/schema_template.c, src/object/schema_template.h
http://jira.cubrid.org/browse/CBRD-22624
For unique indexes and foreign keys, the class constraints would have been decached and we would have lost the `shared_cons_name` value which was needed to skip the loading. I have added a workaround to tackle this issue by not allowing the online index creation since the `btree` is already loaded from the shared constraint. This way, we handle it like a normal index which translates into setting the `btid` of the shared constraint to the current one.
=> [CBRD-22624] Fix shared constraints with foreign keys

src/object/schema_manager.c, src/object/schema_template.c, src/object/schema_template.h
http://jira.cubrid.org/browse/CBRD-22628
`smt_edit_class_mop` would have already acquired a lock on the current class therefore any usages of online index creation would have been translated into a normal index creation. This PR should better handle those situations correctly.
=> [CBRD-22628] Revert last PR and better handle shared constraints with online index

src/object/schema_manager.c
=> [CBRD-22633] fix memory leak of #1397

src/storage/storage_common.c
http://jira.cubrid.org/browse/CBRD-22639
```sql
create index i_t_j on t(mode(j,3));
```
Notice typo, `mode` from the case.
=> [CBRD-22639] remove assertions for unknown function code

src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-22645
It was accidentally removed as #1399.
=> [CBRD-22645] fix slip of #1399 on pt_is_const_expr_node
