src/parser/semantic_check.c
src/query/scan_json_table.cpp
src/query/scan_json_table.hpp
src/query/scan_manager.c

http://jira.cubrid.org/browse/CBRD-22438
Fix fetch host variable values in json table scan.

[CBRD-22438] fix using hostvar in json table expression

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-22459
Fix some leaks.

[CBRD-22459] Fix possible leaks for online index

---

src/query/arithmetic.c

http://jira.cubrid.org/browse/CBRD-22457

[CBRD-22457] fix memory leak in json unquote

---

src/base/system_parameter.c
src/base/system_parameter.h
src/storage/file_io.c

http://jira.cubrid.org/browse/CBRD-22319

[CBRD-22319] add system parameter for read ahead fadvise

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22431
The issue is different precision of value packed into list file and then unpacked by list scan.
From my observations, all cases I tested use no precision for both packing and unpacking the value. However, folder IF case use a fixed precision for packing.
This is a hack to fold IF function to a varchar. A proper fix should make sure that list scan domains are the same as the ones used on pack. However, I don't think we have time to properly investigate and fix in this milestone.
We should open a different issue and fix it in the next mileston.

[CBRD-22431] fold IF function to a varchar

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22460

[CBRD-22460] online creation of function index leaked

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22462
save point was omitted.

[CBRD-22462] online creation of index should manage savepoint

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22466

[CBRD-22466] online IB uses scancache to scan heap

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-22468

[CBRD-22468] fix rv_keyval_data memory leaks

---

src/storage/btree.c
src/transaction/log_manager.c

http://jira.cubrid.org/browse/CBRD-22470

[CBRD-22470] fix btree_insert_sysop_end rcvindex

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-22471
http://jira.cubrid.org/browse/CBRD-22472
latch leaked and it caused server crashed or hung.

[CBRD-22471] fix latch leaks to overflow page

---

src/parser/csql_grammar.y

http://jira.cubrid.org/browse/CBRD-22475

[CBRD-22475] fix translation of ->> operator

---

src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22473

[CBRD-22473] fix memory leak in json_search function

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-22480

[CBRD-22480] fix slip of #1295 on btree_delete_sysop_end

---

src/object/schema_manager.c
src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22499

[CBRD-22499] Remove bad btid assignment

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-22483
accept upper/lowercase 'one'/'all' arguments

[CBRD-22483] uppercase 'one'/'all' args in json_search

---

src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-22503

[CBRD-22503] Fix big tuple case for aggregates

---

src/communication/network_interface_cl.c

http://jira.cubrid.org/browse/CBRD-22508
avoid overwriting btid in online index loading

[CBRD-22508] avoid overwriting btid in online index loading

---

src/parser/csql_grammar.y

http://jira.cubrid.org/browse/CBRD-22500
fixed 2nd argument case

[CBRD-22500] json_length does not support path argument

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22504

[CBRD-22504] JSON_OBJECTAGG: cast key to string

---

src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22482
Fix slip of finding a match in a find_one case of a json_search. Ignore other values that might match after.

[CBRD-22482] core dumped in JSON_SEARCHER::CallOnArrayIterate

---

src/compat/db_json.cpp
src/compat/db_json.hpp
src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-22487
Transformed wildcard json_paths to regexes that match desired json_paths

[CBRD-22487] Enable wildcard paths in json_search

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22516
Don't load secondary index twice on partition class

[CBRD-22516] fix partition secondary index loading

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22519
Status change from online loading to normal was not passed to partitions, just partitioned class.
Fix by using smt_change_constraint_status

[CBRD-22519] fix passing status to partitions

---

src/query/scan_json_table.cpp
src/xasl/access_json_table.cpp
src/xasl/access_json_table.hpp

http://jira.cubrid.org/browse/CBRD-22535
Fix m_scan_cursor_depth to be reset for new scan

[CBRD-22535] Core dumped in JSON_ARRAY_ITERATOR::has_next

---

src/compat/db_vdb.c

http://jira.cubrid.org/browse/CBRD-22538

[CBRD-22538] Fix QEWC when execute multiple queries

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22526

[CBRD-22526] fix memory leak of create_or_drop_index_helper

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22524
Fixed clearing of filter predicate for partitions case; Index function should also be covered now.

[CBRD-22524] Fixed clearing of filter predicate for partitions case

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22532
http://jira.cubrid.org/browse/CBRD-22521

[CBRD-22532] Don't allow online index on hierarchies

---

src/broker/cas_execute.c

http://jira.cubrid.org/browse/CBRD-21554

[CBRD-21554] Fixed commit issue when CCI is used

---

src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22478
Fix handling merge of two objects or two arrays.

[CBRD-22478] fix JSON_MERGE_PRESERVE for objects/arrays

---

src/query/arithmetic.c

http://jira.cubrid.org/browse/CBRD-22550

[CBRD-22550] forget error to determine return type of width_bucket

---

src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-22552
http://jira.cubrid.org/browse/CBRD-22551

[CBRD-22552] JSON_OBJECTAGG: do not allow null keys

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22558

[CBRD-22558] fix return type of json_extract

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22489
If lock promotion fails due to interrupt, clear error and transaction interrupt flag and try again.

[CBRD-22489] online index: do not interrupt lock promotion

---

src/communication/network_interface_cl.c

http://jira.cubrid.org/browse/CBRD-22554
Fix online index for SA mode.

[CBRD-22554] Fix online index issue for SA mode

---

src/compat/db_json.cpp
src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-22577

[CBRD-22577] cover uint/uint64 types on json serialize/deserialize

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-22574
```sql
drop table if exists t1;
create table t1 (a set(int));
insert into t1 values({1,2,3,4,5});
select a into set1 from t1;
select json_objectagg(set1,set1)  from table(set1);
```
Last statement will report error mentioned below
```sql
In the command from line 2,
ERROR: Semantic: before '   from table(set1); '
Nested or invalid use of aggregate function. 
```

[CBRD-22574] report invalid use of aggregate function

---

contrib/pystatdump/README.md
contrib/pystatdump/pystatdump.py

http://jira.cubrid.org/browse/CBRD-22600

[CBRD-22600] pystatdump : tool for CUBRID statdump vizualizer and analyzer

---

src/optimizer/query_rewrite.c
src/parser/parse_tree.h
src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-22570

[CBRD-22570] set collation on PT_DOT_ node when converting from attref to dotexpr

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-22581

[CBRD-22581] Fixed redo recovery issue for overflow OID

---

src/parser/csql_grammar.y
src/parser/csql_lexer.l

http://jira.cubrid.org/browse/CBRD-22593

[CBRD-22593] reset json_table_column_count on enter/exit of json_table_rule grammar rule

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22589

[CBRD-22589] fixed flush force when DWB flush thread is disabled

---

src/parser/func_type.cpp

http://jira.cubrid.org/browse/CBRD-22602

[CBRD-22602] fix precision assignment for return type in case of ELT function

---

src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-22017
Inherited issue.

[CBRD-22017] Fixed index of log page

---

src/parser/csql_grammar.y

http://jira.cubrid.org/browse/CBRD-22603

[CBRD-22603] fix json_table grammar for optional AS

---

src/base/system_parameter.c

http://jira.cubrid.org/browse/CBRD-21737

[CBRD-21737] Fix system parameter range conversion function

---

src/storage/disk_manager.c
src/storage/disk_manager.h
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-22586

[CBRD-22586] Flush data volume header page at backup and checkpoint

---

src/query/vacuum.c
src/storage/extendible_hash.c
src/storage/system_catalog.c

http://jira.cubrid.org/browse/CBRD-22621

[CBRD-22621] Handle interrupt at file_dealloc

---

src/optimizer/query_graph.c

http://jira.cubrid.org/browse/CBRD-22618

[CBRD-22618] Skip online and invisible indexes for query graph build

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22536
Change the common type from JSON to STRING between STRING and JSON.

[CBRD-22536] change common type between json and string to string

---

src/parser/xasl_generation.c
src/query/arithmetic.c
src/query/arithmetic.h

http://jira.cubrid.org/browse/CBRD-22609
Two issues fixed:
1. aggregate output name info and value list miss-match.
2. unchecked error.

[CBRD-22609] fix json_objectagg

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22620

[CBRD-22620] Fixed some er_log_debug calls

---

src/parser/csql_grammar.y
src/parser/csql_lexer.l

http://jira.cubrid.org/browse/CBRD-22643

[CBRD-22643] fix json functions as identifiers

---

src/query/arithmetic.c

http://jira.cubrid.org/browse/CBRD-22647

[CBRD-22647] fix memory leak of json_contains_path()

---

src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-22638

[CBRD-22638] Consider compression when computes length of nchar varying

---

.gitignore
src/parser/csql_lexer.l

http://jira.cubrid.org/browse/CBRD-22664
Fix json_array as identifier slip.

[CBRD-22664] Unexpected error returend when using json functions as identifiers.

---

src/object/object_representation.c
src/object/transform_cl.c
src/transaction/boot_cl.c

http://jira.cubrid.org/browse/CBRD-22665

[CBRD-22665] fix client memory leaks mainly json schema

---

src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-22681

[CBRD-22681] Fixed printing collation

---

src/base/mem_block.cpp

http://jira.cubrid.org/browse/CBRD-22726

[CBRD-22726] assign new size to memory block when doing exponential realloc

---

src/compat/db_json.cpp
src/compat/db_json.hpp
src/parser/csql_grammar.y
src/parser/func_type.cpp
src/parser/type_checking.c
src/query/arithmetic.c

http://jira.cubrid.org/browse/CBRD-22651
Add overload for json_object & json_array for empty args

[CBRD-22651] overload json_object & json_array for empty args

---

src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22708
Match regex posix exended special charactecters properly

[CBRD-22708] special chars are not matched

---

src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22697
Change json_pretty output format for null values

[CBRD-22697] change json_pretty output format for null values

---

src/compat/db_json.cpp
src/compat/db_json.hpp

http://jira.cubrid.org/browse/CBRD-22674
Use db_val's size when using a db_val of domain type char

[CBRD-22674] fix case db_val's domain type is db_type_char

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22724
Add json path does not point to array cell error.

[CBRD-22724] Json_array_insert expected error message is incorrect

---

src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-22718

[CBRD-22718] Fixed reset sysop start LSA

---

src/communication/network_interface_cl.c
src/communication/network_interface_cl.h
src/communication/network_interface_sr.c
src/loaddb/load_common.cpp
src/loaddb/load_common.hpp
src/loaddb/load_db.c
src/loaddb/load_db_value_converter.cpp
src/loaddb/load_driver.cpp
src/loaddb/load_driver.hpp
src/loaddb/load_error_handler.cpp
src/loaddb/load_error_handler.hpp
src/loaddb/load_sa_loader.cpp
src/loaddb/load_scanner.hpp
src/loaddb/load_server_loader.cpp
src/loaddb/load_session.cpp
src/loaddb/load_session.hpp

http://jira.cubrid.org/browse/CBRD-22660
Report error with the line number related to the input object file.

[CBRD-22660] loaddb: fix line numbering

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22754

[CBRD-22754] Handle correct worker pool destroy in case of errors

---

src/communication/network_interface_cl.c
src/communication/network_interface_cl.h
src/storage/storage_common.h
src/transaction/boot_sr.h
src/transaction/log_impl.h
src/transaction/log_manager.h
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-22772
Move bo_restart_arg to boot_sr.h. Change boot_restart_from_backup  as SA_MODE only.

[CBRD-22772] move bo_restart_arg to boot_sr.h

---

src/compat/db_json.cpp

http://jira.cubrid.org/browse/CBRD-22752
Make json_replace perform no_ops instead of throwing errors according to the json functions document

[CBRD-22752] JSON_REPLACE does not perform a no_op

---

cs/CMakeLists.txt
cubrid/CMakeLists.txt
sa/CMakeLists.txt
src/base/msgcat_set_log.hpp
src/storage/file_io.c
src/transaction/log_applier.c
src/transaction/log_common_impl.h
src/transaction/log_manager.c
src/transaction/log_page_buffer.c
src/transaction/log_recovery.c
src/transaction/log_writer.c

http://jira.cubrid.org/browse/CBRD-22788
Header of MSGCAT_SET_LOG message ids.

[CBRD-22788] MSGCAT_SET_LOG header

---

src/transaction/log_common_impl.h
src/transaction/log_impl.h
src/transaction/log_manager.c
src/transaction/log_page_buffer.c
src/transaction/log_writer.c

http://jira.cubrid.org/browse/CBRD-22794
Remove log_common_impl.h obsolete enum and LOG_HEADER field.

[CBRD-22794] remove obsolete LOG_PSTATUS

---

src/base/xserver_interface.h
src/communication/network_interface_cl.h
src/communication/network_interface_sr.c
src/object/elo.h
src/transaction/log_common_impl.h
src/transaction/log_manager.c

http://jira.cubrid.org/browse/CBRD-22790
Move LOB_LOCATOR_STATE from log_common_impl.h to elo.h.

[CBRD-22790] LOB_LOCATOR_STATE to elo.h

---

cs/CMakeLists.txt
cubrid/CMakeLists.txt
sa/CMakeLists.txt
src/communication/network_interface_cl.h
src/query/query_monitoring.hpp
src/transaction/log_common_impl.h
src/transaction/log_tran_table.c

http://jira.cubrid.org/browse/CBRD-22792
Create header file for query monitoring.
Moved TRAN_QUERY_EXEC_INFO from log_common_impl.h.

[CBRD-22792] Header for query monitoring

---

src/transaction/log_archives.hpp

http://jira.cubrid.org/browse/CBRD-22800
Fix initializing background_archiving_info.vdes on constructor.

[CBRD-22800] init background_archiving_info.vdes

---

src/compat/db_json.cpp
src/compat/db_json.hpp

http://jira.cubrid.org/browse/CBRD-22752
Fix differences with [json functions document](https://docs.google.com/spreadsheets/d/1d6vjoOk6dvlhh2-KHkDmyHuhXOeNL0gaI8nZ7dwjJ0s/edit#gid=1663818372) that describes functionality left by #1479 .

[CBRD-22752] JSON_REPLACE no_op issues

---

src/transaction/log_impl.h
src/transaction/log_manager.c
src/transaction/replication.h

http://jira.cubrid.org/browse/CBRD-22825
Move LOG_REPL_FLUSH/LOG_REPL_RECORD to replication.h

[CBRD-22825] Move LOG_REPL_FLUSH/LOG_REPL_RECORD to replication.h

---

src/storage/double_write_buffer.c
src/transaction/transaction_transient.cpp

http://jira.cubrid.org/browse/CBRD-22823
Remove bad safe-guard. Regression of https://github.com/CUBRID/cubrid/pull/1503.

[CBRD-22823] Remove bad check

---

.circleci/config.yml
Jenkinsfile

update to use devtoolset-8 for CI
update cubridmanager submodule to latest HEAD (a91c4ac)

[CBRD-22854] use devtoolset-8 (gcc8) for CI

---

src/base/dtoa.c
src/cci/cci_network.c
src/communication/network_cl.c
src/compat/db_date.c
src/compat/db_macro.c
src/compat/db_query.c
src/compat/db_value_printer.cpp
src/executables/unload_schema.c
src/object/object_domain.c
src/object/object_printer.cpp
src/object/object_representation.c
src/optimizer/plan_generation.c
src/optimizer/query_graph.c
src/parser/parse_dbi.c
src/parser/parse_evaluate.c
src/parser/parse_tree_cl.c
src/parser/semantic_check.c
src/parser/type_checking.c
src/parser/view_transform.c
src/parser/xasl_generation.c
src/query/arithmetic.c
src/query/fetch.c
src/query/string_opfunc.c
src/storage/es.c
src/storage/heap_file.c
src/transaction/boot_cl.c
src/transaction/log_2pc.c
src/transaction/log_applier.c

fix some new warnings.
There were some defects regarding fall through case.

[CBRD-21524] fix some gcc8 warnings

---

src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-22702
Fix nested_paths prints.

[CBRD-22702] fail to execute view with single NESTED_PATH

---

src/parser/semantic_check.c
src/query/scan_json_table.cpp

http://jira.cubrid.org/browse/CBRD-22672
Use only one domain check policy from scan_json_table casting.

[CBRD-22672] json_table using host variable inconsistent behavior

---

src/base/printer.cpp
src/base/printer.hpp

http://jira.cubrid.org/browse/CBRD-22870

[CBRD-22870] clear string_buffer contents on flush

---

src/executables/master_heartbeat.c

http://jira.cubrid.org/browse/CBRD-22901
Improve error handling on heartbeat request/response.
The issue is caused by wrong HA configuration (when own host is not specified in the `ha_node_list`), therefore it fails to send heartbeat request if myself link from heartbeat cluster is `NULL` (it means cluster is unhealthy)

[CBRD-22901] improve error handling on heartbeat req/resp

---

src/query/query_executor.c
src/query/serial.c

http://jira.cubrid.org/browse/CBRD-22907

[CBRD-22907] Force get MVCCID for serial update and selupd query.

---

src/connection/server_support.c

http://jira.cubrid.org/browse/CBRD-22912

[CBRD-22912] Fix stop order of modules in cub_server

---

src/base/system_parameter.c

http://jira.cubrid.org/browse/CBRD-22914

[CBRD-22914] increase default stream buffer size

---

src/base/multi_thread_stream.cpp

http://jira.cubrid.org/browse/CBRD-22915

[CBRD-22915] remove assert on stream destructor

---

src/transaction/log_tran_table.c

http://jira.cubrid.org/browse/CBRD-22913

[CBRD-22913] do not explicitly call destructor of objects in LOG_TDES

---

src/query/arithmetic.c
src/query/string_opfunc.c

Fix db_get_strings in json functions.
http://jira.cubrid.org/browse/CBRD-22904

[CBRD-22904] fix db_get_string reads in json functions

---

.gitmodules
Jenkinsfile
build.sh

http://jira.cubrid.org/browse/CBRD-22902
http://jira.cubrid.org/browse/CUBRIDORG-144
This file is copied from Jenkinsfile of 10.2 and modified for 10.1 build env.
I tested it in my fork repository (sjkim777/cubrid ). 
**Verification** 
- No test fails.
- Build Artifacts are as below. 
  CUBRID-CCI-Windows-x64-10.1.3.7701-8d1f0f3.zip
  CUBRID-CCI-Windows-x86-10.1.3.7701-8d1f0f3.zip
  CUBRID-Windows-x64-10.1.3.7701-8d1f0f3.msi
  CUBRID-Windows-x64-10.1.3.7701-8d1f0f3.zip
  CUBRID-Windows-x86-10.1.3.7701-8d1f0f3.msi
  CUBRID-Windows-x86-10.1.3.7701-8d1f0f3.zip
  CUBRID-10.1.3.7702-b7d00f3f0-Linux.x86_64-debug.sh
  CUBRID-10.1.3.7702-b7d00f3f0-Linux.x86_64-debug.tar.gz
  CUBRID-10.1.3.7702-b7d00f3f0-Linux.x86_64.rpm
  CUBRID-10.1.3.7702-b7d00f3f0-Linux.x86_64.sh
  …

[CBRD-22902] Create Jenkinsfile for 10.1 branch

---

src/executables/loader.c
src/transaction/boot_cl.c

Fixed json loaddb leaks.
http://jira.cubrid.org/browse/CBRD-21742

[CBRD-21742] fix json loaddb leaks

---

src/base/stream_entry.hpp
src/replication/log_generator.cpp
src/replication/log_generator.hpp
src/replication/replication_stream_entry.cpp
src/transaction/log_manager.c
src/transaction/log_tran_table.c

http://jira.cubrid.org/browse/CBRD-22917
Fix MCCID on stream entry of sys_op_commit
Remove pre-commit phase of log_generator.
Simplify code in log_generator
Delete non-trivial constructors of cubstream::stream_entry (default ones have unexpected behavior)

[CBRD-22917] Fix MVCCID on stream entry of sys_op_commit

---

src/base/multi_thread_stream.cpp

http://jira.cubrid.org/browse/CBRD-22931

[CBRD-22931] Fix race condition on m_last_recyclable_pos

---

src/storage/record_descriptor.cpp

http://jira.cubrid.org/browse/CBRD-22934

[CBRD-22934] Fix data source for record_descriptor::unpack

---

src/transaction/log_tran_table.c

http://jira.cubrid.org/browse/CBRD-22916

[CBRD-22916] Use new allocator for LOG_TDES

---

src/replication/replication_stream_entry.hpp

http://jira.cubrid.org/browse/CBRD-22937

[CBRD-22937] Fix bit mask on replication_stream_entry packing

---

src/replication/log_consumer.cpp

http://jira.cubrid.org/browse/CBRD-22938

[CBRD-22938] clear error before apply of replication object

---

src/storage/record_descriptor.cpp
src/storage/record_descriptor.hpp

http://jira.cubrid.org/browse/CBRD-22943

[CBRD-22943] Move constructor for record_descriptor

---

src/transaction/log_append.cpp
src/transaction/log_manager.c
src/transaction/log_record.hpp
src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-22935
Log record from stream_pos + tx_group: LOG_REC_GROUP_COMMIT with tx_group trans info in redo.
TODO: GC recovery

[CBRD-22935] append GC log record

---

src/replication/log_consumer.cpp

http://jira.cubrid.org/browse/CBRD-22969
`log_consumer::fetch_stream_entry` delete stream_entry in case of error

[CBRD-22969] [log_consumer] fix memory leak

---

src/transaction/log_manager.c

[CBRD-22944] fixes bad merge of #1581

---

src/transaction/log_manager.c

http://jira.cubrid.org/browse/CBRD-22976
Fix bad safe-guard of CBRD-22976

[CBRD-22976] fix log_rollback safe-guard

---

src/replication/log_consumer.cpp

http://jira.cubrid.org/browse/CBRD-22987

[CBRD-22987] Fix applier task  order of transactions on slave

---

src/transaction/locator_sr.c

http://jira.cubrid.org/browse/CBRD-22989

[CBRD-22989] Set infinite lock timeout for replication apply

---

src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-22993
Port #1608 on develop

[CBRD-22993] fix compression for DB_TYPE_VARNCHAR

---

unit_tests/common/mock_stream.cpp
unit_tests/common/mock_stream.hpp
unit_tests/replication_channels/slave_replication_channel_mock.cpp
unit_tests/replication_channels/slave_replication_channel_mock.hpp
unit_tests/replication_channels/test_main.cpp

http://jira.cubrid.org/browse/CBRD-22950
Fix slip of https://github.com/CUBRID/cubrid/pull/1609 (compile issue) & test behavior.

[CBRD-22950] fix replication_channels unit test compile & test

---

src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-23001

[CBRD-23001] Free transaction descriptor at redo of log_group_complete record

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-23002
Port #1618 on develop

[CBRD-23002] do name resolution & semantic checks on select pt node for PT_CREATE_ENTITY node

---

src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-23009

[CBRD-23009] free tdes on redo of LOG_FINISH_POSTPONE

---

src/communication/communication_channel.hpp
src/communication/stream_transfer_receiver.cpp

http://jira.cubrid.org/browse/CBRD-23003

[CBRD-23003] Fix stream receive amount to be aligned to 8 bytes.

---

src/replication/log_consumer.cpp
src/replication/replication_master_node.cpp
src/replication/replication_master_node.hpp
src/replication/replication_stream_entry.cpp
src/replication/replication_stream_entry.hpp

http://jira.cubrid.org/browse/CBRD-22956
Add stream entry to signify a new master became active

[CBRD-22956] Stream entry for new master becoming active

---

src/storage/heap_file.c
src/storage/heap_file.h
src/transaction/boot_sr.c
src/transaction/locator_sr.c
src/transaction/locator_sr.h

[CBRD-22978] Revert "[CBRD-22978] New locator function specialized on inserting multiple records"

---

src/transaction/log_global.c
src/transaction/log_impl.h
src/transaction/log_page_buffer.c
src/transaction/log_record.hpp
src/transaction/log_recovery.c
src/transaction/transaction_master_group_complete_manager.cpp
src/transaction/transaction_master_group_complete_manager.hpp

http://jira.cubrid.org/browse/CBRD-22953
Add last_ack positions in END_CHKPT record & recover log_Gl's m_ack_stream_position from END_CHKPT & GROUP_COMPLETE records.

[CBRD-22953] Ack stream pos for END_CHKPT record 

---

src/transaction/log_manager.c

http://jira.cubrid.org/browse/CBRD-23017

[CBRD-23017] Remove duplicate on_transaction_commit call

---

src/session/session.c

http://jira.cubrid.org/browse/CBRD-23025
Initialize session time zone region to system time zone region

[CBRD-23025] init session tz_region

---

src/query/query_executor.c
src/query/scan_manager.c
src/query/serial.c
src/storage/catalog_class.c
src/storage/heap_file.c
src/transaction/locator_sr.c
src/transaction/lock_manager.c

http://jira.cubrid.org/browse/CBRD-23039
dd2e43b fixes the case, while 38327fa does other potential UMRS.

[CBRD-23039] fix UMR on callers of heap_get_visible_version

---

src/replication/replication_node_manager.cpp

Fix slip of https://github.com/CUBRID/cubrid/pull/1641 (stream delete order)

[CBRD-22780] fix stream delete order

---

src/replication/log_consumer.hpp
unit_tests/stream/test_stream.cpp

http://jira.cubrid.org/browse/CBRD-23036
Fix compile issues generated by https://github.com/CUBRID/cubrid/pull/1661.

[CBRD-23036] fix compile

---

src/base/packer.cpp
src/base/packer.hpp

http://jira.cubrid.org/browse/CBRD-23051
Add packer method to add objects to extensible block.
Primitives for pack/unpack OID.

[CBRD-23051] Pack list of OID

---

src/replication/replication_row_apply.cpp

http://jira.cubrid.org/browse/CBRD-23058
Allocate recdes area big enough to allow heap_update_adjust_recdes_header execute safely.
Backport #1611 after #1616 refactor

[CBRD-23058] [replication] reserve area size for heap adjustment

---

src/replication/replication_slave_node.cpp

http://jira.cubrid.org/browse/CBRD-23066
Fix ctrl_sender init.

[CBRD-23066] Fix uninited ctrl_sender

---

src/base/error_manager.c
src/base/language_support.c
src/base/locale_support.c
src/base/tz_compile.c
src/base/unicode_support.c
src/broker/broker.c
src/broker/broker_admin_pub.c
src/broker/broker_filename.c
src/broker/broker_tester.c
src/broker/cas.c
src/broker/cas_log.c
src/broker/cas_sql_log2.c
src/broker/shard_proxy_log.c
src/cci/cas_cci.c
src/cm_common/cm_dep_tasks.c
src/executables/checksumdb.c
src/executables/csql.c
src/executables/util_cs.c
src/storage/es_posix.c
src/storage/file_io.c
src/storage/page_buffer.c
src/tools/cci_applier.c
src/transaction/log_applier.c
src/transaction/log_applier_sql_log.c

Fix -Wformat-truncation GCC warnings

[CBRD-21524] suppress -Wformat-truncation GCC warning

---

cs/CMakeLists.txt
cubrid/CMakeLists.txt
sa/CMakeLists.txt
src/base/semaphore.hpp

http://jira.cubrid.org/browse/CBRD-23067
Semaphore class template by value type.
Add event class (based on semaphore with two states).

[CBRD-23067] Add semaphore class

---

src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-22786
backup now considers vacuum jobs.

[CBRD-22786] fix to backup considers vacuum

---

src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-22786
backup now considers vacuum jobs.

[CBRD-22786] [10.1p3] fix to backup considers vacuum (#1693)

---

src/query/vacuum.c

[CBRD-22786] Windows build fix

---

src/compat/db_macro.c
src/compat/dbtype.h
src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-23080
It is a back port of #1672.

[CBRD-23080] fix UMR of accessing null value (#1672)

---

src/compat/db_date.c

http://jira.cubrid.org/browse/CBRD-23081
It is a backport of #1562

[CBRD-23081] [10.1p3] avoid dereferencing from outside of buffer (#1562)

---

src/storage/file_io.c

http://jira.cubrid.org/browse/CBRD-23083
It is a backport of #1540

[CBRD-23083] [10.1p3] fix free (page|sector) size of partition (#1540)

---

src/compat/db_json_path.cpp

http://jira.cubrid.org/browse/CBRD-23072
Improve json object key validation.

[CBRD-23072] [JSON] Fix path validation

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-21948
Server start hanged during recovery because it tried to notify vacuum workers of dropped file when no workers was running.
Fixed by skipping notification during recovery.
Backport #1029

[CBRD-21948] skip dropped file notification during recovery

---

src/transaction/log_page_buffer.c

[CBRD-22017] Fixed index of log page (#1375)

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-22574
drop table if exists t1;
create table t1 (a set(int));
insert into t1 values({1,2,3,4,5});
select a into set1 from t1;
select json_objectagg(set1,set1)  from table(set1);
Last statement will report error mentioned below
In the command from line 2,
ERROR: Semantic: before '   from table(set1); '
Nested or invalid use of aggregate function.
backport of #1360

[CBRD-22574] report invalid use of aggregate function (#1360)

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-22164
Safe-guard failed after copydb because `logpb_last_complete_blockid ()` returns `VACUUM_NULL_LOG_BLOCKID`. Fix the case by skipping `vacuum_Data.set_last_blockid ()` in this case.
This is a hack to reset last_blockid of vacuum data on the first start of copied database (last_blockid is inherited from original database). It is not a proper fix and we should probably find a better one :).
The way now copydb works makes it hard to find non-hackish fix for the issue.
Backport of #1131 and #1139

[CBRD-22164] fix vacuum_data_load_and_recover after copydb

---

src/storage/extendible_hash.c
src/storage/system_catalog.c

http://jira.cubrid.org/browse/CBRD-22621
backport #1390

[CBRD-22621] Handle interrupt at file_dealloc (#1390)

---

src/parser/parse_tree_cl.c
src/parser/parser.h
src/parser/semantic_check.c

Include limit node in pt_apply_union_node.
backport #1246

[CBRD-22409] fix walking/copying union parser node (#1246)

---

src/executables/master.c

http://jira.cubrid.org/browse/CBRD-22396
backport #1244

[CBRD-22396] fix potential ABW of cub_master (#1244)

---

src/transaction/log_recovery.c

Squash merge of related 3 fixes:
http://jira.cubrid.org/browse/CBRD-22718
http://jira.cubrid.org/browse/CBRD-22370
http://jira.cubrid.org/browse/CBRD-22343
backport #1209 #1227 #1455

[CBRD-22718] Fixed reset sysop start LSA (#1455, #1227, #1209)

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22327
backport #1204

[CBRD-22327] fix vulerability of pt_eval_type_pre (#1204)

---

locales/make_locale_x64.bat

[CBRD-21966]  Make locale based on %VS150COMCOMNTOOLS% for VS2017 v150 (#1043, #1048)

---

src/compat/db_macro.c

http://jira.cubrid.org/browse/CBRD-23104

[CBRD-23104] [10.1p3] fix zero precision

---

src/storage/disk_manager.c
src/storage/file_io.c
src/storage/file_manager.c
src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-23107

[CBRD-23107] fix slip of file_extdata_collect_ftab_pages and fileio_expand_to

---

CMakeLists.txt
build.sh

[CBRD-23111] fix abbrev length in version string to 7 (#1520)

---

cs/CMakeLists.txt
cubrid/CMakeLists.txt
sa/CMakeLists.txt
src/replication/ha_server_state.h
src/transaction/boot.h

http://jira.cubrid.org/browse/CBRD-23109
Move HA server state from boot.h to its own header.

[CBRD-23109] HA server state header

---

src/replication/log_generator.cpp

http://jira.cubrid.org/browse/CBRD-23110
Get MVCCID when appends replication objects

[CBRD-23110] Assign MVCCID if a transactions has replication objects

---

src/base/stream_entry.hpp
src/replication/log_generator.cpp
src/replication/log_generator.hpp

http://jira.cubrid.org/browse/CBRD-23102

[CBRD-23102] Fixed slow unpacking stream entry

---

src/parser/compile.c
src/parser/view_transform.c

http://jira.cubrid.org/browse/CBRD-23134

[CBRD-23134] Fixed crash caused by accessing deallocated memory

---

src/query/execute_schema.c

http://jira.cubrid.org/browse/CBRD-23136

[CBRD-23136] Fixed crash caused by accessing corrupted memory

---

src/transaction/log_append.cpp
src/transaction/log_tran_table.c

http://jira.cubrid.org/browse/CBRD-23140

[CBRD-23140] set head_lsa as tail_lsa for first log record of transaction

---

src/storage/heap_file.c
src/storage/oid.c
src/storage/oid.h

Change oid_is_system_class signature.

[CBRD-21524] change oid_is_system_class signature

---

src/query/execute_schema.c

[CBRD-23136] Fixed crash caused by accessing corrupted memory (#1775)

---

src/query/partition.c
src/query/query_executor.c

- do not set pruned flag if error occurred during partition_prune_spec (next time it will early out)
- add safe-guards to catch errors inside qexec_open_scan / qexec_prune_spec

[CBRD-22130] Do not set pruned flag on errors

---

src/replication/log_consumer.cpp

http://jira.cubrid.org/browse/CBRD-23153
Fix dispatcher leaks on abort, new master & stop.

[CBRD-23153] Fix dispatcher memory leaks

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-23156
When no MVCC ops are executed for a long time, update and keep vacuum data with two log blocks behind log append.
backports #1786.

[CBRD-23156] vacuum data trailing log in long no mvcc case

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-23163

[CBRD-23163] Fixed chain logging when remove VPID

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-23163
undo log to change the previous page of removing page was bad.
backport #1806

[CBRD-23163] Fixed chain logging when remove VPID (#1806)

---

src/replication/stream_senders_manager.cpp
unit_tests/replication_channels/cub_master_mock.cpp
unit_tests/replication_channels/master_replication_channel_mock.cpp
unit_tests/replication_channels/master_replication_channel_mock.hpp
unit_tests/replication_channels/test_main.cpp

http://jira.cubrid.org/browse/CBRD-23181
Remove if defined SERVER_MODE of stream sender manager code
Fix unit tests

[CBRD-23181] remove if defined SERVER_MODE and fix unit tests

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-23197

[CBRD-23197] Fixed vacuum job offset

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-23188
Fix slip of #1822

[CBRD-23188] fix unfix data_page in vacuum_create_file_for_vacuum_data

---

src/transaction/locator_sr.c

http://jira.cubrid.org/browse/CBRD-23170
Fix regression of #1815

[CBRD-23170] locator multi insert: fix log of the page

---

src/executables/util_cs.c

http://jira.cubrid.org/browse/CBRD-23180
Fix slip of pull request #1808

[CBRD-23180] Fix slip of #1808

---

CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-23112
Add a comment with solutions for a common Windows issue caused by git installation.

[CBRD-23112] comment for windows execute_process issue

---

src/executables/master_heartbeat.c

http://jira.cubrid.org/browse/CBRD-23224
Send hostname of the master node to cub_server only when process is registered

[CBRD-23224] cub_master: fix send hostname of the master node

---

src/connection/server_support.c
src/thread/thread_entry_task.cpp

http://jira.cubrid.org/browse/CBRD-23023
Backport.
We don't have a repro scenario. It may not even reproduce on develop.

[CBRD-23023] reset private_lru_index on retire and recycle context

---

src/base/string_buffer.cpp
src/base/string_buffer.hpp

http://jira.cubrid.org/browse/CBRD-23230
Backport string_buffer::hex_dump from ha_replication branch

[CBRD-23230] backport string_buffer::hex_dump

---

src/base/perf_monitor.c
src/loaddb/load_worker_manager.cpp

[CBRD-23144] fix crashes of loaddb worker pool

---

src/query/vacuum.c

Replace ugly macros to get and set blockid and flags to vacuum data entries with functions. Code becomes more readable.
set_vacuumed also clears interrupted flag. set_interrupted also changes status to available. no set_available function (status starts as available, then it can only become available if interrupted).
No behavior changes.

[CBRD-23226] vacuum data entry functions

---

src/query/vacuum.c

Wrap all required operations on vacuum data entry when starting a job into vacuum_data_job::start_job_on_current_entry function.

[CBRD-23226] vacuum data job cursor start_job_on_current_entry

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-23249
regression of #1844

[CBRD-23249] initialize classname entry of hfid table

---

src/loaddb/load_db.c

http://jira.cubrid.org/browse/CBRD-23258
data file open may not be given.

[CBRD-23258] loaddb data file open may not be given

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-23255
When last block of vacuum data is vacuumed, the cursor was incremented without updating vacuum data. The loop breaks and check that vacuum data is empty fails.
Fix to always update vacuum data (and remove vacuumed blocks) before breaking loop.

[CBRD-23255] xvacuum update data when cursor becomes invalid

---

contrib/pystatdump/pystatdump.py

http://jira.cubrid.org/browse/CBRD-22600
Robustness fixes to pystatdump.py

[CBRD-22600] Robustness fixes to pystatdump.py

---

src/parser/parse_tree_cl.c

[CBRD-22679] fix hdr comment of pt_function_is_allowed_as_function_index

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-22729
Avoid dummy benchmark func evaluation when resolving domains for aggregation.

[CBRD-22729] Avoid dummy benchmark func evaluation

---

unit_tests/packing/test_packing.cpp
unit_tests/packing/test_packing.hpp

http://jira.cubrid.org/browse/CBRD-22879
Fx slip of #1884

[CBRD-22879] Fix compile

---

src/loaddb/load_server_loader.cpp

http://jira.cubrid.org/browse/CBRD-23271

[CBRD-23271] loaddb: check for heap_attrinfo_set errors

---

src/loaddb/load_common.cpp

http://jira.cubrid.org/browse/CBRD-23285
Skip empty lines from input data file on preprocessing of the file content

[CBRD-23285] loaddb: skip empty lines

---

src/loaddb/load_db_value_converter.cpp

http://jira.cubrid.org/browse/CBRD-23293
Added a new function for the conversion of numeric type.
_EDIT: new function is equivalent of ldr_int_elem_

[CBRD-23293] Fix conversion function for numeric type

---

msg/de_DE.utf8/utils.msg
msg/en_US.utf8/utils.msg
msg/en_US/utils.msg
msg/es_ES.utf8/utils.msg
msg/fr_FR.utf8/utils.msg
msg/it_IT.utf8/utils.msg
msg/ja_JP.utf8/utils.msg
msg/km_KH.utf8/utils.msg
msg/ko_KR.euckr/utils.msg
msg/ko_KR.utf8/utils.msg
msg/ro_RO.utf8/utils.msg
msg/tr_TR.utf8/utils.msg
msg/vi_VN.utf8/utils.msg
msg/zh_CN.utf8/utils.msg
src/loaddb/load_db.c

http://jira.cubrid.org/browse/CBRD-23303
Changed the message thrown by the --load-only parameter when used in CS_MODE.

[CBRD-23303] Changed the message of --load-only parameter

---

src/loaddb/load_db.c

http://jira.cubrid.org/browse/CBRD-23308

[CBRD-23308] stop loading when interrupted or failed

---

src/compat/db_json_path.cpp

http://jira.cubrid.org/browse/CBRD-23321
Fix slip of json_extract unicode characters encoding [Pull Request](https://github.com/CUBRID/cubrid/pull/1911)

[CBRD-23321] Fix array_end_token dump assertion

---

src/loaddb/load_server_loader.cpp

http://jira.cubrid.org/browse/CBRD-23318

[CBRD-23318] loaddb shows detailed error messages

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-22990
The issue is caused by the fact that transaction was not aborted.

[CBRD-22990] Fixed sysop in select incr

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-23313

[CBRD-23313] Check snapshot before key generation when function index is involved

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-23322

[CBRD-23322] Fixed unique statistics

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-23331
It fixes two regressions of #1921 
- To close sys op that was not started
- instant lock was not closed

[CBRD-23331] fix slips of incr patch: #1921

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-23341
(outer) scan may start instant lock mode.
regression of #1931

[CBRD-23341] scan may start instant lock mode

---

src/loaddb/load_db_value_converter.cpp

http://jira.cubrid.org/browse/CBRD-23338

[CBRD-23338] allow numbers to monetary conversions

---

.appveyor.yml
CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-23336
Automatically download and install win_flex_bison dependency on windows

[CBRD-23336] cmake: download and install win_flex_bison

---

src/loaddb/load_server_loader.cpp
src/storage/btree.c
src/storage/heap_file.c
src/transaction/locator_sr.c
src/transaction/lock_manager.c
src/transaction/lock_manager.h

http://jira.cubrid.org/browse/CBRD-23337

[CBRD-23337] Loaddb workers does not acquire locks

---

src/loaddb/load_db.c

http://jira.cubrid.org/browse/CBRD-23346

[CBRD-23346] loaddb: fix load from server file system

---

src/loaddb/load_server_loader.cpp

http://jira.cubrid.org/browse/CBRD-23299

[CBRD-23299] loaddb: do not copy CLOB/BLOB files

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-23344

[CBRD-23344] Fixed issue caused by unique statistics

---

src/connection/server_support.c
src/connection/server_support.h
src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-23353
to promote table lock might be failed in case of server shutdown.

[CBRD-23353] online index loading might fail to promote table lock

---

src/query/string_opfunc.c

Fix slip of [1930](https://github.com/CUBRID/cubrid/pull/1930)

[CBRD-23317] fix skip ci compile error slip

---

src/query/string_opfunc.c

[CBRD-23317] fix no return slip

---

msg/de_DE.utf8/utils.msg
msg/en_US.utf8/utils.msg
msg/en_US/utils.msg
msg/es_ES.utf8/utils.msg
msg/fr_FR.utf8/utils.msg
msg/it_IT.utf8/utils.msg
msg/ja_JP.utf8/utils.msg
msg/km_KH.utf8/utils.msg
msg/ko_KR.euckr/utils.msg
msg/ko_KR.utf8/utils.msg
msg/ro_RO.utf8/utils.msg
msg/tr_TR.utf8/utils.msg
msg/vi_VN.utf8/utils.msg
msg/zh_CN.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23374
gencat complains. It was added as #1881.

[CBRD-23374] remove bad blank line from loaddb usage

---

src/storage/file_manager.c
src/transaction/log_system_tran.cpp

http://jira.cubrid.org/browse/CBRD-23325

[CBRD-23325] Corrects initial state of system transaction at recovery

---

src/loaddb/load_session.cpp
src/transaction/lock_manager.c

http://jira.cubrid.org/browse/CBRD-23375
Until a more clear alternative is found, force no locking on load workers.

[CBRD-23375] no locking for load workers

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-23351

[CBRD-23351] btree helper structures : replace initializer with constructors

---

src/compat/db_vdb.c

http://jira.cubrid.org/browse/CBRD-23386

[CBRD-23386] Cast host variable if not already casted

---

src/loaddb/load_sa_loader.cpp

http://jira.cubrid.org/browse/CBRD-23387
- report invalid characters based on current codeset in loaddb SA mode
- remove INDENT-OFF/INDENT-ON from load_sa_loader.cpp since it is not longer required

[CBRD-23387] loaddb: report invalid characters on loaddb SA

---

src/transaction/mvcc_active_tran.cpp

http://jira.cubrid.org/browse/CBRD-23389

[CBRD-23389] Corrects assert

---

src/loaddb/load_common.cpp
src/loaddb/load_server_loader.cpp
src/query/arithmetic.c

[CBRD-23398] fix compile issue

---

src/query/arithmetic.c

[CBRD-23398] fix compile issue of #1982

---

src/compat/dbtype_def.h
src/executables/unload_schema.c
src/query/execute_statement.c
src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-23396
Fix limits for numeric type

[CBRD-23396] Fix numeric type limits

---

src/loaddb/load_common.cpp
src/loaddb/load_server_loader.cpp

http://jira.cubrid.org/browse/CBRD-23398
Fixed the ignore classes mechanism on server by using the systems collation and charset when checking if a class is ignored or not.

[CBRD-23398] Fix ignore classes for different charsets

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-23416
fix slip of #1980

[CBRD-23416] fix UMR of db_alter_serial

---

src/transaction/log_manager.c
src/transaction/log_postpone_cache.cpp

http://jira.cubrid.org/browse/CBRD-23415
reset postpone cache on rollback

[CBRD-23415] reset postpone cache on rollback

---

src/object/object_domain.c

http://jira.cubrid.org/browse/CBRD-22646
Cast float/real to json

[CBRD-22646] cast float to json

---

src/loaddb/load_session.cpp

http://jira.cubrid.org/browse/CBRD-23311

[CBRD-23311] suppress update stats msg when no stats option is given

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-22741
Similarly to previously removed check, private list being over quota is not a reliable check. Between search and check, new bcb's may be added to LRU list and it can exceed quota.

[CBRD-22741] remove data flush unreliable safe-guard

---

src/transaction/log_system_tran.cpp

http://jira.cubrid.org/browse/CBRD-23440
Avoid generating tran_ids for recycled tdes.

[CBRD-23440] Reuse tran_ids for recycled tdes

---

unit_tests/string_buffer/src/test_string_buffer.cpp

[CBRD-23444] fix -Wmultichar

---

src/base/lockfree_bitmap.cpp
src/storage/heap_file.c
src/transaction/log_writer.c
src/xasl/xasl_stream.cpp

[CBRD-23444] fix -Wsign-compare

---

src/base/perf.cpp
src/base/perf.hpp

[CBRD-23444] fix -Wdeprecated-copy warning

---

src/storage/btree.c

[CBRD-23444] fix -Wreorder

---

src/monitor/monitor_statistic.hpp
src/monitor/monitor_transaction.hpp

[CBRD-23444] fix -Wclass-memaccess warning for monitor module

---

src/compat/db_macro.c
src/storage/page_buffer.c
src/transaction/mvcc_active_tran.cpp

 [CBRD-23444] fix -Wtype-limits warnings

---

.travis.yml
src/executables/esql_grammar.y
src/loaddb/load_grammar.yy
src/parser/csql_grammar.y

[CBRD-23444] fix -Wdeprecated grammar warnings

---

src/thread/thread_entry.cpp

[CBRD-23444] fix -Wswitch warning

---

src/parser/parse_tree.c
src/parser/semantic_check.c
src/query/string_opfunc.c
src/query/string_opfunc.h

http://jira.cubrid.org/browse/CBRD-22753
Fix json_table db_values not cleared.

[CBRD-22753] fix json_table leak in parser_free_tree

---

src/communication/network_interface_cl.c
src/communication/network_interface_cl.h
src/object/class_object.c
src/object/schema_manager.c
src/storage/statistics.h
src/storage/statistics_cl.c

http://jira.cubrid.org/browse/CBRD-23427
Fix to handle NULL return of stats_get_statistics.

[CBRD-23427] Fix to handle return code of client-server requests

---

src/base/tz_support.c
src/base/uca_support.c
src/jsp/jsp_cl.c
src/query/numeric_opfunc.c
src/query/query_opfunc.c

[CBRD-23444] fix Wmaybe-uninitialized warnings

---

src/transaction/log_writer.c

[CBRD-23444] Fix regresion in log_writer of #2033

---

src/object/authenticate.c
src/object/transform_cl.c

[CBRD-23444] Revert "fix -Wreturn-local-addr warnings"

---

src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-23460
Fix mr_readval_varnchar_internal for read size zero and peek case.

[CBRD-23460] Fix mr_readval_varnchar_internal for read size zero and peek case

---

src/object/authenticate.c
src/object/transform_cl.c

Reverts CUBRID/cubrid#2063 (reapplies #2055)

[CBRD-23444] reapply "fix -Wreturn-local-addr warnings"

---

src/broker/cas_execute.c
src/compat/cnv.c
src/compat/db_elo.c
src/compat/db_elo.h
src/compat/db_macro.c
src/compat/dbtype_function.h
src/compat/dbtype_function.i
src/loaddb/load_object.c
src/object/object_domain.c
src/object/object_primitive.c
src/query/query_executor.c
src/query/query_opfunc.c
src/query/string_opfunc.c

Change db_get_bit function signature to return const char *
Part 3 of #1656

[CBRD-23444] const db_get_bit

---

src/compat/dbtype.h
src/compat/dbtype_function.h

http://jira.cubrid.org/browse/CBRD-23466

[CBRD-23466] remove declared but not defined functions from C API

---

src/storage/record_descriptor.cpp
src/transaction/log_writer.c

Fix remaining sign compare warnings outside of grammar.

[CBRD-23444] Fix remaining sign compare warnings

---

src/executables/csql.c

Fix -Wsizeof-pointer-memaccess

[CBRD-23444] fix strncat warning

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-23469

[CBRD-23469] accept heap_cache_class_info interrupts

---

src/base/intl_support.c

[CBRD-23444] fix intl_identifier_fix

---

contrib/systemtap/cubrid_func.stp

http://jira.cubrid.org/browse/CBRD-23481
systemtap script was abandoned.

[CBRD-23481] fix systemtap function for lock mode changes

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/connection/tcp.c

http://jira.cubrid.org/browse/CBRD-22861
Set error code when getaddrinfo fails.

[CBRD-22861] set error code when getaddrinfo fails

---

src/base/intl_support.c

http://jira.cubrid.org/browse/CBRD-23482
Fix EUC lower/upper.

[CBRD-23482] Fix EUC lower/upper

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-23475
This patch only fixes block data buffer becoming full if vacuum workers are blocked.
The question why workers are blocked for so long remains. @alexstanro  pointed that log archive daemon may be blocked on renaming archive volume as `test_lgar.removed`

[CBRD-23475] vacuum consume log buffer even if queue is full

---

src/loaddb/load_session.cpp

http://jira.cubrid.org/browse/CBRD-23484
session::load_batch does an infinite_wait for until one of the next conditions are met:
- "statistics" update, that occurs when a job is ended
- job is successfully pushed
However, it can only be notified when a job ends. If pool was full on the first batch, there will be no event that wakes load_batch to try to push task again.
Fix by using timed wait and forcing an attempt to push task every 10 milliseconds.

[CBRD-23484] fix session::load_batch hang

---

src/loaddb/load_server_loader.cpp

http://jira.cubrid.org/browse/CBRD-23501
If we encounter a syntax failure during syntax checking, we do not increment the number of rows checked. This PR should fix this issue.

[CBRD-23501] Fix incorrect lines checked reporting

---

src/storage/catalog_class.c
src/storage/heap_file.c
src/storage/system_catalog.c

http://jira.cubrid.org/browse/CBRD-21390

[CBRD-21390] Fixed issue in catalog

---

src/executables/csql.c

http://jira.cubrid.org/browse/CBRD-23507
QA reports Windows does not work. Hope this fixes.

[CBRD-23507] fix csql ;get level session command

---

src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-23487

[CBRD-23487] Skip cast to enum for host variable

---

src/transaction/log_postpone_cache.cpp

http://jira.cubrid.org/browse/CBRD-23508
Steps to reproduce the issue:
- Execute postpone of file destroy based on cache
- Remove from file tracker and deallocate page of file tracker
- append new postpone redo data to cache
- reallocate cache buffer to fit new data
- execute postpone of page deallocation
- resume executing file destroy, but continue reading data from old cache buffer (before reallocation)
Fix by copying buffer data before passing to execution funtion.

[CBRD-23508] Fix dangling postpone cache pointers

---

jdbc/CMakeLists.txt
src/jdbc/cubrid/jdbc/jci/UUType.java

http://jira.cubrid.org/browse/CBRD-23503
Include JSON in range of accepted types.
Change cmake of jdbc to use simple copy (I had problems both on linux and windows with jdbc jar not corresponding to actual source code).

[CBRD-23503] Include JSON in range of accepted types.

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-23477
Fix case missed from https://github.com/CUBRID/cubrid/pull/2096
After getting prior mutex, vacuum_Block_data_buffer must be checked too. Last block may have been produced.

[CBRD-23477] fix last_blockid after huge log record

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-23513
"Catch" bad precision error in db_string_pad. qstr_make_typed_string does not detect such errors.
Added a safe-guard to qstr_make_typed_string to make sure no error is missed.

[CBRD-23513] fix memory leak of untreated error in db_string_pad

---

src/base/system_parameter.c
src/base/system_parameter.h
src/storage/heap_file.c
src/storage/heap_file.h

http://jira.cubrid.org/browse/CBRD-23519
Add a system parameter to activate heap cache info logging

[CBRD-23519] Debugging logs for heap info cache

---

src/query/query_aggregate.cpp

http://jira.cubrid.org/browse/CBRD-23514
We had two leaks of error. It lead to list file leaks.

[CBRD-23514] fix list file leaks. error was not propagated

---

src/storage/heap_file.c
src/storage/heap_file.h
src/transaction/recovery.c

http://jira.cubrid.org/browse/CBRD-23187
Verbose dump for heap append pages log record.

[CBRD-23187] Recovery dump for heap append pages

---

CMakeLists.txt
src/query/cursor.c

http://jira.cubrid.org/browse/CBRD-23516
Fix csql_results not clearing json contained in set.

[CBRD-23516] set(json) cursor leak

---

src/parser/csql_grammar.y
src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-23556
Invert on empty & on error order.

[CBRD-23556] json_table on empty & on error order

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-23545
Do not allow interrupt in DWB wait functions to avoid crash in flush_all.
Checking interruption in flush_all looks dangerous now. I propose to let it as it is, since is legacy.

[CBRD-23557] Do not allow interrupt in DWB wait functions

---

src/transaction/log_page_buffer.c

[CBRD-23119] indent #2150

---

src/storage/file_io.c
src/storage/file_io.h
src/transaction/log_writer.c

http://jira.cubrid.org/browse/CBRD-23562

[CBRD-23562] avoid fsync to dismount immature log active

---

msg/es_ES.utf8/cubrid.msg
msg/es_ES.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23573

[CBRD-23573] Translate es_ES messages

---

msg/tr_TR.utf8/cubrid.msg
msg/tr_TR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23577

[CBRD-23577] Translate tr_Tr messages

---

src/parser/csql_grammar.y
src/parser/csql_lexer.l
src/parser/scanner_support.c

http://jira.cubrid.org/browse/CBRD-23580
replace custom lineno with yylineno of flex.
It will issue manual test since it may bring regressions.

[CBRD-23580] use yylineno of flex

---

src/parser/csql_grammar.y

http://jira.cubrid.org/browse/CBRD-23570

[CBRD-23570] reset yylineno for one statement parsing

---

msg/ro_RO.utf8/cubrid.msg
msg/ro_RO.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23576

[CBRD-23576] Translate ro_Ro message

---

msg/it_IT.utf8/cubrid.msg
msg/it_IT.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23575

[CBRD-23575] Italian catalog messages

---

msg/fr_FR.utf8/cubrid.msg
msg/fr_FR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23574

[CBRD-23574] catalog message french

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg

[CBRD-23571] add missing message of MSGCAT_RUNTIME_INVALID_JSON

---

msg/de_DE.utf8/cubrid.msg
msg/de_DE.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-23572

[CBRD-23572] Translate de_De messages

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-23595
`child_page` might be badly unfixed for some error cases.

[CBRD-23595] fix potential bad unfix of a page due to UMR

---

CMakeLists.txt
build.sh

Revert "[CBRD-23601] Initialize the extra version number into zero"

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-22837
Fix slip of #1671.

[CBRD-22837] fix slip setting error when collation incompatible 

---

.travis.yml

http://jira.cubrid.org/browse/CBRD-23619

[CBRD-23619] gcc and g++  version 8 to build Regex library

---

src/transaction/replication.c

http://jira.cubrid.org/browse/CBRD-22135
- The Russian painter's algorithm make performance slower in HA environments.
- See the linked issue for what the Russian painter algorithm is.
- My opinion is that there is no need to use this algorithm for serial processing.

[CBRD-22135] Improve performance when using serial in HA environment.

---

src/transaction/log_manager.c
src/transaction/log_manager.h

[CBRD-23609] fix build error on Windows

---

src/transaction/replication.c

http://jira.cubrid.org/browse/CBRD-22135
backport https://github.com/CUBRID/cubrid/pull/2206

[CBRD-22135] Improve performance when using serial in HA environment. (#2206)

---

contrib/scripts/ha/ha_make_slavedb.sh

http://jira.cubrid.org/browse/CBRD-23603
backport https://github.com/CUBRID/cubrid/pull/2187

[CBRD-23603] The ha_make_slavedb.sh script should delete intended database exactly. (#2187)

---

src/executables/util_cs.c
src/storage/file_io.c

http://jira.cubrid.org/browse/CBRD-23640
backport #1078

[CBRD-23640] backupdb also allows a FIFO (named pipe) file (#1078)

---

Jenkinsfile

http://jira.cubrid.org/browse/CBRD-23644
Disable 10.2 release branch auto build. 

[CBRD-23644] Change 10.2 branch ci build manually

---

src/base/system_parameter.c
src/executables/util_cs.c

http://jira.cubrid.org/browse/CBRD-23631
backport https://github.com/CUBRID/cubrid/pull/2217

[CBRD-23631] Change the maximum value of the 'ha_apply_max_mem_size' property from 500MB to INT_MAX. (#2217)

---

src/broker/broker.c
src/broker/broker_shm.c
src/broker/broker_shm.h
src/broker/cas.c
src/broker/cas_function.h
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
src/jdbc/cubrid/jdbc/jci/UTimedDataInputStream.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

http://jira.cubrid.org/browse/CBRD-23633
**Environment:**
Endless busy waiting JDBC Client connected to a broker/cas in abnormal network circumstance.
**Purpose:**
Prevent the endless busy waiting of JDBC driver in abnormal network circumstance.
**Method:**
Add a new protocol between JDBC and broker/cas to provide the information of cas.

[CBRD-23633] Prevent endless busy waiting for query execution in abnormal network circumstance

---

src/broker/broker.c
src/broker/cas_common.h
src/broker/cas_function.h
src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

[APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException

---

src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/jci/UStatement.java

http://jira.cubrid.org/browse/APIS-822
This is a back port for #2227 
* [APIS-822] In JDBC Driver, translating empty string to null when the option oracleStyleEmptyString is set.
* [APIS-822] revised to remove unnecessary code

[APIS-822] In JDBC Driver, translating empty string to null when the option oracleStyleEmptyString is set

---

src/broker/broker.c
src/broker/broker_shm.c
src/broker/broker_shm.h
src/broker/cas.c
src/broker/cas_function.h
src/broker/cas_protocol.h
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
src/jdbc/cubrid/jdbc/jci/UTimedDataInputStream.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

http://jira.cubrid.org/browse/CBRD-23633
This is for back port #2219, #2259.

[CBRD-23633] Prevent endless busy waiting for query execution in abnormal network circumstance (#2219, #2259)

---

src/base/porting.h
src/broker/cas_log.c

http://jira.cubrid.org/browse/CBRD-22975
backport #2188

[CBRD-22975] Broker CAS hangs in CLIENT_WAIT status when log file size is greater than 2G on Windows 64 (#2188)

---

src/broker/broker.c
src/broker/cas_common.h
src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

Revert "[APSI-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException (#2256)"

---

src/broker/broker.c
src/broker/cas_common.h
src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

Revert "[APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException (#2256)"

---

src/broker/broker.c
src/broker/cas_common.h
src/broker/cas_function.h
src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

[APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException (#2256)

---

src/jdbc/cubrid/jdbc/driver/CUBRIDDriver.java
src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

[CBRD-23637] Implementation of secure CUBRID jdbc driver

---

cmake/CPackWixPatch.cmake.in
msg/de_DE.utf8/cubridtray.msg
msg/en_US.utf8/cubridtray.msg
msg/en_US/cubridtray.msg
msg/es_ES.utf8/cubridtray.msg
msg/fr_FR.utf8/cubridtray.msg
msg/it_IT.utf8/cubridtray.msg
msg/ja_JP.utf8/cubridtray.msg
msg/km_KH.utf8/cubridtray.msg
msg/ko_KR.euckr/cubridtray.msg
msg/ko_KR.utf8/cubridtray.msg
msg/ro_RO.utf8/cubridtray.msg
msg/tr_TR.utf8/cubridtray.msg
msg/vi_VN.utf8/cubridtray.msg
msg/zh_CN.utf8/cubridtray.msg
win/build.bat

* Fix PopupBox text(start/stop) to be enable on trayicon.
* Add msg file to display text in DialogBox on trayicon.
http://jira.cubrid.org/browse/CBRD-22862

[CBRD-22862] fix cubridtray actions for Windows

---

cmake/CPackWixPatch.cmake.in
msg/de_DE.utf8/cubridtray.msg
msg/en_US.utf8/cubridtray.msg
msg/en_US/cubridtray.msg
msg/es_ES.utf8/cubridtray.msg
msg/fr_FR.utf8/cubridtray.msg
msg/it_IT.utf8/cubridtray.msg
msg/ja_JP.utf8/cubridtray.msg
msg/km_KH.utf8/cubridtray.msg
msg/ko_KR.euckr/cubridtray.msg
msg/ko_KR.utf8/cubridtray.msg
msg/ro_RO.utf8/cubridtray.msg
msg/tr_TR.utf8/cubridtray.msg
msg/vi_VN.utf8/cubridtray.msg
msg/zh_CN.utf8/cubridtray.msg

* Fix PopupBox text(start/stop) to be enable on trayicon.
* Add msg file to display text in DialogBox on trayicon.
http://jira.cubrid.org/browse/CBRD-22862

[CBRD-22862] fix cubridtray actions for Windows (#2271)

---

conf/cubrid_broker.conf
src/broker/broker_config.h

* change cubrid.conf
`SSL = OFF`

[CBRD-23639] Change default SSL mode to OFF (cubrid_broker.conf)

---

src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java

[CBRD-23637] change default useSSL value true to false.

---

Jenkinsfile

http://jira.cubrid.org/browse/CBRD-23652

[CBRD-23652] Docker image in JenkinsFile for 10.2 release branch

---

CMakeLists.txt
src/broker/cas_ssl.c
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

* Change SSL Library to EXTERNAL

[CBRD-23639] Change SSL lib to EXTERNAL

---

src/storage/file_io.c

[CBRD-23609] Change incorrectly patched code in #2228

---

src/jdbc/cubrid/jdbc/jci/UConnection.java

This is a revised PR for #2267

[APIS-782] revised: JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException

---

src/connection/server_support.c
src/executables/master_heartbeat.c
src/executables/master_heartbeat.h
src/transaction/log_manager.c
src/transaction/log_manager.h

It was decided to apply only some of the modifications in #2228. so remove any modifications other than syslog ().

[CBRD-23609] Remove modifications other than syslog () in #2228

---

src/connection/server_support.c
src/executables/master_heartbeat.c
src/executables/master_heartbeat.h
src/transaction/log_manager.c
src/transaction/log_manager.h

It was decided to apply only some of the modifications in #2222. so remove any modifications other than syslog ().

[CBRD-23609] Remove modifications other than syslog () in #2222.

---

src/jsp/jsp_cl.c

* In case of jsp, we always uses plain communication.

[CBRD-23613] Fix bug for SSL with jsp

---

src/broker/cas_ssl.c
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

[CBRD-23639] Change TLS default

---

src/jdbc/cubrid/jdbc/jci/UErrorCode.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

* add error code : 
- CAS_ER_SSL_TYPE_NOT_ALLOWED = -10103
* add error string : 
- The requested SSL mode is not permitted, the CAS server is running in a different mode (check useSSL property). 

[CBRD-23637] add ssl error code

---

src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
src/jdbc/cubrid/jdbc/driver/CUBRIDLobHandle.java
src/jdbc/cubrid/jdbc/jci/UGetTypeConvertedValue.java
src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
src/jdbc/cubrid/jdbc/jci/UStatement.java

http://jira.cubrid.org/browse/APIS-825
backport #2303

[APIS-825] Supports ResultSet.getBlob() or ResultSet.getClob() method to read BIT VARYING type or VARCHAR type. (#2303)

---

src/storage/file_io.c

[CBRD-23243] Modify the way to calculate available disk space in sector unit (#2330)

---

src/jdbc/cubrid/jdbc/jci/UConnection.java

[APIS-782] revised: added an omitted code

---

src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
src/jdbc/cubrid/jdbc/jci/UConnection.java

omitted codes:
- isValid(timeout), timeout unit is second not millisecond.
- make correct session id

[APIS-782] revised: added omitted codes

---

src/jdbc/cubrid/jdbc/driver/CUBRIDDriver.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

[CBRD-23637] Changing the method of sending magicString for SSL

---

src/connection/server_support.c
src/executables/master_heartbeat.c
src/executables/master_heartbeat.h
src/transaction/log_manager.c
src/transaction/log_manager.h

It was decided to apply only some of the modifications in #2195. so remove any modifications other than syslog ().

[CBRD-23609] Remove modifications other than syslog () in #2195

---

src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
src/jdbc/cubrid/jdbc/jci/UErrorCode.java
src/jdbc/cubrid/jdbc/net/BrokerHandler.java

* Add error code for ssl handshake exception
Error message : "SSL handshake failure"

[CBRD-23637] Add error code for ssl handshake exception

---

src/optimizer/query_graph.c
src/parser/parse_tree_cl.c
src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22925
backport #2185

[CBRD-22925] An error occurs when there are two 'IN' operators and rewriting predicate to reduce the equality term. (#2185)

---

src/optimizer/query_rewrite.c
src/parser/parse_tree.h

http://jira.cubrid.org/browse/CBRD-23618
backport #2200

[CBRD-23618] Error occur when rewriting subquery into derived table in delete or update statement (#2200)

---

src/query/query_aggregate.cpp
src/query/query_aggregate.hpp
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-23605
backport #2208

[CBRD-23605] Wrong results returning in some select queries which has aggregate function as select list by groupby clause. (#2208)

---

src/optimizer/query_graph.c
src/optimizer/query_graph.h

http://jira.cubrid.org/browse/CBRD-21886
backport #2315

[CBRD-21886] No query results if DECODE, CASE, or IF is used in a nested left outer join query (#2315)

---

src/parser/xasl_generation.c
src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-21022
backport #2323

[CBRD-21022] executeBatch returns Cannot communicate with the broker or received invalid packet & CAS down with core dump (#2323)

---

src/optimizer/plan_generation.c
src/parser/xasl_generation.c
src/parser/xasl_generation.h
src/query/query_executor.c
src/query/stream_to_xasl.c
src/query/xasl.h
src/query/xasl_to_stream.c

http://jira.cubrid.org/browse/CBRD-23650
backport #2343

[CBRD-23650] When a query specifying an OVER function in an aggregate function using rownum has a plan, the result is null. (#2343)

---

src/parser/type_checking.c
src/query/query_dump.c

http://jira.cubrid.org/browse/CBRD-23697
backport #2361

[CBRD-23697] occurred error "Cannot coerce value of domain character to domain integer" when executing update. (#2361)

---

src/base/system_parameter.c
src/broker/broker_shm.h

change the following
* an limit value of db's max_clients from 2000 to 4000.
* an limit value of broker's max_num_appl_server from 2048 to 4096.

[CBRD-23714] change an limit value of max_clients

---

.circleci/config.yml

http://jira.cubrid.org/browse/CBRD-23719

[CBRD-23719] Update circle ci for 10.2

---

CMakeLists.txt
broker/CMakeLists.txt
cas/CMakeLists.txt
src/broker/broker.c
src/broker/broker_config.c
src/broker/broker_config.h
src/broker/cas.c
src/broker/cas_error.h
src/broker/cas_network.c
src/broker/cas_protocol.h
src/broker/cas_ssl.c
src/jsp/jsp_cl.c

http://jira.cubrid.org/browse/CBRD-23687
* Apply Secure Broker/CAS (SSL) into develop

[CBRD-23687] Apply SSL Broker/CAS to damson

---

src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
src/jdbc/cubrid/jdbc/driver/CUBRIDDatabaseMetaData.java
src/jdbc/cubrid/jdbc/jci/CUBRIDIsolationLevel.java
src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
src/jdbc/cubrid/jdbc/jci/UConnection.java

http://jira.cubrid.org/browse/APIS-833
* Add isolation level of CUBRID Engine version 9 or earlier for backward compatibility (level 1, 2, 3)

[APIS-833] Add isolation level 1,2,3 for backward compatibility

---

src/base/system_parameter.c
src/parser/semantic_check.c
src/query/execute_schema.c

modified to get default value of reuse_oid from system parameter, if don't use table option related reuse_oid.

[CBRD-23708] change table option's default value to reuse_oid

---

src/cci/cci_common.h
src/cci/cci_network.c

http://jira.cubrid.org/browse/CBRD-23722
**Environment:**
Endless busy waiting CCI Client connected to a broker/cas in abnormal network circumstance.
**Purpose:**
Prevent the endless busy waiting of CCI driver in abnormal network circumstance.
**Method:**
Add a new protocol between CCI and broker/cas to provide the information of cas.

[CBRD-23722] Prevent endless busy waiting for query execution in abnormal network circumstanec

---

src/executables/util_cs.c

* ignore user and password option and connect to server by disable password at tranlist utility. 
* ignore password option if don't use -i or --kill option at killtran utility.

[CBRD-23730] ignore user and password option at tranlist and killtran utility

---

win/CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-23703
Fix slip of https://github.com/CUBRID/cubrid/pull/2391

[CBRD-23703] fix build error on Windows

---

src/parser/csql_grammar.y
src/parser/csql_lexer.l
src/parser/keyword.c
src/parser/show_meta.c
src/query/show_scan.c
src/storage/page_buffer.c
src/storage/page_buffer.h
src/storage/storage_common.h

http://jira.cubrid.org/browse/CBRD-22803
New PR with 4 fixes from #1587
1. merge conflict
2. compile error
3. fixed an issue where the heading of the result started with a lowercase letter.
4. an atomic operation is applied to prevent the data race.
5. protects the critical section.

[CBRD-22803] show statement for page buffer status

---

msg/ko_KR.utf8/csql.msg

[CBRD-23736] add query-output and loaddb-output option to csql utility

---

src/query/query_hash_scan.c
src/query/scan_manager.c

http://jira.cubrid.org/browse/CBRD-23665
fix to avoid compilation warning. (remove int == null condition)

[CBRD-23665] fix to avoid compilation warning

---

build.sh

http://jira.cubrid.org/browse/CBRD-23601
For using "build.sh -v"

[CBRD-23601] Fixed start date for git count

---

src/transaction/boot_sr.c

[CBRD-23629] Fix slip of checking java_stored_procedure on standalone

---

src/transaction/boot_sr.c

[CBRD-23629] Fix assertion caused by getting prm with wrong type

---

src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-23783

[CBRD-23783] Fix incorrect domain definition is printed for SET of arbitrarily type

---

msg/en_US.utf8/utils.msg

[CBRD-23629] Slip, remove wrong message changes in en_US.utf8/utils.msg

---

src/executables/util_service.c

http://jira.cubrid.org/browse/CBRD-23786
Please refer to the Jira comment for the analysis.

[CBRD-23786] Always loading system parameter in process_heartbeat_util()

---

src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
src/jdbc/cubrid/jdbc/jci/UConnection.java
src/jdbc/cubrid/jdbc/jci/UJCIManager.java
src/jdbc/cubrid/jdbc/jci/UResCache.java
src/jdbc/cubrid/jdbc/jci/UStatement.java
src/jdbc/cubrid/jdbc/jci/UStatementCacheData.java
src/jdbc/cubrid/jdbc/jci/UStmtCache.java
src/jdbc/cubrid/jdbc/jci/UUrlCache.java

http://jira.cubrid.org/browse/CBRD-23801
This is for regression test #2443 
After cursor forward or backward jumped to the position not fetched yet, the tuples is not read properly.

[CBRD-23801] [Regression] In JDBC, the cursor forward and backward doesn't work.

---

src/object/object_domain.c
src/object/object_primitive.c
src/parser/parser_support.c
src/query/string_opfunc.c
src/storage/btree.c

Revert "[CBRD-23812] [Regression] The results of two queries that scan different indexes in the same transaction are different."

---

src/object/object_domain.c
src/object/object_primitive.c
src/parser/csql_grammar.y
src/parser/parser_support.c
src/parser/type_checking.c
src/query/string_opfunc.c

Revert "[CBRD-23812] [revised] The results of two queries that scan different indexes in the same transaction are different."

---

src/storage/tde.c

Fixed a bug that occurred in the following PR.
- https://github.com/CUBRID/cubrid/pull/2546

[CBRD-23608] bug fix in PR#2546

---

cmake/CPack.STGZ_Header.sh.in
contrib/rpm/cubrid.sh

http://jira.cubrid.org/browse/CBRD-23587
* Fix OS identification error for fedora

[CBRD-23587] Fix OS identification error - fedota

---

msg/de_DE.utf8/cubrid.msg
msg/de_DE.utf8/utils.msg
msg/en_US.utf8/cubrid.msg
msg/en_US.utf8/utils.msg
msg/en_US/cubrid.msg
msg/en_US/utils.msg
msg/es_ES.utf8/cubrid.msg
msg/es_ES.utf8/utils.msg
msg/fr_FR.utf8/cubrid.msg
msg/fr_FR.utf8/utils.msg
msg/it_IT.utf8/cubrid.msg
msg/it_IT.utf8/utils.msg
msg/ja_JP.utf8/cubrid.msg
msg/ja_JP.utf8/utils.msg
msg/km_KH.utf8/cubrid.msg
msg/km_KH.utf8/utils.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.euckr/utils.msg
msg/ko_KR.utf8/cubrid.msg
msg/ko_KR.utf8/utils.msg
msg/ro_RO.utf8/cubrid.msg
msg/ro_RO.utf8/utils.msg
msg/tr_TR.utf8/cubrid.msg
msg/tr_TR.utf8/utils.msg
msg/vi_VN.utf8/cubrid.msg
msg/vi_VN.utf8/utils.msg
msg/zh_CN.utf8/cubrid.msg
msg/zh_CN.utf8/utils.msg
src/base/release_string.c

- remove a space character from copryright of CUBRID, when run cubrid --version

[CBRD-23825] change comment such as copyright and license

---

cmake/CPack.STGZ_Header.sh.in

http://jira.cubrid.org/browse/CBRD-23834

[CBRD-23834] Change the way to find bash as login shell

---

.circleci/config.yml
Jenkinsfile

http://jira.cubrid.org/browse/CBRD-23806
Updated dockerci branch for 11.0 release.

[CBRD-23806] Docker ci release branch

---

src/broker/broker_admin_pub.c
src/broker/broker_config.c

http://jira.cubrid.org/browse/CBRD-23883

[CBRD-23883] Change keyword to JDBC_CACHE_ONLY_HINT

---

src/broker/broker_admin_pub.c
src/broker/broker_config.c

http://jira.cubrid.org/browse/CBRD-23860
* Compensate #2600
* Two files were missing for changing JDBC_CACHE_ONLY_HINT -> JDBC_CACHE_HINT_ONLY

[CBRD-23860] Change broker keyword JDBC_CACHE_HINT_ONLY

---

src/broker/broker_config.c

http://jira.cubrid.org/browse/CBRD-23860
* Add SHARD_NUM_PROXY as a broker keyword.

[CBRD-23860] Add a broker keyword, SHARD_NUM_PROXY

---

msg/de_DE.utf8/utils.msg
msg/en_US.utf8/utils.msg
msg/en_US/utils.msg
msg/es_ES.utf8/utils.msg
msg/fr_FR.utf8/utils.msg
msg/it_IT.utf8/utils.msg
msg/ja_JP.utf8/utils.msg
msg/km_KH.utf8/utils.msg
msg/ko_KR.euckr/utils.msg
msg/ko_KR.utf8/utils.msg
msg/ro_RO.utf8/utils.msg
msg/tr_TR.utf8/utils.msg
msg/vi_VN.utf8/utils.msg
msg/zh_CN.utf8/utils.msg
src/communication/network.h
src/communication/network_cl.c
src/communication/network_interface_cl.c
src/communication/network_interface_cl.h
src/communication/network_interface_sr.c
src/communication/network_interface_sr.h
src/communication/network_sr.c
src/executables/util_admin.c
src/executables/util_cs.c
src/executables/utility.h
src/query/vacuum.c
src/query/vacuum.h

http://jira.cubrid.org/browse/CBRD-23881
backport #2629

[CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum (#2629)

---

src/broker/broker_config.c

http://jira.cubrid.org/browse/CBRD-23860
* Add broker keywords, SHARD_PROXY_LOG_DIR, SHARD_PROXY_LOG

[CBRD-23860] Add broker keywords, SHARD_PROXY_LOG, SHARD_PROXY_LOG_DIR

---

contrib/windows_scripts/cubrid_env.bat

http://jira.cubrid.org/browse/CBRD-21446
Modify the example file for setting CUBRID environment variables.

[CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.

---

src/cci/cas_cci.c
src/cci/cci_common.h
src/cci/cci_query_execute.c
src/win_tools/cubridtray/CASManage.cpp
src/win_tools/cubridtray/COMMONMETHOD.CPP
src/win_tools/cubridtray/PARSEDB.CPP
src/win_tools/cubridtray/PARSESTATUS.CPP

http://jira.cubrid.org/browse/CBRD-23899

[CBRD-23899] Fix errors detected by cppcheck in cci, win_tools.

---

.github/workflows/check.yml

http://jira.cubrid.org/browse/CBRD-23900
#2663 is also valid for cppcheck.

[CBRD-23900] Limit cppcheck only to specific file formats

---

src/loaddb/load_session.cpp

http://jira.cubrid.org/browse/CBRD-23891
* Fix num instances committed in loaddb CS

[CBRD-23891] Fix num_instance for loaddb cs

---

src/loaddb/load_sa_loader.cpp

http://jira.cubrid.org/browse/CBRD-23906
do update statistics on all tables, tables with 0 records including base table of partition table, in loaddb SA.

[CBRD-23906] do update statistics on all tables in loaddb SA

---

CMakeLists.txt
build.sh
win/build.bat

http://jira.cubrid.org/browse/CBRD-23884
We need to copy JDBC jars into output dir which set by "-o" option in build.sh

[CBRD-23884] Fix slip of copying JDBC into output dir

---

src/executables/csql_launcher.c
src/parser/csql_grammar.y
src/parser/parse_tree.h
src/query/query_manager.c

http://jira.cubrid.org/browse/LETS-73
The project contains duplicate declarations for functions and macros

[Lets-73] Fix -Wredundant-decls warnings 

---

src/base/memory_hash.c
src/base/memory_hash.h
src/parser/type_checking.c
src/query/query_hash_scan.c
src/query/query_hash_scan.h
src/query/scan_manager.c

http://jira.cubrid.org/browse/CBRD-23828
backport (#2537)

[CBRD-23828] Support the use of OID of temp file in HASH LIST SCAN. (#2537)

---

src/optimizer/query_graph.c
src/optimizer/query_graph.h
src/optimizer/query_planner.c

http://jira.cubrid.org/browse/CBRD-23879
backport (#2625)

[CBRD-23879] Outer dependency is set improperly when rewriting SQL from outer join to inner join (#2625)

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-23888
backport #2631

[CBRD-23888] Error -1106 occurs when using MERGE INTO statement with GROUP BY (#2631)

---

src/executables/csql_launcher.c
src/parser/csql_grammar.y
src/parser/parse_tree.h
src/query/query_manager.c

http://jira.cubrid.org/browse/LETS-73
The merge of LETS-72 sign compare branch has overwritten the changes of this branch

 REAPPLY - [Lets-73] Fix -Wredundant-decls warnings

---

src/broker/cas_function.c

http://jira.cubrid.org/browse/CBRD-23915
Purpose
* Log more meaningful information in SQL_LOG for binding VARCHAR variables:
* Log num chars instead of num bytes
Implementation
N/A
Remarks
N/A

[CBRD-23915] Log num chars in sql_log for bind VARCHAR variables

---

src/compat/db_class.c
src/compat/dbi.h
src/executables/util_sa.c
src/object/schema_manager.c
src/object/schema_manager.h
src/parser/csql_grammar.y
src/parser/parse_tree.h
src/parser/parse_tree_cl.c
src/query/execute_schema.c

http://jira.cubrid.org/browse/CBRD-23922
See the Jira issue for more description.

[CBRD-23922] Add a new TRUNCATE option: CASCADE

---

src/jsp/com/cubrid/jsp/ExecuteThread.java
src/jsp/com/cubrid/jsp/ExecuteThreadStatus.java
src/jsp/com/cubrid/jsp/Server.java
src/jsp/com/cubrid/jsp/SpSecurityManager.java
src/jsp/com/cubrid/jsp/StoredProcedure.java
src/jsp/com/cubrid/jsp/StoredProcedureClassLoader.java
src/jsp/com/cubrid/jsp/TargetMethod.java
src/jsp/com/cubrid/jsp/TargetMethodCache.java
src/jsp/com/cubrid/jsp/exception/ExecuteException.java
src/jsp/com/cubrid/jsp/exception/TypeMismatchException.java
src/jsp/com/cubrid/jsp/value/BooleanValue.java
src/jsp/com/cubrid/jsp/value/ByteValue.java
src/jsp/com/cubrid/jsp/value/DateValue.java
src/jsp/com/cubrid/jsp/value/DatetimeValue.java
src/jsp/com/cubrid/jsp/value/DoubleValue.java
src/jsp/com/cubrid/jsp/value/FloatValue.java
src/jsp/com/cubrid/jsp/value/IntValue.java
src/jsp/com/cubrid/jsp/value/LongValue.java
src/jsp/com/cubrid/jsp/value/NullValue.java
src/jsp/com/cubrid/jsp/value/NumericValue.java
src/jsp/com/cubrid/jsp/value/OidValue.java
src/jsp/com/cubrid/jsp/value/ResultSetValue.java
src/jsp/com/cubrid/jsp/value/SetValue.java
src/jsp/com/cubrid/jsp/value/ShortValue.java
src/jsp/com/cubrid/jsp/value/StringValue.java
src/jsp/com/cubrid/jsp/value/TimeValue.java
src/jsp/com/cubrid/jsp/value/TimestampValue.java
src/jsp/com/cubrid/jsp/value/Value.java

http://jira.cubrid.org/browse/CBRD-23918
I ran the following command for all files
```
java -jar google-java-format-1.7-all-deps.jar -a -r "$1"
```

[CBRD-23918] Correct code format for Java SP Server code

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-23877
backport #2611

[CBRD-23877] To CREATE a table as SELECT query, the alias of attributes should be checked. (#2611)

---

src/query/list_file.c
src/query/list_file.h
src/query/query_manager.c
src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-23856
it's back port #2559

[CBRD-23856] backport: Adding mutex for result-cache to process multi-threaded transaction (#2559)

---

src/cci/cas_cci.c
src/cci/cci_common.h
src/cci/cci_query_execute.c
src/win_tools/cubridtray/CASManage.cpp
src/win_tools/cubridtray/COMMONMETHOD.CPP
src/win_tools/cubridtray/PARSEDB.CPP
src/win_tools/cubridtray/PARSESTATUS.CPP

http://jira.cubrid.org/browse/CBRD-23899
Purpose
- Backport #2661  to 11.0.1
- Fix errors detected by cppcheck in cci, wintools
Implementation
N/A
Remarks
N/A

[CBRD-23899] Backport #2661 to 11.0.1, Fix errors detected by cppcheck in cci, win_tools.

---

src/query/scan_manager.c

http://jira.cubrid.org/browse/CBRD-23828
fix comment of trace.
```
hash temp buildtime : ==> hash temp, build time:
```

[CBRD-23828] fix comment of trace

---

src/api/cci_stub.c
src/base/locale_support.c
src/base/system_parameter.c
src/base/tz_compile.c
src/base/tz_support.c
src/base/util_func.c
src/cci/cci_query_execute.c
src/cm_common/cm_dep_tasks.c
src/cm_common/cm_mem_cpu_stat.c
src/cm_common/cm_trigger_info_sa.c
src/cm_common/cm_utils.c
src/compat/cnv.c
src/connection/connection_list_cl.c
src/executables/compactdb_common.c
src/executables/csql_result_format.c
src/executables/esql_declare.c
src/executables/esql_symbol_table.c
src/executables/gencat.c
src/loaddb/load_error_handler.cpp
src/loaddb/load_object.c
src/parser/compile.c
src/query/execute_statement.c
src/storage/extendible_hash.c
src/storage/external_sort.c
src/storage/file_io.c
src/thread/thread_manager.cpp
src/transaction/log_applier_sql_log.c
unit_tests/memory_alloc/test_db_private_alloc.cpp
unit_tests/memory_alloc/test_memory_alloc_helper.hpp
unit_tests/string_buffer/src/test_string_buffer.cpp

http://jira.cubrid.org/browse/CBRD-23898
backport of #2673, #2722

[CBRD-23898] Fix errors detected by cppcheck (11.0)

---

src/broker/broker_log_converter.c
src/broker/broker_log_util.c

http://jira.cubrid.org/browse/CBRD-23915
Purpose
* Due to spec. change of sql_log format to log num chars instead of num bytes
* It is required to change broker_log_converter and some functions used in broker_log_runner
Implementation
N/A
Remarks
* This is a relatively simple work.
* However, This task was not easy due to the coding style of the person who wrote it before.
* Personally, I think it is necessary to rewrite some part, however it is relatively low importance and limited time,
* I worked in the form of minimize changes.

[CBRD-23915] Change broker_log_converter and utils for spec. change

---

src/base/language_support.c
src/base/language_support.h
src/object/object_primitive.c
src/query/query_manager.c
src/query/scan_manager.c
src/query/scan_manager.h
src/query/string_opfunc.h
src/storage/btree.c
win/cubridcs/cubridcs.def
win/cubridsa/cubridsa.def

http://jira.cubrid.org/browse/CBRD-23905
backport #2670

[CBRD-23905] Enhance Index scan performance (#2670)

---

msg/en_US/cubrid.msg
src/base/error_code.h
src/object/schema_manager.c
src/storage/oid.h

http://jira.cubrid.org/browse/CBRD-23930
See the Jira issue for more information.
Note:
I'll add `cubrid.msg` files in other languages than en_US after this review is done.

[CBRD-23930] Change the TRUNCATE spec. with the CASCADE option

---

src/executables/csql_launcher.c

http://jira.cubrid.org/browse/CBRD-23935
Purpose
- fix a bug due to wrong comment
Implementation
N/A
Remarks
N/A
http://jira.cubrid.org/browse/CBRD-XXXX
Describe here

[CBRD-23935] --single-line and --no-single-line should not be used together in csql

---

src/parser/parse_tree.h

http://jira.cubrid.org/browse/CBRD-23927
Purpose
Simplify macros
Implementation
Remove "(  ?  :   )" control statement
(cond_A ? true : false)     ==> (cond_A)
(cond_B ? cond_C : false) ==> (cond_B && cond_C)
Remarks
N/A

[CBRD-23927]  Rewrite  the macro declared in parse_tree.h

---

src/query/vacuum.c
src/storage/heap_file.c
src/storage/heap_file.h
src/transaction/locator_cl.c
src/transaction/locator_sr.c

http://jira.cubrid.org/browse/CBRD-23936
See the Jira issue for more information.

[CBRD-23936] Make hfid-cache allow the hfid of a class to be changed

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-23948
also related to http://jira.cubrid.org/browse/CBRD-23877
See the detail at the JIRA http://jira.cubrid.org/browse/CBRD-23877
In this issue the following case as like "WITH CTE" is fixed:
```
create table src (a int, b int, name1 varchar, name2 varchar(20));
create table t4 as with cte as
(
select (a*0), b from src
)
select * from cte;
```
The above statement should raise error but does not in actual because it does not properly check the WITH clause.

[CBRD-23948] To CREATE a table as WITH cte query, the alias of attributes should be checked.
