CUBRID/cubrid

- src/object/schema_manager.c
http://jira.cubrid.org/browse/CBRD-22640
Whenever the last index on a class was removed, statistics on that class were never updated automatically. This should fix it.
> [CBRD-22640] update stats even though table has no index

- src/parser/func_type.cpp
- src/query/arithmetic.c
http://jira.cubrid.org/browse/CBRD-22646
JSON valid returns true if:
1. argument is a json
2. argument is a string that can be parsed as a json
JSON valid returns false if:
1. argument is neither json, nor string
2. argument is a string, but it cannot be parsed as a json
> [CBRD-22646] correct json_valid behavior

- msg/de_DE.utf8/cubrid.msg
- msg/en_US.utf8/cubrid.msg
- msg/en_US/cubrid.msg
- msg/es_ES.utf8/cubrid.msg
- msg/fr_FR.utf8/cubrid.msg
- msg/it_IT.utf8/cubrid.msg
- msg/ja_JP.utf8/cubrid.msg
- msg/km_KH.utf8/cubrid.msg
- msg/ko_KR.euckr/cubrid.msg
- msg/ko_KR.utf8/cubrid.msg
- msg/ro_RO.utf8/cubrid.msg
- msg/tr_TR.utf8/cubrid.msg
- msg/vi_VN.utf8/cubrid.msg
- msg/zh_CN.utf8/cubrid.msg
- src/base/error_code.h
- src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-22642
We do not allow partition creation on a class that resides in a hierarchy chain. I added a new error code to tackle this issue.
> [CBRD-22642] Set new error in case of partition created on a class in a hierarchy

- src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-22612
Set expected json_array error in case of resolving a parent to json_object with a valid path for it.
> [CBRD-22612] csql crash in db_json_array_shift_values

- src/query/scan_manager.c
- src/query/stream_to_xasl.c
http://jira.cubrid.org/browse/CBRD-22495
Scenario: Prepared plan containing json table is never executed. Allocated resources that are normally freed on final clear depend on s_id.type. However s_id.type is initialized on open scan, which is never called.
Fixed by initializing s_id.type when XASL is unpacked.
> [CBRD-22495] initialize json table scan properly

- src/object/schema_manager.c
http://jira.cubrid.org/browse/CBRD-22652
It is a regression of #1407 which updates statistics of a target class even though it has no index. 
However, it also allowed view classes. We don't absolutely want it.
> [CBRD-22652] do not update statistics on views

- src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-22648
Keep the order of the json_paths in the json_extract outputs
> [CBRD-22648] JSON_EXTRACT returned order does not match the input order

- src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-22658 
Fix regressions left by (#1415)
In db_json_extract_document_from_path do not allocate a json_doc in case of no result found.
> [CBRD-22658] Fix json_contains regressions

- src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-22659
Use mr_data_lengthval_string to compute json_validator's length to take in account extra compression data.
> [CBRD-22659] JSON csql crashed when insert json data with enable_string_compression=n

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/storage/record_descriptor.cpp
- src/storage/record_descriptor.hpp
http://jira.cubrid.org/browse/CBRD-22675
Wrap current struct recdes with a C++ class record_descriptor that can provide an enhanced and safer interface to operate with records.
1. peek/copy mode functions. peeked records are protected against writes.
2. getters/setters (that can provide const property to buffers).
3. data manipulation functions - modify, delete, insert and move data.
4. record_descriptor should manage memory extensions (using extensible memory blocks) and automatically free allocated memory on destruction.
> [CBRD-22675] record_descriptor

- src/query/arithmetic.c
http://jira.cubrid.org/browse/CBRD-22677
Fix leaks in cases of validation or regex compilation in json_search.
> [CBRD-22677] JSON_SEARCH leaked when json_path is not valid

- src/optimizer/plan_generation.c
http://jira.cubrid.org/browse/CBRD-22696
The MRO execution relies on XASL fields orderby_list & outptr_list. However, these two are not in sync in aggregate queries:
Aggregate code that actually uses outptr_list as input for aggregate and buildlist->g_outptr_list as output:
```c
if (pt_has_aggregate (parser, select_node))
...
xasl->outptr_list = pt_to_outlist (parser, group_out_list, NULL, UNBOX_AS_VALUE);
...
aggregate =
pt_to_aggregate (parser, select_node, xasl->outptr_list, buildlist->g_val_list, buildlist->g_regu_list,
buildlist->g_scan_regu_list, group_out_list, &buildlist->g_grbynum_val);
...
buildlist->g_outptr_list = pt_to_outlist (parser, select_node->info.query.q.select.list, NULL, unbox);
```
But orderby_list is always generated based on select list:
```c
xasl->orderby_list = …
```
> [CBRD-22696] no MRO for aggregate queries

- src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-22698
JSON table names are already resolved after tree is copied and ID's reset.
> [CBRD-22698] Accept json table resolved names 

- CMakeLists.txt
- src/compat/db_json.cpp
- src/compat/db_json.hpp
- src/query/arithmetic.c
- src/query/string_opfunc.c
- src/query/string_opfunc.h
http://jira.cubrid.org/browse/CBRD-22685
Use libregex when using gcc < 4.9.0 and switch the regex definition language from ECMAScript to POSIX.
> [CBRD-22685] GCC < 4.9.0 std::regex is experimental

- src/query/scan_json_table.cpp
- src/xasl/access_json_table.cpp
- src/xasl/access_json_table.hpp
http://jira.cubrid.org/browse/CBRD-22699
After finishing iterating, m_ordinality should be reinited in the cursor's parent node.
> [CBRD-22699] Ordinality in nested path does not get reset

- src/base/packable_object.hpp
- src/base/packer.cpp
- src/base/packer.hpp
- src/base/stream_entry.hpp
- src/replication/replication_object.cpp
- src/replication/replication_object.hpp
- src/replication/replication_stream_entry.cpp
- src/replication/replication_stream_entry.hpp
- unit_tests/packing/test_packing.cpp
- unit_tests/packing/test_packing.hpp
- unit_tests/stream/test_stream.cpp
- unit_tests/stream/test_stream.hpp
http://jira.cubrid.org/browse/CBRD-22673
1. Separate packer and unpacker functions (moved all unpack functions to unpacker). Unpacker can work with const buffers.
2. Use copies or references for pack/unpack arguments. Remove return codes.
3. Extend the packer/unpacker interfaces with bool type, switching to or_buf, get_current_size and is_ended functions. Add aliases for C-files - packing_packer and packing_unpacker.
4. Adjust packable_object function signatures and add a default implementation for is_equal in order to allow not extending it. TODO: remove it completely.
5. Add deserializator/get_unpack to stream_entry.
> [CBRD-22673] separate packer and unpacker

- src/object/object_print.h
http://jira.cubrid.org/browse/CBRD-22717
Unfortunately, the current ctltool won't be built by g++.
I hope we will fix it someday.
> [CBRD-22717] fix ctltool build issue - help_class_names

- src/base/packer.cpp
- src/base/packer.hpp
- unit_tests/packing/test_main.cpp
- unit_tests/packing/test_packing.cpp
- unit_tests/packing/test_packing.hpp
http://jira.cubrid.org/browse/CBRD-22673
Simplify packing/unpacking code using template parameter packs:
1. get total size of all arguments
2. pack all arguments
3. unpack all arguments
4. automatically resize buffer to the packed size of all arguments and pack them all.
Developer is still responsible to make sure arguments match (type & order) when packed and unpacked.
> [CBRD-22673] Extend packer with overloaded/bulk functions

- src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-22636
Do not override ER_JSON_INVALID_JSON errors to ER_TP_CANT_COERCE because they are more descriptive.
> [CBRD-22636] Improper cast to json error message

- msg/de_DE.utf8/utils.msg
- msg/en_US.utf8/utils.msg
- msg/en_US/utils.msg
- msg/es_ES.utf8/utils.msg
- msg/fr_FR.utf8/utils.msg
- msg/it_IT.utf8/utils.msg
- msg/ja_JP.utf8/utils.msg
- msg/km_KH.utf8/utils.msg
- msg/ko_KR.euckr/utils.msg
- msg/ko_KR.utf8/utils.msg
- msg/ro_RO.utf8/utils.msg
- msg/tr_TR.utf8/utils.msg
- msg/vi_VN.utf8/utils.msg
- msg/zh_CN.utf8/utils.msg
- src/communication/network.h
- src/communication/network_cl.c
- src/communication/network_interface_cl.c
- src/communication/network_interface_cl.h
- src/communication/network_interface_sr.c
- src/communication/network_interface_sr.h
- src/communication/network_sr.c
- src/loaddb/load_common.cpp
- src/loaddb/load_common.hpp
- src/loaddb/load_db.c
- src/loaddb/load_sa_loader.cpp
- src/loaddb/load_server_loader.cpp
- src/loaddb/load_session.cpp
- src/loaddb/load_session.hpp
http://jira.cubrid.org/browse/CBRD-22746
On SIGINT/SIGQUIT signal is CS_MODE, notify server loaddb session for interruption. As well when server is down, close the client and print an error message to stderr.
> [CBRD-22746] loaddb: handle SIGINT and SIGQUIT signals

- src/query/scan_json_table.cpp
- src/query/xasl_to_stream.c
- src/xasl/access_json_table.cpp
- src/xasl/access_json_table.hpp
http://jira.cubrid.org/browse/CBRD-22744
Clear the resources allocated by xts_debug_check.
Added an interface function clear_xasl to be used by XASL structures. It will be called by xts_debug_clear by default.
xts_debug_clear can be overloaded.
> [CBRD-22744] xts_debug_clear

- cci/CMakeLists.txt
- cubrid/CMakeLists.txt
- src/cci/cas_cci.h
- src/compat/dbi.h
- src/compat/dbi_compat.h
- src/compat/dbtran_def.h
- src/compat/dbtype_def.h
- src/executables/csql_result.c
- src/transaction/boot_sr.c
- src/transaction/log_comm.h
- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-22768
Separate transaction related code of dbtype_def.h and move to dbtran_def.h. File is exposed to CUBRID includes.
> [CBRD-22768] Move code from dbtype_def.h to dbtran_def.h

- cs/CMakeLists.txt
- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/object_representation.h
- src/base/perf_monitor.h
- src/base/porting.h
- src/base/porting_inline.hpp
- src/communication/network_interface_sr.c
- src/compat/db_json.cpp
- src/compat/dbtype_function.i
- src/object/object_domain.c
- src/object/object_representation.c
- src/query/vacuum.h
- src/storage/btree.c
- src/storage/disk_manager.c
- src/storage/double_write_buffer.c
- src/storage/file_io.h
- src/storage/file_manager.c
- src/storage/heap_file.c
- src/storage/page_buffer.c
- src/storage/slotted_page.c
- src/storage/storage_common.h
- src/transaction/boot_sr.c
- src/transaction/log_manager.c
- src/transaction/log_page_buffer.c
- src/transaction/log_recovery.c
- src/transaction/mvcc.c
http://jira.cubrid.org/browse/CBRD-22759
Move all macros related to cross-platform compatibility of inline functionality to porting_inline.hpp.
> [CBRD-22759] Header file for inline macros

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-22769
vacuum_consume_buffer_log_blocks needs system operations to allocate pages.
changes:
1. converting thread to master/worker claims system worker. restore thread retires it and sets tran_index to system (conversion functions are expected to be run by system thread only).
2. vacuum_recover_lost_block_data: convert thread to master in order to call vacuum_consume_buffer_log_blocks.
> [CBRD-22769] vacuum_recover_lost_block_data as system worker

- src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-22773
Set transaction index to LOG_SYSTEM_TRAN_INDEX when recycling thread entry for index builder. By default, recycle sets transaction index to NULL_TRAN_INDEX, thus invalidating the system worker.
We might consider avoid setting NULL_TRAN_INDEX altogether.
> [CBRD-22773] Fix recycling index build thread entry

- cubrid/CMakeLists.txt
http://jira.cubrid.org/browse/CBRD-22768
Remove duplicate dbtran_def.h install as quick fix.
TODO: make a proper fix by setting properly project dependencies and fixing CMS build.
> [CBRD-22768] quick fix for windows build issue

- src/compat/dbtran_def.h
http://jira.cubrid.org/browse/CBRD-22777
Brought back missing CCI aliases of isolation levels.
> [CBRD-22777] add isolation aliases for CCI backward compatibility

- src/communication/network_interface_sr.h
- src/executables/util_common.c
- src/transaction/log_common_impl.h
- src/transaction/log_global.c
- src/transaction/log_impl.h
- src/transaction/log_page_buffer.c
- src/transaction/log_writer.c
- src/transaction/log_writer.h
http://jira.cubrid.org/browse/CBRD-22791
1. Move logwr_mode from log_common_impl.h to log_writer.h
2. Move LOG_BGARV_HEADER from log_common_impl.h to log_writer.c
3. logwr_info constructor instead of LOGWR_INFO_INITIALIZER
4. Move logwr_status, logwr_entry and logwr_info from log_impl.h to log_writer.h.
5. Changed log_Gl.writer_info to pointer to avoid log_writer.h dependency.
> [CBRD-22791] Move log impl to log writer

- src/connection/server_support.c
- src/query/vacuum.c
- src/storage/btree_load.c
- src/storage/disk_manager.c
- src/storage/heap_file.c
- src/storage/page_buffer.c
- src/transaction/boot_sr.c
- src/transaction/log_impl.h
- src/transaction/log_manager.c
- src/transaction/log_manager.h
- src/transaction/log_page_buffer.c
- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-22809
Moved LOG_CS_xxx macro's to log_manager.h and converted them to functions.
Added logpb_force_flush_pages/logpb_force_flush_header_and_pages functions to automatically lock/unlock critical section.
> [CBRD-22809] Moved LOG_CS to log_manager

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/transaction/log_2pc.c
- src/transaction/log_2pc.h
- src/transaction/log_impl.h
- src/transaction/log_manager.c
- src/transaction/log_recovery.c
- src/transaction/log_storage.hpp
- src/transaction/transaction_sr.c
http://jira.cubrid.org/browse/CBRD-22811
Move two phase commit structures and function declarations from log_impl.h to newly created header log_2pc.h. Some functions have been renames (by adding "2pc" to name prefix) and extern was stripped from function declarations.
Unused functions have been deleted.
> [CBRD-22811] Log 2pc header

- cs/CMakeLists.txt
- cubrid/CMakeLists.txt
- src/base/memory_private_allocator.hpp
- src/base/memory_reference_store.hpp
- src/compat/db_json.cpp
- src/compat/db_json.hpp
- src/query/arithmetic.c
- src/query/scan_json_table.cpp
- src/xasl/access_json_table.cpp
http://jira.cubrid.org/browse/CBRD-22797
Comprising changes:
1. Avoid copying in db_value_to_json_doc when the json_doc_wrapper does not need to own the json_doc
2. Add cubmem::reference_store<T> to manage T's deallocations if it is owner during destructor. Use JSON_DOC_STORE = cubmem::reference_store<JSON_DOC> when appropriate
3. Begin replacing db_allocate_doc & db_json_delete_doc with JSON_DOC_STORE in arithmetic.c
> [CBRD-22797] Avoid superfluous copying in db_value_to_json_doc

- jdbc/build.xml
http://jira.cubrid.org/browse/CBRD-22812
The DriverManager methods getConnection and getDrivers have been enhanced to support the Java SE Service Provider mechanism (SPM). According to SPM, a service is defined as a well-known set of interfaces and abstract classes, and a service provider is a specific implementation of a service. It also specifies that the service provider configuration files are stored in the META-INF/services directory. JDBC 4.0 drivers must include the file META-INF/services/java.sql.Driver. This file contains the name of the JDBC driver's implementation of java.sql.Driver.
> [CBRD-22812] Add java.sql.Driver service provider

- src/object/authenticate.c
- src/object/authenticate.h
- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-22818
1. Add au_has_user_name function - returns true if any name was provided, false otherwise.
2. is au_has_user_name returns false, use AU_PUBLIC_USER_NAME
> [CBRD-22818] Use default PUBLIC when no user name is provided.

- src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-22813
Here, we allocate the new key using the global heap id. However, when we want to get the disk size of the newly created value, if the string compression is enabled it will allocate the compressed string using the heap id of the calling thread. This will fail during the clearing of the value since the clearing is done using the global heap id. This PR should fix it by calling the disk size function when we are using the global heap id.
> [CBRD-22813] Index Builder has to use the global HEAPID when generating compressed strings

- src/transaction/log_append.cpp
http://jira.cubrid.org/browse/CBRD-22841
LOG_PRIOR_LSA_LAST_APPEND_OFFSET is not a constant. It depends on log page size configuration.
> [CBRD-22841] fix LOG_PRIOR_LSA_LAST_APPEND_OFFSET

- src/transaction/client_credentials.cpp
- src/transaction/client_credentials.hpp
- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-22838
Strip path from program name using basename_r. Move log_Client_id_unknown_string to clientids::UNKNOWN_ID.
This is a regression of clientids refactoring.
> [CBRD-22838] Strip path from program name

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/query/filter_pred_cache.c
- src/query/filter_pred_cache.h
- src/query/xasl_cache.c
- src/query/xasl_cache.h
- src/transaction/locator_sr.c
- src/transaction/log_impl.h
- src/transaction/log_manager.c
- src/transaction/log_tran_table.c
- src/transaction/transaction_transient.cpp
- src/transaction/transaction_transient.hpp
http://jira.cubrid.org/browse/CBRD-22823
Separate transaction transient objects (lifetime expires with transaction) from `log_impl.h`. The plan is to add here all similar objects. Long-term we may identify a common approach for all these objects.
- move modified_class_list and rename as tx_transient_class_entry/tx_transient_class_registry.
- tx_transient_class_entry: change class name to std::string.
- tx_transient_class_registry: provide necessary interface to interact with modified classes: add/decache_heap_repr/clear, empty/has_class, map, to_string
NOTE: to_string is used for logtb_descriptors_start_scan and provides more verbose information than it used to. test results revising may be needed.
- replace all usages with new interface.
- replace log_rollback_classrepr_cache with …
> [CBRD-22823] Transaction transient objects - modified classes

- src/base/bip_buffer.hpp
- src/base/ini_parser.c
- src/base/perf_monitor.c
- src/broker/cas_net_buf.c
- src/cm_common/cm_nameval.c
- src/compat/dbtype_function.c
- src/connection/heartbeat.c
- src/object/class_object.h
- src/object/object_domain.c
- src/object/work_space.c
- src/object/work_space.h
- src/parser/compile.c
- src/parser/csql_grammar.y
- src/parser/csql_lexer.l
- src/parser/parse_tree.c
- src/parser/parser.h
- src/parser/xasl_generation.c
- src/query/query_executor.c
- src/query/scan_json_table.cpp
- src/query/scan_json_table.hpp
- src/query/xasl_to_stream.c
- src/storage/btree.c
- src/storage/btree_load.h
- src/storage/double_write_buffer.c
- src/storage/page_buffer.c
- src/storage/record_descriptor.cpp
- src/xasl/xasl_stream.cpp
- unit_tests/lockfree/test_cqueue_functional.cpp
- unit_tests/object_factory/test_object_factory.hpp
- unit_tests/packing/test_packing.cpp
Fix list of warnings:
-Wsign-compare
-Wtype-limits
-Waddress
-Wmissing-prototypes
-Wnonnull-compare
-Wredundant-decls
-Wformat=
Other changes:
- moved a block of code in page buffer to fix dependency on pgbuf_Pool. the only real change is replacing PGBUF_THREAD_HAS_PRIVATE_LRU macro with inline function.
- inline function for BTREE_MVCC_SET_HEADER_FIXED_SIZE
- changed signature of scanner::scan_next_internal (size_t depth)
- chagned signature of pt_append_string/pt_append_string_for (const char * old_string)
- changed work_space mvcc_snapshot_version to unsigned int
> [CBRD-21524] Fix warnings

- src/storage/double_write_buffer.c
Fix slip of PR#1505 - safe-guard `assert (initial_block_no >= 0);`
> [CBRD-21524] Fix bad safe-guard from df3e705

- src/transaction/log_append.cpp
http://jira.cubrid.org/browse/CBRD-22844
Fix casting `logpb_get_memsize ()` to log_Gl.prior_info.list_size type = INT64.
> [CBRD-22844] cast logpb_get_memsize () to INT64

- src/base/perf_monitor.c
- src/base/perf_monitor.h
- src/base/system_parameter.c
- src/base/system_parameter.h
- src/connection/server_support.c
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-22849
Use hidden system parameter stats_on to automatically collect statistics on server mode. When server is stopped, all stats are dumped to error log file.
> [CBRD-22849] Stats ON system parameter

- src/compat/db_json.cpp
- src/compat/db_json_path.cpp
- src/compat/db_json_path.hpp
- src/query/scan_json_table.cpp
- src/query/scan_json_table.hpp
http://jira.cubrid.org/browse/CBRD-22798
Implement & use JSON_PATH::extract instead of more expensive json_walkers.
> [CBRD-22798] Low performance of JSON_WALKER

- msg/de_DE.utf8/cubrid.msg
- msg/en_US.utf8/cubrid.msg
- msg/en_US/cubrid.msg
- msg/es_ES.utf8/cubrid.msg
- msg/fr_FR.utf8/cubrid.msg
- msg/it_IT.utf8/cubrid.msg
- msg/ja_JP.utf8/cubrid.msg
- msg/km_KH.utf8/cubrid.msg
- msg/ko_KR.euckr/cubrid.msg
- msg/ko_KR.utf8/cubrid.msg
- msg/ro_RO.utf8/cubrid.msg
- msg/tr_TR.utf8/cubrid.msg
- msg/vi_VN.utf8/cubrid.msg
- msg/zh_CN.utf8/cubrid.msg
- src/base/error_code.h
- src/compat/db_json.cpp
- src/compat/db_json.hpp
- src/compat/db_json_path.cpp
- src/compat/db_json_path.hpp
- src/query/arithmetic.c
http://jira.cubrid.org/browse/CBRD-22784
Added new Invalid json path; index too large error (-1207).
> [CBRD-22784] Large json array index causes unclear invalid path error

- src/compat/db_json_path.cpp
- src/query/arithmetic.c
- src/query/string_opfunc.c
- src/query/string_opfunc.h
http://jira.cubrid.org/browse/CBRD-22684
Do transformation for special characters during escaping (\t -> t).
> [CBRD-22684] JSON_QUOTE wrong behavior for special character-strings

- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22692
Fix linked-list cycle created by pt_substitute_analytic_reference (e.g pt_function with 2 args would cause cycle 1-2-2)
> [CBRD-22692] pt_to_set_aptr stack overflow

- src/query/scan_json_table.cpp
- src/query/scan_json_table.hpp
- src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-22596
Avoid changing sid.status from S_STARTED to S_ENDED (it is set for all scans in scan_end_scan).
> [CBRD-22596] fix JSON_TABLE scan status

- src/loaddb/load_common.cpp
- src/loaddb/load_common.hpp
- src/loaddb/load_db.c
- src/loaddb/load_error_handler.cpp
- src/loaddb/load_error_handler.hpp
- src/loaddb/load_object.c
- src/loaddb/load_object.h
- src/loaddb/load_server_loader.cpp
- src/loaddb/load_server_loader.hpp
http://jira.cubrid.org/browse/CBRD-22869
The `--error-file-control` argument was not implemented on the server. When the argument is provided for loading a database we parse the file and collect errors that need to be filtered by the error handler. We create vector with these errors which is sent to the server and the load workers will treat the cases where an error can be ignored by looking up in the filtered errors vector.
> [CBRD-22869] Implement the --error-file-control argument on the server

- src/loaddb/load_common.hpp
- src/loaddb/load_db.c
http://jira.cubrid.org/browse/CBRD-22867
In case the periodic commit argument is set to 0, the loading will fail and will crash the server. Since we set the batch size to be equal to the periodic commit, batches will have a size of 0 when the periodic commit is not provided. Therefore, we add a default value to the periodic commit argument in case it is not provided during the loading.
> [CBRD-22867] Fix the periodic-commit argument

- src/executables/master_heartbeat.c
http://jira.cubrid.org/browse/CBRD-22874
Allow HA to be configured with both hostname  and canonical name
> [CBRD-22874] [regression][ha] fix hostname/canonical name comparison

- src/base/packer.cpp
- src/base/packer.hpp
- src/storage/record_descriptor.cpp
- src/storage/record_descriptor.hpp
http://jira.cubrid.org/browse/CBRD-22878
- record_descriptor extends packable_object.
- add pack_buffer_with_length/unpack_buffer_with_length to packer.
- add header guard to record_descriptor.hpp
> [CBRD-22878] record_descriptor extends packable_object

- src/transaction/log_lsa.hpp
http://jira.cubrid.org/browse/CBRD-22881
We often use C-style allocation of structures that have log_lsa in their composition; the value is then initialized using LSA_SET_NULL. Initialize both pageid and offset to make sure the value is fully initialized.
This fixes UMR in issue. It is kind of strange that we end up having this issue in pgbuf_flush_page_and_neighbors_fb, but I did not investigate further.
> [CBRD-22881] initialize offset in log_lsa::set_null

- src/transaction/mvcc.c
- src/transaction/mvcc_active_tran.cpp
- src/transaction/mvcc_active_tran.hpp
- src/transaction/mvcc_table.cpp
http://jira.cubrid.org/browse/CBRD-22882
- add `copy_safety::THREAD_SAFE/THREAD_UNSAFE` argument to `mvcc_active_tran::copy_to`.
- deactivate `mvcc_active_tran` validity check during `build_mvcc_info`; data is not protected and concurrent access may invalidate it
- postpone data validity check when it is safe
> [CBRD-22882] mvcc_active_tran::copy_to thread safety

- src/transaction/mvcc_active_tran.cpp
- src/transaction/mvcc_active_tran.hpp
- src/transaction/mvcc_table.cpp
http://jira.cubrid.org/browse/CBRD-22885
Fix mvcc_tran_active after a failed copy.
> [CBRD-22885] Fix building snapshot when copy fails.

- src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-22886
It is a legacy issue. Small partition might not allow to create a volume.
> [CBRD-22886] fix free (page|sector) size of partition

- src/transaction/log_manager.c
- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-22896
checkpoint clears transaction descriptor which invalidates system operation. don't call checkpoint under system operation.
> [CBRD-22896] SA_MODE: don't do checkpoint during sysop

- src/transaction/mvcc_active_tran.cpp
- src/transaction/mvcc_active_tran.hpp
http://jira.cubrid.org/browse/CBRD-22897
Clear all BITAREA_MAX_MEMSIZE, not current bit area memory size.
> [CBRD-22897] fix mvcc_active_tran::reset_active_transactions

- src/compat/dbtype.h
http://jira.cubrid.org/browse/CBRD-22877
Avoid checking uninitialized type before checking for is_null flag.
> [CBRD-22877] avoid checking type if db_val is null

- src/storage/record_descriptor.cpp
- src/storage/record_descriptor.hpp
http://jira.cubrid.org/browse/CBRD-22907
Add custom memory allocators to record_descriptor. Default allocator remains private.
Change m_own_data to cubmem::extensible_block.
> [CBRD-22907] record_descriptor custom allocator

- src/base/packer.hpp
- unit_tests/packing/test_packing.cpp
- unit_tests/packing/test_packing.hpp
http://jira.cubrid.org/browse/CBRD-22872
Extend packer/unpacker with following functionality:
* `cubpacking::packer` with `template <typename T> void pack_to_int (const T &t);` function to pack object as `int` type
* `cubpacking::unpacker` with `template <typename T> void unpack_from_int (T &t);` function to unpack object from `int` type to `T` type
> [CBRD-22872] extend packer/unpacker to automatically convert to/from int

- src/base/mem_block.hpp
- src/query/query_executor.c
- src/query/serial.c
- src/storage/heap_file.c
- src/storage/heap_file.h
- src/storage/record_descriptor.cpp
- src/storage/record_descriptor.hpp
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-22910
1. change new_recdes type from RECDES * to record_descriptor *
2. when record data buffer is not enough, extend it by DB_PAGESIZE and retry
3. update serial_update_serial_object and locator_allocate_copy_area_by_attr_info to use new signature
1. remove while loop since heap_attrinfo_transform_to_disk should success on first try
2. consume record_descriptor allocated buffer; it there is an allocated buffer, it means that the initial copy area was not enough; release it and allocate another copy area big enough to hold all record data.
1. new setter function for recdes info: set_record_length, set_type
2. buffer manipulation functions: resize_buffer, set_external_buffer, release_buffer.
> [CBRD-22910] heap_attrinfo_transform_to_disk resize record

- src/transaction/transaction_complete_manager.cpp
http://jira.cubrid.org/browse/CBRD-22933
Pure virtual destructor must have a body, since destructors are always called in the reverse order of the class derivation.
```cpp
class base
{
public:
virtual ~base () = 0;
};
```
If `base` class is inherited and then child instance is deleted, `base`'s destructor will eventually be called.
Since it is pure and doesn't have a body it is undefined behavior
> [CBRD-22933] add destructor body for tx_complete_manager class

- src/base/stream_file.cpp
- src/base/stream_file.hpp
http://jira.cubrid.org/browse/CBRD-22963
Set explicitly file permission for replication file to read/write access for user.
**bug behavior**:
Creation of the replication file is done without specifying permissions, therefore the file has just user execute access (0100).
After file is created the file descriptor is closed and the file is opened again with `O_RDWR` flag, which will fail since the file has no read/write access.
> [CBRD-22963] [replication] set user read/write access for replication file

- src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-22964
Enable db modification before  `ha_Server_state` is forced set to `HA_SERVER_STATE_ACTIVE`
This is a quick fix, we need atomic operation when `db_Disable_modifications` and `ha_Server_state` are changed
**bug behavior**
When in `css_change_ha_server_state` function `ha_Server_state` is forced set to `HA_SERVER_STATE_ACTIVE` thread might be preempted, therefore `db_Disable_modifications` will remain with value `1` until thread will be scheduled again on CPU, in the meantime another thread which sees that ha server state is active can commit a transaction
> [CBRD-22964] [replication] enable db modification before ha server state is forced set to active

- src/storage/record_descriptor.cpp
http://jira.cubrid.org/browse/CBRD-22967
Set record descriptor's data source before resizing internal buffer on unpack operation
> [CBRD-22967] [record_descriptor] set data source properly when unpacking

- src/replication/log_generator.cpp
- src/replication/log_generator.hpp
- src/replication/replication_master_senders_manager.cpp
- src/replication/replication_object.cpp
http://jira.cubrid.org/browse/CBRD-22968
Delete changed_attrs_row_repl_entry entry on update on a table without primary key
NOTE: fix also std::vector::erase using iterators
> [CBRD-22968] [log_generator] fix memory leak

- src/base/multi_thread_stream.cpp
- src/replication/replication_master_node.cpp
- src/replication/replication_node.cpp
- src/replication/replication_slave_node.cpp
http://jira.cubrid.org/browse/CBRD-22971
There is invalid read reported by valgrind in `cubstream::stream::get_last_committed_pos` caused by wrong order in which members of `cubreplication::replication_node` are destroyed
This is the order of initialization:
```cpp
master_node *instance = master_node::get_instance (...);
instance->m_stream = new cubstream::multi_thread_stream (...);
instance->m_stream_file = new cubstream::stream_file (...);
```
Correct destroy order will be:
```cpp
delete m_stream_file;
m_stream_file = NULL;
delete m_stream;
m_stream = NULL;
```
> [CBRD-22971] [replication_node] fix delete order of members

- src/base/mem_block.cpp
- src/base/mem_block.hpp
- src/storage/heap_file.c
- src/storage/heap_file.h
http://jira.cubrid.org/browse/CBRD-22977
The functionality around heap_scancache->area/area_size was rewritten using memory block and block allocator.
The heap scan cache area is designed to be reused for multiple heap operations and it is set to multiple record descriptors in this process. The reusing of a single block of memory for various operations was rewritten as *single_block_allocator*, a structure that maintains a single block and that provides an allocator that always returns this block.
For heap, this is specialized with a HEAP_SCANCACHE_BLOCK_ALLOCATOR.
> [CBRD-22977] scan cache area block allocator

- src/replication/log_generator.cpp
http://jira.cubrid.org/browse/CBRD-22944
Old Stream entry containing with stream_entry_header::TRAN_STATE::GROUP_COMMIT is needed from log_consumer to execute apply tasks.  
Quick fix: undo removing until properly adopting the stream entry for group commit into log_consumer.
> [CBRD-22944] log_consumer does not receive GROUP_COMMIT stream_entry

- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-22961
Transaction table is not protected against writes while getting stored info from it, therefore we need to allocate a bigger buffer for serialization so we are safe in case data size changes between size calculation and packing operations.
> [CBRD-22961] fix log tran table info packing

- src/query/query_executor.c
- src/transaction/log_append.cpp
- src/transaction/log_impl.h
- src/transaction/log_tran_table.c
- src/transaction/mvcc.c
- src/transaction/mvcc.h
http://jira.cubrid.org/browse/CBRD-22972
qexec_execute_selupd_list is used to do fast click counter operations; changes are locked/unlocked and committed immediately. If one of the rows impacted by click counter was previously locked, modified rows are no longer unlocked and changes are not immediately committed, however complete sub-mvcc is still executed (but shouldn't).
The "instant" locking is forcefully disabled by lock manager. An operation reordering is required to correctly handle the case - first lock all to-be-modified rows, then check that instant locking was not disabled and only then decide to use system operation and sub-mvcc to make the changes.
1. run two loops on selupd list: in the first iteration collect increment info and lock objects; on the second iteration call …
> [CBRD-22972] fix qexec_execute_selupd_list operations

- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-22983
On HA cluster database.txt might contain multiple hosts, in case when db host is not passed to ddl_proxy it might be the case that ddl_proxy will connect to wrong host
database.txt example
```
#db-name  vol-path                 db-host                 log-path                 lob-base-path
test_db   /var/lib/cubrid/test_db  master-host:slave-host  /var/lib/cubrid/test_db  file:/var/lib/cubrid/test_db/lob
```
> [CBRD-22983] [ddl proxy] connect explicitly to localhost

- src/object/object_primitive.c
- src/replication/replication_object.cpp
http://jira.cubrid.org/browse/CBRD-22993
The issue occurs when the primary key is of type `DB_TYPE_VARNCHAR` and the values is longer than 255 characters (in order to be compressed).
```sql
create table t1 (id NCHAR VARYING primary key, nr integer);
insert into t1 values (n'aaaaaa ....', 1); /* id string must be longer than 255 characters */
```
There are two issues with compression of the `DB_TYPE_VARNCHAR` type:
1. there is an inconsistency between `mr_setval_varnchar` and `pr_do_db_value_string_compression` function. `mr_setval_varnchar` does not copy the compressed_buf even though `pr_do_db_value_string_compression` does compression for `DB_TYPE_VARNCHAR` type
2. there are cases when packing of the `m_key_value` from `single_row_repl_entry` class might allocate memory (in this case …
> [CBRD-22993] fix 

- src/replication/replication_object.cpp
- src/storage/heap_file.c
- src/storage/heap_file.h
http://jira.cubrid.org/browse/CBRD-22997
allocate recdes area big enough to allow heap_update_adjust_recdes_header execute safely.
> [CBRD-22997] adjust recdes area for apply

- src/base/hostname.hpp
- src/master/master_heartbeat.cpp
- src/master/master_heartbeat.hpp
http://jira.cubrid.org/browse/CBRD-22998
Prevent slave_node connect to self master_node.
Use hostname_type instead of char * to make code more robust.
> [CBRD-22998] prevent slave_node connect to self master_node

- src/executables/util_cs.c
- src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-23002
1. add name resolution and semantic check for queries of form `CREATE ... AS SELECT ..`
2. collect and log all parse tree errors on ddl_proxy_client
Fix from point 1. needs to be ported on develop as well
> [CBRD-23002] do name resolution & semantic checks on select pt node for PT_CREATE_ENTITY node

- src/storage/record_descriptor.cpp
http://jira.cubrid.org/browse/CBRD-22997
Regression of #1611
A newly created `record_descriptor` will have `m_data_source = data_source::INVALID` and `area_size = 0` (zero), therefore allow resizing newly created instance and set data source to `data_source::NEW` after resize operation
> [CBRD-22997] record_descriptor: allow resizing a record_descriptor with a invalid 

- src/loaddb/load_lexer.l
- src/loaddb/load_scanner.hpp
http://jira.cubrid.org/browse/CBRD-23013
With the new approach, string conversion errors were not correctly handled on SA_MODE. The lexer should throw a fatal error in case it finds such a conversion error, however, on the current SA_MODE, the lexer would just set the session as failed, which was not entirely correct. Now, on SA_MODE we will detect the conversion errors at the time they are encountered by removing the override of `LexerError` and letting the old implementation handle the error scenario.
> [CBRD-23013] Fix error handling in case of string conversion scenarios

- src/storage/heap_file.c
- src/storage/heap_file.h
- src/storage/slotted_page.c
- src/storage/slotted_page.h
- src/transaction/boot_sr.c
- src/transaction/locator_sr.c
- src/transaction/locator_sr.h
http://jira.cubrid.org/browse/CBRD-22978
This is a Work In Progress PR.
This function should be specialized into inserting an array of records into the same heap file. It works as it follows:
- ~~Records passed as parameters for this function should have already been partition pruned before this.~~ Pruning is handled by the insert function.
- Insert any records that are not normal ones (`REC_HOME`) using the old implementation of `locator_insert_force`.
- The normal records are then collected until we manage to fill a whole heap page. (~~TODO: Needs to be checked~~).
- When the size limit is hit, the insert is issued and we get a new page in which all of the records should have been inserted.
TODO:
- Create the heap chain using the pages and append the chain to the heap.
- Check for …
> [CBRD-22978] New locator function specialized on inserting multiple records

- src/storage/heap_file.c
- src/storage/heap_file.h
- src/transaction/boot_sr.c
- src/transaction/locator_sr.c
- src/transaction/locator_sr.h
http://jira.cubrid.org/browse/CBRD-22978
This is a Work In Progress PR.
This function should be specialized into inserting an array of records into the same heap file. It works as it follows:
- ~~Records passed as parameters for this function should have already been partition pruned before this.~~ Pruning is handled by the insert function.
- Insert any records that are not normal ones (`REC_HOME`) using the old implementation of `locator_insert_force`.
- The normal records are then collected until we manage to fill a whole heap page. (~~TODO: Needs to be checked~~).
- When the size limit is hit, the insert is issued and we get a new page in which all of the records should have been inserted.
TODO:
- Create the heap chain using the pages and append the chain to the heap.
- Check for …
> [CBRD-22978] Locator multi insert function

- src/base/tz_support.c
http://jira.cubrid.org/browse/CBRD-23006
This does not fix the issue, it just adds assertion to catch the issue earlier.
> [CBRD-23006] Add assert in timezone module to catch internal error.

- src/replication/replication_object.cpp
http://jira.cubrid.org/browse/CBRD-23018
Change private heap id when allocating memory on `pack` and `get_packed_size` of the `changed_attrs_row_repl_entry` (the memory is allocated when compressing strings)
> [CBRD-23018] changed_attrs_row_repl_entry: use proper heap id on pack/get_packed_size

- src/base/tz_support.c
- src/compat/dbtype_def.h
- src/connection/connection_defs.h
- src/connection/connection_sr.c
- src/connection/connection_support.c
- src/connection/server_support.c
- src/session/session.c
- src/session/session.h
- src/session/session_sr.c
- src/thread/thread_entry.cpp
- src/thread/thread_entry.hpp
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23006
Allow to create session without a connection entry; in this case, the session is linked directly into thread entry.
The session is linked to both thread entry and connection entry.
TODO:
The apply thread should require timezone (or other specific session parameters) only for value printing.
We may need to rethink the replicating of system parameters to apply also for RBRs (currently they apply only for SBRs as in legacy behavior).
Implement reference count and timeout for session without connection.
> [CBRD-23006] create session without connection for replication apply

- src/executables/util_cs.c
http://jira.cubrid.org/browse/CBRD-23008
Trigger execution needs to be disabled in ddl_proxy client, as legacy implementation of applylogdb does.
https://github.com/CUBRID/cubrid/blob/b85a234af25f8f27bb08cb7b8bf377383bcafa21/src/executables/util_cs.c#L2926
> [CBRD-23008] [replication] ddl_proxy: disable trigger execution

- src/replication/replication_master_node.cpp
- src/replication/replication_master_senders_manager.cpp
- src/replication/replication_master_senders_manager.hpp
- unit_tests/replication_channels/cub_master_mock.cpp
- unit_tests/replication_channels/master_replication_channel_mock.cpp
- unit_tests/replication_channels/master_replication_channel_mock.hpp
http://jira.cubrid.org/browse/CBRD-23020
- fix memory leak when erasing a transfer_sender https://github.com/CUBRID/cubrid/blob/0257b3ec51ac5f757d1f9a49799b3c148b281208/src/replication/replication_master_senders_manager.cpp#L185
- remove `cubreplication::master_senders_manager::g_stream` pointer, because when `cubreplication::master_node::g_instance` is deleted the pointer remains dangling
> [CBRD-23020] [replication] fix memory leak in master_senders_supervisor_task::execute

- src/connection/server_support.c
- src/replication/replication_master_node.cpp
- src/replication/replication_slave_node.cpp
http://jira.cubrid.org/browse/CBRD-23024
`cubreplication` `master_node` and `slave_node` instances are initialized only if `!HA_DISABLED` and `conn != NULL` (conn is the connection to the cub_master). Nodes must be stopped under same conditions, in order to avoid stopping uninitialized nodes
> [CBRD-23024] safe guard master/slave node finalize

- src/connection/server_support.c
- src/thread/thread_entry_task.cpp
http://jira.cubrid.org/browse/CBRD-23023
The thread_entry context may be reused between thread worker pools.
A thread entry may server as context for replication apply worker pool (a private lru is assigned) and then attached to server worker pool.
The fix resets private lru on retire and recyle of context.
TODO : same fix on develop branch.
> [CBRD-23023] reset private lru index after execution

- src/session/session.c
http://jira.cubrid.org/browse/CBRD-23027
`session_get_session_parameter`: return `NULL` if `session_p->session_parameters` are missing
> [CBRD-23027] fix get session parameter when session parameters are missing

- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23030
Some tests: like https://github.com/CUBRID/cubrid-testcases/blob/e0941ae9902e18232d95c7809cde7bebb5b1296e/sql/_13_issues/_14_1h/cases/bug_bts_12463.sql sometimes exceeds 10m timeout on circleci test_sql job. It was caused by debug replication data being enabled by default
> [CBRD-23030] disable by default debug replication data

- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23033
Log cast db value instead of original db value in case domain do not match for update statements.
**Failing tests**:
* sql/_27_banana_qa/issue_5765_timezone_support/_02_type_conversions/_02_implicit_conversion/cases/_02_upd_t_to_with_tz.test
* sql/_27_banana_qa/issue_5765_timezone_support/_02_type_conversions/_02_implicit_conversion/cases/_04_upd_character_to_dt.test
* sql/_27_banana_qa/issue_5765_timezone_support/_02_type_conversions/_02_implicit_conversion/cases/_04_upd_date_time_to_t.test
* sql/_27_banana_qa/issue_5765_timezone_support/_02_type_conversions/_02_implicit_conversion/cases/_04_upd_character_to_t.test
* sql/_27_banana_qa/issue_5765_timezone_support/_02_type_conversions/_02_implicit_conversion/cases/_04_upd_character_to_ts.test
* …
> [CBRD-23033] [replication] fix replication log generator for update statements

- src/connection/server_support.h
- src/session/session.c
- src/thread/thread_entry_task.hpp
- src/thread/thread_manager.hpp
- src/thread/thread_task.hpp
http://jira.cubrid.org/browse/CBRD-23032
Make it easy to instantiate custom callable_tasks based on execution callable (and optionally retire callable). 
Changes:
- callable_task classes (with and without context). template constructors with callable types.
- entry_callable_task specialization.
- replace session_control_daemon_task as proof of concept.
Future todo: replace other task classes with callable_task.
> [CBRD-23032] thread tasks with callables

- src/replication/replication_stream_entry.cpp
- src/replication/replication_stream_entry.hpp
http://jira.cubrid.org/browse/CBRD-22937
Separate packing of stream entry tran state and count to avoid bitmask missmatch.
Code extracted from https://github.com/CUBRID/cubrid/pull/160
> [CBRD-22937] pack stream entry state and count separately

- src/base/packer.cpp
- src/base/packer.hpp
- src/base/stream_entry.hpp
- src/communication/network_interface_sr.c
- src/replication/replication_object.cpp
- src/replication/replication_object.hpp
- src/replication/replication_stream_entry.hpp
- src/replication/slave_control_channel.hpp
- src/transaction/locator_sr.c
- src/transaction/replication.h
- unit_tests/packing/test_packing.cpp
http://jira.cubrid.org/browse/CBRD-23035
- fix warnings
- make LOG_LSA constructor argument for replication_object const (allow initializing with NULL_LSA).
- add safe-guards to locator function to catch missed issue
[EDIT] Code extracted from https://github.com/CUBRID/cubrid/pull/1605
> [CBRD-23035] minor changes (fix warnings & other)

- src/base/udp_rpc.hpp
- src/master/heartbeat_cluster.cpp
- src/master/master_heartbeat.cpp
http://jira.cubrid.org/browse/CBRD-23037
heartbeat shutdown thread and heartbeat net poll thread shared same mutex. Therefore when shutdown event is fired the mutex is acquired but the poll thread won't exit since it is blocked on the same mutex.
The deadlock was caused by the fact that heartbeat udp server is stopped under acquired mutex, the fix is to stop the server under no mutex after the cluster is stopped.
> [CBRD-23037] fix heartbeat cluster shutdown deadlock

- src/master/heartbeat_cluster.cpp
- src/master/master_heartbeat.cpp
http://jira.cubrid.org/browse/CBRD-23037
Fix slip of #1652, stop first hearbeat udp server then the heartbeat cluster
> [CBRD-23037] fix hearbeat deadlock on shutdown

- src/query/vacuum.c
- src/replication/replication_master_senders_manager.cpp
- src/replication/replication_master_senders_manager.hpp
- src/storage/disk_manager.c
- src/storage/double_write_buffer.c
- src/storage/external_sort.c
- src/storage/file_io.c
- src/storage/page_buffer.c
- src/thread/thread_task.hpp
- src/transaction/lock_manager.c
- src/transaction/log_manager.c
http://jira.cubrid.org/browse/CBRD-23034
- replace simple tasks with cubthread::entry_callable_tasks based on function
- add cubthread::callable_task::exec_func_type
- fix several file_io.c warnings
> [CBRD-23034] replace simple task classes with callable tasks

- src/transaction/mvcc_active_tran.cpp
http://jira.cubrid.org/browse/CBRD-23040
Move check_valid check from end of add_long_transaction to end of cleanup_migrate_to_long_transations. m_bit_area_start_mvccid is not updated until ltrim_area, which causes safe-guard fail:
```c
assert (MVCC_ID_PRECEDES (m_long_tran_mvccids[i], m_bit_area_start_mvccid));
```
> [CBRD-23040] fix cleanup_migrate_to_long_transations check_valid safe-guard

- src/replication/replication_slave_node.cpp
- src/replication/slave_control_channel.cpp
- src/replication/slave_control_channel.hpp
Fix slip of https://github.com/CUBRID/cubrid/pull/1617 (slave_node contains no connection to a master)
> [CBRD-22951] fix case slave_node has no connection to a master

- src/base/packer.cpp
- src/base/packer.hpp
- src/replication/replication_object.cpp
- unit_tests/packing/test_packing.cpp
- unit_tests/stream/test_stream.cpp
http://jira.cubrid.org/browse/CBRD-23041
- add get_all_packed_size_starting_offset (same as get_all_packed_size, but with start_offset not zero).
- backport get_packed_int_vector_size signature change from ha_replication.
> [CBRD-23041] packer::get_all_packed_size_starting_offset

- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23043
`left` value might not be null terminated.
> [CBRD-23043] fix UMR of db_add_time

- src/communication/stream_transfer_receiver.cpp
- src/communication/stream_transfer_sender.cpp
http://jira.cubrid.org/browse/CBRD-23048
when cub_server process is killed transfer sender/receiver daemons will continue receiving from the socket which will log a lot of message into the server err log file
> [CBRD-23048] [replication] fix flooding of the server err log file

- src/object/transform_cl.c
Fix warning: cast between incompatible function types [-Wcast-function-type]
> [CBRD-21524] fix warning: cast between incompatible function types

- src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-23045
NULL value may not have its precision. It's incorrect to extract precision from NULL value.
> [CBRD-23045] fix UMR of accessing null value

- src/object/object_representation.c
http://jira.cubrid.org/browse/CBRD-23057
Fix setting representation id in replication context by converting values between host and network byte order.
> [CBRD-23057] [replication] fix set representation id

- src/replication/log_generator.cpp
- src/replication/log_generator.hpp
- src/transaction/transaction_sr.c
http://jira.cubrid.org/browse/CBRD-23004
DML statements server-side execution and xlocator_force are guarded with xtran_server_start_topop/xtran_server_end_topop to keep changes atomic. If statements have many changes, it is possible that multiple replication stream entries will be generated and applied on slave side. We need to make sure changes are atomic on slave side too.
We discussed internally and reached the conclusion that the easiest solution is to generate savepoint names based on LSA. This guarantees name uniqueness, start/end name consistency and very unlikely conflicts with user defined savepoints.
**TODO:**
- remove replication objects for unused generated savepoints. in some production scenarios, point insert/delete/update statements may be dominating. for each …
> [CBRD-23004] convert xtran start/end sysop intro replication savepoints

- src/base/error_code.h
- src/base/lock_free.c
http://jira.cubrid.org/browse/CBRD-23063
windows only
- force include winerr.h in error_code.h
- disable C4197 in lock_free.c
> [CBRD-23063] suppress windows spammer warnings

- CMakeLists.txt
- src/base/encryption.c
- src/compat/db_json.cpp
- src/compat/db_json_allocator.hpp
- src/compat/db_json_path.cpp
- src/compat/db_json_path.hpp
- src/compat/db_json_types_internal.hpp
- src/compat/db_rapidjson.hpp
- src/heaplayers/customheaps.cpp
- src/heaplayers/heaplayers.h
- Disable cmake download progress for external projects
- Suppress external libraries compile warnings for:
- libexpat cmake target
- libjansson cmake target
- libedit cmake target
- liblzo cmake target
- libgpg-error cmake target
- libgcrypt cmake target and header includes
- rapidjson header includes
- heaplayers header includes
> [CBRD-21524] suppress external libraries compile warnings

- src/base/ini_parser.c
- src/broker/broker_acl.c
- src/broker/broker_admin_pub.c
- src/broker/cas_execute.c
- src/broker/shard_admin_pub.c
- src/transaction/log_writer.c
Fix -Wformat-overflow GCC warnings:
- https://github.com/CUBRID/cubrid/blob/56f2a7ca244c8a8ec8dde991726e51fd787cd003/src/base/ini_parser.c#L645
- https://github.com/CUBRID/cubrid/blob/56f2a7ca244c8a8ec8dde991726e51fd787cd003/src/broker/broker_admin_pub.c#L2293
- https://github.com/CUBRID/cubrid/blob/56f2a7ca244c8a8ec8dde991726e51fd787cd003/src/broker/broker_admin_pub.c#L2341
- https://github.com/CUBRID/cubrid/blob/56f2a7ca244c8a8ec8dde991726e51fd787cd003/src/broker/broker_admin_pub.c#L2389
- https://github.com/CUBRID/cubrid/blob/56f2a7ca244c8a8ec8dde991726e51fd787cd003/src/broker/cas_execute.c#L5851
- https://github.com/CUBRID/cubrid/blob/56f2a7ca244c8a8ec8dde991726e51fd787cd003/src/transaction/log_writer.c#L1127
- …
> [CBRD-21524] fix -Wformat-overflow GCC warning

- src/replication/replication_row_apply.cpp
http://jira.cubrid.org/browse/CBRD-23068
Set error when returning ER_OBJ_OBJECT_NOT_FOUND to fix crash.
TODO: testing the safe-guarded branch should reveal why object was not found earlier. For now, set error to suppress crash.
> [CBRD-23068] set ER_OBJ_OBJECT_NOT_FOUND error

- src/storage/record_descriptor.cpp
- src/storage/record_descriptor.hpp
http://jira.cubrid.org/browse/CBRD-22675
Backport record descriptor changes from ha replication branch
> [CBRD-22675] backport record descriptor changes from ha replication

- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23070
Reflect new vacuum data last blockid value as `logpb_last_complete_blockid ()` before SA_MODE shutdown.
> [CBRD-23070] Update SA_MODE vacuum data last blockid

- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23070
Update vacuum data last blockid before shutting down SA_MODE to make sure it is not left way behind after a long stand-alone session (e.g. loaddb).
> [CBRD-23070] Update vacuum last blockid on SA_MODE shutdown

- src/query/query_executor.c
- src/query/scan_manager.c
- src/query/serial.c
- src/storage/catalog_class.c
- src/storage/heap_file.c
- src/transaction/locator_sr.c
- src/transaction/lock_manager.c
http://jira.cubrid.org/browse/CBRD-23075
This is a back port of #1665. 
It also includes one extra fix to `xlocator_prefetch_repl_update_or_delete` that was removed in develop.
> [CBRD-23075] [10.1p3] fix UMR on callers of heap_get_visible_version (#1665)

- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23076
It is a backport of #1664
> [CBRD-23076] [10.1p3] fix UMR of db_add_time (#1664)

- src/object/object_primitive.h
http://jira.cubrid.org/browse/CBRD-23082
It is a backport of #1545.
> [CBRD-23082] [10.1p3] avoid checking type if db_val is null (#1545)

- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23090
Save when vacuum data is initialized if this is a restoredb session and avoid vacuum_sa_reflect_last_blockid on shutdown.
> [CBRD-23090] do not update/reflect vacuum data last blockid on restoredb

- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22692
Fix pt_substitute_analytic_reference for PT_FUNCTIONs.
backport of #1524
> [CBRD-22692] fix pt_substitute_analytic_reference (#1524)

- src/object/transform_cl.c
- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-22805
disk_to_class did not check returned value of sm_find_class and missed error. Fix by checking it is not null.
printing callstack of boot_server_die_or_changed helped me find where the error was leaked. I activated it on TEST_MODE.
backport of #1510
> [CBRD-22805] fix disk_to_class missing error (#1510)

- src/optimizer/plan_generation.c
http://jira.cubrid.org/browse/CBRD-22696
The MRO execution relies on XASL fields orderby_list & outptr_list. However, these two are not in sync in aggregate queries:
Aggregate code actually uses outptr_list as input for aggregate and buildlist->g_outptr_list as output:
```c
if (pt_has_aggregate (parser, select_node))
...
xasl->outptr_list = pt_to_outlist (parser, group_out_list, NULL, UNBOX_AS_VALUE);
...
aggregate =
pt_to_aggregate (parser, select_node, xasl->outptr_list, buildlist->g_val_list, buildlist->g_regu_list,
buildlist->g_scan_regu_list, group_out_list, &buildlist->g_grbynum_val);
...
buildlist->g_outptr_list = pt_to_outlist (parser, select_node->info.query.q.select.list, NULL, unbox);
```
But orderby_list is always generated based on select list:
```c
xasl->orderby_list = …
```
> [CBRD-22696] no MRO for aggregate queries (#1428)

- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22594
In case of an error, the OID would have been kept as locked after propagating the error. However the assert fails so, in case of an error, we now also unlock the object.
backport of #1373
> [CBRD-22594] Fix case of error during unique search (#1373)

- src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-22590
heap_get_visible_version was interrupted, but error was not handled by scan_next_index_lookup_heap
backport of #1358
> [CBRD-22590] scan_next_index_lookup_heap: handle S_ERROR (#1358)

- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-22484
It is a legacy issue.
To exit redundant backup request cleared some globals and the existing backup might be dead ended.
The fix is to early out the extra backup request without initializing backup session (globals).
backport of #1349
> [CBRD-22484] backup failed with any other backup (#1349)

- src/storage/disk_manager.c
- src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-22441
This issue was a regression of propagating interrupt error from fileio_initialize_pages, because it lead to inconsistencies between volume header and disk cache.
After we "commit" the changes in volume header, we cannot permit any interruptions. Fix by verifying logtb_get_check_interrupt in fileio_initialize_pages.
backport #1274
> [CBRD-22441] do not interrupt fileio_expand_to (#1274)

- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22403
Create as subquery creates underneath an insert subquery. Since there is a false where in the non_recursive part of the cte, the non_recursive part is transformed to a false_subquery. This transforms the non_recursive part into a PT_VALUE, making the assert test fail.
It is however alright to just change the assertion since the non_recursive_part will not get its xasl built. Execution does recognize non_recursive_part null as being a false where.
backport #1249
> [CBRD-22403] Core dumped in pt_uncorr_post (#1249)

- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-22394
Registered uncleared db_vals of char type to be cleared as parser orphans.
backport #1241
> [CBRD-22394] pt_to_aggregate_node memory leak (#1241)

- src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-22266
Deallocate is undone and a compensate record is appended to overwrite usual fetch mode - we need to force page fix even if it is deallocated.
However, it does not mean fixed page is always deallocated. Compensation may have been flushed to disk.
Backport #1175
> [CBRD-22266] expect allocated page for OLD_PAGE_DEALLOCATED (#1175)

- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-22197
db_find_string_in_in_set(): rewrite loop and test string-end before reading
backport #1145
> [CBRD-22197] fix UMR of db_find_string_in_in_set (#1145)

- src/storage/btree.c
a class lock is required to consistent read.
backport #1111
> [CBRD-22130] "show index" statements needs a table lock (#1111)

- src/object/work_space.c
http://jira.cubrid.org/browse/CBRD-22127
This must be a legacy issue.
To decache a class mop whose class name is missing caused crash.
backport #1109
> [CBRD-22127] safer decaching class mop from workspace (#1109)

- src/query/query_executor.c
- src/storage/statistics_sr.c
- src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-21897
This is a legacy issue.
Dead-lock/latch between qexec_execute_build_indexes and xstats_get_statistics_from_server.
The latter acquires lock and then fixes a page latch to access class representation, while the former did into reverse. This caused deadlock chances.
Fix is to make show indexes to follow the same order of query execution.
backport #1003
> [CBRD-21897] fix to avoid deadlock of "show indexes" (#1003)

- src/cci/cas_cci.c
http://jira.cubrid.org/browse/CBRD-21895
It is a legacy bug which can be reproduced when connection to cas is disconnected and cci retries.
The return of qe_set_cas_change_mode is confusing. Fix separates input cas mode from return code.
backport #990
> [CBRD-21895] cci_set_cas_change_mode: fixes bad retry (#990)

- src/base/memory_hash.c
http://jira.cubrid.org/browse/CBRD-21862
This is also a legacy bug.
It might badly access zero length string to generate hash key.
backport #986
> [CBRD-21862] IVR of mht_get_hash_number with zero length string (#986)

- src/object/object_template.c
- src/object/object_template.h
- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-21860
http://jira.cubrid.org/browse/CBRD-21871
http://jira.cubrid.org/browse/CBRD-21892
Freed template was read and also double freed for an error case.
backport #984 #987 #988
> [CBRD-21860] (potential) FMR of do_insert_template (#984, #987, #988)

- src/object/object_domain.c
http://jira.cubrid.org/browse/CBRD-21861
fixes UMR to cast zero length string to number.
backport #985
> [CBRD-21861] UMR of tp_atof with zero length string (#985)

- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/boot_sr.c
- src/transaction/log_impl.h
- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-22174
Add a routine to handle first boot after copydb. Log header is extended for this purpose, but it should be backward compatible.
Properly handle the case when log_blockid is `NULL`. It may happen on both branches of condition:
`if (LSA_ISNULL (&vacuum_Data.recovery_lsa) && LSA_ISNULL (&log_Gl.hdr.mvcc_op_log_lsa))`
Backport #1148
> [CBRD-22174] first boot after copydb

- src/query/vacuum.c
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23089
Declare variables in the start of function scope (old C syle).
> [CBRD-23089] Fix windows compile

- src/query/vacuum.c
- src/storage/btree.c
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23105
Back-port of #1176 
http://jira.cubrid.org/browse/CBRD-22268
b-tree page initialization is logged with undoredo. on undo, page type is set to deallocated/unknown. xbtree_add_index initialized root page twice; which lead to inconsistent state during rollback.
remove duplicate b-tree root page initialization.
> [CBRD-23105] remove duplicate b-tree root initialization

- src/connection/server_support.c
- src/transaction/log_comm.c
http://jira.cubrid.org/browse/CBRD-23101
In log_does_allow_replication there was a window during commute_to_master_state when the pair (ha_state, db_Disable_modifications) was inconsistent. Fix order in css_change_ha_server_state()
> [CBRD-23101] Fix crash during slave to master

- src/query/query_executor.c
- src/query/serial.c
- src/replication/log_generator.cpp
- src/storage/heap_file.c
- src/transaction/locator_sr.c
- src/transaction/log_impl.h
- src/transaction/log_manager.c
- src/transaction/log_tran_table.c
- src/transaction/transaction_master_group_complete_manager.cpp
- src/transaction/transaction_sr.c
http://jira.cubrid.org/browse/CBRD-23113
Hide replication generator in use with a getter. CBRD-23055 can switch replication generator to sub-transaction.
Conflicts with other patches are very likely.
> [CBRD-23113] Add getter for transaction descriptor replication generator

- src/base/system_parameter.c
- src/base/system_parameter.h
- src/communication/network_interface_sr.c
- src/loaddb/load_driver.cpp
- src/loaddb/load_driver.hpp
- src/loaddb/load_session.cpp
- src/loaddb/load_session.hpp
http://jira.cubrid.org/browse/CBRD-23100
We have decided to switch the individual client worker pool to a global one, which is created by the first session to initialize the loading process. Any other session that comes and wants to load will use the same worker pool and the last session to finish will also destroy it.
To ease the usage of this new worker pool I have also added a system parameter called `loaddb_worker_count ` which can be modified depending on the user's needs. The default size of the pool is set to 4 workers.
> [CBRD-23100] Implement a global worker pool for loaddb

- src/replication/log_generator.cpp
http://jira.cubrid.org/browse/CBRD-23124
After calling add_packable_entry, the replication object is owned by the stream_entry, so it should not be used anymore.
TODO: A more robust fix is planned in CBRD-23079; we experimented a solution, but due to design (class inheritance) we didn't reach a compileable code.
> [CBRD-23124] Fix invalid access on replication_object

- cs/CMakeLists.txt
- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/generic_utils.hpp
- src/base/multi_thread_stream.cpp
- src/base/stream_entry_fetcher.hpp
- src/base/type_traits_utils.hpp
- src/replication/log_consumer.cpp
- src/replication/log_consumer.hpp
- src/replication/replication_slave_node.cpp
http://jira.cubrid.org/browse/CBRD-23128
Comprising changes:
1. Unify fetcher & dispatcher threads (make the dispatch thread fetch directly from stream)
2. Move ack-sending to dispatcher
> [CBRD-23128] Stream fetcher refactoring

- src/loaddb/load_session.cpp
- src/loaddb/load_worker_manager.cpp
- src/loaddb/load_worker_manager.hpp
- src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-23097
This PR integrates the new working pool which limits how many tasks are executed at once. This should limit the number of batches that are executed on the server, thus fixing the issue regarding huge memory usage to store these batches on the server.
TODO: We also need to backport the changes to develop of the workerpool since it no longer requires the thread manager in its implementation.
> [CBRD-23097] Integrated the workerpool which limits how many tasks are pushed

- src/base/system_parameter.c
- src/base/system_parameter.h
- src/thread/thread_manager.cpp
- src/thread/thread_waiter.hpp
- src/thread/thread_worker_pool.cpp
- src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-23139
We need to pool and keep threads alive to allow perf test collect all their stats.
> [CBRD-23139] keep threads always alive for perf test

- src/storage/heap_file.c
- src/transaction/log_manager.c
Do not reset the LSA marker of modified class when representation is decached on partial rollback. 
Backport of #1784.
> [CBRD-22130] fix decaching representation on partial rollback

- src/query/partition.c
- do not set pruned flag if error occurred during partition_prune_spec (next time it will early out)
Backport of #1788
> [CBRD-22130] Do not set pruned flag on errors

- src/parser/compile.c
- src/parser/view_transform.c
* Fixed crash caused by accessing deallocated memory
* filter out warnings
backport #1772
> [CBRD-23134] Fixed crash caused by accessing deallocated memory (#1772)

- src/transaction/log_page_buffer.c
Reverts CUBRID/cubrid#1792
http://jira.cubrid.org/browse/CBRD-23166 is a counter case to this fix.
Since these two are conflicting each other, I don't see a fix for both. 
If a slave lags and master removes logs that it needs, it should be rebuilt.
> [CBRD-23147] Revert #1792: Removing archived log should also care copied log positi…"

- src/thread/thread_worker_pool.cpp
http://jira.cubrid.org/browse/CBRD-23171
Using stringstream.str ().c_str () is unsafe. Make a string copy and then call c_str ().
> [CBRD-23171] Fix wp_er_log_stats dangling pointer issue

- src/base/resource_tracker.cpp
- src/base/resource_tracker.hpp
http://jira.cubrid.org/browse/CBRD-23154
Change resource tracker dump output from cerr to error log file. Most our QA scenarios save error log files, but cerr output is lost. Dumping to error log file should help investigating issues.
It is not easy to print std::map in gdb and finding leak source from core file is difficult.
_Note: this does not fix jira issue_
> [CBRD-23154] dump resource tracker to error log file

- src/loaddb/load_server_loader.cpp
- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23161
Previously we inserted each record using a `SINGLE_ROW_INSERT` operation. Now we want to insert them using `MULTI_ROW_INSERT` so that maybe we will minimize the logging operations needed for inserting multiple records.
> [CBRD-23161] Change SINGLE_ROW_INSERT to MULTI_ROW_INSERT

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23175
vacuum may be finalized before vacuum data was loaded. check if loaded before trying to consume from block buffer.
> [CBRD-23175] do not consume if vacuum data was not loaded

- src/query/vacuum.c
- src/transaction/log_append.cpp
- src/transaction/log_page_buffer.c
- src/transaction/log_storage.hpp
http://jira.cubrid.org/browse/CBRD-23172
This is a regression of updating vacuum data last blockid when no mvcc ops are executed for a long time.
To fix it, I've done something I wanted to do long ago: produce the vacuum data block when first log record of next block is generated instead of first mvcc log record.
A flag in log header was added to know if current log block needs vacuum. Also updated prior_lsa_next_record_internal and vacuum_recover_lost_block_data.
> [CBRD-23172] produce vacuum data block immediately

- src/storage/heap_file.c
- src/storage/heap_file.h
- src/storage/page_buffer.c
- src/storage/page_buffer.h
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23170
This minimizes the logging required for the loading of the data. Since we are the only ones accessing the pages that we are inserting into, we can just log the entire page instead of every record inserted into this page. For now, I have added some sort of a "hack-ish" method to check if the insert has to log the heap operation by checking if we have `BU_LOCK` and if we cache the fixed page; this is only happening for multi insert operation, for now, but it should be addressed.
> [CBRD-23170] Log entire heap page

- src/loaddb/load_server_loader.cpp
- src/storage/heap_file.c
- src/storage/heap_file.h
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23150
Added the `classname` to `scancache` so that `locator_add_or_remove_index_internal` will not try to get the classname if the `scancache` already has it. This fixes some performance penalties for indexes during loading.
> [CBRD-23150] Added classname to scancache

- src/transaction/lock_table.c
http://jira.cubrid.org/browse/CBRD-23205
NULL + NULL was wrong.
regression of #1816
> [CBRD-23205] fix slip on lock conversion table

- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23210
Do not log postpone if no pages are appended to heap.
> [CBRD-23210] Do not log empty operation

- src/thread/thread_task.hpp
http://jira.cubrid.org/browse/CBRD-23152
Allow callable tasks to be created with move-only F. E.g move-only standard structs: unique_lock, unique_ptr, future, thread.
> [CBRD-23152] Overload Callable tasks constructor for move-only F

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23188
Fixed dirty page flag after reflecting last blockid update.
- added vacuum_init_data_page_with_last_blockid to include repeated code. 
- call vacuum_data_empty_update_last_blockid to correctly reflect last blockid change.
Regression of #1797
> [CBRD-23188] Fix reflecting last blockid into vacuum data page

- src/transaction/log_append.cpp
http://jira.cubrid.org/browse/CBRD-23192
Recovery appends DUMMY_CRASH_RECOVERY log record and it tries to generate a vacuum data block. Since log_Gl.hdr.mvcc_op_log_lsa is immature during recovery, we cannot generate vacuum data blocks at this time.
Vacuum will make sure all blocks are appended after recovery.
Regression of #1812.
> [CBRD-23192] do not generate vacuum data blocks during recovery

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23211
The issue is caused by an untreated new situation - while xvacuum executes cleanup based on current vacuum data, a new log block is generated by log append.
To fix, the block must be consumed before going into final phases of xvacuum.
Regression of #1797
> [CBRD-23211] consume log blocks generated during SA_MODE xvacuum

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23199
Clear info from log_Gl.hdr in first phase and set relevant information only if mvcc op is found after vacuum data last blockid.
Regression of #1797 #1812
> [CBRD-23199] fix how vacuum_recover_lost_block_data changes log_Gl.hdr

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/log_impl.h
- src/transaction/log_lsa.hpp
- src/transaction/log_manager.c
- src/transaction/log_postpone_cache.cpp
- src/transaction/log_postpone_cache.hpp
- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-22755
Extract log postpone cache implementation to separate files and make use of it in all transactions not just for vacuum workers.
**renamings**:
*`struct/enum`*
`vacuum_cache_postpone_entry -> log_postpone_cache::cache_entry`
`vacuum_cache_postpone_status -> log_postpone_cache::cache_status`
*`define`*
`VACUUM_CACHE_POSTPONE_ENTRIES_MAX_COUNT -> log_postpone_cache::MAX_CACHE_ENTRIES`
*`function`*
`vacuum_cache_log_postpone_redo_data -> log_postpone_cache::add_redo_data`
`vacuum_cache_log_postpone_lsa -> log_postpone_cache::add_lsa`
`vacuum_do_postpone_from_cache -> log_postpone_cache::do_postpone`
> [CBRD-22755] extend log postpone cache to all transactions

- src/base/packer.hpp
- unit_tests/packing/test_packing.cpp
http://jira.cubrid.org/browse/CBRD-23213
Fix append_to_buffer_and_pack_all, add unit tests for packing list of OIDs.
Replace size_t with std::size_t
> [CBRD-23213] fix append_to_buffer_and_pack_all

- src/transaction/log_postpone_cache.cpp
http://jira.cubrid.org/browse/CBRD-23221
Do log postpone from disk when a LSA is missing from log postpone cache
> [CBRD-23221] fix log postpone cache

- src/object/authenticate.c
http://jira.cubrid.org/browse/CBRD-22892
Undo change performed with 22152 (#1487).
The change is not required since password of ddl_proxy was removed by #1697.
> [CBRD-22892] remove unnecessary code (not covered by remove password ddl_proxy)

- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23229
Partial backport of 22152.
> [CBRD-23229] Fix statement print for replication when contains host var or parameters

- src/query/vacuum.c
- remove SA_MODE code from vacuum_push_task and move to new function vacuum_sa_run_job
- include perf_tracking in vacuum_sa_run_job
- add claim/retire wroker to vacuum_worker_context_manager and remove function friendship.
> [CBRD-23226] Separate server/sa_mode run task function

- src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-23118
Fix the LSA used to reset log in media crash case. Instead of using current LSA that couldn't be fetched from file, use prev_lsa, which was successfully fetched.
> [CBRD-23118] set media crash resetlog before broken log record

- src/loaddb/load_server_loader.cpp
- src/transaction/locator_sr.c
- src/transaction/locator_sr.h
http://jira.cubrid.org/browse/CBRD-22661
We need to disable the FK check for loaddb. This can easily be done by checking if the insert uses the `BU_LOCK` during its operation. If so, we disable the foreign key check as well.
> [CBRD-22661] Disable FK check for loaddb

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23240
Set is partial block argument to true when calling vacuum_sa_run_job on immature block.
Regression of https://github.com/CUBRID/cubrid/pull/1850
> [CBRD-23240] Correct vacuum_sa_run_job is partial block argument

- src/transaction/log_postpone_cache.cpp
- src/transaction/log_postpone_cache.hpp
- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-23217
Refactor log postpone cache to use extensible memory block as redo data container
> [CBRD-23217] use ext mem block for log postpone cache entry

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23244
vacuum_process_log_block modifies the data entry passed as argument and it was passed a reference directly into vacuum data page.
fix by passing a copy
Regression of #1850
> [CBRD-23244] pass vacuum_process_log_block a data entry copy

- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-23239
fix uninitialized variable in btree_delete_key_from_leaf
RECDES leaf_record;
is not initialized for the case leafrec_pnt->key_len >= 0  ==> delete_helper>is_system_op_started ==false
> [CBRD-23239] fix uninitialized variable in btree delete key from leaf

- src/connection/connection_support.c
- src/query/vacuum.c
- src/storage/catalog_class.c
- src/storage/compactdb_sr.c
- src/storage/heap_file.c
- src/storage/heap_file.h
- src/storage/page_buffer.c
- src/transaction/boot_sr.c
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23201
This PR adds the `classname` to the `hfid` cache. Now, each time an entry is added into the `hfid` cache, the classname will be added as well, in order to retrieve whenever the retrieval of hfid is required. Also, I have merged two similar functions into one since they were doing almost the same thing.
> [CBRD-23201] Added the classname to the hfid cache

- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23246
This is a slip from the previous PR. The locator function uses a default parameter which should be the last one in the prototype, but I called the function with a different order of the parameters. This should fix it.
> [CBRD-23246] Fix foreign key check

- src/executables/unittests_snapshot.c
- src/query/vacuum.c
- src/query/vacuum.h
- src/storage/btree_load.c
- src/transaction/locator_sr.c
- src/transaction/log_append.cpp
- src/transaction/log_impl.h
- src/transaction/log_manager.c
- src/transaction/log_page_buffer.c
- src/transaction/log_storage.hpp
- src/transaction/log_tran_table.c
- src/transaction/mvcc_table.cpp
- src/transaction/mvcc_table.hpp
Rename variables to clarify their meaning. Replace "active" names with "visible". An MVCCID may be inactive (it was committed/aborted), but it is still visible as long as it is seen as active by concurrent transactions. When all concurrent transactions are finished, the MVCCID becomes invisible.
Vacuum for instance has to wait for an MVCCID to become invisible to clean after it. Inactive is not enough.
Patch includes no logic changes.
> [CBRD-23226] rename oldest/newest mvccid variables

- src/query/vacuum.c
Fix default constructor for vacuum_data_entry failing safe-guards.
Regression of #1867
> [CBRD-23226] Fix vacuum_data_entry default constructor

- src/loaddb/load_db_value_converter.cpp
http://jira.cubrid.org/browse/CBRD-23253
We fixed the conversion table for the `DB_C_NUMERIC` in order to use the correct conversion function during load.
> [CBRD-23253] Fix conversion table for conversion functions

- src/loaddb/load_worker_manager.cpp
- src/thread/thread_worker_pool.hpp
http://jira.cubrid.org/browse/CBRD-23259
We increased the number of tasks available so that new tasks are queued and are left waiting for an open thread to be executed on. This will remove the dead time between finishing a task and getting a new one.
> [CBRD-23259] Increase the number of tasks available in the workerpool

- src/transaction/log_impl.h
- src/transaction/log_page_buffer.c
- src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-23118
- is_new_append_page argument was always false. removed it
- made new_append_lsa/new_prev_lsa const pointers. also logpb_fetch_page had to be updated.
> [CBRD-23118] remove log_recovery_resetlog is_new_append_page argument

- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-23264
Since the introduction of the `BU_LOCK` and the removal of the instance locking, the b-tree insert operation during loaddb should not always require and `X_LOCK` on the object. I have updated the check and it translates into: 
`Transaction has an X_LOCK on the object`
- or -
` Transaction has a BU_LOCK on the class`
> [CBRD-23264] Fix locks check during index insert

- src/base/packable_object.hpp
- src/storage/record_descriptor.cpp
- src/storage/record_descriptor.hpp
- src/transaction/client_credentials.cpp
- src/transaction/client_credentials.hpp
http://jira.cubrid.org/browse/CBRD-22879
Backport from ha_replication.
Add offset to signature of packable_object::get_packed_size.
Side changes:
- use std::size_t instead of size_t
- remove undefined templetized contructor of record_descriptor
> [CBRD-22879] Change signature of packable_object::get_packed_size

- src/base/area_alloc.c
- src/object/set_object.c
- src/object/set_object.h
http://jira.cubrid.org/browse/CBRD-23267
Regression of 1876. when area_final is called, the set variables must also be reset.
> [CBRD-23267] Reset set_Ref_area and set_Object_area on area_final

- src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-22679
Blacklist functions returning db_json_type from being accepted function_indexes.
> [CBRD-22679] blacklist functions returning json_types as function_indexes

- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23273
Initialize parser driver on thread when table is passed as command line argument.
In case table is missing, diver is used to get line number in order to log the error.
> [CBRD-23273] loaddb: initialize load driver on thread

- src/loaddb/load_session.cpp
- src/loaddb/load_session.hpp
http://jira.cubrid.org/browse/CBRD-23281
Since `m_last_batch_id` is atomic there is a race condition between notification sent to `m_commit_cond_var` and `m_last_batch_id` assignment. Therefore assignment on `m_last_batch_id` must be protected by `m_commit_mutex`.
> [CBRD-23281] loaddb: fix race condition on batch commit

- src/storage/btree.c
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23279
Fixed incorrect page unfix in case of error during index insert. If the heap succeeds but the index insert fails, the `home_hint_p` watcher is cleared and its replaced by the `scan_cache` watcher. This should correctly clear the page in case it was not. Also, I fixed the locking requirement of the unique index on the delete operation as well, since it was not implemented.
> [CBRD-23279] Fix incorrect page unfix

- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23283
Check if there are any not null columns which are missing from data file, e.g:
schema:
```sql
CREATE TABLE foo;
ALTER TABLE foo ADD COLUMN
si int NOT NULL,
ev int;
```
objects:
```
%class foo (ev)
20
```
In this case column `si` is marked as not null and it is missing from object file, therefore this case must fail with: `Attribute "si" cannot be made NULL.`
> [CBRD-23283] loaddb: check missing not null attributes

- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23291
Attributes are added as definition order as SA_MODE loaddb does.
> [CBRD-23291] attributes are added as definition order

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/lockfree_freelist.hpp
- unit_tests/lockfree/CMakeLists.txt
- unit_tests/lockfree/test_freelist_functional.cpp
- unit_tests/lockfree/test_freelist_functional.hpp
- unit_tests/lockfree/test_main.cpp
http://jira.cubrid.org/browse/CBRD-23266
Implement a class for subset functionality of existing LF_FREELIST. lockfree::freelist provides lock-free claim and retire of preallocated resources, but it does not guarantee no thread is accessing retired resources. This guarantee is to be provided by lock-free transaction system.
Freelist is a template class and can be specialized with any type that has a method with the signature `lockfree::freelist::atomic_link_type &get_freelist_link`, with `using atomic_link_type = std::atomic<T *>`. This link is used by freelist internally. Resources can then be claimed or retired one by one, or retired as a list using freelist link.
There are two tests in the unit test, with 4 threads and 64 threads respectively. The 64 threads test fails, I need to …
> [CBRD-23266] lock-free freelist

- src/base/lockfree_circular_queue.hpp
- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23290
The existing logic of updating oldest unvacuumed in empty data corner case relies on the assumption that if `lockfree_circular_queue::is_empty ()` return false, following consume must succeed. The assumption is wrong, consume does additional checks (e.g. production is in progress) that may fail.
The fix just simplifies to only update oldest unvacuumed when data is not empty. As consequence, the oldest unvacuumed value may lag behind, but keeping an updated value is not critical. It is used for sanity checks that are still possible with a lagging value.
> [CBRD-23290] no oldest unvacuumed update when data is empty

- src/loaddb/load_class_registry.cpp
- src/loaddb/load_class_registry.hpp
http://jira.cubrid.org/browse/CBRD-23295
Make sure that after attribute c-tor is called, the attribute name is not moved and can be used
> [CBRD-23295] loaddb: copy attribute name

- src/base/intl_support.c
- src/base/intl_support.h
- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23306
activate intl_check_input_string on server & update system paratemer.
EDIT: test case still passes, but I checked intl_check_string is executed.
> [CBRD-23306] activate intl_check_input_string on server

- src/loaddb/load_db_value_converter.cpp
- src/loaddb/load_driver.cpp
- src/loaddb/load_driver.hpp
- src/loaddb/load_error_handler.cpp
- src/loaddb/load_error_handler.hpp
- src/loaddb/load_server_loader.cpp
- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23301
When it happened to get an error during loading and the error was filtered, the worker will still insert the record, which proved to be `NULL`. Now, we avoid inserting the records that generated errors that were filtered during the load and we track them so that we generate the correct number of rows that were inserted.
Also, for the QA issue, the error that needs to be filtered to successfully avoid the coercion problem should be `ER_TP_CANT_COERCE -181`.
> [CBRD-23301] Fix error filtering and rows committed message

- src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-23319
Online index workers inherit conn_entry (and session along with it) from thread triggering online index.
Thread context manager is used to pass conn_entry pointer to workers.
> [CBRD-23319] add session to online index workers

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23320
Add return when should not interrupt vacuum master iteration. Add logging to see master daemon interruptions in log file.
May have caused the reported issue.
> [CBRD-23320] fix vacuum_master_task::should_interrupt_iteration return

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23330
- Readjust cursor after first vacuum data update in each iteration.
- Destroy worker pool after master daemon. Daemon pushes task on own thread if pool is destroyed.
Regression of #1915
> [CBRD-23330] Fix vacuum_master_task refactoring regressions

- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/CBRD-23349
Disable safe-guard that does not allow interruptions on system transaction for SA_MODE. It was added to protect against faulty logic of interrupt in server mode. SA_MODE is single-threaded and can reach hit the safeguard. if it is not assigned a transaction.
> [CBRD-23349] Disable interrupt safe-guard in SA_MODE

- src/storage/catalog_class.c
- src/transaction/locator_sr.c
- src/transaction/locator_sr.h
http://jira.cubrid.org/browse/CBRD-23364
loaddb does not need to lock objects to check FK.
> [CBRD-23364] loaddb does not lock objects to check fk constraint

- src/communication/network_interface_sr.c
- src/loaddb/load_session.cpp
- src/loaddb/load_session.hpp
http://jira.cubrid.org/browse/CBRD-23373
if load session completes before workers, its lock is released and workers are left unprotected. load session complete needs to wait for workers.
added a counter to track active tasks; it is incremented when batch is loaded and decremented when batch finished is notified (transactions are committed/aborted before this, so it is a safe point to decrement the counter). only counter decrements are protected by mutex, increments are atomic (increments are done on same thread that will wait for completion).
removed waiting for completion on interrupt request; load batch request will wait instead.
> [CBRD-23373] wait for workers to complete loaddb

- src/connection/server_support.c
- src/loaddb/load_session.cpp
- src/loaddb/load_worker_manager.cpp
- src/loaddb/load_worker_manager.hpp
http://jira.cubrid.org/browse/CBRD-23328
use load worker manager to track registered sessions and interrupt all of them on shutdown.
> [CBRD-23328] shutdown load sessions

- src/communication/network_interface_sr.c
- src/query/query_executor.c
- src/query/serial.c
- src/storage/system_catalog.c
- src/transaction/locator_sr.c
- src/transaction/lock_manager.c
- src/transaction/lock_manager.h
http://jira.cubrid.org/browse/CBRD-23371
Fixed the other functions regarding locks to also take into consideration the loaddb workers.
> [CBRD-23371] Update get lock functions for loaddb workers

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/lock_free.c
- src/base/lock_free.h
- src/executables/unittests_lf.c
- src/thread/thread_entry.cpp
- src/thread/thread_entry.hpp
- src/thread/thread_lockfree_hash_map.cpp
- src/thread/thread_lockfree_hash_map.hpp
http://jira.cubrid.org/browse/CBRD-23339
Wrap existing lock-free hash functionality into C++ interface that can be easily reused for refactorized transaction system.
The interface is templatized by key and node type:
```c
template <class Key, class T>
hash_map
{
class iterator;  // to iterate map
init/destroy // initializes/destroys hash & freelist
// operations on keys/nodes
find, find_or_insert, insert, insert_given, erase, erase_locked
// after finishing reading from/writing to node
unlock (T);   // end transaction or unlock mutex
clear ();  // remove all
};
```
**thread_lockfree_hash_map**
A new class was added - cubthread::lockfree_hashmap - with the purpose of converting thread entry into lock-free transaction entry before calling the corresponding hashmap function.
Until …
> [CBRD-23339] C++ interface for existing lock-free hash

- src/loaddb/load_db_value_converter.cpp
http://jira.cubrid.org/browse/CBRD-23300
Fixed the collation and codeset for string type values in loaddb. The old one would use the system collation which is not correct.
> [CBRD-23300] Fixed codeset and collation for string types during load

- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23302
Schema definitions with shared attributes might confuse normal attributes def_orders. Info about attributes from class_repr might look like this (if there is a shared attribute): 
shared_attrib[:].def_order = [1]
attrib[:].def_order = [2, 0]
This patch normalizes def_order from [2, 0] to [1, 0]
> [CBRD-23302] Normalize def_order of attributes

- src/loaddb/load_common.cpp
- src/loaddb/load_db_value_converter.cpp
http://jira.cubrid.org/browse/CBRD-23350
```sql
create table t (s string);
```
object file:
```
%class t (s)
'
aaa
bbb
ccc
'
```
Take into account when splitting object file into batches cases when new line is part of data
> [CBRD-23350] loaddb: check for matching single quotes on split

- src/parser/parse_tree.h
- src/parser/parse_tree_cl.c
- src/parser/parser_support.c
- src/parser/type_checking.c
- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23310
checksumdb utility uses schema_def() function which is const folded during parser.
However, the logic of checksumdb requires that the statement string is replicated using original text.
> [CBRD-23310] use original expression print for folded expressions in context of SBR replication

- src/loaddb/load_db_value_converter.cpp
http://jira.cubrid.org/browse/CBRD-23376
Refactor loaddb generic to_char.. functions to use common code.
Fix for trimming trailing spaces : use codeset dependent code.
> [CBRD-23376] refactor loaddb generic to_char.. functions

- src/loaddb/load_session.cpp
- src/loaddb/load_session.hpp
http://jira.cubrid.org/browse/CBRD-23378
Decrements, failure and setting last batch id should always be done under mutex and they should always notify waiting threads.
> [CBRD-23378] fix wait_for_complete

- cubrid/CMakeLists.txt
http://jira.cubrid.org/browse/CBRD-23377
fix unit test buiding for windows
> [CBRD-23377] add FLEX_INCLUDE_DIRS to cubrid-win-lib

- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23379
Attrib_order[i] is already the i-th idx in the or_attributes[:].def_order array. Before this patch was wrongly thought that attrib_order is a normalization of or_attributes[:].def_order (a index swapping step would be required for this). Fix usage of attrib_order.
> [CBRD-23379] Fix attribute gathering

- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23378
an early out of task execution doesn't notify session it is ended.
to avoid these kind of slips, task keeps a flag that tracks notification and forces notification on destruction. session is notified even if task is not executed for some reason.
> [CBRD-23378] always notify session when task is done

- src/executables/unload_schema.c
http://jira.cubrid.org/browse/CBRD-23380
http://jira.cubrid.org/browse/CBRD-23383
Fix unload of the schema when string contains % character
> [CBRD-23380] unloaddb: fix schema extract

- src/loaddb/load_common.hpp
- src/loaddb/load_sa_loader.cpp
- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23251
Added the ignore classes beginning with `glo_` on the server-side. This is related to old system tables which should be ignored if the unload is done on an old CUBRID version and the load is done on a newer one.
> [CBRD-23251] Added glo_* classes as ignored on server side

- src/loaddb/load_common.cpp
- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23398
Fixed the ignore classes mechanism on server by disabling case sensitivity for class names.
> [CBRD-23398] Fix ignore classes to be case insensitive

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23397
If xvacuum starts with empty data, it missed consuming vacuum_Block_data_buffer.
Fix by making sure vacuum_Block_data_buffer is consumed before and after vacuum data is processed.
> [CBRD-23397] xvacuum always consume vacuum_Block_data_buffer

- cubrid/CMakeLists.txt
- src/connection/server_support.c
- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23384
The crash is generated by log block being pushed after vacuum is finalized. Keep vacuum master active until no logging is possible.
This required separation of stopping vacuum workers and vacuum master. Also added mutex/conditional variable to make shutdown sequence safe, but making sure master is notified before destroying workers.
> [CBRD-23384] fix vacuum shutdown sequence

- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23407
Vacuum master daemon needs to be stopped if boot fails before exiting boot_restart_server.
> [CBRD-23407] stop vacuum master daemon on failed boot

- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23414
Protect logtb_free_tran_index call by m_commit_mutex. Otherwise, the tran_index may be reassigned before transaction end is registered by sesson.
> [CBRD-23414] [loaddb] free tran_index when registering tran end

- src/storage/heap_file.c
- src/storage/heap_file.h
- src/transaction/log_postpone_cache.cpp
- src/transaction/log_postpone_cache.hpp
http://jira.cubrid.org/browse/CBRD-23415
Bad computation of total_size of redo data invalidates postpone cache, affecting loaddb performance.
Changes:
- fix total_size computation
- pass heap_pages_array reference to heap_log_postpone_heap_append_pages (instead of copy)
- free buffer if its size exceeds BUFFER_RESET_SIZE (1k)
- fix compile warning (case from size_t to int)
> [CBRD-23415] fix postpone cache bad invalidation

- src/object/schema_manager.c
- src/object/transform_cl.c
http://jira.cubrid.org/browse/CBRD-23168
Maybe is better to move ER_OBJ_CANT_ASSIGN_OID error inside of locator_assign_permanent_oid.
> [CBRD-23168] Returns error if permanent oid was not assigned

- src/loaddb/load_server_loader.cpp
- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23410
If a classname which has a too long name is given as the `-t` argument of loaddb, an error is set so that it will not try to install the said class.
> [CBRD-23410] Added error when a too long classname is given as argument to loaddb

- src/object/schema_manager.c
http://jira.cubrid.org/browse/CBRD-23419
This is a legacy SA_MODE issue.
Once SA finalized wm and restarts, accessing `oid_Root_class_oid` is free-memory-read.
> [CBRD-23419] oid_Root_class_oid should remain pointing to oid_Root_class

- src/base/lockfree_bitmap.cpp
http://jira.cubrid.org/browse/CBRD-23261
Fix to decrement used entry count on free intead of incrementing. Fixes memory being quickly consumed by area_alloc.
Replace compare_exchange_strong with compare_exchange_weak in loops.
> [CBRD-23261] fix bitmap entry free

- src/base/system_parameter.c
- src/base/system_parameter.h
- src/thread/thread_lockfree_hash_map.cpp
- src/thread/thread_lockfree_hash_map.hpp
- src/thread/thread_manager.hpp
http://jira.cubrid.org/browse/CBRD-23339
Added system parameter to switch between lockfree hash implementation.
A common init wraps init_as_new/init_as_old; the parameter will decide which functions is called.
> [CBRD-23339] switch between lockfree hash implementations

- src/loaddb/load_db_value_converter.cpp
http://jira.cubrid.org/browse/CBRD-23412
In case of a not null attribute defined in the schema, the correct error which needs to be thrown if we load a null value should be `ER_OBJ_ATTRIBUTE_CANT_BE_NULL`. This PR will fix it.
> [CBRD-23412] Fix error in case of not null attribute

- src/loaddb/load_server_loader.cpp
- src/loaddb/load_server_loader.hpp
http://jira.cubrid.org/browse/CBRD-23411
Use the same idea to store attributes and classnames as lowercase strings inside the class registry.
> [CBRD-23411] Apply lowercase mechanism to classname and attributes as well

- src/storage/btree_load.c
- src/transaction/lock_manager.c
http://jira.cubrid.org/browse/CBRD-23418
On shutdown, lock upgrade is abandoned and index creation is aborted/rollbacked. Concurrent transactions that accessed the index may access again to rollback their own work.
Fix by forcing lock upgrade even if shutdown forces timeout.
> [CBRD-23418] fix dropping online index on shutdown

- src/base/lock_free.h
- src/base/lockfree_hashmap.hpp
- src/base/lockfree_transaction_system.cpp
- src/storage/slotted_page.c
- src/storage/slotted_page.h
- src/thread/thread_lockfree_hash_map.hpp
- src/thread/thread_manager.cpp
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23421
- replace spage_saving_freelist/spage_saving_ht with spage_Saving_hashmap
- remove return error code from spage_boot
- fix cubthread::lockfree_hashmap::destroy uninitialized & cubthread::lockfree_hashmap::init_as_old
- add start_tran/end_tran functions to all hashmaps
- add one more transaction to thread manager's lock-free transaction system to account for main thread
> [CBRD-23421] replace slotted page saving hash table

- src/base/packer.hpp
http://jira.cubrid.org/browse/CBRD-23426
- fix assert when checking current pointer being between start and end
- change packer start pointer when memory block is reallocated
> [CBRD-23426] packer: fix append to buffer

- src/transaction/boot_sr.c
- src/transaction/log_manager.c
- src/transaction/log_manager.h
http://jira.cubrid.org/browse/CBRD-23424
HA delay info daemon adds log entries and must be stopped before vacuum master on shutdown.
On failed boot, enforcing this order is not necessary because the daemon does nothing.
> [CBRD-23424] stop HA delay info daemon before vacuum master

- src/storage/slotted_page.c
- src/transaction/lock_manager.c
- src/transaction/lock_manager.h
http://jira.cubrid.org/browse/CBRD-23421
Add constructor and destructor to properly initialize and destroy mutex when allocated and deallocated by lockfree::freelist.
> [CBRD-23421] construct/destruct lk_res and spage_save_head

- src/base/lockfree_hashmap.hpp
- src/storage/double_write_buffer.c
http://jira.cubrid.org/browse/CBRD-23421
- replace double write buffer hash table
- check edesc.f_init/f_uninit not null before invoking them
> [CBRD-23421] replace dwb hash table

- src/transaction/log_append.cpp
http://jira.cubrid.org/browse/CBRD-23430
A very large log record that spans over multiple blocks breaks the safe-guard saying current blockid must be one less than the blockid of next log record. Update to consider this case.
```
log_header = {
prev_tranlsa = {
pageid = 2081,
offset = 4128
},
back_lsa = {
pageid = 2081,
offset = 4128
},
forw_lsa = {
pageid = -1,
offset = -1
},
trid = 24,
type = LOG_UNDO_DATA
},
start_lsa = {
pageid = 3709,
offset = 2504
},
```
> [CBRD-23430] update prior_lsa_next_record_internal safe-guard

- src/query/filter_pred_cache.c
- src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-21800
move iterator constructors after checking if xasl cache / filter predicate cache are enabled to avoid.
> [CBRD-21800] no iterator on uninitialized hashmap

- src/base/lockfree_hashmap.hpp
http://jira.cubrid.org/browse/CBRD-23432
old lock-free implementation on SA_MODE disables mutex functions. Migrating this to new implementation is necessary
> [CBRD-23432] dont use mutexes in SA_MODE

- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23433
force generating a new set of statistics when fetching stats finds nothing but session is completed.
hint: it seems no batches are executed (m_last_batch_id == m_max_batch_id == 0).
to be properly handled and fixed with patch that unifies load/fetch requests.
> [CBRD-23433] [loaddb] quick fix for missing completed statistic

- src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-22741
when flush daemon thread finds no victim candidates, we do many safe-guard checks to see if it there was a fault in searching victim candidates or if it is normal.
one condition is that if list has count_vict_cand greater than zero, then it was expected to find a victim in the list. however, between searching the list and checking safe-guard, new candidates may appear. the condition is not stable and sometimes provides false alarms. fix by removing.
> [CBRD-22741] remove unstable data flush safe-guard

- src/loaddb/load_sa_loader.cpp
- src/transaction/locator_cl.c
http://jira.cubrid.org/browse/CBRD-23437
This includes two fixes:
- flush error was not propagated
- SA loaddb has PRM_ID_LOADDB_FLUSH_INTERVAL whose default value is 1000. deactivate the param when shorter periodic commit interval is given.
> [CBRD-23437] flush error was not properly propagated

- src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-22714
Recursive_part's status was never set to something different than XASL_INITIALIZED when recursive_part was prunned, causing a leak during qexec_clear_xasl recursive_part clearing.
> [CBRD-22714] Fix prunned recursive cte execution clearing

- src/loaddb/load_db.c
http://jira.cubrid.org/browse/CBRD-23438
Fix order between fetching stats and pushing a batch
> [CBRD-23438] loaddb: fix order between fetching stats and pushing a batch

- src/query/filter_pred_cache.c
- src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-21800
If parameter for xasl/filter cache size is 1, block size was set to 0. Fix by forcing minimum size of 1.
> [CBRD-21800] avoid zero-sized hashmap freelist block

- src/base/packer.cpp
- src/base/packer.hpp
- src/loaddb/load_common.cpp
http://jira.cubrid.org/browse/CBRD-23434
Fix packing of a string containing byte zero.
Loader CS : open objects file with binary mode.
> [CBRD-23434] Fix packing a string containing byte zero

- src/executables/unload_schema.c
http://jira.cubrid.org/browse/CBRD-23441
legacy bug.
> [CBRD-23441] unload missed order of PK/unique key column

- src/query/query_evaluator.c
- src/query/query_evaluator.h
- src/query/scan_manager.c
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-20008
This is a legacy issue.
To evaluate a particular key filter (oracle_style_empty_string) is neither useful nor correct.
> [CBRD-20008] remove useless extra key filter evaluation

- src/communication/network.h
- src/communication/network_cl.c
- src/communication/network_interface_cl.c
- src/communication/network_interface_cl.h
- src/communication/network_interface_sr.c
- src/communication/network_interface_sr.h
- src/communication/network_sr.c
- src/loaddb/load_db.c
- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23286
Statistics were not correctly updated and reported on the server side. With this PR, after a session completes, the client will send a request to update the class statistics, and then fetch the new messages as well to print them to the user.
> [CBRD-23286] Fixed class statistics report and update

- src/compat/db_value_printer.cpp
- src/compat/db_value_printer.hpp
- src/compat/dbtype.h
- src/compat/dbtype_function.h
- src/object/work_space.h
http://jira.cubrid.org/browse/CBRD-23452
remove unused struct db_collection from engine code to avoid confusions; it is kept only as a definition in API headers.
> [CBRD-23452] remove unused struct db_collection

- src/cci/cas_cci.c
- src/cci/cci_common.h
- src/cci/cci_log.cpp
- src/cci/cci_map.cpp
- src/cci/cci_map.h
- src/cci/cci_mutex.h
- src/cci/cci_net_buf.h
- src/cci/cci_network.c
- src/cci/cci_query_execute.c
- src/cci/cci_t_set.c
- src/cci/cci_util.c
Fix following warning:
```
In file included from /usr/include/c++/9.2.0/ext/hash_map:60,
from ./cubrid/src/cci/cci_map.cpp:43:
/usr/include/c++/9.2.0/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
32 | #warning
```
> [CBRD-23444] fix cci map warning

- src/executables/file_hash.c
http://jira.cubrid.org/browse/CBRD-23454
Don't use preallocated buffer when using tmpnam.
> [CBRD-23454] file_hash : change to no use preallocated buffer for tmpnam

- src/loaddb/load_db_value_converter.cpp
- src/loaddb/load_db_value_converter.hpp
- src/loaddb/load_server_loader.cpp
http://jira.cubrid.org/browse/CBRD-23294
Add string size to signature of conversion functions.
This fix aims for loaddb (server side) to accept strings containing zero byte in the middle.
> [CBRD-23294] Add string size to signature of conversion functions

- src/object/object_primitive.c
http://jira.cubrid.org/browse/CBRD-23461
Fix `mr_cmpval_string, mr_cmpval_char` and `mr_cmpval_varnchar` comparison functions when codeset for right string is not taken into account
> [CBRD-23461] fix string codeset comparison

- CMakeLists.txt
(Warning: "format not a string literal and no format arguments")
Disable, since we could not find a nice solution:
snprintf calls can not be fixed by gcc's `__attribute__(__format__(__snprintf__(....)))` snprintfs are not supported.
printf (msgcat, args...) are difficult to fix.
Switching to a formating library (e.g. fmt) instead of raw printfs is a possiblity to fix such problems.
> [CBRD-23444] suppress -Wformat-security

- src/parser/parse_tree.c
- src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-22753
Fix slip of #2053 . Json table column info dbvals are shallow copied by parser_copy_tree, and the original tree loses its reference when the tree-copy is freed.
> [CBRD-22753] fix clearing after parser_copy_tree

- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23458
Make no_backslash_escapes also as server parameter.
> [CBRD-23458] fix client-PRM accessed on server

- src/base/unicode_support.c
- src/base/unicode_support.h
- src/broker/cas_execute.c
- src/compat/dbtype.h
- src/compat/dbtype_function.h
- src/compat/dbtype_function.i
- src/object/object_domain.c
- src/object/object_primitive.c
- src/object/object_representation.c
- src/parser/parse_dbi.c
- src/parser/type_checking.c
Use `const char *` for `db_make_enumeration, db_get_enum_string` and `DB_GET_ENUM_ELEM_STRING`
Part 2 of #1656
> [CBRD-23444] const db enumeration

- src/thread/thread_looper.cpp
http://jira.cubrid.org/browse/CBRD-23462
It is not a fix for the issue but while investigating I observed that m_wait_type was not the one expected. The reason is that copy constructor does not copy it.
> [CBRD-23462] Copy wait type in looper copy constructor

- src/broker/cas_execute.c
- src/cm_common/cm_dep_tasks.c
- src/compat/dbtype_function.h
- src/compat/dbtype_function.i
- src/executables/csql_result_format.c
- src/object/object_primitive.c
- src/query/string_opfunc.c
Change `db_get_char` and `db_get_nchar` functions signature to return `const char *`
Part 4 of #1656
> [CBRD-23444] const db_get_char and db_get_nchar

- src/storage/file_io.c
- src/storage/file_io.h
- src/transaction/log_writer.c
http://jira.cubrid.org/browse/CBRD-23467
Copylogdb : delete entire copied log active volume if header page appears corrupted but is just formatted.
> [CBRD-23467] copylogdb : delete log active volume if header is just formatted (corrupted)

- src/communication/network_interface_sr.c
- src/communication/network_interface_sr.h
- src/communication/network_sr.c
- src/session/session.c
- src/session/session.h
http://jira.cubrid.org/browse/CBRD-23468
Stop (and wait for stop) attached threads (now only those attached to load session) to a session when connection is terminated.
session_state_uninit  : move stop code at start of function; attached load threads may still access session data before stopping them: better to stop them before destroying data.
> [CBRD-23468] Stop attached threads (load session) when connection is terminated

- src/loaddb/load_class_registry.cpp
http://jira.cubrid.org/browse/CBRD-23465
Whenever an ignored class was added to the class registry, it was added without locking the mutex over the map. Which means that some thread could overwrite another entry in the map if both of them arrived at the same time. THis PR should fix it.
> [CBRD-23465] Fix register class call without mutex

- src/broker/broker_admin_pub.c
http://jira.cubrid.org/browse/CBRD-23474
Return error when long path socket length (regression of #2062).
> [CBRD-23474] Fix regression of #2062

- src/transaction/log_recovery.c
http://jira.cubrid.org/browse/CBRD-23476
Do not increment topops.last value during checkpoint analysis if it was already incremented. The log record of start atomic or start postpone may be found by analysis before checkpoint.
It was not reproduced before check pointing system workers because active workers rarely need postpone during sysops.
> [CBRD-23476] fix topops.last recovery

- src/loaddb/load_common.hpp
- src/loaddb/load_db.c
- src/loaddb/load_driver.cpp
- src/loaddb/load_driver.hpp
- src/loaddb/load_sa_loader.cpp
- src/loaddb/load_sa_loader.hpp
- src/loaddb/load_server_loader.cpp
- src/loaddb/load_server_loader.hpp
- src/loaddb/load_session.cpp
- src/loaddb/load_session.hpp
http://jira.cubrid.org/browse/CBRD-23453
* move `driver::m_lines_inserted` member to `object_loader::get_rows_number` interface as a virtual function
* remove duplicate LOADDB_MSG_COMMITTED_INSTANCES message log from load_db.c
* fix object syntax checking message logging
> [CBRD-23453] [loaddb] fix periodic commit verbose messages

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23477
A very big log record broke vacuum_consume_buffer_log_blocks trying to force updates on last vacuum data blockid when log advances without mvcc ops.
To fix `log_Gl.hdr.does_block_need_vacuum` must be considered. For a safe check, reading it and log_Gl.prior_info.prior_lsa must hold prior mutex.
> [CBRD-23477] fix update last blockid after big log record

- src/storage/page_buffer.c
- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-22741
There is no stable safe-guard that can tell for sure that flushing nothing is bad or not. Reported case has nothing flushed because all candidates were fixed at the time of check.
Removed safe-guard and replaced with logging that can be activated if flush issues are observed.
> [CBRD-22741] Replace unstable data flush safe-guard with logging

- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23479
If heap_get_class_info_from_record fails, remove entry from hash and free allocated resources.
> [CBRD-23479] remove entry if heap_cache_class_info is interrupted

- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-21390
Adds new class name to modified list, in case of rename.
This corrects abort issue. Thus SAVEPOINT LSA of LOCATOR_CLASSNAME_ENTRY is set for the new class. This allows to correctly build the entries history which are used in case of abort.
> [CBRD-21390] Adds new class to modified class list in case of rename

- src/query/query_aggregate.cpp
http://jira.cubrid.org/browse/CBRD-23514
qdata_finalize_aggregate_list leaks list files if there are multiple aggregates and an error occurs before finalizing last aggregate.
> [CBRD-23514] Destroy all aggregate list files in case of error

- src/transaction/locator.c
http://jira.cubrid.org/browse/CBRD-23518
It is not a real UMW.
valgrind complains the aligned copy area is not set.
> [CBRD-23518] clear padded area to make valgrind silent

- src/loaddb/load_common.hpp
- src/loaddb/load_error_handler.hpp
http://jira.cubrid.org/browse/CBRD-23505
It seems that `snprintf` was not properly used as the windows version would not use its correct implementation, leading to bad results. Fixed it by including the `porting.h` header.
> [CBRD-23505] Fixed bad message reporting in windows in loaddb

- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-22941
`db_get_user_name` returns NULL when connection is not set.
It is a regression of #1560
> [CBRD-22941] user name of client credentials was missing

- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23528
Fix how heap get errors are treated by locator_update_force in the least intrusive way - acknowledge interrupt error.
> [CBRD-23528] locator_update_force accept heap get interrupt

- src/executables/util_cs.c
http://jira.cubrid.org/browse/CBRD-23522
Set system parameter for error log file in copylogdb process instead of default cub_client.err.
> [CBRD-23522] Set system parameter for error log file in copylogdb process

- src/transaction/log_writer.c
http://jira.cubrid.org/browse/CBRD-23527
Prevent copylogdb to raise corrupted log page severity error when page is just formatted.
> [CBRD-23527] Fix copylogdb corrupted log page severity error

- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23532
fix regression of #2108
> [CBRD-23532] fix memory free of db_string_pad

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23531
Change vacuum_update_keep_from_log_pageid to be more conservative. Since vacuum_Data last blockid now closely trails end of log even if there are no MVCC operations, we can afford to set keep_from_log_pageid immediately after last blockid when vacuum data is empty.
Previous code missed one corner case:
- vacuum data is empty
- "current block" is split by last archive and active log
- there are no MVCC operations in current block when archives are removed. that means vacuum_Data.keep_from_log_pageid is null and all archives are considered safe to remove.
- an MVCC operation is logged in the active part of current block
- logpb_backup checks all archives required for vacuum are present. however, current block's first part is now missing and check …
> [CBRD-23531] Fix vacuum_update_keep_from_log_pageid corner case

- src/query/vacuum.c
http://jira.cubrid.org/browse/CBRD-23534
vacuum_Data_load is initialized by vacuum_data_load_and_recover. however, after an xvacuum session, it can become outdated.
Fix by updating vacuum_Data_load on vacuum_data_unload_first_and_last_page.
> [CBRD-23534] fix vacuum_Data_load for reload

- src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-23537
missed to free alloced recdes area for some error cases.
> [CBRD-23537] fix memory leak of recdes

- src/compat/db_json.cpp
http://jira.cubrid.org/browse/CBRD-23535
Quick fix: treat json uint64 as double since we do not have an unsigned bigint type.
> [CBRD-23535] Treat json uint64 as double

- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23519
Calling heap_hfid_cache_get on a dropped class is possible. For instance, client may save dangling OID's. However, it fails getting class record.
Next heap create that recycles class OID finds the entry added by heap_hfid_cache_get, although it is not mature.
Fixes:
- Remove entry from heap_hfid_cache_get if an error occurs while trying to obtain info.
- Expect concurrent access on hash entry during heap_cache_class_info call
> [CBRD-23519] remove cache entry if heap_hfid_cache_get fails

- src/compat/db_json.cpp
- src/compat/db_json.hpp
- src/query/arithmetic.c
- src/query/scan_json_table.cpp
- src/xasl/access_json_table.cpp
http://jira.cubrid.org/browse/CBRD-23539
Replace all unchecked db_get_string with db_value_to_json_key and db_value_json_path. Update db_value_to_json_path and db_json_extract_document_from_path signatures to use strings instead of `const char *`.
> [CBRD-23539] safe conversions to json key/path

- src/communication/network_sr.c
- src/connection/connection_defs.h
- src/connection/connection_support.c
- src/connection/server_support.c
http://jira.cubrid.org/browse/CBRD-23546
Connection may be closed between pushing a request from client to worker pool and actually running it. Reusing connection resets the session_p field of CSS_CONN_ENTRY. If the thread that runs this lost request is preempted right when connection is reused, it is possible to generate reported crash.
Fix by tracking pending requests (pushed but not yet executed) and waiting for all of them to be accounted before closing connection.
> [CBRD-23546] wait pending request to close connection

- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-23544
Force tp_value_compare_with_error call if keys are strings with different collation.
> [CBRD-23544] btree_compare_key set error for different collation

- src/connection/connection_defs.h
- src/connection/connection_sr.c
- src/connection/connection_support.c
http://jira.cubrid.org/browse/CBRD-23555
fix regression of #2134 by initializing `pending_request_count`.
> [CBRD-23555] fix UMR of pending_request_count

- src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-23149
Remove annoying safe-guard. It often falsely flags because of errors leaked from other operations.
> [CBRD-23149] file_create: remove no error safe-guard

- src/query/arithmetic.c
- src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-23553
- Return null if any JSON_EXTRACT argument is null
- Return null if path argument of JSON_KEYS is null
- small refactoring by using is_any_arg_null in all json functions where it is applicable
> [CBRD-23553] return null on null json path argument

- src/storage/file_io.c
http://jira.cubrid.org/browse/CBRD-23548
Severity of ER_IO_SYNC as fatal error.
> [CBRD-23548] Severity of ER_IO_SYNC as fatal error.

- src/query/serial.c
http://jira.cubrid.org/browse/CBRD-23530
serial_load_attribute_info_of_db_serial "leaks" scan cache (including its page watcher) if heap_get_class_record returns with error (interrupt in this case).
since serial_get_attrid doesn't propagate error, it gets called again, with the same stack, and a new scan cache is initialized at the very same stack address; after second heap_get_class_record, it finds the inconsistency (the leaked page watcher now has next watcher; it was expected to be empty).
fix scan cache leak and add error propagation to serial_get_attrid.
> [CBRD-23530] fix serial handling interrupt error

- src/query/query_executor.c
- src/storage/catalog_class.c
- src/storage/heap_file.c
- src/storage/system_catalog.c
- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23559
#2147 leads to me these bad usages. 
Fixes are:
* bad free: qexec_execute_build_indexes, qexec_execute_build_columns
* leak: catcls_compile_catalog_classes, heap_class_get_partition_info, catalog_fixup_missing_disk_representation(unused)
> [CBRD-23559] fix bad scancache usages

- src/loaddb/load_sa_loader.cpp
http://jira.cubrid.org/browse/CBRD-23563
Fixed slip of `SA_MODE` error reporting when `-t` parameter is enabled. If any errors occur before the parsing of the object file has started, we should never report the error line since is not concise.
> [CBRD-23563] Fix slip of SA_MODE when parsing has not started yet

- src/loaddb/load_error_handler.hpp
- src/loaddb/load_scanner.hpp
http://jira.cubrid.org/browse/CBRD-23560
Fixed a bug regarding `LexerError`. Since the approach is to raise an error and then try to fail the session if `--data-file-check-only` is not enabled, reporting the error would use the driver line, instead of the scanner line. This patch will fix it and use the scanner line instead.
> [CBRD-23560] Fix slip of LexerError

- src/transaction/locator_sr.c
http://jira.cubrid.org/browse/CBRD-23095
When we compute the size of the records that might fit in a page during `locator_multi_insert`, we should use the aligned size of the record to be sure that subsequent insert operations are successful.
> [CBRD-23095] Use the aligned size of the record

- src/compat/db.h
- src/compat/db_vdb.c
- src/loaddb/load_db.c
http://jira.cubrid.org/browse/CBRD-23566
Verbose messages were reported wrongly using the line from the parser. We instead use the line of the last compiled statement to print messages now.
This was a legacy bug.
> [CBRD-23566] Fix bad line error report during schema load

- src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-22860
Allow derived with entity spec
(Fixes a regression of #541)
> [CBRD-22860] Allow derived with entity spec

- src/parser/func_type.cpp
- src/storage/btree_load.c
http://jira.cubrid.org/browse/CBRD-23568
Issue is caused by an inconsistency between the result of db_json_quote function and parent regu variable domain. Reguvar domain is generated based on node.data_type.type_enum. In a special case like `JSON_QUOTE ( CAST ( int_col as CHAR(10) ) )`, node.type_enum is converted from char to varchar, precision is set floating preicision (-1), but node.data_type.type_enum remains char. The regu variable domain char and, in some cases, it is used as expected domain. In other cases, expected domain is based on node.type_enum.
A simple repro for this inconsistency (crash) is the next scenario:
```sql
CREATE TABLE t (a INT);
INSERT INTO t VALUES (1);
SELECT JSON_QUOTE (CAST (a as CHAR(10)));
```
Fixes:
- set variable string type in both node.type_enum and …
> [CBRD-23568] correct return type as varchar

- src/broker/broker_shm.c
- src/broker/cas_network.c
http://jira.cubrid.org/browse/CBRD-23581
probably `gethostname` dead-ended `ENAMETOOLONG`.
> [CBRD-23581] fix bad usages of gethostname

- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23588
The life cycle on an lockfree hash table entry is:
alloc, init/uninit[, init/uninit], free.
Classname needs to be freed on uninit to avoid leaks.
> [CBRD-23588] free classname on heap_Hfid_table entry uninit

- src/cci/cci_util.c
http://jira.cubrid.org/browse/CBRD-22793
fix invalid CCI URL succeeded. 
regex_match should be used which returns true when the entire URL has been matched.
regression of #1509
> [CBRD-22793] fix regression of #1509

- CMakeLists.txt
- build.sh
http://jira.cubrid.org/browse/CBRD-23601
As CUBRID bumping up major build number for damson milestone, CUBIRD_EXTRA_VERSION needs to be initialized to zero.
CUBRID's versioning rule is as follow;
```
${CUBRID_MAJOR_VERSION}.${CUBRID_MINOR_VERSION}.${CUBRID_PATCH_VERSION}.${CUBRID_EXTRA_VERSION}${CUBRID_HASH_TAG}
```
> [CBRD-23601] Initialize the extra version number into zero

- CMakeLists.txt
- build.sh
http://jira.cubrid.org/browse/CBRD-23601
As CUBRID bumping up major build number for damson milestone, CUBIRD_EXTRA_VERSION needs to be initialized to zero. Because CUBRID_EXTRA_VERSION has to be 4-digits, awk command is added to both build shell and CMake command.
CUBRID's versioning rule is as follow;
`${CUBRID_MAJOR_VERSION}.${CUBRID_MINOR_VERSION}.${CUBRID_PATCH_VERSION}.${CUBRID_EXTRA_VERSION}${CUBRID_HASH_TAG}`
> [CBRD-23601] Initialize the extra version number

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-23600
When the CASE expressions are used recursively and values specified in the THEN clause are numeric and integer types order repeatedly, one of the numeric values is rounded up unexpectedly.
this bug causes because the arg1 pointer variable for PT_NODE is incorrectly re-used at the part of checking the next case clause. please see the changes in this PR. To make a common data type of expression, pt_upd_domain_info () is invoked with the possibly wrong assigned arg1. As a consequence, the data type is going to be updated incorrect precision and scale.
It fixes to keep the arg1 from being re-used incorrectly.
> [CBRD-23600] Unexpected rounding up a numeric value when the case expressions are used recursively

- src/parser/parser_support.c
http://jira.cubrid.org/browse/CBRD-23599
To check whether the select list contains an analytic function, pt_is_analytic_node () is invoked in traversing for the select list nodes. In order not to traverse inside of subquery, it changes traversal behavior into PT_LIST_WALK. But the traversal behavior has to be restored from the next node.
> [CBRD-23599] Error occurs if select list has in the order of an scalar subquery and expression which include an analytic function

- src/optimizer/query_graph.c
- src/parser/parse_tree_cl.c
- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-22925
There are two problems.
1. The RHS of the 'IN' operator is not converted to the range (= or) format because of rewriting RHS's enum type to PT_TYPE_NONE.
The reason for changing to PT_TYPE_NONE is to recheck the type for the function set in pt_semantic_type ().
Use the function_info.is_type_checked variable to remove side-effects caused by changing to PT_TYPE_NONE.
2. Two range list index scans(range(1= or 2=), in (1,2) ) are selected as index keys.
'RANGE LIST' flag is set for 'IN' OP to avoid duplication of 'RANGE LIST' scan.
> [CBRD-22925] An error occurs when there are two 'IN' operators and rewriting predicate to reduce the equality term.

- contrib/scripts/ha/ha_make_slavedb.sh
http://jira.cubrid.org/browse/CBRD-23603
When the ha_make_slavedb.sh script runs, it should delete intended database exactly in copy_backup_db_from_target () function. so I added the -w option to the grep command to distinguish between two databases with the same prefix, like demodb and demodb2.
> [CBRD-23603] The ha_make_slavedb.sh script should delete intended database exactly.

- src/connection/heartbeat.c
- src/connection/heartbeat.h
- src/executables/master_heartbeat.c
- src/executables/master_heartbeat.h
http://jira.cubrid.org/browse/CBRD-23604
The cub_master process has information about copylogdb and applylogdb including copied log file path. when they terminate abnormally, the cub_master process make them restart using this information. however, the restart of them is failed if the length of copied log file path is over 64. the reason is that the size of array containing the copied log file path is limited to 64 by the HB_MAX_SZ_PROC_ARGV macro.
> [CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64.

- src/connection/heartbeat.c
- src/connection/heartbeat.h
- src/executables/master_heartbeat.c
- src/executables/master_heartbeat.h
Reverts CUBRID/cubrid#2191
reason: missing issue tracking linker '[CBRD-23604]'
> Revert "[CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64."

- src/query/string_opfunc.c
- src/query/string_regex.cpp
- src/query/string_regex.hpp
http://jira.cubrid.org/browse/CBRD-23612
This PR is to fix regression of #2186.
- moved getting a compiled pattern and regex object at the beginning of each function to avoid NULL is assigned wrongly when parameter checking is failed.
- fixed memory leak when regex object is created with reference std::string.
- slip of indentation inside of `*INDENT-OFF*` comment.
> [CBRD-23612] Fix memory leak of compiled regex and pattern

- src/query/string_regex.cpp
http://jira.cubrid.org/browse/CBRD-22783
This PR fixed the following
1. Matching for char range on case insensitive flag doesn't work well on Windows 
`   e.g) SELECT REGEXP_REPLACE ("Aa", "[a-z]", "#"); -- the default is case insensitive`
The result should be "##", but A is not replaced; "A#".
2. Slip of concatenating suffix of matching when last matching or nothing matched.
> [CBRD-22783] Fix regression of #1647

- src/parser/query_result.c
http://jira.cubrid.org/browse/CBRD-22979
PT_NODE.info is changed using the other node_type.
```
if (col->type_enum == PT_TYPE_NA || col->type_enum == PT_TYPE_NULL)
{
db_make_null (&col->info.value.db_value);
}
```
info.value.db_value.is_null is changed to '1' when col->node_type is NOT 'PT_VALUE' type.
i fixed to check node type is 'PT_VALUE'
> [CBRD-22979] Segmentation fault occurs when query has derived table with 3 or more unions

- Jenkinsfile
http://jira.cubrid.org/browse/CBRD-23616
The time 1 AM starting CI build is too late to check QA regression result fast.
This is for a quick checking QA regression failures by QA members.
It's good to start CI build at 9 PM which is 4 hours earlier
> [CBRD-23616] Time change to start ci build.

- src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
patch for: Clob's length() returns -1 when empty string
http://jira.cubrid.org/browse/CBRD-21023
> [CBRD-21023] JDBC Driver patch for Clob's length() returns -1 for empty string

- src/compat/dbtype_def.h
- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-23617
This issue occurs because the maximum length of query specification string of the base catalog class where the syntax for creating a virtual class is stored and the query specification string of the catalog virtual class generated from the base class are set to 4096 bytes.
So, modify the length of 'DB_MAX_SPEC_LENGTH' from 4096 to 0x3FFFFFFF and the schema of 'spec' from varchar(4096) to varchar(1073741823).
Note that 'schema' operation of csql utility get the 'Query Specification' string from root class of sm.
> [CBRD-23617] Query specification from system catalog is not displayed correctly when the syntax for creating view exceeds 4K

- src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-22970
This issue is related to fixing memory leaks in XASL_CLONE.
https://github.com/CUBRID/cubrid/pull/360
When creating XASL_CLONE, regular variables use global memory allocation. After that, the private allocation is used during the executor process.
So it is fixed that allocated memory on XASL_CLONE generation is deallocated on XASL destruction by setting the 'REGU_VARIABLE_CLEAR_AT_CLONE_DECACHE' flag.
qexec_end_mainblock_iterations
qexec_end_buildvalueblock_iterations
qdata_set_valptr_list_unbound
– fixed by (https://github.com/CUBRID/cubrid/pull/360)
```
if (!REGU_VARIABLE_IS_FLAGED (&reg_var_p->value, REGU_VARIABLE_CLEAR_AT_CLONE_DECACHE))
{
/* this may be shared with another regu variable that was already evaluated */
pr_clear_value (dbval_p);
} …
```
> [CBRD-22970] Constant variable is set to null when reusing cached XASL which is executed without data

- src/optimizer/query_rewrite.c
- src/parser/parse_tree.h
http://jira.cubrid.org/browse/CBRD-23618
Problem is that the number of host vars in cached XASL does not match the number of host vars in current query.
see the jira issue CBRD-23618 in detail
I fixed to not auto parameterize predicate which is copy pulled from select_list's constant value.
> [CBRD-23618] Error occur when rewriting subquery into derived table in delete or update statement

- CMakeLists.txt
http://jira.cubrid.org/browse/CBRD-23625
The Jenkins CI build has  trouble with downloading library which required to build cubrid.
This causes build failure. 
So need to increase library download timeout more than now. 
Log : 
[ 13%] Creating directories for 'libgcrypt'
[ 14%] Performing download step (download, verify and extract) for 'libgcrypt'
​error: downloading[ 14%] [ 14%] No patch step for 'libgcrypt'
[ 14%] Performing configure step for 'libgcrypt
> [CBRD-23625] Increased library download timeout required at build time

- src/query/numeric_opfunc.c
http://jira.cubrid.org/browse/CBRD-23623
when overflow occurs, numeric_prec_scale_when_overflow () is called again to get common prec and scale. numeric_prec_scale_when_overflow() checks if the actual value has more than 38 digits.
I fix to clear error if there is no overflow by calling numeric_prec_scale_when_overflow().
> [CBRD-23623] Unexpected data overflow error occurs by order of select list when the numeric type and ROUND are used together

- src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
Modified for correcting the length of clob by twice callings of readClobPartially  because the clobCharLength is already set in readClobPartially(...).
> [CBRD-21023] JDBC Clob's length() returns -1 when empty string

- src/cci/cci_util.c
http://jira.cubrid.org/browse/CBRD-22793
The performance degradation of connection by CCI caused when matching connection URL by regular expressions. It is fixed by reusing the compiled regex object of a URL pattern.
> [CBRD-22793] Reuse compiled regex for better performance of url matching

- src/connection/server_support.c
- src/executables/master_heartbeat.c
- src/executables/master_heartbeat.h
- src/storage/file_io.c
- src/transaction/log_manager.c
- src/transaction/log_manager.h
- Failover with insufficient disk space does not leave enough logs.
- Therefore, it is too difficult for the DBA to figure out why failover occurred.
- Allows the system logger to record the information in case of problems with insufficient disk space.
> [CBRD-23609] Send messages to the system logger when there is insufficient space in operating system device.

- src/query/string_regex.hpp
http://jira.cubrid.org/browse/CBRD-22837
Matching `[[:blank:]]` for the blank character doesn't work.
To match this kind of character class, `ctype<wchar_t>::is ()` is invoked.
And the blank character class type is not recognized by this function.
So for backward compatibility, use` iswblank ()` explicitly to match the blank character.
> [CBRD-22837] Fix matching blank character class for regex

- src/storage/file_io.c
- When getting the number of free pages of a partition, If the block size of the file system is bigger than page size (IO_PAGE_SIZE, LOG_PAGESIZE or whatever), Arithmetic Exception occurs.
- It is because of the order to calculate.
- So, I've changed the order, calculating the total available space first.
- Since 64 bit OS is required for CUBRID, size_t can cover 2^64-1 and the type of buf.* variable is "long", so it can cover 2^63-1 bytes, 16 Exabyte, which is big enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cubrid/cubrid/2218)
> [CBRD-23243] Modify the way to caculate available disk space

- src/base/system_parameter.c
- src/executables/util_cs.c
http://jira.cubrid.org/browse/CBRD-23631
- The maximum memory size of applylogdb can be set with the "ha_apply_max_mem_size" property, and the maximum value of this property has a limitation that can be set up to 500MB. This limitation was caused by the GC_MALLOC(related to CUBRIDSUS-5209, CUBRIDSUS-6068 etc), and GC_MALLOC was replaced by malloc(related to CUBRIDSUS-15243).
- Sometimes applylogdb requires more than 500MB of memory to process log records, but this limitation causes a problem that data cannot be applied to the slave DB.
- So, change the maximum value of this property from 500MB to INT_MAX.
> [CBRD-23631] Change the maximum value of the 'ha_apply_max_mem_size' property from 500MB to INT_MAX.

- src/connection/heartbeat.c
- src/connection/heartbeat.h
- src/executables/master_heartbeat.c
- src/executables/master_heartbeat.h
http://jira.cubrid.org/browse/CBRD-23604
backport https://github.com/CUBRID/cubrid/pull/2193
> [CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64. (#2193)

- src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
- src/jdbc/cubrid/jdbc/jci/UConnection.java
- src/jdbc/cubrid/jdbc/jci/UStatement.java
When the option oracleStyleEmptyString is set as a connection string parameter, the empty string "" should be translated to null automatically.
This modified feature is applied to the following database types as JAVA string type:
- CHAR
- VARCHAR
- CLOB
> [APIS-822] In JDBC Driver, translating empty string to null when the option oracleStyleEmptyString is set.

- src/base/system_parameter.c
- src/storage/file_io.c
- src/storage/file_io.h
It is fixed wrong max value of system parameter(backup_volume_max_size_bytes) and functions of backupdb for this parameter.
> [CBRD-21879] MAX value of system parameter 'backup_volume_max_size_bytes' is wrong

- src/base/intl_support.c
- src/base/language_support.c
http://jira.cubrid.org/browse/CBRD-23611
When blank is padded to a character type, multi-bytes blank is padded to a table set to EUCKR. But when the table is set to UTF8, a single byte blank is padded.
And when a blank is added by manually, the inserted data has single byte blank.
Therefore, a padding blank should be a single byte.
> [CBRD-23611] multi bytes blank is padded in char data of the table set to euckr

- src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
The revised method UInputBuffer has  two interface.
One is the interface with timeout as a parameter.
The other is the interface without timeout parameter.
This revision is for compatibility with Test Case of QA.
> [CBRD-23633] revised: UInputBuffer constructor modified for compatibility

- src/base/porting.h
- src/broker/cas_log.c
http://jira.cubrid.org/browse/CBRD-22975
A CAS hangs in CLIENT_WAIT status if the CAS's log size is greater than 2G on Windows 64. However, the same issue does not happen on Linux.
The size of `long int` is 8 byte in gcc while the size is 4 byte in MSVC. `cas_ftell ()` and `cas_fseek ()` use `long int` as a return and an argument respectively. So these methods will not be able to access the log file correctly If The CAS log file is greater than 2G.
The fix is as follows;
- _ftelli64 is added which omitted in porting.h
- INT64 needs to be used declared in system.h
> [CBRD-22975] Broker CAS hangs in CLIENT_WAIT status when log file size is greater than 2G on Windows 64

- src/storage/file_io.c
it prevents arithmetic error when block size is bigger than page size.
backport #2218
> [CBRD-23243] Modify the way to caculate available disk space (#2218)

- src/compat/dbtype_def.h
- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-23617
backport #2201
> [CBRD-23617] Query specification from system catalog is not displayed correctly when the syntax for creating view exceeds 4K (#2201)

- src/broker/cas_protocol.h
- src/jdbc/cubrid/jdbc/jci/UConnection.java
- src/jdbc/cubrid/jdbc/jci/UTimedDataInputStream.java
http://jira.cubrid.org/browse/CBRD-23633
It's needed to upgrade cas protocol V8 to V9 for backward compatibility.
> [CBRD-23633] protocol: Prevent endless busy waiting for query execution in abnormal network circumstance

- src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-23643
This issue occurs because the pthread mutex object of 'file_Tempcache' has dummy value before executing dynamic initialization function. 
In RHEL6 & RHEL7, problems related with robust mutex were reported about 2016 and resolved RHEL7.6. 
So, over RHEL7.6(CentOS 7.6) the same issue doesn't occur. 
But in CentOS 6.9~7.4, the problem still remain so, change the memory allocation function from malloc to calloc.
> [CBRD-23643] A hang occurs when exiting 'csql' after connecting to server through csql in standalone mode

- src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
http://jira.cubrid.org/browse/CBRD-21023
This is a back port for CBRD-21023
> [CBRD-21023] [JDBC] Clob's length() returns -1 when empty string

- src/base/porting.h
- src/broker/cas_log.c
http://jira.cubrid.org/browse/CBRD-22975
backport #2188
> [CBRD-22975] Broker CAS hangs in CLIENT_WAIT status when log file size is greater than 2G on Windows 64 (#2188)

- src/broker/broker.c
- src/broker/cas_common.h
- src/broker/cas_function.h
- src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
- src/jdbc/cubrid/jdbc/jci/UConnection.java
- src/jdbc/cubrid/jdbc/net/BrokerHandler.java
This is for a back port #2256 
* [APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException
* [APIS-782] revised: wrong redundant modify
* [APIS-782] revised: shorten, readability, and indentation
* [APIS-782] revised: synchroized, protocol version checking
* [APIS-782] indentation
> [APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException (#2256)

- src/base/intl_support.c
- src/base/language_support.c
> Revert "[CBRD-23611] multi bytes blank is padded in char data of the table set to euckr"

- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23611
This is a back port #2273
> [CBRD-23611] multi bytes blank is padded in char data of the table set to euckr (#2273)

- src/parser/xasl_generation.c
- src/query/query_executor.c
- src/query/xasl.h
http://jira.cubrid.org/browse/CBRD-23653
Due to the characteristic of the 'EXISTS' operation, if only 1 row is searched, it is possible to check true or false.
'XASL_NEED_SINGLE_TUPLE_SCAN' is added to the XASL.flag.
In case of 'EXISTS' operation in XASL generation step, the 'XASL_NEED_SINGLE_TUPLE_SCAN' flag is set.
Fix to stop scan when 1 row is searched in execution step.
> [CBRD-23653] subquery in 'EXISTS' operation retrieves the entire data and degrades the performance.

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-23658
This issue is a regression of CBRD-21694
In CBRD-21694, logic to change count_star when argument of count function is constant has been added.
When the argument of the count function is null, I modify it so that it does not change to count_star.
And I eliminates unnecessary duplicate logic in the type check.
> [CBRD-23658] counting Error occurred when argument of COUNT function is constant 'NULL'.

- src/jdbc/cubrid/jdbc/jci/UConnection.java
This is a revised PR for #2270
> [APIS-782] revised: JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException

- src/optimizer/query_graph.c
- src/optimizer/query_graph.h
http://jira.cubrid.org/browse/CBRD-21886
fix to change term class to TC_during_join when predicate is on 'ON' clause and TC_OTHER
> [CBRD-21886] No query results if DECODE, CASE, or IF is used in a nested left outer join query

- src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
- src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
- src/jdbc/cubrid/jdbc/driver/CUBRIDLobHandle.java
- src/jdbc/cubrid/jdbc/jci/UGetTypeConvertedValue.java
- src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
- src/jdbc/cubrid/jdbc/jci/UStatement.java
http://jira.cubrid.org/browse/APIS-825
In case of LOB columns in CUBRID, only the LOB locator(file path) is synchronized, and the actual data in that file is not replicated in HA environment. usually, to avoid this problem, table schema is created by converting BLOB column to BIT VARYING type and CLOB column to VARCHAR(MAX) type. therefore, when calling ResultSet.getBlob() or ResultSet.getClob() in JDBC, it should be supported if the table schema is BIT VARYING type or VARCHAR(MAX) type.
- The same result should be obtained when BLOB method is called for BLOB column and BIT VARYING column.
- The same result should be obtained when CLOB method is called for CLOB column and VARCHAR column.
> [APIS-825] Supports ResultSet.getBlob() or ResultSet.getClob() method to read BIT VARYING type or VARCHAR type.

- src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
- src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
- src/jdbc/cubrid/jdbc/driver/CUBRIDLobHandle.java
- src/jdbc/cubrid/jdbc/jci/UGetTypeConvertedValue.java
- src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
- src/jdbc/cubrid/jdbc/jci/UStatement.java
http://jira.cubrid.org/browse/APIS-825
backport #2303
> [APIS-825] Supports ResultSet.getBlob() or ResultSet.getClob() method to read BIT VARYING type or VARCHAR type. (#2303)

- src/storage/file_io.c
It handles the way to calculate available disk space in sector unit. The way is the same as #2218 , which is about the same issue.
> [CBRD-23243] Modify the way to calculate available disk space in sector unit

- src/storage/file_io.c
> [CBRD-23243] Modify the way to calculate available disk space in sector unit (#2330)

- src/parser/xasl_generation.c
- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-21022
fix to enable XASL cache for insert statements containing clobs and blobs and do not reuse XASL at XASL generator step
> [CBRD-21022] executeBatch returns Cannot communicate with the broker or received invalid packet & CAS down with core dump

- src/parser/name_resolution.c
http://jira.cubrid.org/browse/CBRD-20577
**The order by clause should allow the alias name specified at select list as ORACLE.**
The function **pt_resolve_names** calls **parser_walk_tree with pt_mark_group_having_pt_name**.
And  the function **pt_mark_group_having_pt_name** calls again _parser_walk_tree_ with _node->info.query.q.select.group_by_ and _node->info.query.q.select.having_ for resolving name resolutions.
We need to add parser_walk_tree with _node->info.query.order_by_.
As the same reason, we need to add the loop by **pt_resolve_group_having_alias_internal** with _node->info.query.order_by_ in the function **pt_resolve_group_having_alias**.
> [CBRD-20577] Use of alias with function inside ‘Order By’ Clause

- src/executables/util_service.c
http://jira.cubrid.org/browse/CBRD-23677
The cub_server process and heartbeat start normally when the 'cubrid service start' command is executed successfully after setting the properties of 'service=server,heartbeat' and 'server=database_name' in cubrid.conf. however, if a database with ha_mode=off is set in the server property, heartbeat fails to start even though there is a database participating in HA.
> [CBRD-23677] The heartbeat fails to start when 'cubrid service start' command is executed successfully even though the settings are normal.

- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23680
Temporary Volume File Path can be set using parameter 'temp_volume_path'.
However, the path for temporary volume file is not used when deleting temporary volume files.
Therefore, temp_volume_path will be used to delete temporary volume file if the parameter is set.
> [CBRD-23680] temporary temp volume file is not cleared when server restarted with temp_volume_path option

- src/optimizer/query_planner.c
http://jira.cubrid.org/browse/CBRD-23686
heuristic factor of index scan formula is eliminated.
heuristic factor should be eliminated for the following reasons.
1. if the selectivity is less than the heuristic constant, a combination of multiple columns can be counted as worse.
2. In cubrid, the limit of selectivity is set with accumulated index cardinality, so selectivity is not excessively large.
3. When calculating the IO cost, the page size of the index leaf is considered, so if there are the same conditions, the index with many columns is not selected.
> [CBRD-23686] If the number of index columns is large, the optimizer cannot select a more appropriate index.

- src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
- src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
- src/jdbc/cubrid/jdbc/jci/UConnection.java
- src/jdbc/cubrid/jdbc/jci/UErrorCode.java
- src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java
- src/jdbc/cubrid/jdbc/net/BrokerHandler.java
* Add useSSL to property.
* Add MagicStr(CUBRS) for SSL.
* Add SSL parameter for Broker connection.
* Add SSL for encryption only. (without server authentication)
* Add error code : CAS_ER_SSL_TYPE_NOT_ALLOWED = -10103
* Add driverInfossl for SSL
> [CBRD-23637] Implementation of secure CUBRID jdbc driver

- src/optimizer/query_graph.c
- src/optimizer/query_graph.h
- src/optimizer/query_planner.c
http://jira.cubrid.org/browse/CBRD-23689
This issue is a regression of CUBRIDSUS-13884.
I fix to add 'QO_TERM_OR_PRED' flag to the term. and in the case of 'QO_TERM_OR_PRED', if there are outer join among all the nodes included, modify term classification to become after-join-term.
> [CBRD-23689] If both outer join and inner join are present, the optimizer cannot find the optimal join order.

- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-23642
With #2251, if a too early backup time is given while "restoredb", it prints FATAL_ERROR and fails.
However, FATAL_ERROR is a too severe error to handle the case in which a utility to fail gracefully because of the wrong parameter. So, I relieve the severity of Error to ERROR from FATAL_ERROR.
As a note, the severity level is as following:
FATAL > ERROR > SYNTAX > NOTIFICATION > WARNING
> [CBRD-23642] Relieve error severity with a wrong backup time

- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-22637
This issue is caused by the modification of 'Refactor btree.c'.(CUBRIDSUS-15385)
In CUBRIDSUS-15385 fix, btree_search_key_and_apply_functions() was added for general usage in other btree operations. The problem is that btid_int regenerates in scan_next_scan() without using btid_int saved when opened.
When called from qexec_execute_mainblock() ==> scan_next_scan(), btid_int must be modified to be reused. I modify to reuse btid_int by adding the reuse_btid_int variable.
> [CBRD-22637] Excessive domain cache degrades search performance using index scan

- src/query/query_manager.c
http://jira.cubrid.org/browse/CBRD-23602
It's needed to process in case that xasl clone is disable, so it will use xclone.xasl instead of xasl_cache_entry_p in checking the query type.
> [CBRD-23602] processing in case that xasl clone is disable

- src/optimizer/query_graph.c
- src/optimizer/query_graph.h
http://jira.cubrid.org/browse/CBRD-23696
1. Term classification of 'QO_TC_DUMMY_JOIN' is excluded from pseudo-term of derived table dependency.
AS-is : QO_IS_FAKE_TERM()
- QO_TC_DEP_LINK, QO_TC_DEP_JOIN,  QO_TC_DUMMY_JOIN.
TO-be : QO_IS_DEP_TERM()
- QO_TC_DEP_LINK, QO_TC_DEP_JOIN
2. dep-set  is added to plan-output.
> [CBRD-23696] Core dump occurs when correlated subquery is used as in-line view.

- src/optimizer/query_rewrite.c
http://jira.cubrid.org/browse/CBRD-23598
backport #2178
> [CBRD-23598] Even with LIMIT 1 in a scalar subquery that uses union all, "Query result contains more than a single tuple." Error occurred (#2178)

- src/parser/query_result.c
http://jira.cubrid.org/browse/CBRD-22979
backport #2196
> [CBRD-22979] Segmentation fault occurs when query has derived table with 3 or more unions (#2196)

- src/query/query_opfunc.c
http://jira.cubrid.org/browse/CBRD-22970
backport #2197
> [CBRD-22970] Constant variable is set to null when reusing cached XASL which is executed without data(#2197)

- src/query/numeric_opfunc.c
http://jira.cubrid.org/browse/CBRD-23623
backport #2204
> [CBRD-23623] Unexpected data overflow error occurs by order of select list when the numeric type and ROUND are used together (#2204)

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-23658
backport #2296
> [CBRD-23658] counting Error occurred when argument of COUNT function is constant 'NULL'.(#2296)

- src/optimizer/query_graph.c
- src/optimizer/query_graph.h
http://jira.cubrid.org/browse/CBRD-23696
backport #2354
> [CBRD-23696] Core dump occurs when correlated subquery is used as in-line view.(#2354)

- src/parser/type_checking.c
- src/parser/xasl_generation.c
- src/query/query_dump.c
http://jira.cubrid.org/browse/CBRD-23697
1. fix to coerce the value to the type of the assigned column in set clause at semantic check.
2. add type of regu_var to xasl dump output.
> [CBRD-23697] occurred error "Cannot coerce value of domain character to domain integer" when executing update.

- src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-23709
fix to display 'Multiple rows in source table match the same row in destination table.' error when there are no existing errors
> [CBRD-23709] error message is displayed incorrectly in 'MERGE' clause

- src/loaddb/load_db_value_converter.cpp
- src/loaddb/load_sa_loader.cpp
http://jira.cubrid.org/browse/CBRD-21828
* **loaddb** cannot handle '.5' style number in loaddb_object file.
* Generally, you will not see the'.5' style number in the loaddb object file, this is because **DBMS**, **unloaddb**, and **CMT** will convert .5 to 0.5.
* As a some exceptional case, If you build loaddb object file yourself using query result to file in Oracle, you can see .5, .12 style number.
* Currently, if loaddb meet '.5' style number in loaddb object file, it **calculate the precision of the number as  0**, and fail to load it, **it should be 1.**
> [CBRD-21828] Process '.5' style number in loaddb_object as well as '0.5

- src/object/authenticate.c
- src/object/transform.h
- src/parser/parser_support.c
- src/parser/xasl_generation.c
- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-23649
make a 'dual' table to replace 'db_root' which was used as a dummy table.
- dual table is made by 'createdb'
- DBA and PUBLIC user are not allowed to drop, alter, insert, update and delete on dual table
- db_root is replaced when skip "FROM" in SELECT clause 
- db_root is replaced when creating SELECT clause in the process of making "show create table" query.
> [CBRD-23649] make dummy table instead of db_root

- src/compat/db_macro.c
- src/object/object_domain.c
- src/object/object_domain.h
- src/optimizer/query_rewrite.c
- src/parser/xasl_generation.c
- src/query/execute_schema.c
- src/query/fetch.c
- src/query/query_executor.c
- src/query/query_opfunc.c
- src/query/regu_var.hpp
- src/query/string_opfunc.c
- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23679
During query compiling the overflowed string is truncated at string operation including schema modify through ALTER clause.
We have to change to specification to produce semantic error with message like "can not coerce ..."
PRM_ID_ALLOW_TRUNCATED_STRING is added and the default value is "false" (not allowed string truncated)
PRM_ID_ALTER_TABLE_CHANGE_TYPE_STRICT default value is changed to "true"
In addition, in altering table, "nchar" to "char" type change is allowed only if the precision is valid.
> [CBRD-23679] Adding a configuration parameter and control for strict type translation

- src/base/system_parameter.c
- src/broker/broker_shm.h
- src/connection/connection_globals.h
backport from develop
change the following
* an limit value of db's max_clients from 2000 to 4000.
* an limit value of broker's max_num_appl_server from 2048 to 4096.
> [CBRD-23714] ] change an limit value of max_clients

- CMakeLists.txt
- src/broker/broker_config.c
- src/broker/broker_config.h
- src/broker/cas.c
- src/broker/cas_error.h
- src/broker/cas_network.c
- src/broker/cas_protocol.h
- src/broker/cas_ssl.c
- src/jsp/jsp_cl.c
http://jira.cubrid.org/browse/CBRD-23687
* This is backport of #2387 to release/10.2.
* It has exactly the same functionality with 10.2.1, and stable version 
(10.2.1 TestCases could be applicable without changes)
* Network I/O was changed to support async mode with timeout.
* Checks validity of certificate.
* contains resource return at the middle of error
* The SSL library will be built in a thread-safe way.
> [CBRD-23687] Backport CBRD-23687 (#2387) to 10.2

- src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
- src/jdbc/cubrid/jdbc/driver/CUBRIDDatabaseMetaData.java
- src/jdbc/cubrid/jdbc/jci/CUBRIDIsolationLevel.java
- src/jdbc/cubrid/jdbc/jci/UConnection.java
http://jira.cubrid.org/browse/APIS-833
Backported for #2395.
* Add isolation level of CUBRID Engine version 9 or earlier for backward compatibility (level 1, 2, 3)
> [APIS-833] Backport APIS-833(#2395) to 10.2

- src/parser/type_checking.c
- src/query/query_dump.c
http://jira.cubrid.org/browse/CBRD-23697
backport #2403
In the case of the same type as the allocated column, incorrect precision is entered without coerce the type. fix to coerce value to the type of the assigned column even if it is the same type.
> [CBRD-23697] Fix regression caused by different domain of db_value (#2403)

- src/base/system_parameter.c
modify system parameter (create_table_reuseoid) to can be changed at  client during session.
> [CBRD-23708] change table option's default value to reuse_oid

- src/query/fetch.c
http://jira.cubrid.org/browse/CBRD-23734
The resource tracker detects a memory leak and generates a core by assertion.
The points where memory leaks occur are at fetch_val_list()
The pr_share_value() in fetch_val_list() ignores the dest value and overwrites it with the src value.
add pr_clear_value() in fetsch_val_list() to prevent this potential memory leak.
> [CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456

- src/query/fetch.c
http://jira.cubrid.org/browse/CBRD-23734
Reverts CUBRID/cubrid#2423
The vfetch_to variable can be referenced in other reguvars, so it must be cleared at the end of execution of the XASL block.
> Revert "[CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456"

- cmake/CPackWixPatch.cmake.in
http://jira.cubrid.org/browse/CBRD-23733
* There are cases where dll cannot be installed in windows7, so Update warning popup is added during installation.
> [CBRD-23733] Add update warning popup when os is Window 7

- src/executables/unload_object.c
http://jira.cubrid.org/browse/CBRD-23649
fix a bug reported from the regression test.
> [CBRD-23649] The dual table is excluded from the results of unloaddb utility because it is a system catalog.

- src/executables/master_heartbeat.c
- src/executables/master_heartbeat.h
http://jira.cubrid.org/browse/CBRD-23737
The master process performs failover when a server hang occurs. there are two conditions for determining it.
1. no network response.
2. no logs were added for a certain period.
so, leaves a message to distinguish two conditions which are causing the failover.
> [CBRD-23737] Leaves a log to trace the cause when a failover is occurred due to a server hang.

- src/executables/util_service.c
http://jira.cubrid.org/browse/CBRD-23677
When executing cubrid hb start without setting ha_mode=on in cubrid.conf, the following incorrect message is displayed.
> Invalid Parameter. ha_db_list
Could not load one or more mandatory properties in configuration files.
++ cubrid heartbeat start: fail
so, it was modified to display the correct message as follows.
> The server was not configured for HA.
++ cubrid heartbeat start: fail
> [CBRD-23677] fixes bug reported in regression test.

- src/executables/util_service.c
http://jira.cubrid.org/browse/CBRD-23701
The 'cubrid hb start' command operates incorrectly if a database with ha_mode=off is registered in ha_node_list. this bug is caused by not applying the properties set in individual sector correctly.
> [CBRD-23701] Unexpected copylogdb is started even though a database with ha_mode=off

- src/parser/csql_grammar.y
http://jira.cubrid.org/browse/CBRD-21560
This change removes the returning error block when "default" is specified in fmt argument for TRUNC() and ROUND().
```
create table foo (a int, b date);
insert into foo values (1, '20170821');
insert into foo values (2, NULL);
create view foo_num as select trunc(sysdate-b) c1, round(sysdate-b) c2 from foo;
select * from foo_num;
create view foo_dt as select trunc(sysdate) c1, round(sysdate) c2 from foo;
select * from foo_dt;
```
The following is query specification information of each view.
```
csql> ;schema foo_num
...
<VClass Name> 
foo_num
...
<Query_specifications> 
select  trunc( SYS_DATE -[foo].[b], _iso88591'default'),  round( SYS_DATE -[foo].[b], _iso88591'default') from [foo] [foo]
csql> ;schema foo_num
...
<VClass Name> 
foo_dt
... …
```
> [CBRD-21560] Syntax errors can occur when a view containing TRUNC() or ROUND() function is fetched

- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23606
this is a revised version of https://github.com/CUBRID/cubrid/pull/2411
revised for windows build fail
> [CBRD-23606] An error occurs when the binding value is larger than 256 chars in merge query

- src/query/crypt_opfunc.c
http://jira.cubrid.org/browse/CBRD-23704
Fix slip of https://github.com/CUBRID/cubrid/pull/2406
> [CBRD-23704] Exclude null-terminator from returned len

- msg/de_DE.utf8/csql.msg
- msg/en_US.utf8/csql.msg
- msg/en_US/csql.msg
- msg/es_ES.utf8/csql.msg
- msg/fr_FR.utf8/csql.msg
- msg/it_IT.utf8/csql.msg
- msg/ja_JP.utf8/csql.msg
- msg/km_KH.utf8/csql.msg
- msg/ko_KR.euckr/csql.msg
- msg/ko_KR.utf8/csql.msg
- msg/ro_RO.utf8/csql.msg
- msg/tr_TR.utf8/csql.msg
- msg/vi_VN.utf8/csql.msg
- msg/zh_CN.utf8/csql.msg
- src/executables/csql.c
- src/executables/csql.h
- src/executables/csql_launcher.c
- src/executables/csql_result.c
- src/executables/csql_result_format.c
- src/executables/utility.h
http://jira.cubrid.org/browse/CBRD-23736
- The -q (--query-output) option displays query friendly format with --delimiter and --enclosure option.
- The -d (--loaddb-output) option displays loaddb friendly format.
- The two options only work with -c or -i option and are ignored if -c and -i option are omitted or -l option is used together.
- This options can't work together and also use with -q option.
> [CBRD-23736] add query-output and loaddb-output option to csql utility

- src/thread/thread_worker_pool.hpp
change wait timeout for stopping thread from 30 to 60 seconds on debug mode.
> [CBRD-23740] Core dumped in cubthread::worker_pool<cubthread::entry>::stop_execution at src/thread/thread_worker_pool.hpp:672

- src/storage/heap_file.c
* modify condition of assert() by considering copydb utility and reuse_oid table option.
> [CBRD-23742] Core dumped in heap_update_set_prev_version at src/storage/heap_file.c:24343

- src/executables/util_cs.c
http://jira.cubrid.org/browse/CBRD-23692
case 1 : copylogdb process repeatedly try to connect to server 
-  The master node can be routed to the slave node, but it cannot connect to the slave's server process
case 2 : copylogdb process is shut down
- master node is not able to be routed to slave nodes 
the heartbeat process succeeds if copylogdb process is not shut down like in case 1. 
To make the policy consistent, Case 2 follows the actions of Case 1. 
So, add the error returned by case 2 while connecting to server process to the retry condition like case 1.
> [CBRD-23692] The heartbeat starts fail on the master node if master and slave node exist on the different network and can't communicate each other.

- src/parser/parse_tree_cl.c
- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23678
- implementation of /*+ USE_SBR */ hint for DML in HA environment.
- refer to simple test scenario in issue.
- various tests are required. so I added /*+ USE_SBR */ hint to the CTP testcases and it is in progress
> [CBRD-23678] implementation of /*+ USE_SBR */ hint for DML in HA environment

- src/query/query_executor.c
- src/query/query_manager.c
- src/storage/heap_file.c
- src/storage/overflow_file.c
- src/thread/thread_entry.cpp
- src/thread/thread_entry.hpp
- src/transaction/log_manager.c
- src/transaction/log_manager.h
- src/transaction/replication.c
http://jira.cubrid.org/browse/CBRD-23682
Supports to /*+ NO_LOGGING */ hint.
**Specifications**
- /*+ NO_LOGGING */ hint can be used in DML syntax.
- Does not write redo logs for table records when using /*+ NO_LOGGING */ hint in a DML statement.
- Does not write the replication log related to table records.
- Writes undo logs. because it must work normally that the transaction rollback by a user, a statement abort due to constraint violations, and so on.
- Among the logs generated when executing a DML statement, only those related to table records are affected by this hint.
> [CBRD-23682] Support to /*+ NO_LOGGING */ hint

- src/loaddb/load_common.cpp
http://jira.cubrid.org/browse/CBRD-23752
- 10.2+ supports loaddb CS mode
- 10.2, in loaddb cs mode, the class line of an object file recognizes only the %class keyword.
- In the loaddb object file, lines starting with %class and %CLASS should be recognized as class definition lines.
- %ID and %id will be handled same way.
> [CBRD-23752] Case-insensitive handling of %class keyword in loaddb object

- src/cci/cci_network.c
http://jira.cubrid.org/browse/CBRD-23688
* Fixed an error that returned CCI_ER_COMMUNICATION instead of CCI_ER_SSL_HANDSHAKE
> [CBRD-23688] fix incorrect error code return

- src/parser/parse_tree_cl.c
http://jira.cubrid.org/browse/CBRD-23678
Fixed a bug that occurred in the following medium test case. an infinite loop occurs If the table name and column name are the same.
- medium/_02_xtests/cases/coerce1.sql
> [CBRD-23678] Remove the HANG bug that occurred when the table name and column name are the same.

- src/broker/broker_config.c
http://jira.cubrid.org/browse/CBRD-23715
- When the user executes the '**cubrid broker info**', all parameter values ​​of the currently running brokers are displayed.
- The SSL status, which is a broker configuration parameter, is added to the output of this command.
> [CBRD-23715] Display SSL parameter in broker info

- src/jdbc/com/cubrid/jsp/ExecuteThread.java
- src/jdbc/cubrid/jdbc/jci/UServerSideConnection.java
- src/jdbc/cubrid/jdbc/jci/UStatementHandlerCache.java
- src/jsp/jsp_cl.c
http://jira.cubrid.org/browse/CBRD-23753
- Disabled ssl_client in the destroying state of Java SP processing
- Added defensive code
- Avoid caused unexpected NullPointerException in UStatementHandlerCache
- Added checkReconnect() in UServerSideConnection.disconnect(). In some cases, output buffer (outBuffer) is not allocated and NullPointerException is caused.
- Added REQ_CODE_END not to call libcas_main() when InternalJDBCConnection was not used in the stored procedure.
> [CBRD-23753] Fix destroying Internal JDBC resources is not working and unexpected behavior

- src/broker/cas_ssl.c
http://jira.cubrid.org/browse/CBRD-23687
* Add a caslog for both certificate & private key were not found.
We already have caslog with no certificate or private key.
The user will see one of the three error messages below regarding the SSL file.
1. SSL: Certificate not found: /home/kshan/db/CUBRID/conf/cas_ssl_cert.crt
2. SSL: key not found: /home/kshan/db/CUBRID/conf/cas_ssl_cert.key
3. **SSL: Both the certificate & Private key could not be found: /home/CUBRID/conf/cas_ssl_cert.crt, /home/CUBRID/conf/cas_ssl_cert.key**
> [CBRD-23687] Add error message for both cert & pk were not found (SSL)

- src/object/object_primitive.c
- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-23759
This a bug from #2476 (http://jira.cubrid.org/browse/CBRD-23731)
This is a bug from btree index prefix processing under char-type index key.
the prefix is handled as varchar in comparing const key value, but the comparing function for char-type mr_cmpval_char handles two comparing argument as ti-style only if both of two arguments type are DB_TYPE_CHAR.
So, we have to change the mr_cmpval_char to process specially in case that one of argument type is DB_TYPE_CHAR under the btree-comparing. I have an idea that cmpval's argument do_coercion has value 2 in btree-compare and mr_cmpval_char do process the case in special.
> [CBRD-23759] [Regression][ha_repl_debug] Core dumped in btree_get_prefix_separator

- CMakeLists.txt
http://jira.cubrid.org/browse/CBRD-23601 
Commit count error. 
Sometimes the output of git ..... --after "[date]" .... is wrong . 
The git option "–after [date]" should exclude commits on the date.
This has not been working properly.  
It should be changed to a date with no commits for stability.
> [CBRD-23601] Git version and initial date not to include commits on the date

- src/base/language_support.c
http://jira.cubrid.org/browse/CBRD-23756
This a bug from #2476 (http://jira.cubrid.org/browse/CBRD-23731)
This is a bug from computing the weight of utf8 code set character.
the weights array for a collation consists as two arrays, weights[] and weights_ti (for trailing ignore).
but some collations from lib consists single array only, weights[].
So, we have to change the logic to compute the weight for trailing ignore.
> [CBRD-23756] [Regression] [sql] Core dumped in lang_get_w_first_el

- src/optimizer/query_rewrite.c
- src/parser/parser_support.c
http://jira.cubrid.org/browse/CBRD-23767
'1 = 1' is value node. index scan cannot be used because of !PT_IS_VALUE_NODE() condition.
'PT_IS_VALUE_NODE()' condition is unnecessary because value predicate split into filter part, NOT join part in pt_split_join_preds().
so I remove it.
> [CBRD-23767] Index scan cannot be used in hierarchical queries when there is a value predicate like '1=1'

- src/base/language_support.c
- src/executables/csql_result.c
- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23731
This is a revised version for #2483 
The below bug is patched:
- Turkey character set, comparison with ignoring trailing space.
- French (utf8_fr_exp_ab) character set, comparison with ignoring trailing space.
- two fixed length char-type db-string is compared with ignoring trailing space only if both type of them is char-type.
- issue fixed the string concatenation result in sub-query
> [CBRD-23731] regression-revised: In data comparing, no ignoring to trailing spaces at the end of the data.

- src/optimizer/query_rewrite.c
http://jira.cubrid.org/browse/CBRD-23754
```
AND table3.col_varchar_10_key <= 'z'
OR table1.col_varchar_10_key >= 'yeah'
```
As above, if predicates referenced by another tables are connected by OR, the outer join cannot be converted to inner join.
If the predicate contains an OR operation, modify it so that it is not converted to inner join.
> [CBRD-23754] Outer join is incorrectly changed to inner join in queries that contain OR operation.

- win/cubridsa/cubridsa.def
http://jira.cubrid.org/browse/CBRD-23791
^M (CRLF) is added in the win/cubridsa.def file by accident at CBRD-23629. 
We need to remove it.
> [CBRD-23791] Remove CRLF in win/cubridsa.def

- src/base/release_string.c
http://jira.cubrid.org/browse/CBRD-23789
The disk image was changed from CBRD-23608, CBRD-23703, and CBRD-23731. so it is necessary to change the disk compatibility level. I left a comment on the related issue about which tests were performed. please refer to it.
> [CBRD-23789] increase the disk compatibility level.

- src/communication/network_interface_cl.c
http://jira.cubrid.org/browse/CBRD-23787
In csession_create_prepared_statement(), 
if `SHA1Compute() returns an error, `local_alias_print` remains not freed.
> [CBRD-23787] Memory leak in csession_create_prepared_statement()

- src/executables/util_sa.c
http://jira.cubrid.org/browse/CBRD-23788
- in the file src/util_sa.c:3966, character array **inputpath_local** was defined inside if-block, and its address was referenced outside the block, as following style:
```
char *ptr;
if (cond)
{
char inputpath_local[PATH_MAX] = { 0 };
ptr = inputpath_local;
}
..
if (timezone_compile_data (input_path, tz_gen_type, db_name, NULL, checksum) != NO_ERROR)
  {
      exit_status = EXIT_FAILURE;
    goto exit;
  } 
```
> [CBRD-23788] Change declaration position of a character array

- src/win_tools/cubridservice/cubridservice.cpp
`break;` is omitted for stopping server routine on windows
> [CBRD-23629] Fix slip in cubridservice on windows

- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23793
http://jira.cubrid.org/browse/CBRD-23794
related from http://jira.cubrid.org/browse/CBRD-23731
In db_string_compare, ignore-trailing-space comparing should be considered because that db_string_unique_prefix calls the db_string_compare use char-type and varchar-type as arguments. The b-tree node uses char-type can be separated at some point and the prefix of the key is used for doing this separation. Therefore, the prefix of key (varchar) is compared with origin key value including trailing space and the comparing.
I will fix it by adding the comparing function for index prefix.
> [CBRD-23793] [Regression] Core dumped in db_string_unique_prefix

- src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
- src/jdbc/cubrid/jdbc/jci/UStatement.java
http://jira.cubrid.org/browse/CBRD-23797
In TYPE_SCROLL_SENSITIVE setting
```
Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
ResultSet rs = stmt.executeQuery("select * from table3 order by a asc");
rs.next();
rs.updateInt(1, 100);
rs.updateRow();  --> ArrayIndexOutOfBoundsException Exception
```
In maxRows setting
```
Statement stmt = con.createStatement();
stmt.execute("CREATE TABLE maxRows (val int)"
+ " INSERT INTO maxRows VALUES (1)"
+ " INSERT INTO maxRows VALUES (2)");
PreparedStatement pstmt = con.prepareStatement("SELECT * FROM maxRows WHERE val<? ORDER BY val");
pstmt.setInt(1, 100);
pstmt.setMaxRows(1);
ResultSet rs = pstmt.executeQuery(); --> …
```
> [CBRD-23797] [Regression] JDBC, in TYPE_SCROLL_SENSITIVE and in maxRows setting, exception fail

- src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-23795
also related http://jira.cubrid.org/browse/CBRD-23602
after drop table cub_server process terminated. in case after insert data and drop table occurs ERROR:111 'Your transaction has been aborted by the system due to server failure or mode change.'.
I found a bug at xcache_invalidate_entries and xcache_invalidate_qcaches.
When DDL or DML is committed, related SELECT query cache should be invalidated but related DML is also applied.
It's a bug. Any related DML must not be applied because the DML has no cache entry. 
xcache_invalidate_entries  is called at DDL committing (ex, drop table).
> [CBRD-23795] [Regression] cub_server terminate after drop table query.

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-23796
There are two problems. 
1. wrong precision like 'char(-1)'
==> '-1' is mean to TP_FLOATING_PRECISION_VALUE. '-1' is not wrong precision. it is not a problem.
2. assertion fail related to enumeration comparison.
==> I fixed it to not generate PT_TO_ENUMERATION_VALUE() when argument is 'null'.
> [CBRD-23796] some rewrite query was not found the character size

- src/parser/csql_grammar.y
http://jira.cubrid.org/browse/CBRD-23800
SELECT
/*+ QUERY_CACHE */
SERIAL_NEXT_VALUE(serial_no);
the above query must not be cached.
I modified the parser not to be cached at SERIAL related node.
> [CBRD-23800] [Regression] the query includes function related to serial is cached unnecessarily

- src/base/language_support.c
http://jira.cubrid.org/browse/CBRD-23798
also related to http://jira.cubrid.org/browse/CBRD-23731
This is related to the issue http://jira.cubrid.org/browse/CBRD-23731 processing ignore trailing space.
The trailing space should be ignore in System Parameter ignore_trailing_space=no, but in some collations the ignoring code is missed.
lang_fastcmp_byte is used at iso8859 collation and lang_strmatch_utf8_uca_w_level is used at uf8_uca collations should be reconsidered because ignoring space is not completed.
First, in lang_fastcmp_byte trailing space is processed well but 0-weight character is not, 0-weight character is ASCII code value 0 and it doesn't mean null.
In lang_strmatch_utf8_uca_w_level, modified point is as below.
**is_match and ignore_trailing_space follows the same string …
> [CBRD-23798] [Regression] some collation has wrong checked the null value

- src/executables/util_service.c
- unexpected result: 'usage' is not displayed for `cubrid javasp status` without <db_name>. STATUS was not correctly checked in `process_javasp()`.
- there is a bug that `cubrid javasp stop` is always printed as 'fail'. but actually it is successfully stopped on windows. it is because of the wrong testing of `is_javasp_running ()` in `process_javasp_stop()`.
- slip, there may be no return case in `is_javasp_running ()`
- Make _javasp utility_ run last so that it does not occupy another CUBRID process's port first when the javasp utility is run from the service utility.
> [CBRD-23629] Fix regression of Java SP server utility

- src/executables/util_admin.c
- src/executables/utility.h
CUBRID uses the literal word 'C' to check whether it is CS mode or not. 
So using dummy words like 14000 for the short option name of CS mode made TDE always load SA library.
Generally, dummy words are used to make it impossible to use the option, but this trick can't be used for the short name for mode selection.
> [CBRD-23608] Fix to use --CS-mode for TDE

- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23802
also related to http://jira.cubrid.org/browse/CBRD-23731
The configurable parameter 'ignore_trailing_space' is a serious component to affect a whole database system environment and operations.
If this parameter could be changed easily, the database applications using index with unique string keys faced with serious circumstance.
So, we should change the parameter's property to 'hidden' not to change the value.
> [CBRD-23802] The 'ignore_trailing_space' system parameter's property becomes 'hidden'

- src/base/system_parameter.c
- src/query/list_file.c
- src/query/query_manager.c
The parameters related to 'query_cache_mode' is as below:
- max_query_cache_entries
- query_cache_size_in_pages
By the above parameters, the query cache mode can be changed to enable or disable.
In order to this, the related some routines is need to be changed.
> [CBRD-23803] The parameters related to 'query_cache_mode' reconfigured to change the mode.

- src/transaction/boot_sr.c
The file descriptor for a backup file must be closed after validation for the backup key file (no need to keep it), but it was missed not considering WINDOWS.
After validation, the backup key file is mounted. In WINDOWS, the file locking in `fileio_mount()` uses constants for [file-sharing modes](https://docs.microsoft.com/ko-kr/cpp/c-runtime-library/sharing-constants?view=msvc-160) given to open(), although Linux uses file lock interface. Because WINDOWS `_SH_DENYWR` to lock a file in `fileio_mount()`, we need to close the file opened with `O_RDWR`. This is not a problem in LINUX.
> [CBRD-23608] Close the vdes of backup key file after validation (restoredb)

- src/executables/util_service.c
Even `javasp` is not set in the `service` section, the usage of javasp is displayed unexpectedly.
It caused because database names are not set in `service::server` so the argument of `javasp status` is not given, usage is displayed in the `javasp status` routine unexpectedly.
> [CBRD-23629] Fix usage of javasp is displayed by cubrid service status

- src/executables/util_service.c
Instead of the general routine of javasp, call javasp stop and javasp start function.
> [CBRD-23629] Revise calling function on restarting javasp

- src/storage/file_manager.c
http://jira.cubrid.org/browse/CBRD-23809
Temp file should be deleted when a query is closed or a result cache is removed.
The code is modified not to return without deleting temp file. I remove one line unnecessary "return NO_ERROR" of the code to prior CBRD-23602.
> [CBRD-23809] [Regression] Decreased volume reuse rate.

- src/query/list_file.c
- src/query/list_file.h
- src/query/query_manager.c
- src/query/xasl_cache.c
http://jira.cubrid.org/browse/CBRD-23810
Improvement of DML and transaction processing for result-cache
The update query affects the result-cache by cache invalidation for related tables.
We should minimize the affect for performance and the transaction processing should be also dealt in detail.
- The invalidation for DML does not need to start for 0 cache entry.
- The invalidation for DML does not need to start for no-cache mode.
- query caches "IN Transaction" must not refer.
> [CBRD-23810] Improvement of DML and transaction processing for result-cache

- src/executables/csql.c
http://jira.cubrid.org/browse/CBRD-23808
In case of FILE_INPUT type in csql, sql_user_text of the statement is null. Therefore, add null check to sql_user_text
> [CBRD-23808] Core dumped in csql_execute_statements

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-23731
in prepare statement containing + ''%'''  query cast as char which '' expected cast as varchar.
> [CBRD-23731] Regression: in prepare containing + '%' query cast as char which expected cast as varchar.

- src/query/query_manager.c
- src/storage/btree.c
- src/storage/file_manager.c
This fetch includes:
- Fix to cleanup VFIDs if `file_apply_tde_algorithm()` fails (in some cases)
- Revise error handling and missed cleanup OR_CLASS_REPR in `xfile_apply_tde_to_class_files()`
> [CBRD-23608] Revise error handling and cleanup when applying tde to files fails

- src/executables/javasp.cpp
- win/cubridsa/cubridsa.def
This PR fixes the following regression. It caused because an error is not cleared before starting JVM in javasp_start_server (). errors created by er_set() in javasp_is_running () was detected by jsp_start_server() and was handled incorrectly. it should be cleared.
**Repro.**  
```
cubrid javasp start demodb
ps -ef | grep cub_javasp
kill -9 <pid>
cubrid javasp start demodb
```
**Expected**
```
@ cubrid javasp start: demodb
++ cubrid javasp start: success
```
**Actual** 
```
@ cubrid javasp start: demodb
Can't connect Java VM: connect()
++ cubrid javasp start: fail
```
And I fixed some trivial slip.
> [CBRD-23629] Fix slip of javasp utility

- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-23804
http://jira.cubrid.org/browse/CBRD-23814
also related to http://jira.cubrid.org/browse/CBRD-23731
Core dumped in btree_key_find_and_insert_delete_mvccid
The b-tree key compare is not same as general compare when the char-type and varchar-type is mixed.
The mixed type case is commonly made at splitting b-tree node  to check a split position of the tree nodes.
I modified the codes related to b-tree compare to process mixed char and varchar-type.
The coerce 2 means tow comparing arguments may have char-type and varchar-type each other.
> [CBRD-23804][Regression] Core dumped in btree_key_find_and_insert_delete_mvccid

- src/base/ddl_log.c
- src/base/ddl_log.h
- src/executables/csql.c
- src/loaddb/load_db.c
http://jira.cubrid.org/browse/CBRD-23726
* Change to record ddl audit log when running csql with -i, --no-single- line option
ex) $ csql -u dba demodb --no-single-line --no-auto-commit -i test.sql
* When recording the log, the loaded file is also copied.
file path : $CUBRID/log/ddl_audit/csql
> [CBRD-23726] change to record ddl audit log in csql 

- src/transaction/replication.c
http://jira.cubrid.org/browse/CBRD-23819
The Valgrind said that the conditional jump or move depends on uninitialized value. So, fixed it.
> [CBRD-23819] [Regression] Conditional jump or move depends on uninitialised value(s)

- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23827
The result-cache is a new feature at 11.0, but disabling the future is needed to consider the stable and performance for updating-bias environment.
We should set the system parameter "max_query_cache_entries" and "query_cache_size_in_pages" to 0 in default.
> [CBRD-23827] Policy changing to disable result-cache in default.

- src/object/object_domain.c
- src/object/object_primitive.c
- src/parser/parser_support.c
- src/query/string_opfunc.c
- src/storage/btree.c
http://jira.cubrid.org/browse/CBRD-23812
related to http://jira.cubrid.org/browse/CBRD-23731
Environment:
1. Create a table by increasing columns from 2 to 30.
2. Insert/update/select sequentially with 10 threads targeting each table.
3. 10,000 times per thread.
Fail case:
When comparing each column value by executing the same select query that scans different indexes in the same transaction, in the select result comparison step, the result of the first query is failing with 0 tuple.
I found a weak point to compare with "midxkey" in b-tree index processing. The point is related to coercion at the different components consist of multi-column key. The comparing is performed by pr_midxkey_compare_element  through the pr_midxkey_compare function. I modified the coercion of pr_midxkey_compare …
> [CBRD-23812] [Regression] The results of two queries that scan different indexes in the same transaction are different.

- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23678
The syntax error occurs on the slave node when using /\*+ USE_SBR hint \*/. Because the input insert statement is changed as follows:
- on MASTER node:
- insert /*+ USE_SBR */ into xoo values(1);
- on SLAVE node:
- insert /*+ USE_SBR */ into xoo (encrypt) values (1);
So, convert the identifier into [identifier] for keyword support as follows:
- AS-IS:
- insert /*+ USE_SBR */ into xoo (encrypt) values (1);
- TO-BE:
- insert /*+ USE_SBR */ into [xoo] ([encrypt]) values (1);
> [CBRD-23678] support to keywords when using /*+ USE_SBR */ hint.

- src/object/object_domain.c
- src/object/object_primitive.c
- src/parser/csql_grammar.y
- src/parser/parser_support.c
- src/parser/type_checking.c
- src/query/string_opfunc.c
http://jira.cubrid.org/browse/CBRD-23812
also related to http://jira.cubrid.org/browse/CBRD-23731
Environment:
Create a table by increasing columns from 2 to 30.
Insert/update/select sequentially with 10 threads targeting each table.
10,000 times per thread.
Fail case:
When comparing each column value by executing the same select query that scans different indexes in the same transaction, in the select result comparison step, the result of the first query is failing with 0 tuple.
I changed the default type to VARCHAR for constant string.
And I also modified comparing routine mr_cmpval_string and mr_cmpval_char.
In the modified comparing routine, varchar-type data comparing always no ignore trailing spaces and char-type data comparing always ignore trailing spaces.
> [CBRD-23812] [revised] The results of two queries that scan different indexes in the same transaction are different.

- src/storage/page_buffer.c
http://jira.cubrid.org/browse/CBRD-22803
Fixed the performance degradation in the wips workload of the TPC-W benchmark. The global variable is used to record the state of the page buffer. And when calling the pgbuf_fix() function, etc., this global variable is increased. As a result, performance degradation of about 150 TPS occurred. It was identified as a problem caused by several threads competing for one global variable. Therefore, I have resolved this problem.
> [CBRD-22803] Fixed the performance degradation in the wips workload of the TPC-W benchmark.

- src/transaction/boot_cl.c
http://jira.cubrid.org/browse/CBRD-23649
Eliminated warning that caused by trying to convert a string constant to char*.
"char* dummy" are passed as a argument to the db_make_varchar() function, but db_make_varchar() takes argument of type const char*.
> [CBRD-23649] Get rid of warnings due to data type

- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23830
This issue is from result-cache where it checks if OID is included in a query.
> [CBRD-23830] [Regression] [shell_ext] Core dumped in do_prepare_select

- src/executables/util_cs.c
- src/storage/tde.c
- src/transaction/log_page_buffer.c
- Regression issue
- https://github.com/CUBRID/cubrid-testcases-private-ex/blob/develop/shell/_36_damson/cbrd_23608_tde/utility_16/cases/utility_16.sh
- Description
- In the Windows environment, the restrictions are removed so that the master key can be changed using the cubrid tde utility.
- When designing, it was decided that the change of the master key and the backupdb cannot be performed at the same time.
- To ensure this, a file lock was acquired by using the fileio_mount() function in the cubrid utility and the cub_server.
- But, different processes cannot hold a file lock in _SH_DENYWR and _SH_DENYNO modes at the same time in the Windows environment.
- Therefore, the fileio_open function() is used instead of the fileio_mount() function when …
> [CBRD-23608] [regression] Modified to be able to change master key in Windows environment.

- cmake/CPackWixPatch.cmake.in
http://jira.cubrid.org/browse/CBRD-23733
In the case of the following OS, a security patch notification pop-up is displayed.
* Windows 7
* Windows Server 2008 R2
* Windows 7, Service Pack 1
* Windows Server 2008 R2
* Windows Home Server 2011
* Windows Server 2012
* Windows 8
* Windows 8.1
* Windows Server 2012 R2
> [CBRD-23733] add windows security patch update notification popup when cubrid install

- demo/make_cubrid_demo.bat
http://jira.cubrid.org/browse/CBRD-23833
The default character set is changed to utf8 from iso-88591 in 11.0 but the default is not changed yet in Windows.
> [CBRD-23833] Changing default character set to utf8 for demodb in Windows

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-23831
A codeset of collection type is not considered when implicit cast.
I add code set which is bigger among set's elements.
I also fix wrong inequality sign to avoid potential problems.
> [CBRD-23831] Some collection-related (has VARCHAR elements) query returns incorrect result

- src/base/memory_hash.c
- src/base/memory_hash.h
- src/parser/type_checking.c
- src/query/query_hash_scan.c
- src/query/query_hash_scan.h
- src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-23828
The HASH LIST SCAN operates with the following priorities. (check_hash_list_scan() )
```
1. in-memory hash if all data can be stored (hash value : tuple)
2. Hybrid in-memory hash if all OID of data can be stored (hash value : OID)
3. LIST SCAN if all data cannot be stored (After CBRD-23816, use HASH TEMP FILE.)
```
**Hash table for HASH LIST SCAN**
In order to minimize the size of the hash entry, a hash table for HASH LIST SCAN is created separately. It has the following features.
```
1. lru, act is not used. (remove variable related to lru, act)
2. key comparison is performed in executor. (remove key of hash entry)
3. put data orderly. (add tail pointer for it)
4. Since hash size is fixed, rehashing the hash table is not necessary.
```
A key of …
> [CBRD-23828] Support the use of OID of temp file in HASH LIST SCAN.

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/server_type.cpp
- src/base/server_type.hpp
- src/base/system_parameter.c
- src/base/system_parameter.h
- src/loaddb/load_error_handler.cpp
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/LETS-5
Add a system parameter for configuring whether the server starts as a page- or a transaction-server (default when parameter is missing in `cubrid.conf`).
I had to include <algorithm> in `src/loaddb/load_error_handler.cpp`, otherwise it didn't build and also fixed some `unused variable` warnings in `boot_sr.c`
> [LETS-5] Add server_type system parameter

- src/parser/type_checking.c
http://jira.cubrid.org/browse/CBRD-22856
I correct my mistake.
```
func->type_enum == PT_TYPE_SEQUENCE;
==>
func->type_enum = PT_TYPE_SEQUENCE;
```
The reason the test was normal despite the above fault,
This is because type_enum is PT_TYPE_SEQUENCE even without the above code.
The code above is a defense code for unexpected situations.
> [CBRD-22856] fix to avoid compilation warning

- src/transaction/log_recovery.c
http://jira.cubrid.org/browse/LETS-17
The check against 'is_mvcc_op' is superfluous as for the log type 'LOG_MVCC_UNDO_DATA' it would be true anyway; it is also incorrect because it is not properly initialized in the 'LOG_MVCC_UNDO_DATA' label's context.
This  is a preliminary change intended to help in a subsequent refactoring/extension of the log recovery mechanism where we intend to introduce a parallelization mechanism to speed up the process.
> [LETS-17] incorrect test against mvcc flag in log recovery

- src/connection/tcp.c
- src/connection/tcp.h
- src/connection/wintcp.c
- src/connection/wintcp.h
- src/executables/master.c
- win/cubridcs/cubridcs.def
http://jira.cubrid.org/browse/LETS-18
Use existing code to open only TCP sockets (and not UNIX)
There was a single function in tcp.c which opened (for linux) both TCP and UNIX sockets (css_tcp_master_open). To be able to re-use the functionality for TCP sockets only, this was extracted to a new function (css_tcp_socket_bind_listen), which creates the TCP sockets, set socket options, binds, listens. The original one calls the new one for TCP and continues with the UNIX part. I also renamed it to "css_master_open_sockets"
> [LETS-18] Separate TCP and UNIX socket open

- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23854
When using /*+ USE_SBR */, an error occurs on the slave node.
We can use sql_user_text of parser to replicate query for SBR.
The host variables are replaced the values using string parsing in sql_user_text and host variables.
> [CBRD-23854] When using /*+ USE_SBR */, an error occurs on the slave node.

- src/parser/parse_tree.h
- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-23865
In the case of hierarchical query, the data filter is separately performed to evaluate reserved words of HQ such as 'LEVEL'.
In CUBRID v11, it has been modified to call scan_next_scan() instead of qfile_scan_list_next(). At this point, because the data filter evaluated by scan_next_scan() was removed, fetch_val_list() is called excessively, which is the cause of the slowdown.
By adding a data filter excluding the reserved words of HQ, the cause of the slowdown is eliminated.
In addition, it also fixes the problem that reserved words of HQ may be the target of hash list scan.
> [CBRD-23865] Hierarchical query execution time difference between V11 and V10.2 occurs when using SQL hints /*+ no_hash_list_scan */

- sa/CMakeLists.txt
- src/base/server_type.cpp
- src/transaction/boot_sr.c
- src/transaction/log_append.cpp
- src/transaction/log_manager.c
- src/transaction/log_record.hpp
http://jira.cubrid.org/browse/LETS-7
Disabled vacuum start on page server.
Added 2 new log types to signal if vacuum started on current server.
show threads on transaction server:
```shell
adrian@Sparrow:~/cubridScalabil$ csql -udba workdb -c "show threads" > show_threads.txt
adrian@Sparrow:~/cubridScalabil$ grep "VACUUM" show_threads.txt -c
1
```
show threads on page server:
```shell
adrian@Sparrow:~/cubridScalabil$ csql -udba workdb -c "show threads" > show_threads.txt 
adrian@Sparrow:~/cubridScalabil$ grep "VACUUM" show_threads.txt -c
0
```
err log on transaction server:
```shell
adrian@Sparrow:~/cubridScalabil$ grep "Vacuum" inst/log/server/workdb_latest.err 
Vacuum was started on the transaction server.
```
err log on page server:
```shell
adrian@Sparrow:~/cubridScalabil$ grep …
```
> [LETS-7] Disable vacuum on the page server

- cs/CMakeLists.txt
- src/connection/connection_globals.c
- src/connection/connection_globals.h
- src/storage/file_io.c
- src/transaction/log_common_impl.h
http://jira.cubrid.org/browse/LETS-9
Queries should not be run on the page server, only one sysadm connection is allowed.
Connections on the page server:
```bash
adrian@Sparrow:~/cubridScalabil/cubrid$ csql -udba workdb
Server refused client connection: max clients, (0), exceeded.
Failed to connect to database server, 'workdb', on the following host(s): localhost
```
normal working connection with --sysadm:
```bash
adrian@Sparrow:~/cubridScalabil/cubrid$ csql -udba workdb --sysadm
CUBRID SQL Interpreter
Type `;help' for help messages.
sysadm> ;ex
```
Show threads on sysadm connection on the page server:
```bash
adrian@Sparrow:~/cubridScalabil$ csql --sysadm  -udba workdb -c "show threads" > show_threads.txt
adrian@Sparrow:~/cubridScalabil$ geany show_threads.txt …
```
> [LETS-9] Allow only csql --sysadm connections to the page server

- src/query/arithmetic.c
- src/query/execute_statement.c
http://jira.cubrid.org/browse/CBRD-23859
In the case of a division operation in the process of calculating a double type in the linux gcc environment, 0 may change to 1 at the 16th digit below the decimal point.
If we change this operation to a multiplication operation, it is calculated correctly.
> [CBRD-23859] ROUND()'s result of decimal data type is wrong

- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-23850
When executing backupdb with the -r option, the archive log volume referenced by the transaction(mvcc) is not considered. So, coredump occurs when the transaction reads the old image of mvcc after performing the backupdb. There is a test scenario for this in the comments of the related issue. Looking at that scenario will help you understand. (I defined this problem as PROBLEM-1 in the jira issue.)
> [CBRD-23850] coredump occurs when heap_get_visible_version_from_log() function is called after executing backupdb with -r option.

- cubrid/CMakeLists.txt
- src/communication/request_client_server.hpp
- src/communication/request_sync_send_queue.hpp
- unit_tests/request_client_server/CMakeLists.txt
- unit_tests/request_client_server/comm_channel_mock.cpp
- unit_tests/request_client_server/comm_channel_mock.hpp
- unit_tests/request_client_server/test_main.cpp
http://jira.cubrid.org/browse/LETS-26
Add two new request handling classes to synchronize request pushing and to automatically send pushed requests.
- **request_sync_send_queue**: synchronize request pushes and synchronize send over network. Multiple threads can push and multiple threads can send the pushed requests.
- **request_queue_autosend**: automatically send all requests pushed into a request_sync_send_queue. request_queue_autosend preserves requests order.
The new classes are found in **request_sync_send_queue.hpp**.
test_request_cs unit test was extended with two new test cases for the two new classes. other unit test changes:
- new environment classes that holds client, servers and socket directions for a test case.
- new payload/handlers to also verify the order of handling …
> [LETS-26] Synchronize pushing requests and automate sending

- cs/CMakeLists.txt
- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/server_type.cpp
- src/connection/connection_globals.c
- src/connection/connection_globals.h
- src/connection/connection_server_rules.cpp
- src/connection/connection_server_rules.hpp
- src/connection/connection_sr.c
- src/connection/server_support.c
- src/storage/file_io.c
- src/transaction/boot_cl.c
- src/transaction/log_common_impl.h
http://jira.cubrid.org/browse/LETS-25
Connection server rules were part of connection_global, which was included in both the client and the server modules. To this end a new file connection_server_rules was created to be part only of the the server modules.
> [LETS-25] [Refactoring] Move connection server rules out of connection_globals

- src/compat/db_admin.c
- src/transaction/boot_sr.c
- src/transaction/log_append.cpp
- src/transaction/log_page_buffer.c
- src/transaction/log_tran_table.c
http://jira.cubrid.org/browse/LETS-8
Queries and log creation should be disabled on the page server. Other tools that operate changes on the database like addvoldb, compactdb, loaddb, optimizedb, synccoldb, are also disabled. New error messages will appear when trying to run changes on the page server, or when the server is appending a log record.
> [LETS-8] Disable writing (and log creation) on the page server

- src/base/perf_monitor.c
- src/transaction/boot_cl.c
- src/transaction/log_append.cpp
- unit_tests/log_transfer/test_main_prior_list_serialize.cpp
http://jira.cubrid.org/browse/LETS-39
Set the number of transactions argument of perfmon_initialize(). Also fixes assert that is hit.
**Out of scope**
- Indentation
- Fix unit test compile
> [LETS-39] perfmon_initialize() with one transaction in CS/SA mode 

- src/base/system_parameter.c
- add code to check if the value of system parameter is NULL
> [CBRD-23870] occurred core dump when getting the specific system parameter at csql

- contrib/CMakeLists.txt
- contrib/windows_scripts/cubrid_env.bat
http://jira.cubrid.org/browse/CBRD-21446
When installing CUBRID as a zip file on Windows, execution may fail because there is no DLL, environment variables or registry settings are not set.
In this case, DLL installation, environment variables, and registry settings are required.
> [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.

- src/storage/heap_file.c
http://jira.cubrid.org/browse/CBRD-23866
> [CBRD-23866] Fix not to reuse heap when creating a table with REUSE_OID

- src/transaction/log_page_buffer.c
http://jira.cubrid.org/browse/CBRD-23850
backport #2575
> [CBRD-23850] coredump occurs when heap_get_visible_version_from_log() function is called after executing backupdb with -r option. (#2575)

- src/base/string_buffer.cpp
- src/loaddb/load_class_registry.cpp
- src/transaction/transaction_transient.hpp
http://jira.cubrid.org/browse/LETS-48
Add missing system headers to fix VS2019 compile fail.
@hornetmj should this change be backported to develop?
> [LETS-48] Add missing system headers to fix VS2019 compile fail

- src/base/system_parameter.c
- src/base/system_parameter.h
- src/communication/communication_channel.cpp
http://jira.cubrid.org/browse/LETS-49
cubcomm::channel::recv_int function does not work as expected. It first reads a message length then it expects length bytes.
cubcomm::channel::send_int only sends an integer (4 bytes).
Changed recv_int to onmly read 4 bytes.
**Other changes:**
- Added a system parameter named er_log_comm_channel to activate debug messages of channel functions. The messages are logged into error log files.
> [LETS-49] Match cubcom::channel::recv_int with send_int

- src/base/system_parameter.c
- src/base/system_parameter.h
- src/transaction/log_prior_recv.cpp
- src/transaction/log_prior_send.cpp
- unit_tests/log_transfer/test_main_prior_sendrecv.cpp
http://jira.cubrid.org/browse/LETS-51
Add er_log_prior_transfer system parameter to activate debug messages for sending and receiving log prior lists during log prior transfer.
**Other changes**
- Fix new prior send/receive unit test dependencies.
> [LETS-51] Add debug messages for log prior list send/receive

- src/base/server_type.cpp
- src/base/server_type.hpp
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/LETS-19
This is a loose end of PR #2609. The function was supposed to be renamed as the review suggested, but the change was not pushed.
> [LETS-19] Change name of function to finalize_server_type()

- .circleci/config.yml
- CMakeLists.txt
- run_scalability_unit_tests.sh
http://jira.cubrid.org/browse/LETS-47
Run the scalability unit tests in circle-ci.
- Add a script that runs scalability unit tests.
- Modify circle-ci config file to compile unit tests and run the script during build phase.
The tests included in the script must be very small. No stress/performance tests will be allowed. Any longer unit tests should not be included or should be run in a short version.
> [LETS-47] Run scalability unit tests in circle-ci

- src/base/server_type.cpp
- src/transaction/boot_sr.c
Bug: Regardless of the server type it was always displaying "Starting server type: transaction", because the message is printed before initialization.
Fix: The message is now printed in the server_type initialization function.
```bash
Time: 03/22/21 16:30:08.679 - DEBUG *** file PATH/cubrid/src/base/server_type.cpp, line 56
Starting server type: page
```
```bash
Time: 03/22/21 16:38:36.942 - DEBUG *** file PATH/cubrid/src/base/server_type.cpp, line 56
Starting server type: transaction
```
> [LETS-40] Fix starting server type message

- src/loaddb/load_class_registry.hpp
http://jira.cubrid.org/browse/CBRD-23890
* Change std::uunordered_map to std::map to fix update stat order
> [CBRD-23890] Fix order of update statistics of loaddb CS

- msg/de_DE.utf8/utils.msg
- msg/en_US.utf8/utils.msg
- msg/en_US/utils.msg
- msg/es_ES.utf8/utils.msg
- msg/fr_FR.utf8/utils.msg
- msg/it_IT.utf8/utils.msg
- msg/ja_JP.utf8/utils.msg
- msg/km_KH.utf8/utils.msg
- msg/ko_KR.euckr/utils.msg
- msg/ko_KR.utf8/utils.msg
- msg/ro_RO.utf8/utils.msg
- msg/tr_TR.utf8/utils.msg
- msg/vi_VN.utf8/utils.msg
- msg/zh_CN.utf8/utils.msg
- src/communication/network.h
- src/communication/network_cl.c
- src/communication/network_interface_cl.c
- src/communication/network_interface_cl.h
- src/communication/network_interface_sr.c
- src/communication/network_interface_sr.h
- src/communication/network_sr.c
- src/executables/util_admin.c
- src/executables/util_cs.c
- src/executables/utility.h
- src/query/vacuum.c
- src/query/vacuum.h
http://jira.cubrid.org/browse/CBRD-23881
Add the following two options to the vacuumdb utility.
- --dump
- Prints the following two pieces of information
- smallest log page ID referenced by vacuum
- log volume name including smallest log page ID
- -o, --output-file=FILE
**Usage**
```
$ cubrid vacuumdb
vacuumdb: Vacuums dead records from database.
usage: cubrid vacuumdb [OPTION] database-name
valid options:
-S, --SA-mode                stand-alone mode execution
-C, --CS-mode                client-server mode execution
--dump                   dump current state of vacuum
-o, --output-file=FILE       redirect output messages to FILE; default: none
```
**result of --dump option**
- --CS-mode
```
$ cubrid vacuumdb --CS-mode --dump demodb
*** Vacuum Dump ***
First log page ID referenced = 93 …
```
> [CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum

- .github/workflows/check.yml
http://jira.cubrid.org/browse/CBRD-23876
_jitterbit/get-changed-files@v1_ sometimes spit errors in some corner cases.
The action still works and correctly displays the modified files so we can add continue-on-error: true to skip this issue.
> [CBRD-23860]  Continue on error in Github Checks while get-changed-files

- msg/de_DE.utf8/utils.msg
- msg/en_US.utf8/utils.msg
- msg/en_US/utils.msg
- msg/es_ES.utf8/utils.msg
- msg/fr_FR.utf8/utils.msg
- msg/it_IT.utf8/utils.msg
- msg/ja_JP.utf8/utils.msg
- msg/km_KH.utf8/utils.msg
- msg/ko_KR.euckr/utils.msg
- msg/ko_KR.utf8/utils.msg
- msg/ro_RO.utf8/utils.msg
- msg/tr_TR.utf8/utils.msg
- msg/vi_VN.utf8/utils.msg
- msg/zh_CN.utf8/utils.msg
- src/communication/network.h
- src/communication/network_cl.c
- src/communication/network_interface_cl.c
- src/communication/network_interface_cl.h
- src/communication/network_interface_sr.c
- src/communication/network_interface_sr.h
- src/communication/network_sr.c
- src/compat/db.h
- src/executables/util_admin.c
- src/executables/util_cs.c
- src/executables/utility.h
- src/query/vacuum.c
- src/query/vacuum.h
- src/transaction/boot.h
- src/transaction/boot_sr.c
- src/transaction/boot_sr.h
http://jira.cubrid.org/browse/CBRD-23881
backport #2629
The following is different compared to the develop branch modification.
- When using the --dump option in SA mode, VACUUM should not be performed. For this, I used the code committed in CBRD-23712 when modifying the develop branch. Currently, the modifications of CBRD-23712 are not merged in version 10.1, so only necessary parts have been applied.
- One of the messages is changed in the xvacuum_dump() function. Because, unlike the develop branch, the return value of vacuum_min_log_pageid_to_keep() may be NULL_PAGEID even after vacuum_initialize() in version 10.1. (The code is a little different.)
- AS-IS
- "vacuum did not boot properly."
- TO-BE
- "There are no log pages referenced by vacuum."
- The vacuum_Is_booted global variable …
> [CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum (#2629)

- src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-23888
Error -1106 (Multiple rows in source table match the same row in destination table.) occurs when using MERGE INTO statement with GROUP BY.
> [CBRD-23888] Error -1106 occurs when using MERGE INTO statement with GROUP BY

- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23901
disclose the dont_reuse_heap_file system parameter which has the hidden property on the source code.
> [CBRD-23901] Remove the hidden property of the dont_reuse_heap_file system parameter.

- src/base/system_parameter.c
http://jira.cubrid.org/browse/CBRD-23901
backport #2652
> [CBRD-23901] Remove the hidden property of the dont_reuse_heap_file system parameter. (#2652)

- src/optimizer/query_graph.c
- src/optimizer/query_graph.h
- src/optimizer/query_planner.c
http://jira.cubrid.org/browse/CBRD-23879
AS-is: When written in ANSI SQL syntax, the order of scan of tables cannot be changed.
```
select * from t1 inner join t2 on t1.a = t2.a left outer join t3 on t1.a = t3.a
t1->t2->t3 join order only can be selected
actually t2->t1->t3, t1->t3->t2 can be generated
```
To-be: Outer dependency is set only for outer joined tables.
Dependency is set based on the following two criteria.
1. Left outer join: The preceding table is set as a dependency.
2. Right outer join: The all preceding tables written in the ANSI SQL syntax are set as dependency.
(The right dep set is used to check the preceding tables of the right outer join)
> [CBRD-23879] Outer dependency is set improperly when rewriting SQL from outer join to inner join

- src/connection/server_support.c
- src/server/active_tran_server.cpp
http://jira.cubrid.org/browse/LETS-76
Construct the channels used by active_tran_server to communicate with the page_server and vice-versa with a timeout of 1 second (1000 milliseconds).
As consequence, the request server's don't poll without timeout and the servers do not hang during shutdown.
The patch also fixes the line endings of active_tran_server.cpp file. Use "Hide whitespace changes" setting to see only relevant differences.
> [LETS-76] Set 1 second timeout for ATS<->PS communication channel polls

- src/api/cci_stub.c
- src/broker/broker_log_util.c
- src/broker/broker_process_size.c
- src/broker/cas_dbms_util.c
- src/broker/shard_metadata.c
http://jira.cubrid.org/browse/CBRD-23899
Fix below item error detected by cppcheck
* src/api/cci_stub.c:2614:7: error: Uninitialized variable: res [uninitvar]
* src/api/cci_stub.c:3909:11: error: Uninitialized variable: tset [uninitvar]
* src/broker/broker_log_util.c:228:29: error: Uninitialized variable: size [uninitvar]
* src/broker/broker_process_size.c:469:3: error: Common realloc mistake: 'cntvalue_pid' nulled but not freed upon failure
* src/broker/broker_process_size.c:469:3: error: Common realloc mistake: 'cntvalue_pct_cpu' nulled but not freed upon failure
* src/broker/broker_process_size.c:469:3: error: Common realloc mistake: 'cntvalue_num_thr' nulled but not freed upon failure [memleakOnRealloc]
* src/broker/broker_process_size.c:469:3: error: Common realloc mistake: …
> [CBRD-23899] Fix errors detected by cppcheck in api, broker and cci

- .github/workflows/check.yml
http://jira.cubrid.org/browse/CBRD-23904
This makes Github Checks support some more branches besides develop.
- release/11.** : All the 11.x branches
- feature/**: All the feature branches
To make use of Github Checks, the proper branch prefix has to be used.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> [CBRD-23904] Github Checks to not only develop, but also feature and some release branch

- .github/workflows/check.yml
http://jira.cubrid.org/browse/CBRD-23900
This patch includes:
1. ignore directories when checking license
2. specify file formats to be checked when checking license
- .c .cpp .h .hpp .sh .bat .y .l .ipp .msg 
3. touch results files to prevent an error if no file has been changed during cppcheck
We could check a specific license header for each file format, but now just filter the file formats for convenience. 
We can improve it when the performance matters.
> [CBRD-23900] Limit license checking only to specific file formats

- src/parser/xasl_generation.c
- src/query/query_executor.c
http://jira.cubrid.org/browse/CBRD-23749
When the code-style tool was broken, the code with broken indentation was committed.
> [CBRD-23749] Fix indentation

- src/storage/slotted_page.c
http://jira.cubrid.org/browse/LETS-77
Extend condition to skip slotted page saved space to include also the situation when the server is in page server mode because this - slotted page saved space provisioning - has already been performed on the transaction server.
This occurred in stress testing of sequential replication executing on the page server.
> [LETS-77] Do not use slotted pages' saved space on page server.

- .github/workflows/check.yml
http://jira.cubrid.org/browse/CBRD-23908
I can't find an apt-repo to be able to install cppcheck over 1.9.0 version, so I've chosen to download the source and build manually.
> [CBRD-23908] Upgrade cppcheck version to 2.4.1 in Github Check

- src/base/ddl_log.c
- src/base/tz_support.c
- src/base/tz_support.h
- src/base/util_func.c
- src/broker/broker_util.c
- src/compat/db_vdb.c
- src/query/fetch.c
- src/query/query_executor.c
- src/query/string_opfunc.c
http://jira.cubrid.org/browse/LETS-68
‘int ftime(timeb*)’ is deprecated and should be replaced with the usage of functions from std::chrono
> [LETS-68] Fix -Wdeprecated-declarations caused by use of ftime

- CMakeLists.txt
http://jira.cubrid.org/browse/LETS-62
Unlock new C++ features by upgrading the compiler version from C+11 to C+17.
This unlocks the closing of [LETS-74] Fix tmpnam is dangerous warning by replacing with mkstemp
> [LETS-62] Upgrade to C++17

- .github/workflows/check.yml
http://jira.cubrid.org/browse/CBRD-23913
ㅉe are going to suppress each reported line if a developer assignee and reviewers agree an error on the line is a false positive. To do that, `--inline-suppr` option has to be turned.
> [CBRD-23913] Allow the inline suppressions of cppcheck

- src/query/cursor.c
http://jira.cubrid.org/browse/CBRD-22334
Purpose
In order to transmit the query result to the client, the error of copying the data of page0 to page1 when reading data from the page in the following order has been corrected.
page0 -> page1 -> page0 
Implementation
N/A
Remarks
N/A
> [CBRD-22334] Cursor Holdability on stmt, get wrong results by rs.absolute(num)

- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/cci/cas_cci.h
- src/parser/xasl_generation.c
- src/query/dblink_scan.c
- src/query/dblink_scan.h
- src/query/query_executor.c
- src/query/scan_manager.c
- src/query/scan_manager.h
- src/query/stream_to_xasl.c
- src/query/xasl.h
- src/query/xasl_to_stream.c
http://jira.cubrid.org/browse/CBRD-23907
dblink implementation
- add a new access spec
add a new node **dblink_node** to hybrid_node
``` 
union hybrid_node
{
CLS_SPEC_TYPE cls_node;	/* class specification */
...
METHOD_SPEC_TYPE method_node;	/* method specification */
DBLINK_SPEC_TYPE dblink_node; /* dblink specification */**
...
};	
```
- add a dblink_spec_node
```
struct dblink_spec_node
{
REGU_VARIABLE_LIST regu_list_p;	/* regulator variable list */
char *conn_url;		/* connection URL for remote DB server */
char *conn_user;		/* user name for remote DB server */
char *conn_password;		/* password for remote user */
char *conn_sql;		/* SQL command text for remote database */
};
```
- add new scan, dblink
```
struct regu_variable_list_node;
typedef struct dblink_scan_buffer …
```
> [CBRD-23907] POC: implementation of DBLink by cci

- src/parser/parse_tree.h
- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-23865
backport (#2570)
> [CBRD-23865] Hierarchical query execution time difference between V11 and V10.2 occurs when using SQL hints /*+ no_hash_list_scan */ (#2570)

- contrib/bash/csql
- contrib/bash/cubrid
http://jira.cubrid.org/browse/CBRD-23887
I wrote these for my own use and thought that they might benefit others as well.
Bash autocomplete for `cubrid` utility:
- distinguishes betweend the service's utilities and administrator's utilities
- is aware of the context and, for each utlity, list that utility's options (the long form only, as is customary for bash completion)
- is aware of the context and either lists - or not - the existing database names as well by parsing the names from the `$CUBRID_DATABASES/databases.txt` file
- caveat: uses a hardcoded list of both service's and administrator's utilities
Bash autocomplete script for `csql` utility:
- lists the name of the existing databases by parsing the `$CUBRID_DATABASES/databases.txt` file
If there are other utilities for which bash …
> [CBRD-23887] bash autocompletion scripts for cubrid and csql utilities

- CMakeLists.txt
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/CBRD-23912
1) QA requests "Coverage" and "Profile" prints like "coverage debug" and "profile debug"
2) Print "RelWithDebInfo" as "release"
3) Print the build type string when starting utility (e.g. createdb)
> [CBRD-23912] Revise printing build type string and Fix slip for utility

- src/base/ddl_log.c
- src/base/util_func.c
- src/base/util_func.h
- src/broker/broker_util.c
- src/compat/db_vdb.c
- src/query/fetch.c
- src/query/query_executor.c
- src/query/string_opfunc.c
- win/cubridcs/cubridcs.def
http://jira.cubrid.org/browse/LETS-86
On CentOS devtoolset-8 system compile fails because timespec_get and TIME_UTC are not found, even though the C++17 documentation includes them.
Quick fix by using std::chrono::now() and building the seconds/millisecond parts that were initially generated using the deprecated function ftime.
Some of the changes in db_vdb.c made by #2646 have been reverted.
> [LETS-86] Replace timespec_get with chrono functions

- src/broker/broker_admin_pub.c
- src/broker/broker_config.c
http://jira.cubrid.org/browse/CBRD-23883
Purpose
* backport #2617 to 11.0.1
* Fix broker keyword **_JDBC_CACHE_ONLY_HINT_** to **JDBC_CACHE_HINT_ONLY** as in CUBRID Manual
Implementation
N/A
Remarks
N/A
> [CBRD-23883] backport #2617 to 11.0.1, JDBC_CACHE_HINT_ONLY

- src/loaddb/load_session.cpp
http://jira.cubrid.org/browse/CBRD-23891
Purpose
* backport #2665 to 11.0.1
* Fix num instances committed in loaddb CS
Implementation
N/A
Remarks
N/A
> [CBRD-23891] backport #2665 to 11.0.1, fix num_instance for loaddb cs

- src/loaddb/load_class_registry.hpp
http://jira.cubrid.org/browse/CBRD-23890
Purpose
* backport #2630 to 11.0.1
* Change std::uunordered_map to std::map to fix **update stat order**
Implementation
N/A
Remarks
N/A
> [CBRD-23890] backport #2630 to 11.0.1, std::uunordered_map to std::map

- src/loaddb/load_sa_loader.cpp
http://jira.cubrid.org/browse/CBRD-23906
Purpose
* backport #2669, to 11.0.1
* Do update statistics on all tables, even for the table with number inserted is 0.
Implementation
N/A
Remarks
N/A
> [cbrd-23906] backport #2669 to 11.0.1, do update stat on all tables in loaddb SA

- src/parser/semantic_check.c
http://jira.cubrid.org/browse/CBRD-23877
```
csql> CREATE TABLE nvl_tbl3 AS SELECT SUM(1),MAX(1),COUNT(*),NVL(1,'');
Execute OK. (0.006011 sec) Committed.
1 command(s) successfully processed.
csql> ;sc nvl_tbl3
=== <Help: Schema of a Class> ===
<Class Name>nvl_tbl3<Attributes>sum(1) INTEGER
max(1) INTEGER
count(*) INTEGER
nvl(1, '') CHARACTER VARYING(1073741823)
csql> DESC nvl_tbl3;
=== <Result of SELECT Command in Line 1> ===
Field Type Null Key Default Extra
===================================================================================
'sum(1)' 'INTEGER' 'YES' '' NULL ''
'max(1)' 'INTEGER' 'YES' '' NULL ''
'count(*)' 'INTEGER' 'YES' '' NULL ''
'nvl(1, '')' 'VARCHAR(1073741823)' 'YES' '' NULL '' 
```
**Expected**
`ERROR: Missing an expected attribute name for sum(1). `
Unlike the …
> [CBRD-23877] To CREATE a table as SELECT query, the alias of attributes should be checked.

- .circleci/config.yml
http://jira.cubrid.org/browse/CBRD-23921 
Circleci cannot find jdbc source directory after the JDBC repository is separated.
It needs to update jdbc source which is the submodule.
> [CBRD-23921] JDBC error when building with circleci.

- src/broker/cas_function.c
http://jira.cubrid.org/browse/CBRD-23915
Purpose
In SQL_LOG for binding VARCHAR variable, length will indicate number characters not number bytes.
Implementation
N/A
Reference
N/A
> [CBRD-23915] backport #2698 to 11.0.1, log num chars in sql_log for bind VARCHAR variables

- src/broker/broker_config.c
http://jira.cubrid.org/browse/CBRD-23860
Purpose
* At the broker startup of the BROKER, the keyword validation check will be executed.
* And if there is an error, it will be terminated.
Implementation
N/A
Reference
N/A
> [CBRD-23860] Do broker keyword integration check

- src/object/object_domain.h
- src/parser/xasl_generation.c
- src/query/execute_schema.c
http://jira.cubrid.org/browse/CBRD-23878
```
csql> CREATE TABLE nvl_tbl1 AS SELECT NVL(x,111) AS x, NVL(y,'aaa') AS y, NVL(z,sysdatetime) AS z FROM tbl1;
Execute OK. (0.004824 sec) Committed.1 
command(s) successfully processed.
csql> ;sc nvL_tbl1
=== <Help: Schema of a Class> ===
<Class Name> 
nvl_tbl1
<Attributes>
x INTEGER
y STRING
z DATETIME
```
**Expected:**
```
<Attributes>
x INTEGER 
y VARCHAR(1073741823) 
z DATETIME
```
This is an issue that occurs because the data value of the string type is copied and the precision of the domain is not copied in the process of creating a column through pt_make_regu_arith with the CREATE TABLE AS SELECT statement. For string type domain, the default precision is -1, and this value should be copied from the precision of the data value
> [CBRD-23878] To prevent setting the precision to -1 for STRING type as derived attribute

- src/object/object_domain.h
- src/query/execute_schema.c
…
http://jira.cubrid.org/browse/CBRD-23878
backport #2612
> [CBRD-23878] To prevent setting the precision to -1 for STRING type as derived attribute (#2612)

- src/loaddb/load_object.c
http://jira.cubrid.org/browse/CBRD-23898
the NULL checking for the _buf_ should be performed only for unformatted print.
it caused by #2673. Sorry for missing it while the code review.
> [CBRD-23898] Fix for formatted print

- src/broker/cas.c
http://jira.cubrid.org/browse/CBRD-21908
Purpose
* When there is only one CAS and the CAS and the client are communicating, a "Connection reset" error occurs in the client when the CAS is restarted because the memory used by the CAS exceeds APPL_SERVER_MAX_SIZE.
* To prevent "Connection reset" error, when CAS is terminated, closesocket() was added.
Implementation
N/A
Remarks
N/A
> [CBRD-21908] "cubrid.jdbc.driver.CUBRIDException: Cannot communicate with the broker" when there is one cas on windows

- src/base/perf_monitor.c
- src/transaction/boot_sr.c
http://jira.cubrid.org/browse/LETS-92
The function `perfmon_finalize` does not properly reset `n_watchers` in case the values was incremented because of enabled `PRM_ID_STATS_ON`.
This is visible, for instance, if perfmon logging is always active - `stats_on` parameter is on - and other modules want to do performance logging after the perfmon module is cleaned-up - `boot_server_all_finalize`.
> [LETS-92] Fix perfmon init/finalize of 'n_watchers' when 'stats_on' enabled

- src/thread/thread_entry.cpp
- src/thread/thread_entry.hpp
- src/thread/thread_entry_task.cpp
- src/thread/thread_entry_task.hpp
- src/transaction/log_page_async_fetcher.cpp
- src/transaction/log_page_async_fetcher.hpp
http://jira.cubrid.org/browse/LETS-93
Fix for, when perfmon logging is activated, the tasks dispatched by the `async_page_fetcher` fail upon perfmon calls because of null `tran_index`.
> [LETS-93] Proper transaction index for async log page fetcher threads

- src/api/cci_stub.c
- src/broker/broker_log_util.c
- src/broker/broker_process_size.c
- src/broker/cas_dbms_util.c
- src/broker/shard_metadata.c
http://jira.cubrid.org/browse/CBRD-23899
Purpose
* Backport #2657 to 11.0.1
* Fix errors detected by cppcheck in api, broker
Implementation
N/A
Remarks
N/A
> [CBRD-23899] Backport #2657 to 11.0.1, Fix errors detected by cppcheck in api, broker

- contrib/CMakeLists.txt
- contrib/windows_scripts/cubrid_env.bat
http://jira.cubrid.org/browse/CBRD-21446
Purpose
* backport #2641 to 11.0.1
* Modify the example file for setting CUBRID environment variables.
Implementation
N/A
Remarks
N/A
> [CBRD-21446] backport #2641 to 11.0.1, Installing CUBRID with zip on Windows, cubrid server start fail.

- src/broker/broker_log_converter.c
- src/broker/broker_log_util.c
http://jira.cubrid.org/browse/CBRD-23915
Purpose
* Log more meaningful information in SQL_LOG for binding VARCHAR variables:
* Log num chars instead of num bytes
* backport #2748 to 11.0.1
Implementation
N/A
Remarks
N/A
> [CBRD-23915] backport #2748 to 11.0.1, broker_log_converter

- src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-23932
fix memory leak
> [CBRD-23932] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:455

- src/query/scan_manager.c
http://jira.cubrid.org/browse/CBRD-23828
backport #2739
> [CBRD-23828] fix comment of trace

- build.sh
http://jira.cubrid.org/browse/CBRD-23912
Purpose
In the QA system, there is no .git in the source for coverage builds.
Therefore, a version information file is required when versioning JDBC.
- Related to https://github.com/CUBRID/cubrid-jdbc/pull/14
> [CBRD-23912] JDBC version error in coverage build on the QA system

- src/object/schema_manager.c
- src/storage/oid.h
http://jira.cubrid.org/browse/CBRD-23941
For more information, see the Jira issue.
As a side note,  I've removed a function for "< (lt)" and added one for "!=". The former seems better to add when it is needed, and the latter is for consistency with "==" defined.
> [CBRD-23941] Remove the global type declaration, unordered_oid_set

- src/base/mprec.c
- src/compat/cnvlex.c
- src/executables/csql_result_format.c
- src/object/set_object.c
With the upgrade to C++17 a new type of warning will appear as 
`ISO C++17 does not allow 'register' storage class specifier.`
This PR will remove all `register` specifiers in the project.
> [CBRD-23914] Fix -Wregister warnings 

- src/executables/javasp.cpp
The error message is too small for `Error while opening file` text and a full info_path.
> [CBRD-23914] Fix -Wformat-truncation warnings

- .circleci/config.yml
http://jira.cubrid.org/browse/CBRD-23944
1) `resource_class` for `build` workflow is upgraded to `large`
2) upgrade MAKEFLAGS value from 2 to 10 (large machine provide 4 virtual CPUs, but the build was fast slightly when I set 10)
4) set parallelism from 4 to 8 for SQL test
> [CBRD-23944] Upgrade Parallel level for CircleCI

- src/connection/connection_cl.c
- src/connection/connection_sr.c
http://jira.cubrid.org/browse/LETS-96
Fix for problems introduced by [LETS-74] Fix tmpnam is dangerous warning by replacing with mkstemp:
* css_free_conn could be called twice on the same structure
* socket_fd remained open if css_send_data failed
> [LETS-96] Correct the error handling in some css_connect_to_master_server cases

- src/transaction/log_checkpoint_info.cpp
- src/transaction/log_checkpoint_info.hpp
- src/transaction/log_manager.c
- src/transaction/log_manager.h
- src/transaction/log_page_buffer.c
- src/transaction/log_recovery.c
- unit_tests/log_transfer/test_main_log_meta.cpp
http://jira.cubrid.org/browse/LETS-11
Rewrite checkpoint handling (in logpb_checkpoint and recovery analysis implementation) to use meta log checkpoint info map instead of log records. As a result checkpoint becomes usable on the page server.
**logpb_checkpoint**
- Reactivate checkpoint for page server
- Use checkpoint_info functions and remove all code that added log records and loaded transaction table information into the end checkpoint log record.
- Instead of using LOG_START_CHKPT start_lsa as checkpoint LSA, use log_Gl.prior_info.prev_lsa, the LSA of last appended log record. LSA of last record was chosen instead of end of log LSA because checkpoint LSA has to be less than nxio_lsa.
- Replaced tmp_chkpt.redo_lsa with oldest_unflushed_lsa & new_chkpt_redo_lsa. oldest_unflushed_lsa is …
> [LETS-11] Rewrite checkpoint using meta log checkpoint information.

- src/base/ddl_log.c
- src/broker/broker_shm.h
- src/cci/cci_handle_mng.c
- src/executables/unload_object.c
- src/storage/file_io.c
Comparison between signed and unsigned variables generate warnings.
To fix this the variable type was changed where possible and cast were used where not.
> [CBRD-23914] Fix -Wsign-compare

- src/broker/cas.c
http://jira.cubrid.org/browse/CBRD-21908
Purpose
* When there is only one CAS and the CAS and the client are communicating, a "Connection reset" error occurs in the client when the CAS is restarted because the memory used by the CAS exceeds APPL_SERVER_MAX_SIZE.
* To prevent "Connection reset" error, when CAS is terminated, closesocket() was added.
* **Applies only to Windows**
Implementation
N/A
Remarks
N/A
> [CBRD-21908] cubrid.jdbc.driver.CUBRIDException: Cannot communicate with the broker" when there is one cas on windows

- src/base/ddl_log.c
- src/base/tz_support.c
- src/base/tz_support.h
- src/base/util_func.c
- src/base/util_func.h
- src/broker/broker_util.c
- src/compat/db_vdb.c
- src/query/fetch.c
- src/query/query_executor.c
- src/query/string_opfunc.c
- win/cubridcs/cubridcs.def
The use of ftime is deprecated and should be replaced with functions from std::chrono
> [CBRD-23914] Deprecated usage of ftime

- src/parser/parser.h
- src/parser/parser_support.c
http://jira.cubrid.org/browse/CBRD-23928
Purpose
Changing it to a macro would be more efficient.
Implementation
N/A
Remarks
N/A
> [CBRD-23928] Change pt_has_error() function to macro

- src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
http://jira.cubrid.org/browse/APIS-869
Purpose
The default value of hold_cursor was changed to TRUE.
Implementation
N/A
Remarks
N/A
> [APIS-869] Administrative setting of CUBRID jdbc property

- src/parser/csql_grammar.y
http://jira.cubrid.org/browse/CBRD-23947
Purpose
Error handling for the limit value exceeding the appropriate size in relation to the string type in the create tabel syntax
Implementation
N/A
Remarks
N/A
> [CBRD-23947] A problem that succeeds even when the size of the CHAR or VARCHAR type exceeds MAX when creating a table.

- src/optimizer/query_rewrite.c
- src/parser/name_resolution.c
- src/parser/parse_dbi.c
- src/parser/parse_tree_cl.c
- src/parser/parser.h
- src/parser/parser_support.c
- src/parser/semantic_check.c
- src/parser/view_transform.c
- src/parser/xasl_generation.c
http://jira.cubrid.org/browse/CBRD-23929
Purpose
N/A
Implementation
Modify & Add init functions.
Used when initializing the node for the first time after creation:
PT_NODE * parser_init_node (PT_NODE * node, PT_NODE_TYPE node_type);
Used when re-initializing an existing Node while in use:
PT_NODE * parser_reinit_node (PT_NODE * node);
Remarks
N/A
> [CBRD-23929]  Improved use of parser_init_node() function

- src/object/schema_manager.c
- src/storage/heap_file.c
- src/storage/system_catalog.c
http://jira.cubrid.org/browse/CBRD-23937
See the Jira issue for more information.
As a side note, I've removed "log_does_allow_replication()" condition checking in the code that was commented out. According to my analysis and test, TRUNCATE is logged as one of Statement Based Logging, and it looks working well with destroying heap even if the PK is not dropped. I guess it is a kind of legacy code.
> [CBRD-23937] Recreating heap file while TRUNCATE if REUSE_OID	

- cs/CMakeLists.txt
- cubrid/CMakeLists.txt
- sa/CMakeLists.txt
- src/base/filesys.hpp
- src/base/filesys_temp.cpp
- src/base/filesys_temp.hpp
- src/connection/connection_cl.c
- src/connection/connection_sr.c
- src/connection/tcp.c
- src/connection/tcp.h
- src/executables/csql.c
- src/executables/csql_support.c
- src/executables/file_hash.c
The usage of tmpnam is considered dangerous, this patch replaces usages of the function with std variants and adds the usage of filesystem library.
> [CBRD-23914] Fix tmpnam is dangerous warning by replacing with mkstemp
