CUBRID/cubrid

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20212

[CBRD-20212] Unlock object after serialization error.

---

src/query/vacuum.c
src/storage/page_buffer.c
src/storage/page_buffer.h

Fixed several cases of vacuum data page leaks.
Added debug code (especially related to vacuum data page leaks).
Fixed infinite loop in vacuum_rv_redo_append_data_dump.

[CBRD-20220] Fix vacuum data page leaks.

---

src/query/vacuum.c

Fix compile error inroduced with 1bafa910fddd05da795a50c14c68305037c8e1b9.

[CBRD-20220] Fix compile error

---

CMakeLists.txt
broker/CMakeLists.txt
cas/CMakeLists.txt
cci/CMakeLists.txt
cm_common/CMakeLists.txt
conf/CMakeLists.txt
config.h.cmake
contrib/CMakeLists.txt
cs/CMakeLists.txt
cubrid/CMakeLists.txt
demo/CMakeLists.txt
demo/make_cubrid_demo.bat
java/CMakeLists.txt
jdbc/CMakeLists.txt
locales/CMakeLists.txt
msg/CMakeLists.txt
sa/CMakeLists.txt
timezones/CMakeLists.txt
tools/CMakeLists.txt
util/CMakeLists.txt
win/CMakeLists.txt

CMake 2.8 or higher version is required for Linux and 3.5 or higher version is required for Windows build.
How to build with cmake:
- Linux 64bit Debug
```
$ mkdir build_dir
$ cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=<Path for installation> ..
$ make # or cmake --build .
$ make install  # or cmake --build . --target install
```
- Linux 64bit Release
```
$ mkdir build_dir
$ cmake -DCMAKE_BUILD_TYPE= RelWithDebInfo -DCMAKE_INSTALL_PREFIX=<Path for installation> ..
$ make # or cmake --build .
$ make install  # or cmake --build . --target install
```
- Windows 32bit (Debug or Release)
```
$ mkdir build_dir
$ cmake.exe -G "Visual Studio 9 2008" -DCMAKE_INSTALL_PREFIX=<Path for installation> ..
$ cmake --build . --config <Debug | RelWithDebInfo>
$ cmake --build . --config <Debug | …
```

[CBRD-20155] support CMake for linux and windows build

---

src/query/list_file.c

[CBRD-20246] fixes infinite iteration of getting a list file page. also fixes to correctly detect the end of a list file page.

---

src/executables/util_sa.c

http://jira.cubrid.org/browse/CBRD-20258
The error manager was not available. This is a regression case of [CBRD-20037](http://jira.cubrid.org/browse/CBRD-20037).

[CBRD-20258] fixes gen_tz to start error manager to show error messages

---

src/transaction/log_applier.c

http://jira.cubrid.org/browse/CBRD-20266

[CBRD-20266] Handle RVHF_UPDATE_NOTIFY_VACUUM / REC_RELOCATION combination

---

msg/fr_FR.utf8/utils.msg
msg/ro_RO.utf8/utils.msg
src/query/query_executor.c
src/query/query_manager.c
src/storage/disk_manager.c
src/transaction/log_applier.c

{fr_FR.utf8,ro_RO.utf8}/utils.msg included trailing blanks after the line continuation. Some also missed the line continuation. 
The fix also accidentally includes code layout fixes. Hope you mind it.

[CBRD-20270] fixes broken message of utils.msg

---

src/object/work_space.c
src/object/work_space.h

remove dead stuffs from workspace manager. 
We will handle MOP->mvcc_link and MOP->permanent_mvcc_link later.

[CBRD-20271] remove unused workspace manager stuffs

---

src/executables/unittests_cqueue.c
util/CMakeLists.txt

This is an unit test code to model vacuum_Finished_job_queue which has 1 consumer and 50 producers by default.

[CBRD-20252] add unit test for latch free circular queue

---

src/transaction/locator_cl.c
src/transaction/locator_sr.c

* Also added another check for valid OID in xlocator_does_exist when object class is known.

[CBRD-20304] Fix getting real instance when checking a virtual object does exist

---

cubrid/CMakeLists.txt

Install dbi_compat.h file for public dbi.h header file

[CBRD-20314] fix for public header file dbi.h

---

src/transaction/log_manager.c
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-20336

[CBRD-20336] Fix condition to acquire log cs : use full page id instead of log_lsa to trigger flushing

---

src/query/execute_statement.c

Authentication disable was missing in the do_insert_checks function.

[CBRD-20334]: ERROR: SELECT authorization failure.

---

src/query/execute_statement.c

This should fix both [CBRD-20334] and [CBRD-20333]. Moved the authentication one step above, in `do_prepare_insert` .
http://jira.cubrid.org/browse/CBRD-20334
http://jira.cubrid.org/browse/CBRD-20333

[CBRD-20334] Authentication issues

---

src/transaction/lock_manager.c

http://jira.cubrid.org/browse/CBRD-20349

[CBRD-20349] fix potential overflow of lock hash value

---

src/base/lock_free.c

http://jira.cubrid.org/browse/CBRD-20355

[CBRD-20355] remove duplicated lf_tran_end from lf_list_find

---

src/base/lock_free.c
src/base/lock_free.h

http://jira.cubrid.org/browse/CBRD-20361

[CBRD-20361] Remove LF_LIST_BR_RESTARTED flag from bflags before restarting delete

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20354

[CBRD-20354] Move locking from xcache_find_sha1 to xcache_find_xasl_id

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20364

[CBRD-20364] Save SQL info even if XASL cache logging is disabled

---

src/base/binaryheap.c

http://jira.cubrid.org/browse/CBRD-20358

[CBRD-20358] bh_to_sorted_array: stop swapping when there is only one element left in the binary heap

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20358

[CBRD-20358] Initialize xcache_entry->time_last_rt_check

---

src/query/filter_pred_cache.c

http://jira.cubrid.org/browse/CBRD-20371

[CBRD-20371] Deallocate filter predicate DB_VALUES when cache entry is uninitialized

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20370

[CBRD-20370] Initialize xcache_entry->time_last_used

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20359

[CBRD-20359] add sql_user_text to xcache_dump

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20375
* The cleanup count is now considering all entries above capacity besides a percentage of capacity.
* The preallocated binary heap capacity is set to MAX (2 * cleanup ratio * capacity, 20)
* If preallocated binary heap cannot be used, a binary heap big enough to handle cleanup count is allocated.

[CBRD-20375] Clean 20% of xasl cache capacity and all entries over the capacity

---

src/query/filter_pred_cache.c
src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20384

[CBRD-20384] Reverse compare result in xcache_compare_cleanup_candidates and fpcache_compare_cleanup_candidates

---

src/cm_common/cm_dep_tasks.c
src/compat/db_macro.c
src/executables/csql_result_format.c
src/executables/load_object.c
src/executables/unload_schema.c
src/jsp/jsp_cl.c
src/object/object_domain.c
src/object/object_print.c
src/parser/parse_dbi.c
src/query/numeric_opfunc.c
src/query/numeric_opfunc.h
src/query/string_opfunc.c
src/thread/thread.h

http://jira.cubrid.org/browse/CBRD-20393

[CBRD-20393] remove qp_num_buf from THREAD_ENTRY

---

src/object/object_domain.c

http://jira.cubrid.org/browse/CBRD-20400
It is a slip of #153.

[CBRD-20400] fixes ABW of casting numeric to string

---

src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-20343

[CBRD-20343] Fix recovery : put tran state into aborted and prevent tdes freeing to allow undo.

---

src/communication/network_interface_cl.c
src/communication/network_interface_sr.c
src/connection/connection_sr.c
src/connection/server_support.c

[CBRD-20391] apply indent and rewrite sqmgr_query_execute

---

src/storage/file_io.c

http://jira.cubrid.org/browse/CBRD-20376

[CBRD-20376] fix to create parent of APPLYLOGDB directory if not exist

---

src/query/list_file.c
src/query/query_opfunc.c
src/storage/heap_file.c

[CBRD-20422] add assertions to catch ER_TF_BUFFER_OVERFLOW error cases

---

src/object/object_primitive.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20425
http://jira.cubrid.org/browse/CBRD-20426
Need confirmation for http://jira.cubrid.org/browse/CBRD-20424
This fixes for sure [CBRD-20425] and [CBRD-20426] but will need confirmation for [CBRD-20424].
Running regressions and update here once they are done.

[CBRD-20426] Fixed bad setup in compare functions

---

src/object/object_primitive.c
src/object/object_primitive.h
src/object/object_representation.c
src/query/query_opfunc.c

1. Added error handling of `pr_get_size_and_write_string_to_buffer`
2. Beautify code layout.

[CBRD-20430] error handling, beautify code layout

---

src/query/query_opfunc.c
src/storage/heap_file.c
src/transaction/locator_sr.c

Fix the mistake introduced from the actual fix of CBRD-20449.

[CBRD-20449](2) Fix bad error handling from #199

---

src/executables/unittests_lf.c

* adds unit test for freelist w/o transaction mode
* fixes warnings

[CBRD-20451] add unit test for freelist w/o transaction mode

---

src/parser/csql_lexer.c
src/parser/csql_lexer.l

http://jira.cubrid.org/browse/CBRD-20465
It is a legacy defect.

[CBRD-20465] DDL with C-style comment includes '*' will not be properly replicated.

---

src/base/sha1.h
src/communication/network_interface_sr.c
src/query/scan_manager.c
src/transaction/log_impl.h

[CBRD-20146] fix warnings

---

contrib/gdb_debugging_scripts/log_records.gdb
src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-20460
@eseokoh 
Added some debugging code to get more details on what happens when the issue is reproduced.

[CBRD-20460] Not to deallocate the last page of vacuum data

---

src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-20481

[CBRD-20481] fix overflow to calculate location of LOG_PAGE

---

src/transaction/locator.h
src/transaction/locator_sr.c

Fix object descriptor pointers in case area is realloced

[CBRD-20467] Fix object descriptor objects after area reallocation; fix size of object descriptor.

---

src/base/system_parameter.c
src/base/system_parameter.h
src/transaction/log_page_buffer.c

It was hard to debug log page buffer errors, so I added a new system parameter to log the operations that are done here. Also, the function flush_all_append_pages was refactored.

[CBRD-20483] Added logging for log page buffer and changed flush_all_append_pages

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-20477
I am not sure this will also fix the mentioned issue. However, the bug is also related to vacuum data cursor.
Thank you @funkydvd for discovering it.

[CBRD-20477] Fix the condition of resetting vacuum data cursor.

---

msg/fr_FR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-20495

[CBRD-20495] fix typo on a msg of MSGCAT_UTIL_SET_DIAGDB

---

src/query/vacuum.c
src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-20516

[CBRD-20516] fix vacuum being executed again when it was actually completed

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-20517
Slipped from #244 .

[CBRD-20517] Fix UMR of can_vacuum from vacuum_rv_check_at_undo

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20519

[CBRD-20519] fixed search (OID, MVCC info) in btree key buffer in case of multi updates

---

src/base/perf_monitor.c

http://jira.cubrid.org/browse/CBRD-20539

[CBRD-20539] statdump -s option never ended

---

src/base/perf_monitor.c

http://jira.cubrid.org/browse/CBRD-20534

[CBRD-20534] fix PSTAT_QM_NUM_HOLDABLE_CURSORS as SINGLE_PEEK stat

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20537

[CBRD-20537] heap_delete_logical, heap_update_logical: catch ER_INTERRUPTED error

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20530
I found an issue in code, in heap_update_relocation function, when update relocation -> relocation for instance:
In this case, if the forward page was unfixed meanwhile, we need to read again the forward record.
Otherwise, the following scenario may occur:
* the current transaction reads the forward recdes having valid INSID
* the current transaction calls ordered fix for new home page and unfix the forward page
* VACUUM clears INSID from forward recdes
* current transaction fixes again the forward page, but uses the initial forward recdes (having valid INSID)
* current transaction executes rollback, forward recdes with INSID is wrongly inserted
* concurrent transactions can't find enough free space

[CBRD-20530] corrects the undo record descriptor if forward page is unfixed during relocation update

---

src/transaction/locator_sr.c

http://jira.cubrid.org/browse/CBRD-20523
TestCase for this change will be loaded into the repository 'cubrid-testcases'
sql/_30_banana_pie_qa/issue_20523_foreign_key/

[CBRD-20523] Foreign Key Referential Constraints check on INSERT/UPDATE

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20149

[CBRD-20149] xcache: fix perfmon statistics for full cache and for deleted entries

---

src/base/perf_monitor.c
src/base/perf_monitor.h

http://jira.cubrid.org/browse/CBRD-20551

[CBRD-20551] fix compile warnings of perf_monitor

---

src/storage/heap_file.c
src/storage/heap_file.h

http://jira.cubrid.org/browse/CBRD-20550

[CBRD-20550] avoid multiple calls of or_mvcc_add_header at heap delete

---

src/base/perf_monitor.c
src/base/perf_monitor.h
src/query/xasl_cache.c
src/session/session.c
src/storage/heap_file.c
src/thread/thread.c

http://jira.cubrid.org/browse/CBRD-20541

[CBRD-20541] retrieve PSTAT_PEEK_SINGLE_VALUE typed performance statistics

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20554

[CBRD-20554] Optimizes heap deletion by skipping pack, unpack for unmodified fields

---

src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-20557

[CBRD-20557] Fix readmem string to handle compression.

---

src/base/perf_monitor.c
src/base/perf_monitor.h
src/thread/thread.c

http://jira.cubrid.org/browse/CBRD-20541

[CBRD-20541] Use perfmon_set_stat for PSTAT_HA_REPL_DELAY peek statistic

---

src/base/object_representation.h
src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20558

[CBRD-20558] Optimizes heap updating by skipping pack, unpack when possible

---

src/base/object_representation.h
src/object/object_representation.c
src/query/vacuum.c
src/storage/heap_file.c
src/storage/heap_file.h

http://jira.cubrid.org/browse/CBRD-20560

[CBRD-20560] Optimizes heap vacuum by skipping unpack for unmodified fields

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20583
Added another condition for clearing local `DB_VALUE`.

[CBRD-20583] Fixed leak

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20587
This is a slip of #297 
`DB_GET_OID` function returns `NULL_OID` when the value is NULL, while its macro version returns NULL pointer. 
Patch also includes a quick fix to `DB_GET_OID` calls from `qexec_execute_update` to keep the existing behavior.

[CBRD-20587] fixes NULL pointer references returned from DB_GET_OID macro

---

src/query/fetch.c

This fixes:
http://jira.cubrid.org/browse/CBRD-20606
http://jira.cubrid.org/browse/CBRD-20607
http://jira.cubrid.org/browse/CBRD-20608

[CBRD-20606] revert potential leak fix on fetch_val_list

---

src/compat/dbi_compat.h

dbi_compat.h: add missing changes from DB_CHAR structure

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20613
Fixed clearing of a local `DB_VALUE`.

[CBRD-20613] Fix memory leak

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-20618
File is removed from tracker twice. Remove duplicate removal.

[CBRD-20618] file_tracker_reclaim_marked_deleted: fix remove file

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20623

[CBRD-20623] disk_set_creation: initialize addr

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20622
> cubrid createdb -r temp en_US
When database is recreated, disk_cache_init is called twice. first by boot_remove_all_volumes and again by disk_format_first_volume.
Expect that disk_Cache may be already loaded and reload it in disk_manager_init.

[CBRD-20622] disk_manager_init: reload disk_Cache if it was previously loaded

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20619
File descriptor usually stored the class OID. One exception to this rule is boot_Db_parm file which has no class.

[CBRD-20619] heap file: expect NULL class_oid for boot_Db_parm

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20630
btree_key_append_object_as_new_overflow can be called by btree_key_relocate_last_into_ovf, which already starts a system operation. fix by expecting the case and by handling it properly.

[CBRD-20630] btree_key_append_object_as_new_overflow: handle case when sysop is already started

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20185
fix disk_map_clone functions

[CBRD-20185] disk_map_clone: fix accessing the entries for volids >= 1

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20645
collect temp volume expands

[CBRD-20645] collect temp volume expands

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20636

[CBRD-20636] disk_format: fix computing max_npages

---

src/transaction/log_recovery.c

http://jira.cubrid.org/browse/CBRD-20185
log_rv_redo_fix_page: try to do "if not deallocated" first even if rcvindex is new page initialization to avoid applying changes that already exist

[CBRD-20185] log_rv_redo_fix_page: don't call fix NEW_PAGE directly

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-20649

[CBRD-20649] file_temp_retire: fix leak

---

src/storage/extendible_hash.c

http://jira.cubrid.org/browse/CBRD-20635

[CBRD-20635] ehash_create_helper: initialize variables

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-20638

[CBRD-20638] file_dealloc: accept FILE_HEAP hint when file is FILE_HEAP_REUSE_SLOTS

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20637
btree_modify_overflow_link, btree_modify_leaf_ovfl_vpid: system op is always started

[CBRD-20637] fix btree_modify_overflow_link, btree_modify_leaf_ovfl_vpid

---

src/storage/slotted_page.c

http://jira.cubrid.org/browse/CBRD-20624

[CBRD-20624] spage_header_start_scan: fix when page is deallocated

---

src/storage/disk_manager.c
src/transaction/recovery.h

http://jira.cubrid.org/browse/CBRD-20662
* include RVDK_FORMAT and RVDK_INITMAP to page initialization recovery indexes
* update disk cache on RVDK_FORMAT undo/redo

[CBRD-20662] fix RVDK_FORMAT and RVDK_INITMAP recovery

---

src/session/session.c
src/storage/file_manager.c
src/storage/file_manager.h

http://jira.cubrid.org/browse/CBRD-20665

[CBRD-20665] sentry_to_quentry: save tran temporary file to cache

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-20666

[CBRD-20666] file_alloc: goto exit on error

---

src/storage/extendible_hash.c

http://jira.cubrid.org/browse/CBRD-20667

[CBRD-20667] ehash_expand_directory: call file_alloc_multiple if needed_pages > 0

---

src/storage/file_manager.c
src/storage/file_manager.h
src/storage/overflow_file.c

http://jira.cubrid.org/browse/CBRD-20668

[CBRD-20668] init overflow temporary pages

---

src/storage/external_sort.c

http://jira.cubrid.org/browse/CBRD-20673

[CBRD-20673] sort_checkalloc_numpages_of_outfiles: handle errors

---

src/storage/slotted_page.c

http://jira.cubrid.org/browse/CBRD-20675

[CBRD-20675] spage_slots_start_scan: expect invalid page

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-20689
Even though file_destroy was called, the sectors unreserve was only logged using LOG_POSTPONE, but it was never executed. The correct way of destroying the file is aborting system operation.

[CBRD-20689] btree_load_index: fix destroying empty index

---

src/storage/file_manager.c
src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-20685

[CBRD-20685] file_extdata_collect_ftab_pages: fix adding new VSID

---

src/storage/storage_common.h

http://jira.cubrid.org/browse/CBRD-20693

[CBRD-20693] fix SECTOR_LAST_PAGEID

---

src/base/system_parameter.c

[CBRD-20416] temporarily disable xasl clone

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-20720
This fixes a slip of #371.

[CBRD-20720] fix page latch leak of file_extdata_find_and_remove_item

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20714
It also fixes http://jira.cubrid.org/browse/CBRD-20683, but scenario have to be revised because volume sizes have changed.

[CBRD-20714] Fix typo in volume extension resolve

---

src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-20721

[CBRD-20721] fixed crash caused by clear compressed string

---

src/base/system_parameter.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20726

[CBRD-20726] fixed crash caused by aggregate operand casting

---

src/base/system_parameter.c
src/query/query_evaluator.h
src/query/query_executor.c
src/query/stream_to_xasl.c

http://jira.cubrid.org/browse/CBRD-20729

[CBRD-20729] fixed aggregate domain issue

---

src/base/system_parameter.c
src/query/query_evaluator.h
src/query/query_executor.c
src/query/query_list.h
src/query/stream_to_xasl.c

http://jira.cubrid.org/browse/CBRD-20724

[CBRD-20724] Fixed median issue

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20728

[CBRD-20728] Clear scan id statistics

---

src/query/query_executor.c
src/storage/btree.c
src/storage/file_manager.c
src/storage/overflow_file.c
src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-20744
Some of system operation were not properly ended or badly handled.

[CBRD-20744] fixes system operation leaks

---

src/storage/file_manager.c

Supplementary fixes:
* fix typos on FILE_TEMPCACHE_AS_ARGS
* add debugging function of file_tempcache_check_duplicate

[CBRD-20748] fix typos of FILE_TEMPCACHE_AS_ARGS; add file_tempcache_check_duplicate debugging function

---

src/executables/csql_launcher.c
src/executables/util_service.c
src/executables/util_support.c
src/executables/util_support.h

http://jira.cubrid.org/browse/CBRD-20759
hide password from command-line argument

[CBRD-20759] hide csql & utility password from display of ps command

---

src/base/system_parameter.c

[CBRD-20416] enable xasl clone

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-20769

[CRBD-20769] Fix common type to be used for special cast in inference of collation result

---

src/query/query_executor.c
src/query/query_executor.h
src/query/stream_to_xasl.c

http://jira.cubrid.org/browse/CBRD-20770

[CBRD-20770] Intialize analytic unserialized fields when clears xasl

---

src/base/system_parameter.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20726

[CBRD-20726] When resolves domain for aggregation, clears the value only if the domains are incompatible

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20776

[CBRD-20776] fixed analytic memory issue

---

src/query/query_executor.c
src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20780

[CBRD-20780] fixed memory leak caused by xasl clone status

---

src/broker/broker_log_replay.c
src/broker/cas_runner.c
src/tools/cci_applier.c

http://jira.cubrid.org/browse/CBRD-20764

[CBRD-20764] fix typo

---

src/broker/broker_log_replay.c
src/broker/cas_runner.c
src/tools/cci_applier.c

http://jira.cubrid.org/browse/CBRD-20764

[CBRD-20764] copy args to hide

---

src/base/system_parameter.c

[CBRD-20146] fixes compile warnings

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-20841
Unfortunately, there were a bunch of memory leaks on db_to_... and ..._to_char functions.

[CBRD-20841] fix memory leaks of db_to_... and ..._to_char functions

---

src/base/system_parameter.c

http://jira.cubrid.org/browse/CBRD-20818

[CBRD-20818] changed lower limit for db_volume_size to 0

---

src/query/query_executor.c
src/query/query_executor.h
src/query/stream_to_xasl.c
src/query/xasl_to_stream.c

http://jira.cubrid.org/browse/CBRD-20837
- remove unused list id from cte proc

[CBRD-20837] CTE : force copy list from non recursive part to main CTE list (to get types)

---

src/parser/parse_tree_cl.c

It is a slip of #449. VS will not allow such initialization.

[CBRD-20846] fixed Windows build issue

---

src/parser/parse_tree.h
src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-20873

[CBRD-20873] Handle false where for CTEs.

---

src/query/vacuum.c
src/storage/file_manager.c
src/storage/file_manager.h

http://jira.cubrid.org/browse/CBRD-20842
@eseokoh thank you for your observations. fix according comment:
http://jira.cubrid.org/browse/CBRD-20842?focusedCommentId=4740869&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4740869

[CBRD-20842] Fix error handling in vacuum_heap_get_hfid_and_file_type

---

src/parser/view_transform.c

http://jira.cubrid.org/browse/CBRD-20898
After removing the subquery check as part of CBRD-20856, this kind of subqueries were also rewritten.

[CBRD-20898] Avoid select rewrite for INFO_COLS_SCHEMA flags

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20902
please see #462

[CBRD-20902] fixes out-dated assertion

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-20877
Union between values query inside CTE was not resolved.

[CBRD-20877] Check union compatibility for CTEs with values query

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20904
disk_format for temporary volumes: do not log and remove volume in case of error

[CBRD-20904] disk_format: fix removing temporary volume

---

src/optimizer/query_graph.c

http://jira.cubrid.org/browse/CBRD-20895
The order of the conditions was incorrect.

[CBRD-20895] - Fix incorrect if conditions

---

src/optimizer/query_graph.c

http://jira.cubrid.org/browse/CBRD-20907
fixes #471 again.

[CBRD-20907] fixes regression of CBRD-20895.

---

src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-20872

[CBRD-20872] CTE : Fix printing of tree for union/intersection/difference statements having WITH clause

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20912

[CBRD-20912] fixes a memory leak of index loose scan

---

src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-20910

[CBRD-20910] reset compressed need clear

---

src/storage/system_catalog.c

http://jira.cubrid.org/browse/CBRD-20925
Lock request was not granted because of interruption.

[CBRD-20925] fixes bad assertion of catalog_start_access_with_dir_oid

---

conf/cubrid.conf

http://jira.cubrid.org/browse/CBRD-20924
Tune it as 256M.

[CBRD-20924] change log_buffer_size of default cubrid.conf

---

src/base/system_parameter.c

http://jira.cubrid.org/browse/CBRD-20926

[CBRD-20926] change default error_log_level as ER_NOTIFICATION_SEVERITY

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20905

[CBRD-20905] fixed memory leak in XASL node in access spec

---

src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-20915

[CBRD-20915] do not set aggregate list_id if error happens

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-20918
It is incorrect to remove order_by when the query has limit.

[CBRD-20918] order_by can not be removed if query has limit

---

src/parser/semantic_check.c
src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-20919

[CBRD-20919] Fix semantic type for CAST operator

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20890

[CBRD-20890] clear analytic part value

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20936

[CBRD-20936] fixed memory leak in MRO

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20930
Avoid dead-latch when trying to read class name from class record in b-tree error/notification.
Note that this is a work-around. We should normally be able to access any class name easily without latch pages.

[CBRD-20930] btree_set_error: use conditional latch to fix class record page

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20942
Forcing zero wait for VACUUMS prevent other VACUUMS from fixing a page.
I just want to give up providing class name for VACUUM operations. We may improve it later.

[CBRD-20942] VACUUMs do not provide classname to btree_set_error.

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20905

[CBRD-20905] fixed memory leak be clearing show columns output values

---

src/query/scan_manager.c
src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20949

[CBRD-20949] fixed several memory leak issues in MRO

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-20956

[CBRD-20956] fixed another MRO memory leak

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-20966

[CBRD-20966] disk_add_volume_extension: update total/max sectors

---

msg/ro_RO.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-20976

[CBRD-20976] trailing blank broke line continuation

---

src/query/query_manager.c

http://jira.cubrid.org/browse/CBRD-20967

[CBRD-20967] fixes bad error handling of malloc

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20974

[CBRD-20974] fixed memory leak in show index

---

src/base/tz_compile.c
src/object/schema_manager.c
src/object/virtual_object.c
src/query/execute_statement.c

fixed missing quoted identifiers for internal queries.

[CBRD-20146] use quoted identifiers for system generated queries

---

src/base/memory_alloc.c
src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-20972

[CBRD-20972] fixed memory leak in sys_connect_by_path function

---

src/query/query_opfunc.c

http://jira.cubrid.org/browse/CBRD-20980

[CBRD-20980] fixed crash caused by clearing db_value of output regu variable

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-20997
The new node resulted from folding must keep the WITH clause of the old UNION.
In case the new node also has a WITH clause, the folding is anulated. We could merge the clauses but I believe it is not safe from future changes of the CTEs solving mechanism.

[CBRD-20997] Keep UNION WITH clause when union is folded

---

src/parser/name_resolution.c
src/parser/view_transform.c

http://jira.cubrid.org/browse/CBRD-21025
Also fixes [CBRD-21042](http://jira.cubrid.org/browse/CBRD-21042)

[CBRD-21025] Fix handling of error from semantic_type.

---

src/query/list_file.c

http://jira.cubrid.org/browse/CBRD-21036

[CBRD-21036] fixed overflow int addition issue

---

src/query/stream_to_xasl.c

http://jira.cubrid.org/browse/CBRD-21050

[CBRD-21050] fixed crash by initializing dist percent aggregate

---

src/parser/view_transform.c

http://jira.cubrid.org/browse/CBRD-21051
There were IVR to error messages. It was allocated by view parser which would be destroyed.
To refer to string blocks of a parser, it should be allocated/copied by another.

[CBRD-20151] fixes IVR to view error messages

---

src/parser/name_resolution.c

http://jira.cubrid.org/browse/CBRD-21057

[CBRD-21057] Handling of semantic errors.

---

src/query/scan_manager.c

http://jira.cubrid.org/browse/CBRD-21058

[CBRD-21058] fixed memory leak by restoring ISS range details

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/base/system_parameter.c
src/base/system_parameter.h
src/query/query_executor.c
src/query/query_executor.h
src/query/stream_to_xasl.c

http://jira.cubrid.org/browse/CBRD-20811

[CBRD-20811] Introduce session system parameter for maximum iterations in recursive CTE

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21069

[CBRD-21069] Handle reset of scan tuple number when a new page is fetched.

---

src/transaction/locator_sr.c

http://jira.cubrid.org/browse/CBRD-21045

[CBRD-21045] fixed crash caused by uninitialized record

---

src/base/system_parameter.c
src/base/system_parameter.h
src/broker/broker.c
src/communication/network_sr.c
src/connection/heartbeat.h
src/executables/checksumdb.c
src/executables/master_util.c
src/executables/util_cs.c
src/executables/util_sa.c
src/executables/util_service.c
src/transaction/boot_sr.c

Should fix issues:
http://jira.cubrid.org/browse/CBRD-20813
http://jira.cubrid.org/browse/CBRD-20814

[CBRD-20814] Add system parameter loading flags to avoid special processing of intl parameters from utilities not related to engine

---

src/query/list_file.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21077

[CBRD-21077] Return error if CTE max recursion is reached when list optimization is disabled

---

msg/fr_FR.utf8/utils.msg
msg/ro_RO.utf8/utils.msg

[CBRD-20146] removed blank lines that gencat complains

---

src/base/perf_monitor.c
src/base/perf_monitor.h
src/cm_common/cm_mem_cpu_stat.c
src/cm_common/cm_stat.h

[CBRD-20074] undo the quick fix(#562) of CM stats

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21086

[CBRD-21086] Handle case of flushing non-dirty BCB (neighbor flush)

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-21020
Since temporary volumes are not logged, we cannot abort partial changes made during file_temp_alloc. The only possible errors, that may end up with partial changes, are caused by interruptions.
Fix by not allowing interruptions.

[CBRD-21020] don't interrupt file_temp_alloc

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21091
btree_merge_node_and_advance: read neighbor page from disk even if IO is stressed if child page is almost empty. this should fix cases when all (or most) records are deleted, but no merge is executed.
I expect this to have little to no impact on benchmark performance.

[CBRD-21091] Execute merge under stressed IO.

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21096
It is a slip of #570.

[CBRD-21096] trylock returns 0 for success

---

timezones/tzdata/africa
timezones/tzdata/antarctica
timezones/tzdata/asia
timezones/tzdata/australasia
timezones/tzdata/backward
timezones/tzdata/etcetera
timezones/tzdata/europe
timezones/tzdata/iso3166.tab
timezones/tzdata/leapseconds
timezones/tzdata/northamerica
timezones/tzdata/southamerica
timezones/tzdata/zone.tab

http://jira.cubrid.org/browse/CBRD-20758

[CBRD-20758] Update the latest timezone database from IANA

---

src/storage/disk_manager.c
src/storage/disk_manager.h
src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-21020
revert partial reservations for file_create temporary

[CBRD-21020] file_create temporary: do not interrupt

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21049

[CBRD-21049] fixed memeory leak caused by deadlock at foreign key update

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21114
This fixes a regression of #583.

[CBRD-21114] clear index key for error case; fixes a slip of #583

---

src/base/perf_monitor.h
src/communication/network_interface_sr.c
src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21092

[CBRD-21092]  MANY_IOREADS cannot be shown in the event log

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-21128
disk_reserve_sectors calls disk_unreserve_ordered_sectors_without_csect instead of disk_unreserve_ordered_sectors.

[CBRD-21128] disk_reserve_sectors: fix csect usage

---

src/storage/overflow_file.c

http://jira.cubrid.org/browse/CBRD-21088
After the fix of the page, no error was set if it would fail.

[CBRD-21088] Fixed set of error

---

src/base/system_parameter.c

http://jira.cubrid.org/browse/CBRD-21135

[CBRD-21135] disable data_aout_ratio parameter

---

src/communication/network_sr.c

http://jira.cubrid.org/browse/CBRD-21136
net_server_conn_down: do not interrupt threads with check_interrupt false

[CBRD-21136] net_server_conn_down: fix interrupt

---

src/base/tz_support.c

http://jira.cubrid.org/browse/CBRD-21109

[CBRD-21109] [TimeZone] Insert an unsupported datetimetz format, query successfully processed

---

src/query/list_file.c
src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-21070
removed wrong asserts also

[CBRD-21070] fixed leaked page

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21143

[CBRD-21143] fixed cte memory leak

---

src/storage/system_catalog.c

http://jira.cubrid.org/browse/CBRD-21147

[CBRD-21147] UMR on btree_get_stats

---

src/query/vacuum.c
src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21153

[CBRD-21153] initialize OID to supress valgrind complaint

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21149

[CBRD-21149] fixes leak of pgbuf_Pool.big_private_lrus_with_victims

---

src/parser/name_resolution.c

http://jira.cubrid.org/browse/CBRD-21117

[CBRD-21117] Stop parsing in case of errors.

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-20692
fix typo in comment :).

[CBRD-20692] fix typo of extend logging

---

src/query/scan_manager.h
src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21140

[CBRD-21140] fixed crash caused by null domain in MRO

---

src/storage/system_catalog.c

It fixes nothing but is easier to read.

[CBRD-20146] refactor catalog_get_representation

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-21164

[CBRD-21164] file_log of file_perm_dealloc missed arguments

---

contrib/gdb_debugging_scripts/disk_manager.gdb

[CBRD-20146] fix disk_get_volheader script

---

contrib/gdb_debugging_scripts/page_buffer.gdb
src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21172

[CBRD-21172] Remove assert condition related to LRU quota when no dirties are found

---

src/base/object_representation_sr.c

http://jira.cubrid.org/browse/CBRD-21145

[CBRD-21145] UMR on catalog_update

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-20289
change the safe-guard as er_log, because we have not seen a case vacuum is completely blocked and it bothers us from many cases.

[CBRD-20289] change a safe-guard to catch vacuum is blocked as er_log

---

src/optimizer/query_rewrite.c

http://jira.cubrid.org/browse/CBRD-21170

[CBRD-21170] fixed bad condition

---

src/storage/extendible_hash.c

http://jira.cubrid.org/browse/CBRD-21179

[CBRD-21179] fixes page leak of ehash_expand_directory

---

contrib/gdb_debugging_scripts/page_buffer.gdb
src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21178
I don't think this is really a trouble case. Most of buffers are in invalid list and all LRU lists are almost empty.

[CBRD-21178] there might be not enough buffers to flush victim candidates

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21161

[CRBD-21161] Add debug code and workaround for victim hint

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-20842

[CBRD-20842] propagate error to vacuum to recover deleted table cases

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21185

[CBRD-21185] Add check on old_victim_hint zone and remove risky assert

---

src/storage/statistics_sr.c

http://jira.cubrid.org/browse/CBRD-21193
It was interrupted and statistics is immature. 
The fix makes it silent.

[CBRD-21193] fixed to handle interrupted cases to fetch statistics

---

src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21194
#647 changed not to mount temp volumes during bootstrapping.
However, removing temp volume relied on file manager which requires mounting volumes.
The fix also removes unnecessary codes to remove a volume.

[CBRD-21194] removing temp volume does not rely on file manager

---

src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21196

[CBRD-21196] forget any noisy warning or error to start vacuuming of SA

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-21197
The query timeout caused repeated interruptions during volume extension. Volume gets extended, but thread is interrupted before updating volume header and disk cache. Over and over again.
Do not check for interruptions during volume extensions.

[CBRD-21197] disk_volume_expand: do not interrupt

---

src/storage/page_buffer.c

http://jira.cubrid.org/browse/CBRD-21198

[CBRD-21198] Rewrite assert to a more permissive case.

---

src/base/tz_compile.c

http://jira.cubrid.org/browse/CBRD-21200

[CBRD-21200] Fix query for tz extend tool

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-20997
fixes a slip of #535

[CBRD-20997] fixed bad reference of PT_IS_QUERY_NODE_TYPE

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-21205
fixes slip of #665.

[CBRD-21205] fix disk_rv_redo_format

---

src/base/tz_compile.c

http://jira.cubrid.org/browse/CBRD-21208
Fixed timezone update query.

[CBRD-21208] fixed timezone update query of gen_tz

---

src/storage/btree.c
src/storage/file_manager.c
src/storage/file_manager.h
src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-21228
Bug was discovered while investigating valgrind issues. Fix updating class OID in file descriptor.

[CBRD-21228] fix file descriptor when reusing heap

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-21257
RVDK_FORMAT undo is logged before volume is created. If rollback due to interrupt or other errors occur before volume is created, then disk_rv_undo_format hit an incorrect assert.
Update assert to expect deallocated error.

[CBRD-21257] disk_rv_undo_format: volume was not created

---

src/query/query_executor.c
src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21306

[CBRD-21306] Fix arguments of systemtab query_exe probe

---

src/object/schema_template.c

http://jira.cubrid.org/browse/CBRD-21319

[CBRD-21319] fixed null default value for PK column

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-21320

[CBRD-21320] fixed null oid assignment

---

src/query/execute_schema.c

http://jira.cubrid.org/browse/CBRD-21331

[CBRD-21331] fixed alter table not null with default

---

src/query/execute_schema.c

http://jira.cubrid.org/browse/CBRD-21329
http://jira.cubrid.org/browse/CBRD-21323
http://jira.cubrid.org/browse/CBRD-21324

[CBRD-21329] Default value: clean parser error message before setting a new one.

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-21322

[CBRD-21322] Fix coercion from multibyte charset to binary charset

---

msg/en_US.utf8/utils.msg
msg/en_US/utils.msg
msg/tr_TR.utf8/cubrid.msg
msg/tr_TR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21339
also last sentence for EXTEND english description is updated to sound better.

[CBRD-21339] translate tr_Tr messages

---

msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.euckr/utils.msg
msg/ko_KR.utf8/cubrid.msg
msg/ko_KR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21337

[CBRD-21337] translate ko_KR messages

---

msg/es_ES.utf8/cubrid.msg
msg/es_ES.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21333

[CBRD-21333] Message translation for es_ES

---

msg/fr_FR.utf8/cubrid.msg
msg/fr_FR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21334

[CBRD-21334] Translation of fr_FR messages.

---

msg/it_IT.utf8/cubrid.msg
msg/it_IT.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21335

[CBRD-21335] Message translation it_IT.

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21357

[CBRD-21357] copying OID rather than retrieving reference

---

src/query/execute_schema.c
src/query/execute_statement.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-20146
Related with #722

[CBRD-20146] fixes potential memory leak of DB_VALUE

---

src/communication/network_cl.c
src/communication/network_interface_cl.c
src/connection/connection_cl.c
src/connection/connection_support.c

http://jira.cubrid.org/browse/CBRD-20146
Fixes nothing but layout.

[CBRD-20146] beautify layout

---

src/connection/connection_cl.c

[CBRD-20146] fixes slip of css_return_queued_request

---

src/connection/connection_cl.c

http://jira.cubrid.org/browse/CBRD-21364

[CBRD-21364] reset header_size to retry to receive from server

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21365
btree_check_all crashes because btree_check_by_btid but no error was set. the error_code is inherited from heap_get_indexinfo_of_btid.
heap_get_indexinfo_of_btid fails because another thread is loading index but did not yet modify class object - index info for btid is not found. no error is set, but ER_FAILED is returned.
This is a quick fix specifically added for this case. btree_check_by_btid expects heap_get_indexinfo_of_btid error without an error set, logs the case and considers the case valid. the b-tree can still be checked, but index name will be unknown.

[CBRD-21365] btree_check_by_btid: avoid safe-guard on recently loaded index

---

msg/en_US.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/km_KH.utf8/utils.msg
msg/vi_VN.utf8/cubrid.msg
msg/vi_VN.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21370

[CBRD-21370] fixes bad messages

---

src/storage/heap_file.c
src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21376

[CBRD-21376] fixed hash function for OID->HFID mapping

---

src/base/system_parameter.c
src/transaction/boot_cl.c
src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21008

[CBRD-21008] Fix string compression flag parameter

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-21410

[CBRD-21410] fix memory leak of xcache_check_recompilation_threshold

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-21408
It was interrupted while loading an index and the list leaked.

[CBRD-21408] fixes memory leak: xbtree_load_index

---

src/storage/btree.c
src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-21425
It also fixes http://jira.cubrid.org/browse/CBRD-21429.

[CBRD-21425] handling interrupt when find split point

---

src/base/tz_support.c

http://jira.cubrid.org/browse/CBRD-21427

[CBRD-21427] Fix timezone session value during recovery

---

src/query/query_executor.c
src/query/scan_manager.c
src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21438

[CBRD-21438] error from heap_scancache_start_internal was ignored

---

cmake/CPack.STGZ_Header.sh.in

http://jira.cubrid.org/browse/CBRD-21439

[CBRD-21439] fix script of sh package for dash shell

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-21428
don't reuse heaps considered dropped by vacuum

[CBRD-21428] don't reuse heaps considered dropped by vacuum

---

cmake/CPack.STGZ_Header.sh.in

change to create env files for csh and sh shell.

[CBRD-21443] fix script of sh package to create env files correctly

---

msg/de_DE.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21332

[CBRD-21332] Fix de_DE translation

---

CREDITS

fixed dead links to contributors.

[CBRD-20146] updates CREDITS

---

.gitignore

includes build directories of `build.sh` script.

[CBRD-20146] includes build directories

---

msg/es_ES.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21333

[CBRD-21333] fixes typos of es_ES messages

---

msg/fr_FR.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21334

[CBRD-21334] Fix fr_FR message translation

---

msg/it_IT.utf8/utils.msg

http://jira.cubrid.org/browse/CBRD-21335

[CBRD-21335] Fix it_IT translation

---

src/connection/connection_sr.c

http://jira.cubrid.org/browse/CBRD-21453

[CBRD-21453] fixed assert when free wait queue entry

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21450
It was leaked when an error was raised.

[CBRD-21450] fixes memory leak: lob_info_list of update/delete

---

src/broker/cas_meta.c
src/parser/semantic_check.c
src/parser/xasl_generation.c

[CBRD-20146] fixes bad comparisons

---

src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-21479

[CBRD-21479] Fix collation of max_string special value

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21482

[CBRD-21482] don't interrupt btree_verify_node

---

src/storage/file_manager.c

http://jira.cubrid.org/browse/CBRD-21484
Since indexes are built with SIX_LOCK (it will be upgraded to SCH_M_LOCK later), which allows check access an immature index file.
To skip checking an immature index, check it with IX_LOCK which is incompatible with SIX_LOCK.

[CBRD-21484] uses IX_LOCK checking index files to skip immature indexes

---

src/storage/btree.c

http://jira.cubrid.org/browse/CBRD-21485

[CBRD-21485] fixed interrupt

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-21488
the issue a complicated deadlock case.
we have two possible locking orders: lock class repr, then read latch on class heap page; also read latch on class heap page, then lock class repr. Usually read latches don't block each other, unless there is a write latcher already waiting (our case).
Fix by avoiding latch after locking class representation. Read representation from heap page first, then lock.

[CBRD-21488] fix deadlock: don't latch page after locking class repr

---

src/compat/dbi_compat.h

http://jira.cubrid.org/browse/CBRD-21498

[CBRD-21498] fix missing error code from dbi_compat.h

---

CONTRIBUTING.md

the first draft of CONTRIBUTING

[CBRD-21499] Create CONTRIBUTING.md

---

cs/CMakeLists.txt
sa/CMakeLists.txt
src/base/porting.h
src/executables/loader.h

http://jira.cubrid.org/browse/CBRD-21515

[CBRD-21515] Fixing build issues with MVS 2008

---

src/communication/network_interface_cl.h
src/compat/db_query.h
src/compat/dbi.h
src/compat/dbi_compat.h
src/compat/dbtype.h
src/object/object_print.h
src/object/set_object.h

[CBRD-21516](http://jira.cubrid.org/browse/CBRD-21516)
Done:
* make extern "C" all functions that are needed by qactl
Not Done:
* make extern "C" all external interface functions. Not clear which ones should be.

[CBRD-21516]: fix isolation test can't execute with 10.2.0.7670-4feb3eb build

---

src/transaction/lock_manager.c

http://jira.cubrid.org/browse/CBRD-21521

[CBRD-21521] use LOCK_COMPATIBILITY enum

---

src/communication/network_interface_cl.c
src/communication/network_interface_sr.c

http://jira.cubrid.org/browse/CBRD-21527
fixes a slip of #719

[CBRD-21527] fixes slip of getting ha_Server_state

---

src/object/schema_manager.h
src/object/transform_cl.c

http://jira.cubrid.org/browse/CBRD-21570

[CBRD-21570] Fix memory corruption from schema code

---

src/compat/dbtype.h

http://jira.cubrid.org/browse/CBRD-21537
Expose all value get functions and string/enum put/get codeset/collation.

[CBRD-21537] expose dbtype functions to c compiled app

---

CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-21607

[CBRD-21607] coverage and profile builds won't be built

---

CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-21615
Build is broken with #845 
CI system will be upgraded later.

[CBRD-21615] gcc 4.4.7 which CI adopts will not be built

---

unit_tests/string_buffer/src/test_string_buffer.cpp

http://www.jira.cubrid.org/browse/CBRD-21621
Quick fix for CI build.

[CBRD-21621] VS 2012 does not support <chrono>.

---

src/storage/disk_manager.c

http://jira.cubrid.org/browse/CBRD-21620
Remove backward compatibility with 10.1 in disk volume expand fix.

[CBRD-21620] remove backward compatibility with 10.1

---

src/broker/broker_monitor.c

[CBRD-21524] fix Windows build

---

src/executables/unittests_area.c
src/executables/unittests_cqueue.c
src/executables/unittests_lf.c
src/executables/unittests_snapshot.c

http://jira.cubrid.org/browse/CBRD-21639
Fix overflow issue of unit tests.

[CBRD-21639] fix overflow of strlen expr

---

src/executables/esql_cli.c
src/query/execute_schema.c
src/query/query_dump.c
src/storage/external_sort.c
src/transaction/log_manager.c

[CBRD-21524] fix ugly long lines

---

src/cci/cci_network.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21662

[CBRD-21662] fixes legacy typos

---

src/object/object_print.c
src/query/query_executor.c

I have enclosed the JSON body in single quotes when describing a class.

[CBRD-21656] Correct SHOW CREATE TABLE result

---

src/object/object_domain.c

http://jira.cubrid.org/browse/CBRD-21666
There was a mem leak in object_domain.c:10434 (JSON_DOC *doc).

[CBRD-21666] Mem leak when select json_type(sys_datetime);

---

src/object/object_primitive.c
src/object/object_representation.c
src/object/transform_cl.c

http://jira.cubrid.org/browse/CBRD-21678
Call pr_clear_value in mr_data_writeval_json to clear the compressed string if necessary.

[CBRD-21678] free compressed string

---

src/compat/db_macro.c
src/object/object_primitive.c
src/object/object_representation.c

[CBRD-21524] beautify code layout

---

src/transaction/log_applier.c
src/transaction/log_writer.c

http://jira.cubrid.org/browse/CBRD-21551
#824 missed it.

[CBRD-21551] fixes slip of #824 to log_applier log dump

---

src/object/object_print.c

http://www.jira.cubrid.org/browse/CBRD-21663
make the buffer that holds the schema string large enough

[CBRD-21663] Fix Describe Domain

---

src/transaction/log_impl.h

http://jira.cubrid.org/browse/CBRD-21704
fix #894

[CBRD-21704] fix log_header initializer

---

src/compat/dbtype.h
src/parser/parse_dbi.c
src/parser/parse_tree.c
src/parser/parse_tree.h
src/parser/type_checking.c
src/query/string_opfunc.c

http://www.jira.cubrid.org/browse/CBRD-21665
Add all string cases

[CBRD-21665] Json query will not work well

---

src/parser/parse_dbi.c
src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-21708
add json body to info.value.data_value.str in conversion from DB_VALUE to PT_NODE

[CBRD-21708] Fix Json Crash

---

locales/make_locale_Win32.bat
locales/make_locale_x64.bat
timezones/make_tz_Win32.bat
timezones/make_tz_x64.bat

http://jira.cubrid.org/browse/CBRD-21643

[CBRD-21643] Fix to build with Visual Sutdio 2017

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-21714
Fix mem leak

[CBRD-21714] FixCrash

---

src/parser/semantic_check.c

http://jira.cubrid.org/browse/CBRD-21720
and then check assignment compatible.
It is a legacy bug that is not harmful.

[CBRD-21720] check view definition matches with view query spec first

---

src/base/tz_compile.c

http://jira.cubrid.org/browse/CBRD-21722

[CBRD-21722] remove useless dump of gen_tz

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/compat/dbi_compat.h
src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-21718
throw an error when json name is null

[CBRD-21718] Server crash when adding null name to json object

---

src/connection/tcp.c
src/transaction/boot_sr.c

http://jira.cubrid.org/browse/CBRD-21544

[CBRD-21544] css_hostname_to_ip raises error

---

src/object/object_primitive.c

http://jira.cubrid.org/browse/CBRD-21766
pr_valstring(): move ownership for returned value

[CBRD-21766] createdb crashed

---

src/base/error_manager.c
src/base/error_manager.h
src/communication/network_cl.c
src/communication/network_interface_sr.c
src/connection/client_support.c
src/connection/connection_cl.c
src/connection/server_support.c
src/query/show_scan.c

http://jira.cubrid.org/browse/CBRD-21735
I don't know this fixes the case but there were several flaws of the function.

[CBRD-21735] fixes flaws of er_get_area_error

---

src/base/mem_block.hpp
src/base/string_buffer.hpp
src/compat/db_value_printer.cpp
src/object/object_printer.cpp
src/parser/parser_support.c

fixed memory leaks and mismatched new/delete
also:
http://jira.cubrid.org/browse/CBRD-21785
http://jira.cubrid.org/browse/CBRD-21778
http://jira.cubrid.org/browse/CBRD-21777
http://jira.cubrid.org/browse/CBRD-21765
http://jira.cubrid.org/browse/CBRD-21772
no ideea why sql/_08_javasp/cases/413-2.sql fails in CI, it runs OK locally  and it doesn't appear to have anything to do with my changes

[CBRD-21781] Memory Leaks from string_buffer

---

src/compat/db_json.cpp
src/query/arithmetic.c

http://jira.cubrid.org/browse/CBRD-21780
fixed by initializing variables and output parameters

[CBRD-21780] UMR of JSON

---

src/query/xasl_cache.c

http://jira.cubrid.org/browse/CBRD-20377

[CBRD-20377] Fix to recompile threshold for execute query.

---

.gitattributes
msg/.gitattributes
src/executables/gencat.c

http://jira.cubrid.org/browse/CBRD-21789

[CBRD-21789] Fix gencat to acccept CRLF as line endings; add .gitattributes to msg folder

---

src/executables/gencat.c

http://jira.cubrid.org/browse/CBRD-21817
This is due to incorrect fix of http://jira.cubrid.org/browse/CBRD-21789

[CBRD-21817] Fix handling of line ending (CRLF case)

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-21813
fix check to restart processing vacuum data - or not and!

[CBRD-21813] fix check to restart processing vacuum data

---

src/base/lockfree_circular_queue.hpp
src/thread/thread_task.hpp
src/thread/thread_worker_pool.hpp

Reverts CUBRID/cubrid#947 since we have unexpected crashes.

[CBRD-21805] Revert "[CBRD-21805] delete unexecuted tasks in worker pool"

---

src/executables/gencat.c

http://jira.cubrid.org/browse/CBRD-21821

[CBRD-21821] Fix msg line ending at buffer bound

---

src/connection/wintcp.c

http://jira.cubrid.org/browse/CBRD-21530

[CBRD-21530] Initiate use of Winsock DLL

---

src/jsp/jsp_cl.c

[CBRD-21524] fix a bad enum usage

---

.gitmodules
CMakeLists.txt
Jenkinsfile

Add submodule for cubrid-manager-server and remove stmt for checkout cubridmanager in Jenkinsfile.
(You can checkout cubrid with cubridmanager using '--recursive' option for git clone)

[CBRD-21719] add submodule for cubrid-manager-server

---

src/compat/db_admin.c

http://jira.cubrid.org/browse/CBRD-21834

[CBRD-21834] creates session for createdb

---

src/compat/db_admin.c
src/query/query_manager.c
src/session/session.c
src/session/session.h

http://jira.cubrid.org/browse/CBRD-21831
It also includes #970 and #972

[CBRD-21831] 10.1p1: initializes session state for createdb

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-21854
This fixes a slip of #969

[CBRD-21854] fixes bad assertion of user given recompile hint

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-21854

[CBRD-21854] removes a bad assertion of query recompilation

---

src/thread/thread_worker_pool.hpp

http://jira.cubrid.org/browse/CBRD-21840
It could be possible that a task is pushed for execution after stopping the worker pool, in this case we do
not execute the task and return from worker_pool::run

[CBRD-21840] Don't execute a task if worker pool is not running

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-21860
Freed template was read and also double freed for an error case.

[CBRD-21860] (potential) FMR of do_insert_template

---

src/thread/thread_entry.cpp

http://jira.cubrid.org/browse/CBRD-21896

[CBRD-21896] quick fix to #989 for SA_MODE

---

src/query/vacuum.c
src/thread/thread.c
src/thread/thread.h
src/transaction/lock_manager.c
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-21843

[CBRD-21843] migrate checkpoint daemon thread to new API

---

src/thread/thread.c
src/thread/thread.h
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-21842

[CBRD-21842] migrate remove log archives daemon thread to new API

---

src/thread/thread_looper.hpp
src/transaction/lock_manager.c
src/transaction/lock_manager.h

http://jira.cubrid.org/browse/CBRD-21841
Optimize deadlock detection daemon task, if none of the threads were suspended then just go to sleep

[CBRD-21841] optimize deadlock detection daemon task

---

src/transaction/log_manager.c
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-21903

[CBRD-21903] Fix to delay initialization of log page buffer structures

---

src/session/session.c
src/session/session.h
src/thread/thread.c
src/thread/thread.h
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-21844

[CBRD-21844] migrate session control daemon thread to new API

---

src/storage/disk_manager.c
src/thread/thread.c
src/thread/thread.h

http://jira.cubrid.org/browse/CBRD-21846

[CBRD-21846] migrate auto volume expansion daemon thread to new API

---

src/communication/network_interface_sr.c
src/query/query_manager.c
src/session/session.c
src/storage/disk_manager.c
src/thread/thread.c
src/thread/thread.h
src/transaction/lock_manager.c
src/transaction/log_global.c
src/transaction/log_impl.h
src/transaction/log_manager.c
src/transaction/log_manager.h
src/transaction/log_page_buffer.c
src/transaction/log_tran_table.c
src/transaction/log_writer.c

http://jira.cubrid.org/browse/CBRD-21847

[CBRD-21847] migrate log clock daemon thread to new API

---

src/object/set_object.c

[CBRD-21524] fix ambiguous conditions

---

src/base/error_manager.c
src/communication/network_sr.c
src/transaction/boot_cl.c

http://jira.cubrid.org/browse/CBRD-21939
Quick fix for er_clear being called when error manager is not initialized.

[CBRD-21939] er_clear early out

---

msg/de_DE.utf8/cubrid.msg
msg/en_US.utf8/cubrid.msg
msg/en_US/cubrid.msg
msg/es_ES.utf8/cubrid.msg
msg/fr_FR.utf8/cubrid.msg
msg/it_IT.utf8/cubrid.msg
msg/ja_JP.utf8/cubrid.msg
msg/km_KH.utf8/cubrid.msg
msg/ko_KR.euckr/cubrid.msg
msg/ko_KR.utf8/cubrid.msg
msg/ro_RO.utf8/cubrid.msg
msg/tr_TR.utf8/cubrid.msg
msg/vi_VN.utf8/cubrid.msg
msg/zh_CN.utf8/cubrid.msg
src/base/error_code.h
src/compat/db_json.cpp

Hope this helps avoiding a merge conflict.

[CBRD-21524] reserve some error codes for JSON

---

src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-21951
It is a slip of #1020

[CBRD-21951] fixes memory leak of "show index"

---

src/transaction/log_manager.c

http://jira.cubrid.org/browse/CBRD-21941
Force remove log archives demon wake up in case it is configured to loop for a fix interval and no archives were previously deleted.
This completes #1009

[CBRD-21941] force wake up of remove log archives daemon

---

src/query/query_dump.c

http://jira.cubrid.org/browse/CBRD-21988

[CBRD-21988] pgbuf_block_bcb expects thread handle

---

src/thread/thread.c

http://jira.cubrid.org/browse/CBRD-22032
Main thread had lock free resources and it won't be freed from #1059.

[CBRD-22032] return main entry lf transactions

---

src/executables/util_cs.c
src/storage/file_io.c

http://jira.cubrid.org/browse/CBRD-22044
backupdb accepts
- a directory
- a device file
- a FIFO file (only for *nix)
as backup destination. 
FIFO can be used with 3rd party backup tools.

[CBRD-22044] backupdb also allows a FIFO (named pipe) file

---

util/CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-22079
Don't add link between cub_admin and cubridsa, just add dependency (cubridsa is loaded dynamically). Also add dependency on cubridcs.

[CBRD-22079] remove cub_admin => cubridsa linking

---

win/CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-22077
Fix installing external dll's.
I checked only build/install, must check installing from package.

[CBRD-22077] fix windows install

---

cs/CMakeLists.txt
cubrid/CMakeLists.txt
src/base/process_util.c
src/base/process_util.h
src/compat/db.h
src/compat/db_admin.c
src/compat/db_admin.h
src/executables/ddl_proxy_client.cpp
src/executables/utility.h
unit_tests/CMakeLists.txt
unit_tests/ddl_proxy_client/CMakeLists.txt
unit_tests/ddl_proxy_client/test_main.cpp
util/CMakeLists.txt

http://jira.cubrid.org/browse/CBRD-22042
I implemented a lightweight statement executing client to be used for SBR by wrapping cubridcs library functionalities. I also created an unit test that executes 2 statements and checks whether errors have occurred or not.

[CBRD-22042] [HA] SBR Ad-hoc Client Implementation

---

src/heaplayers/sanitycheckheap.h

http://jira.cubrid.org/browse/CBRD-22101

[CBRD-22101] fix compile for gcc 8.1.0

---

src/query/vacuum.c

http://jira.cubrid.org/browse/CBRD-22102
vacuum worker safe-guard against errors is hit. however, interrupted errors are now possible during shutdown.
update safe-guards and properly handle shutdown interruption.

[CBRD-22012] vacuum worker should expect interrupted error during shutdown

---

src/executables/loaddb.c

http://jira.cubrid.org/browse/CBRD-22075

[CBRD-22075] fix print_log_msg on loaddb

---

src/executables/loaddb.c

http://jira.cubrid.org/browse/CBRD-22116
Fixes error reporting of #1100

[CBRD-22116] show an error that loaddb fails to restart db

---

src/executables/loaddb.c

http://jira.cubrid.org/browse/CBRD-22125
fixes a slip of #1105

[CBRD-22125] loaddb log file was unavailable for restart errors

---

src/executables/loaddb.c

http://jira.cubrid.org/browse/CBRD-22125
fix slip of #1107

[CBRD-22125] correct fclose

---

src/base/dtoa.c
src/base/mprec.c
src/base/mprec.h

http://jira.cubrid.org/browse/CBRD-22154

[CBRD-22154] Replace macro definition P with PREC

---

src/parser/xasl_generation.c

http://jira.cubrid.org/browse/CBRD-22054
fix loop end condition in my last refactoring in https://github.com/CUBRID/cubrid/pull/1120

[CBRD-22054] Update query defaults

---

src/base/error_manager.c

http://jira.cubrid.org/browse/CBRD-22173

[CBRD-22173] fix typo of #1132

---

src/thread/thread_worker_pool.hpp

http://jira.cubrid.org/browse/CBRD-22192
Free leaked worker_pool::core resource m_available_workers.

[CBRD-22192] delete m_available_workers

---

src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-22197

[CBRD-22197] fix UMR of db_find_string_in_in_set

---

src/thread/thread_worker_pool.hpp

http://jira.cubrid.org/browse/CBRD-22213
Two cubthread::worker_pool::worker changes:
1. Retire context immediately after execution; other context may remain "dirty" during worker timeout.
2. When mapping "running" contexts, check if thread has any current tasks (m_task_p != NULL). If not, we cannot consider it running context.
Any of the two changes would have fixed this issue. However, both are required for logic consistency.

[CBRD-22213] fix mapping running contexts

---

src/executables/esql_grammar.y
src/parser/csql_grammar.y
src/storage/es_list.h

http://jira.cubrid.org/browse/CBRD-22210

[CRBD-22210] Remove redefinition of inline

---

src/connection/connection_globals.c
src/connection/server_support.c
src/thread/thread_worker_pool.hpp

http://jira.cubrid.org/browse/CBRD-22216
also refactor css_process_new_client and css_process_new_connection_request

[CBRD-22216] fixed connection worker pool to start a task

---

src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-22227

[CBRD-22227] fix overflow to init log buffer

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22230

[CBRD-22230] fixed to correctly refer to index_status

---

src/object/class_object.c

http://jira.cubrid.org/browse/CBRD-22228
Dropped fk was added back.

[CBRD-22228] fixed dropped fk reference

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22236
Server was unavailable to fetch class object.

[CBRD-22236] fixed unhandled error of sm_stats_remove_online_index_stats

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22239

[CBRD-22239] Fix UMR of dwb_flush_force

---

src/parser/parser_support.c
src/query/query_executor.c

http://jira.cubrid.org/browse/CBRD-22255

[CBRD-22255] show index statement has Visible column

---

src/object/schema_manager.c

http://jira.cubrid.org/browse/CBRD-22272
This is a regression of #1151

[CBRD-22272] class object might be decached

---

src/thread/thread_worker_pool.hpp

http://jira.cubrid.org/browse/CBRD-22278
fixes a regression of #1180

[CBRD-22278] fix assertion of start_thread

---

src/parser/name_resolution.c
src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-22286
fix a slip of CTE extension: #1149

[CBRD-22286] fix a slip of CTE extension: #1149

---

src/compat/db_vdb.c

http://jira.cubrid.org/browse/CBRD-22321

[CBRD-22321] fixes a slip of #1194

---

src/compat/db_vdb.c

http://jira.cubrid.org/browse/CBRD-22309

[CBRD-22309] Enabled QEWC for system tables

---

src/query/execute_statement.c

http://jira.cubrid.org/browse/CBRD-22310

[CBRD-22310] Enabled QEWC for ODKU

---

src/compat/db_vdb.c
src/parser/parse_tree.h
src/parser/view_transform.c

http://jira.cubrid.org/browse/CBRD-22314

[CBRD-22314] apply QEWC optimization to view

---

src/parser/type_checking.c

http://jira.cubrid.org/browse/CBRD-22327
It is also an inherited issue.

[CBRD-22327] fix vulerability of pt_eval_type_pre

---

src/parser/csql_grammar.y

http://jira.cubrid.org/browse/CBRD-22306
Enable a -> operator between a JSON and a String to behave like json_extract.

[CBRD-22306] JSON operator ->

---

src/parser/csql_grammar.y
src/parser/csql_lexer.l

http://jira.cubrid.org/browse/CBRD-22299
Added grammar for `JSON_MERGE_PRESERVE` which is a synonym for existing `JSON_MERGE`.

[CBRD-22299] JSON_MERGE_PRESERVE function

---

src/base/error_manager.c
src/base/error_manager.h
src/executables/util_cs.c

http://jira.cubrid.org/browse/CBRD-22362

[CBRD-22362] Avoid failed assertion of error module init for ha processes.

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22342

[CBRD-22342] consider DWB block version when forcing flush

---

src/parser/xasl_generation.c

[CBRD-22305] fix UMR of pt_to_aggregate_node

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22373

[CBRD-22373] Fixed assertion of dwb_flush_block

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22379

[CBRD-22379] Fixed DWB issue when stop server

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22393

[CBRD-22393] Fixed flush issue when server stops

---

src/storage/btree.c
src/storage/btree.h
src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22400

[CBRD-22400] Index name can't be displayed in the error message

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22402

[CBRD-22402] Fixed flush force issue

---

src/transaction/log_impl.h
src/transaction/log_page_buffer.c
src/transaction/log_writer.c

http://jira.cubrid.org/browse/CBRD-22363

[CBRD-22363] compute log page checksum before log writer send to slave

---

src/storage/heap_file.c

http://jira.cubrid.org/browse/CBRD-22398

[CBRD-22398] bestspace ignores warnings to interogate existing errors

---

src/executables/master.c

http://jira.cubrid.org/browse/CBRD-22396

[CBRD-22396] fix potential ABW of cub_master

---

src/compat/db_json.cpp
src/query/arithmetic.c

http://jira.cubrid.org/browse/CBRD-22414

[CBRD-22414] fix memory leak in json pretty function

---

src/storage/double_write_buffer.c

http://jira.cubrid.org/browse/CBRD-22423

[CBRD-22423] Fixed debug code - slip of 57200d8ec34cb86f

---

src/storage/btree_load.c
src/storage/heap_file.c
src/storage/heap_file.h

http://jira.cubrid.org/browse/CBRD-22420
There was a wrong cast which led to a stack corruption.

[CBRD-22420] Fix bad cast

---

src/transaction/boot_cl.c

http://jira.cubrid.org/browse/CBRD-21755

[CBRD-21755] Add missing row in _db_data_type

---

src/parser/parse_tree_cl.c

http://jira.cubrid.org/browse/CBRD-22406
Fixed Json table print slip

[CBRD-22406] JSON table print issue

---

src/query/query_executor.c
src/query/scan_json_table.cpp
src/query/scan_json_table.hpp
src/query/stream_to_xasl.c
src/query/xasl.h
src/xasl/access_json_table.cpp
src/xasl/access_json_table.hpp
src/xasl/xasl_stream.cpp

http://jira.cubrid.org/browse/CBRD-22417
http://jira.cubrid.org/browse/CBRD-22405
Fix memory leak in json table

[CBRD-22417] fix memory leak in json table

---

src/parser/type_checking.c
src/query/string_opfunc.c

http://jira.cubrid.org/browse/CBRD-22433

[CBRD-22433] add missing expr definition of str_to_date

---

src/parser/type_checking.c
src/query/string_opfunc.c

[CBRD-22433] Revert #1260 - add missing expr definition of str_to_date

---

src/storage/btree_load.c

http://jira.cubrid.org/browse/CBRD-22443
I may have to do best efforts for the first issue. 
To avoid two typical lock acquisition errors such as timeout and deadlocked, the patch forces the IB no timeout and deadlock victim.

[CBRD-22443] demoted lock should be restored even though operation fails

---

src/transaction/log_impl.h
src/transaction/log_manager.c
src/transaction/log_page_buffer.c

http://jira.cubrid.org/browse/CBRD-21936

[CBRD-21936] Force read of log header on restoredb
